// AUTO-GENERATED by: CGO_ENABLED=0 go run ./cmd/sandbox -tier=all -scenario=all -emit-traces
// Generated at: 2026-05-24T09:20:54Z
// Commit: 70163200
// DO NOT EDIT MANUALLY — re-run sandbox with -emit-traces to regenerate
// G8 honesty: this file reflects REAL sandbox execution results, not hardcoded values
window.__SANDBOX_TRACES__ = {
  "generatedAt": "2026-05-24T09:20:54Z",
  "commitHash": "70163200",
  "primitives": [
    {
      "scenario": "hao-encoder-edge",
      "tier": "primitive",
      "status": "pass"
    },
    {
      "scenario": "hao-encoder-failure",
      "tier": "primitive",
      "status": "pass"
    },
    {
      "scenario": "hao-encoder-golden",
      "tier": "primitive",
      "status": "pass"
    },
    {
      "scenario": "hexagram-resolver-edge",
      "tier": "primitive",
      "status": "pass"
    },
    {
      "scenario": "hexagram-resolver-failure",
      "tier": "primitive",
      "status": "pass"
    },
    {
      "scenario": "hexagram-resolver-golden",
      "tier": "primitive",
      "status": "pass"
    },
    {
      "scenario": "ngu-hanh-classifier-edge",
      "tier": "primitive",
      "status": "pass"
    },
    {
      "scenario": "ngu-hanh-classifier-failure",
      "tier": "primitive",
      "status": "pass"
    },
    {
      "scenario": "ngu-hanh-classifier-golden",
      "tier": "primitive",
      "status": "pass"
    },
    {
      "scenario": "nuclear-hexagram-computer-edge",
      "tier": "primitive",
      "status": "pass"
    },
    {
      "scenario": "nuclear-hexagram-computer-failure",
      "tier": "primitive",
      "status": "pass"
    },
    {
      "scenario": "nuclear-hexagram-computer-golden",
      "tier": "primitive",
      "status": "pass"
    },
    {
      "scenario": "reading-scorer-edge",
      "tier": "primitive",
      "status": "pass"
    },
    {
      "scenario": "reading-scorer-failure",
      "tier": "primitive",
      "status": "pass"
    },
    {
      "scenario": "reading-scorer-golden",
      "tier": "primitive",
      "status": "pass"
    }
  ],
  "modules": [
    {
      "scenario": "reading-composer-edge",
      "tier": "module",
      "status": "pass"
    },
    {
      "scenario": "reading-composer-golden",
      "tier": "module",
      "status": "pass"
    }
  ],
  "summary": {
    "total": 17,
    "passed": 17,
    "failed": 0
  }
};
