// size-justification: 631L — startup helper module bundling scheduler logger,
// report-quality/catch-up guards, T4 idempotency dedup guard, per-cadence-period
// monthly dedup guard (shouldSkipMonthlyReplay, FIX-MONTHLYSIGNALQUALITYAUDITJOB-
// MISSED-JULY-RECOVER-GUARD 2026-08-29: +45L cadence param + guard; 530→631 measured),
// and 6 testable DB-backed cron-callback wrappers sharing the recordJobRun/
// shouldSkipRecoveryReplay contract; splitting would fragment tightly-coupled
// callback+guard pairs.
/**
 * startupHelpers.ts — startup helper functions and DB-backed job wrappers (task 1406e)
 *
 * Contains:
 *   - log()                           shared scheduler logger
 *   - eveningReportIsValid()          report-quality guard (task 1408)
 *   - shouldRunCatchup()              startup catch-up decision helper (task 1430)
 *   - shouldSkipRecoveryReplay()      T4 idempotency dedup guard (T1-ARCH-CRON-T4-DEDUP-GUARDS)
 *   - shouldSkipMonthlyReplay()       per-cadence-period T4 guard for monthly jobs
 *                                     (FIX-MONTHLYSIGNALQUALITYAUDITJOB-MISSED-JULY-RECOVER-GUARD)
 *   - scheduleCron()                  Lever-B single-source wrapper (T2-ARCH-CRON-RECOVER-JITTER)
 *   - scheduleForeignFlowCbReset()    CB startup reset (task 1404)
 *   - run*WithDb()                    six testable cron-callback wrappers (task 1420)
 */

import cron from 'node-cron'
import type { ScheduledTask } from 'node-cron'
import { runWeeklyAudit } from './news-analysis/dataAuditJob.js'
import { runBctcReparseJob } from './financial-reports/bctcReparseJob.js'
import { runEvidenceAccumulator } from './news-analysis/evidenceAccumulatorJob.js'
import { runBaseRateComputation } from './macro/baseRateComputationJob.js'
import { runPredictionResolution } from './macro/predictionResolutionJob.js'
import { runCalibrationReportJob } from './macro/calibrationReportJob.js'
import { recordJobRun } from '../infrastructure/db/cronJobRunStore.js'
import { VN_INDEX_FRESHNESS_MS } from '../domain/services/timeConstants.js'
import { breakers } from '../infrastructure/circuitBreakerRegistry.js'
import type { Database } from 'bun:sqlite'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { VN_OFFSET_MS } from '../domain/services/timeConstants.js'

// ─────────────────────────────────────────────────────────────────────────────
// log — shared scheduler logger
// Exported so startScheduler.ts can import it without creating a second logger.
// ─────────────────────────────────────────────────────────────────────────────
export function log(msg: string): void {
  console.log(`[${new Date().toISOString()}] [SCHEDULER] ${msg}`)
}

// ─────────────────────────────────────────────────────────────────────────────
// eveningReportIsValid — task 1408
//
// Returns true when today's YYYY-MM-DD-evening.json report file exists AND
// contains non-stale data:
//   - vnIndex.fetchedAt is within the last 25 hours, AND
//   - newsCount > 0
//
// Used as the reportCheckFn passed to shouldRunCatchup so the startup-catchup
// skips eveningSummaryJob if a valid report was already generated by the
// scheduled 22:30 cron (or a prior catchup that ran with good data).
//
// reportsDir defaults to "./reports" to match assembleEveningSummary.ts.
// ─────────────────────────────────────────────────────────────────────────────
export function eveningReportIsValid(
  reportsDir: string = './reports',
  nowMs: number = Date.now(),
): boolean {
  try {
    // Compute today's date in Vietnam timezone (UTC+7)
    const vnNow = new Date(nowMs + VN_OFFSET_MS)
    const y = vnNow.getUTCFullYear()
    const m = String(vnNow.getUTCMonth() + 1).padStart(2, '0')
    const d = String(vnNow.getUTCDate()).padStart(2, '0')
    const dateStr = `${y}-${m}-${d}`

    const filePath = join(reportsDir, `${dateStr}-evening.json`)
    if (!existsSync(filePath)) return false

    const raw = readFileSync(filePath, 'utf-8')
    const report = JSON.parse(raw) as {
      vnIndex?: { fetchedAt?: string }
      newsCount?: number
    }

    const fetchedAt = report.vnIndex?.fetchedAt
    if (!fetchedAt) return false

    const ageMs = nowMs - new Date(fetchedAt).getTime()
    const vnIndexFresh = ageMs < VN_INDEX_FRESHNESS_MS

    const newsCount = report.newsCount ?? 0

    return vnIndexFresh && newsCount > 0
  } catch {
    // Any parse / IO error → treat as no valid report (fail-open)
    return false
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// shouldRunCatchup — startup catch-up decision helper (task 1430)
//
// Returns true when:
//   (a) nowUtc is at or past the window threshold (windowUtcHour:windowUtcMin), AND
//   (b) cron_job_runs has no blocking row for jobName since the dedup bound.
//
// The dedup bound is cadence-aware (FIX-MONTHLYSIGNALQUALITYAUDITJOB-MISSED-
// JULY-RECOVER-GUARD, 2026-08-29 — generalised per-day → per-cadence-period):
//   - cadence 'day' (default, unchanged): `started_at >= date('now')`, ANY status —
//     a row today of any status blocks today's catch-up (the next scheduled fire
//     retries a failed job within 24h).
//   - cadence 'month': bound = first day of the CURRENT calendar month (derived
//     from nowUtc), AND only a status='success' row blocks. Rationale: any fire
//     within a calendar month resolves to the SAME prior-month target (a monthly
//     job's next natural chance is a month away), so (i) a success anywhere in the
//     current month proves the current target is already audited — catch-up skips;
//     (ii) an 'error' row is a MISS that must be retried on the next boot, never
//     skipped for a month.
//
// On any DB error returns false (fail-safe — do not fire the job).
// nowUtc defaults to new Date() in production; inject a fixed Date in tests.
// ─────────────────────────────────────────────────────────────────────────────
export function shouldRunCatchup(
  db: Database,
  jobName: string,
  windowUtcHour: number,
  windowUtcMin: number,
  nowUtc: Date = new Date(),
  weekdayOnly: boolean = false,
  reportCheckFn?: () => boolean,
  requiredUtcDay?: number,
  cadence: 'day' | 'month' = 'day',
): boolean {
  if (weekdayOnly) {
    const day = nowUtc.getUTCDay()
    if (day === 0 || day === 6) {
      log(`[startup-catchup] ${jobName}: weekend — skipping (weekdayOnly)`)
      return false
    }
  }

  // FIX-CRON-SUNDAY-STARTUP-CATCHUP: weekly-cadence jobs (e.g. Sunday-only) only
  // get ONE scheduled window per week. node-cron's recoverMissedExecutions
  // (scheduleCron's default) does NOT bridge a process restart — it only replays
  // ticks missed by in-process event-loop lag (Scheduler.start() re-seeds
  // lastCheck/lastExecution fresh from `new Date()` on every construction, i.e.
  // every container boot). If the container is down/mid-restart exactly when a
  // weekly job's single window passes, that whole week is silently lost with NO
  // replay — unlike a daily job, it does not get another chance until next week.
  // requiredUtcDay (0=Sunday..6=Saturday) gates the catchup to fire ONLY on the
  // job's actual scheduled day, mirroring weekdayOnly's day-of-week awareness but
  // requiring an EXACT day rather than excluding a weekend range.
  if (requiredUtcDay !== undefined && nowUtc.getUTCDay() !== requiredUtcDay) {
    log(`[startup-catchup] ${jobName}: not the required UTC day (got ${nowUtc.getUTCDay()}, need ${requiredUtcDay}) — skipping`)
    return false
  }

  const utcHour = nowUtc.getUTCHours()
  const utcMin  = nowUtc.getUTCMinutes()
  const windowReached =
    utcHour > windowUtcHour ||
    (utcHour === windowUtcHour && utcMin >= windowUtcMin)

  if (!windowReached) {
    log(`[startup-catchup] ${jobName}: window not reached (utcHour=${utcHour})`)
    return false
  }

  if (cadence === 'month') {
    // Per-cadence-period dedup (FIX-MONTHLYSIGNALQUALITYAUDITJOB-MISSED-JULY-RECOVER-GUARD):
    // success row started anywhere in the current calendar month ⇒ the current
    // prior-month target is already audited → skip. Success-only: an error row is a
    // miss that must be retried on the next boot (the next natural fire is a month
    // away). Bound derives from nowUtc so tests can pin the month deterministically.
    const monthStartIso = `${nowUtc.getUTCFullYear()}-${String(nowUtc.getUTCMonth() + 1).padStart(2, '0')}-01`
    try {
      const row = db
        .prepare<{ cnt: number }, [string, string]>(
          `SELECT COUNT(*) AS cnt FROM cron_job_runs
           WHERE job_name = ? AND status = 'success' AND started_at >= ?`,
        )
        .get(jobName, monthStartIso)
      if ((row?.cnt ?? 0) > 0) {
        log(`[startup-catchup] ${jobName}: already ran this month — skipping`)
        return false
      }
    } catch {
      log(`[startup-catchup] ${jobName}: DB error — skipping (fail-safe)`)
      return false
    }
    return true
  }

  try {
    const row = db
      .prepare<{ cnt: number }, [string]>(
        `SELECT COUNT(*) AS cnt FROM cron_job_runs
         WHERE job_name = ? AND started_at >= date('now')`,
      )
      .get(jobName)
    if ((row?.cnt ?? 0) > 0) {
      log(`[startup-catchup] ${jobName}: already ran today — skipping`)
      return false
    }
  } catch {
    log(`[startup-catchup] ${jobName}: DB error — skipping (fail-safe)`)
    return false
  }

  // Report-quality guard: if caller supplies a check function and it confirms a
  // valid (non-stale) report already exists for today, skip the catchup — it
  // would only overwrite a good report with potentially empty/stale data.
  if (reportCheckFn !== undefined) {
    try {
      if (reportCheckFn()) {
        log(`[startup-catchup] ${jobName}: valid report already exists — skipping`)
        return false
      }
    } catch {
      // fail-open: if the report check throws, do not suppress the catchup
    }
  }

  return true
}

// ─────────────────────────────────────────────────────────────────────────────
// shouldSkipRecoveryReplay — T4 idempotency dedup guard (T1-ARCH-CRON-T4-DEDUP-GUARDS)
//
// Returns true when a successful (status='success') run for `jobName` exists in
// cron_job_runs whose started_at is within the last `cadenceMs * 0.9` milliseconds.
//
// Design (per architect brief §4.2 Lever 2):
//   - Uses 90% of declared cadence as the safe-skip window.
//   - Only a 'success' status blocks replay; an 'error' row lets the job retry.
//   - On any DB error, returns false (fail-open) — the job proceeds and the
//     underlying idempotency at the SQL layer (T2 jobs) or business guard (T3)
//     provides the last line of defence.
//   - nowMsFn is injectable for deterministic unit tests.
//
// @idempotency T4 — cron_job_runs recency guard; replay skipped if last success < 90% cadence
// ─────────────────────────────────────────────────────────────────────────────
export function shouldSkipRecoveryReplay(
  db: Database,
  jobName: string,
  cadenceMs: number,
  nowMsFn: () => number = () => Date.now(),
): boolean {
  try {
    const windowMs = cadenceMs * 0.9
    const cutoffMs = nowMsFn() - windowMs
    const cutoffIso = new Date(cutoffMs).toISOString().replace('T', ' ').slice(0, 19)

    const row = db
      .prepare<{ cnt: number }, [string, string]>(
        `SELECT COUNT(*) AS cnt FROM cron_job_runs
         WHERE job_name = ?
           AND status = 'success'
           AND started_at >= ?`,
      )
      .get(jobName, cutoffIso)

    if ((row?.cnt ?? 0) > 0) {
      log(`[${jobName}] already ran within cadence window — skipping (recovery dedup)`)
      return true
    }
    return false
  } catch {
    // Table missing or schema mismatch — fail-open (let the job proceed)
    return false
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// shouldSkipMonthlyReplay — per-cadence-period T4 dedup guard
// (FIX-MONTHLYSIGNALQUALITYAUDITJOB-MISSED-JULY-RECOVER-GUARD, 2026-08-29)
//
// Returns true when a SUCCESS run for `jobName` exists in cron_job_runs whose
// started_at falls in the CURRENT calendar month (UTC, bound derived from
// nowUtc). For a 1st-of-month 00:00 UTC job, any fire within a calendar month
// resolves to the SAME prior-month target — so a success anywhere in the current
// month proves the current target's report was already sent. Success-only: an
// 'error' row is a miss that must be retried, never blocked.
//
// This is the in-job T4 guard that makes recoverMissedExecutions: true safe on
// the monthlySignalQualityAuditJob registration (schedulerJobTable.ts): a
// recovery replay / startup catch-up / manual trigger can no longer double-send
// the Telegram WORK report for the same target month.
//
// On any DB error returns false (fail-open — let the job proceed; the job's own
// data idempotency is the last line of defence), matching shouldSkipRecoveryReplay.
// nowUtc is injectable for deterministic unit tests.
//
// @idempotency T4 — per-month cron_job_runs recency guard; replay skipped if a success exists in the current month
// ─────────────────────────────────────────────────────────────────────────────
export function shouldSkipMonthlyReplay(
  db: Database,
  jobName: string,
  nowUtc: Date = new Date(),
): boolean {
  try {
    const monthStartIso = `${nowUtc.getUTCFullYear()}-${String(nowUtc.getUTCMonth() + 1).padStart(2, '0')}-01`
    const row = db
      .prepare<{ cnt: number }, [string, string]>(
        `SELECT COUNT(*) AS cnt FROM cron_job_runs
         WHERE job_name = ?
           AND status = 'success'
           AND started_at >= ?`,
      )
      .get(jobName, monthStartIso)

    if ((row?.cnt ?? 0) > 0) {
      log(`[${jobName}] already sent report for current target month — skipping (monthly dedup)`)
      return true
    }
    return false
  } catch {
    // Table missing or schema mismatch — fail-open (let the job proceed)
    return false
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// scheduleCron — Lever B single-source wrapper (T2-ARCH-CRON-RECOVER-JITTER)
//
// Drop-in replacement for `cron.schedule()` that defaults
// `recoverMissedExecutions: true` across the entire scheduler fleet.
//
// Design rationale (architect brief §4.1):
//   - Applying the option at every individual call site creates drift (53d00955
//     pattern: 3 out of 55 calls patched; recurred on reputationComputeJob).
//   - A single wrapper is the only way to guarantee uniform coverage without
//     per-site drift.
//   - Callers that need to OPT OUT pass `recoverMissedExecutions: false` explicitly.
//     Current opt-outs:
//       * foreignFlowFetch (*/1 * * * *) — fires every 60s; recovery would
//         double-fetch within seconds; underlying job has its own freshness guard.
//     NOTE (FIX-MONTHLYSIGNALQUALITYAUDITJOB-MISSED-JULY-RECOVER-GUARD, 2026-08-29):
//     monthlySignalQualityAudit is NO LONGER an opt-out — its registration now sets
//     recoverMissedExecutions: true as defence-in-depth. Safe because
//     runMonthlySignalQualityJob() carries the shouldSkipMonthlyReplay() T4 guard
//     (per-target-month dedup — a replay/catch-up can never double-send the WORK
//     report), and the real recovery for restart-spanning misses is the startup
//     catch-up probe in startScheduler.ts (shouldRunCatchup cadence='month').
//
// Safety gate: every job covered by recoverMissedExecutions: true MUST satisfy
// at least one idempotency tier (T1/T2/T3/T4) — documented in architect brief §6.
// T1 (T1-ARCH-CRON-T4-DEDUP-GUARDS commit 60b48a9b) validated all fleet jobs
// before this wrapper was applied (T2 depends on T1 per migration plan §5.1).
// ─────────────────────────────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────
// dedupeCronTick — FIX-SCHEDULER-DOUBLE-REGISTRATION (2026-07-29)
//
// RAW-verified LIVE (cron_job_runs, named-volume market.db) BEFORE this fix:
// registration was already singular for every job (startScheduler() itself
// is guarded against re-entrant init via __vnMarketSchedulerStarted) — the
// double-registerJob/re-entrant-init hypothesis in the original bug report
// did NOT hold. The real defect is a genuine EXECUTION-level duplicate,
// traced to node_modules/node-cron@3.0.3's scheduler.js Scheduler.matchTime():
// recoverMissedExecutions: true (Lever B, T2-ARCH-CRON-RECOVER-JITTER) makes
// its `i === 0 || this.autorecover` gate always true, so under ordinary
// ~1s setTimeout-loop jitter (no stall required — the interval routinely
// measures just over 1000ms) the scheduler re-examines the immediately
// preceding second on the next poll. Its "already executed" guard compares
// FULL millisecond precision (`lastExecution.getTime() < date_tmp.getTime()`)
// instead of whole-second granularity, so two polls that straddle the same
// scheduled boundary with different sub-second offsets both pass the guard —
// the identical logical tick fires (and therefore executes) twice. Confirmed
// in-process (one Scheduler instance per job, one Bun process — NOT the
// cowork-team-20260615T1620Z dispatcher-overlap class) and NOT specific to
// the two originally-named jobs (vpsServiceHealthJob 10.33%, walCheckpointJob
// 3.74% showed the identical pattern over the same 7-day window).
//
// Wraps a cron callback with a per-registration whole-second last-fired
// guard: a second detection of the SAME scheduled second is skipped (no
// duplicate execution, no duplicate cron_job_runs row); a genuinely new
// second still fires normally. recoverMissedExecutions stays enabled — the
// missed-fire class ARCH-CRON-SCHEDULER-RELIABILITY fixed is not reverted.
// 'manual'/'init' string invocations (admin-triggered / startup one-shots)
// are never deduped — only real scheduled Date ticks are guarded.
// ─────────────────────────────────────────────────────────────────────────────
export function dedupeCronTick(
  func: (now: Date | 'manual' | 'init') => void,
): (now: Date | 'manual' | 'init') => void {
  let lastFiredSecond: number | null = null
  return (now: Date | 'manual' | 'init') => {
    if (now instanceof Date) {
      const flooredSec = Math.floor(now.getTime() / 1000)
      if (lastFiredSecond === flooredSec) {
        log(`[scheduler-dedup] skipped re-entrant fire for already-executed tick=${now.toISOString()}`)
        return
      }
      lastFiredSecond = flooredSec
    }
    return func(now)
  }
}

export function scheduleCron(
  expression: string,
  func: (now: Date | 'manual' | 'init') => void,
  options: Parameters<typeof cron.schedule>[2] & { recoverMissedExecutions?: boolean } = {},
): ScheduledTask {
  const opts = { recoverMissedExecutions: true, ...options }
  return cron.schedule(expression, dedupeCronTick(func), opts)
}

// ─────────────────────────────────────────────────────────────────────────────
// scheduleForeignFlowCbReset — Task 1404
//
// After a container restart the foreignFlow circuit breaker is always CLOSED
// (in-memory state). However if the VPS pushes a batch BEFORE `runVnstockMigrations`
// has run (or while the DB is briefly locked during startup), 5 consecutive
// upsertForeignFlow failures can trip the breaker to OPEN.
//
// This helper schedules a one-shot reset of `breakers.foreignFlow` after a
// configurable delay (default 60 s). By T+60 s all startup migrations are
// guaranteed to have completed, so the reset gives the VPS a fair chance at
// its first successful push.
//
// Exported for testability. In tests, pass delayMs=0 and a custom CircuitBreaker
// instance so the state check and reset operate on the same object.
//
// @param delayMs   Milliseconds after startup before reset fires (default: 60_000)
// @param cb        Circuit breaker to check and reset (default: breakers.foreignFlow)
// @returns         The setTimeout handle (for teardown in tests)
// ─────────────────────────────────────────────────────────────────────────────
export function scheduleForeignFlowCbReset(
  delayMs: number = parseInt(Bun.env.FOREIGN_FLOW_CB_RESET_DELAY_MS ?? '60000', 10),
  cb: { stats: { state: string }; reset: () => void } = breakers.foreignFlow,
): ReturnType<typeof setTimeout> {
  return setTimeout(() => {
    try {
      const stateBefore = cb.stats.state;
      if (stateBefore !== 'closed') {
        cb.reset();
        log(`[foreign-flow-cb] startup reset fired (was ${stateBefore}) — breaker now CLOSED`);
      } else {
        log('[foreign-flow-cb] startup reset: breaker already CLOSED — no-op');
      }
    } catch (err) {
      log(`[foreign-flow-cb] startup reset error: ${err instanceof Error ? err.message : String(err)}`);
    }
  }, delayMs);
}

// ─────────────────────────────────────────────────────────────────────────────
// Testable cron-callback wrappers — task 1420
//
// Each wrapper calls recordJobRun(db, jobName, fn) so the job name always
// appears in cron_job_runs regardless of which DB is passed. Production cron
// callbacks call these with getDb(); tests inject an in-memory DB and a no-op
// fn to verify observability without running real business logic.
// ─────────────────────────────────────────────────────────────────────────────

/** dataAuditJob:weekly — task 157 */
export async function runWeeklyAuditWithDb(
  db: Database,
  fn: () => Promise<void> = async () => { await runWeeklyAudit() },
): Promise<void> {
  await recordJobRun(db, 'dataAuditJob:weekly', fn)
}

/** bctcReparseJob — task 1019
 *
 * FIX-BCTC-REPARSE-DOUBLE-WRAP-DEDUP-GUARD (2026-07-30): default fn previously called
 * runBctcReparseJob() with NO options — options.db stayed undefined, so
 * runBctcReparseJob()'s own trailing fire-and-forget recordJobRun(...) block
 * (bctcReparseJob.ts:892-896, guarded by `if (!options.db)`) ALSO fired on every real
 * run, alongside THIS wrapper's own recordJobRun(db, 'bctcReparseJob', fn) call — the
 * exact "double-wrap" class already fixed for runEvidenceAccumulatorWithDb and
 * runBaseRateComputationWithDb above (SPIKE-BCTC-REPARSE-CADENCE-GUARD-ROOTCAUSE-VERIFY
 * AC-2). RAW-verified live (docker exec, real market.db, 2026-07-29): 100% of ~90
 * sampled cron_job_runs rows across 11 days had rows_written=NULL (fn discarded
 * runBctcReparseJob()'s real ReparseRunResult, returning void) and 2-7 rows/day (vs.
 * the intended 1x/day). Worse: a guard-skipped invocation still reached recordJobRun
 * via THIS wrapper — it had no shouldSkipRecoveryReplay guard of its own, so even
 * though runBctcReparseJob()'s internal guard (bctcReparseJob.ts:718) early-returned a
 * no-op ReparseRunResult, that resolves WITHOUT throwing, so recordJobRun marked a
 * fresh 'success' row anyway — silently re-arming its own 21.6h dedup window on every
 * restart-timed guard-skip (the best-supported explanation for the 2026-07-10 incident
 * ops "fixed" by falsifying cron_job_runs timestamps instead of using nowMsFn).
 *
 * Fixed the same way as runBaseRateComputationWithDb:
 *   1. T4 shouldSkipRecoveryReplay guard replicated into THIS wrapper, checked BEFORE
 *      recordJobRun, so a guard-skip never reaches recordJobRun at all (no fresh row).
 *   2. Default fn now passes { db } into runBctcReparseJob so it (a) operates on the
 *      SAME db this wrapper was given — correct test injection, matching the core-fn
 *      pattern used by baseRateComputation/evidenceAccumulator — and (b) its own
 *      `if (!options.db)` trailing self-record block is skipped (options.db is now
 *      truthy), eliminating the second recordJobRun call on real runs WITHOUT touching
 *      bctcReparseJob.ts (mirrors the base-rate fix's file-touch footprint exactly).
 *   3. The real ReparseRunResult is now captured and mapped to rowsWritten
 *      (resolved + failed = total feedback rows actually processed this run) instead
 *      of being silently discarded.
 *
 * @idempotency T4 — cron_job_runs recency guard; replay skipped if last success < 90% of daily cadence (21.6h window)
 */
export async function runBctcReparseWithDb(
  db: Database,
  fn: () => Promise<{ rowsWritten?: number } | void> = async () => {
    const result = await runBctcReparseJob({ db })
    return { rowsWritten: result.resolved + result.failed }
  },
): Promise<void> {
  const DAILY_CADENCE_MS = 86_400_000
  if (shouldSkipRecoveryReplay(db, 'bctcReparseJob', DAILY_CADENCE_MS)) {
    log('[bctc-reparse] already ran within cadence window — dedup skip (recoverMissedExecutions guard)')
    return
  }
  await recordJobRun(db, 'bctcReparseJob', fn)
}

/** evidenceAccumulatorJob — task 1118
 *
 * Same-day dedup guard (EVIDENCE-ACCUM-SILENT-CRON fix): if recoverMissedExecutions
 * fires the callback twice on the same UTC day, the second call finds an existing
 * success row and skips — preventing double-work without any observable side-effect
 * (evidence_scores uses UPSERT so a second write is idempotent, but double
 * recordJobRun rows are noisy and the dedup prevents them).
 *
 * Double-wrap fix: fn defaults to runEvidenceAccumulator(db) — the core logic that
 * does NOT itself call recordJobRun. Previous default was runEvidenceAccumulatorJob()
 * which called recordJobRun internally, producing two cron_job_runs rows per tick.
 */
export async function runEvidenceAccumulatorWithDb(
  db: Database,
  fn: () => Promise<{ rowsWritten?: number } | void> = async () => {
    const result = await runEvidenceAccumulator(db)
    return { rowsWritten: result.stocks }
  },
): Promise<void> {
  // Same-day dedup: skip if a success or running row already exists for today UTC.
  // Prevents double-execution when recoverMissedExecutions replays a tick that
  // already ran earlier in the same UTC day.
  try {
    const existing = db
      .prepare<{ cnt: number }, []>(
        `SELECT COUNT(*) AS cnt FROM cron_job_runs
         WHERE job_name = 'evidenceAccumulatorJob'
           AND status IN ('success', 'running')
           AND started_at >= date('now')`,
      )
      .get()
    if ((existing?.cnt ?? 0) > 0) {
      log('[evidence-accumulator] already ran today — dedup skip (recoverMissedExecutions guard)')
      return
    }
  } catch {
    // Table missing in test env — proceed without dedup (fail-open)
  }
  await recordJobRun(db, 'evidenceAccumulatorJob', fn)
}

/** baseRateComputationJob — task 1122
 *
 * FIX-BASE-RATE-COMPUTATION-CRON-DEAD (2026-07-23): default fn previously called
 * the self-recording runBaseRateComputationJob() wrapper (baseRateComputationJob.ts),
 * which ALSO calls recordJobRun internally — the exact "double-wrap" anti-pattern
 * already diagnosed and fixed for runEvidenceAccumulatorWithDb above. RAW-verified
 * live against the production DB (docker exec, real market.db, not an isolated
 * :memory: fixture): every daily 19:07 UTC tick produced 2-3 cron_job_runs rows
 * (1-2 noisy rows_written=NULL rows from this outer wrapper alongside the 1 real
 * rows_written=N row from the inner call) instead of 1 — confirmed on 5 consecutive
 * days (2026-07-19..23, ids 137899-151743). Fixed the same way: default fn now
 * calls the core runBaseRateComputation(db) directly (single recordJobRun call).
 * The T4 shouldSkipRecoveryReplay dedup guard — previously living inside
 * runBaseRateComputationJob(), invisible to a second physical node-cron tick
 * because THIS wrapper (not that one) is what schedulerJobTable.ts actually
 * invokes — is replicated here so a genuine same-window double-fire (node-cron's
 * recoverMissedExecutions catching event-loop-lag ticks, confirmed live: a second
 * tick at 19:07:01, ~1s after the 19:07:00 on-time tick, every day in the sample)
 * still no-ops cleanly with ZERO extra row, matching the dedup-before-recordJobRun
 * shape already used by runEvidenceAccumulatorWithDb.
 */
export async function runBaseRateComputationWithDb(
  db: Database,
  fn: () => Promise<{ rowsWritten?: number } | void> = async () => {
    const result = await runBaseRateComputation(db)
    return { rowsWritten: result.triplesUpserted }
  },
): Promise<void> {
  const DAILY_CADENCE_MS = 86_400_000
  if (shouldSkipRecoveryReplay(db, 'baseRateComputationJob', DAILY_CADENCE_MS)) {
    log('[base-rate-computation] already ran within cadence window — dedup skip (recoverMissedExecutions guard)')
    return
  }
  await recordJobRun(db, 'baseRateComputationJob', fn)
}

/** predictionResolutionJob — task 1125
 *
 * FIX-CRON-JOB-RUNS-DOUBLE-LOG (2026-07-31): default fn previously called the
 * self-recording runPredictionResolutionJob() wrapper (predictionResolutionJob.ts),
 * which ALSO calls recordJobRun internally — the exact "double-wrap" anti-pattern
 * already diagnosed and fixed for runEvidenceAccumulatorWithDb / runBaseRateComputationWithDb
 * / runBctcReparseWithDb above. RAW-verified live (docker exec, real market.db,
 * 2026-07-31): every daily 16:35 UTC tick produced exactly 2 cron_job_runs rows —
 * a rows_written=NULL row from THIS outer wrapper (fn discarded
 * runPredictionResolutionJob()'s void return) immediately followed by a
 * rows_written=N row from the inner self-recording call — on every single day
 * sampled (07-21..07-30, ids 144635/144636 through 173661/173662). Fixed the
 * same way: default fn now calls the core runPredictionResolution(db) directly
 * (single recordJobRun call) and maps its real result to rowsWritten. The T4
 * shouldSkipRecoveryReplay dedup guard — previously living only inside
 * runPredictionResolutionJob(), invisible to a second physical node-cron tick
 * because THIS wrapper (not that one) is what schedulerJobTable.ts actually
 * invokes — is replicated here so a genuine same-window double-fire still
 * no-ops cleanly with ZERO extra row.
 *
 * @idempotency T4 — cron_job_runs recency guard; replay skipped if last success < 90% of daily cadence (21.6h window)
 */
export async function runPredictionResolutionWithDb(
  db: Database,
  fn: () => Promise<{ rowsWritten?: number } | void> = async () => {
    const result = await runPredictionResolution(db)
    return { rowsWritten: result.resolved + result.unresolvable + result.excluded }
  },
): Promise<void> {
  const DAILY_CADENCE_MS = 86_400_000
  if (shouldSkipRecoveryReplay(db, 'predictionResolutionJob', DAILY_CADENCE_MS)) {
    log('[prediction-resolution] already ran within cadence window — dedup skip (recoverMissedExecutions guard)')
    return
  }
  await recordJobRun(db, 'predictionResolutionJob', fn)
}

/** calibrationReportJob — task 1128 */
export async function runCalibrationReportWithDb(
  db: Database,
  fn: () => Promise<void> = async () => { await runCalibrationReportJob() },
): Promise<void> {
  await recordJobRun(db, 'calibrationReportJob', fn)
}
