/**
 * startupHelpers.ts — startup helper functions and DB-backed job wrappers (task 1406e)
 *
 * Contains:
 *   - log()                           shared scheduler logger
 *   - eveningReportIsValid()          report-quality guard (task 1408)
 *   - shouldRunCatchup()              startup catch-up decision helper (task 1430)
 *   - shouldSkipRecoveryReplay()      T4 idempotency dedup guard (T1-ARCH-CRON-T4-DEDUP-GUARDS)
 *   - scheduleCron()                  Lever-B single-source wrapper (T2-ARCH-CRON-RECOVER-JITTER)
 *   - scheduleForeignFlowCbReset()    CB startup reset (task 1404)
 *   - run*WithDb()                    six testable cron-callback wrappers (task 1420)
 */

import cron from 'node-cron'
import type { ScheduledTask } from 'node-cron'
import { runWeeklyAudit } from './news-analysis/dataAuditJob.js'
import { runBctcReparseJob } from './financial-reports/bctcReparseJob.js'
import { runEvidenceAccumulator } from './news-analysis/evidenceAccumulatorJob.js'
import { runBaseRateComputationJob } from './macro/baseRateComputationJob.js'
import { runPredictionResolutionJob } from './macro/predictionResolutionJob.js'
import { runCalibrationReportJob } from './macro/calibrationReportJob.js'
import { recordJobRun } from '../infrastructure/db/cronJobRunStore.js'
import { VN_INDEX_FRESHNESS_MS } from '../domain/services/timeConstants.js'
import { breakers } from '../infrastructure/circuitBreakerRegistry.js'
import type { Database } from 'bun:sqlite'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { VN_OFFSET_MS } from '../domain/services/timeConstants.js'

// ─────────────────────────────────────────────────────────────────────────────
// log — shared scheduler logger
// Exported so startScheduler.ts can import it without creating a second logger.
// ─────────────────────────────────────────────────────────────────────────────
export function log(msg: string): void {
  console.log(`[${new Date().toISOString()}] [SCHEDULER] ${msg}`)
}

// ─────────────────────────────────────────────────────────────────────────────
// eveningReportIsValid — task 1408
//
// Returns true when today's YYYY-MM-DD-evening.json report file exists AND
// contains non-stale data:
//   - vnIndex.fetchedAt is within the last 25 hours, AND
//   - newsCount > 0
//
// Used as the reportCheckFn passed to shouldRunCatchup so the startup-catchup
// skips eveningSummaryJob if a valid report was already generated by the
// scheduled 22:30 cron (or a prior catchup that ran with good data).
//
// reportsDir defaults to "./reports" to match assembleEveningSummary.ts.
// ─────────────────────────────────────────────────────────────────────────────
export function eveningReportIsValid(
  reportsDir: string = './reports',
  nowMs: number = Date.now(),
): boolean {
  try {
    // Compute today's date in Vietnam timezone (UTC+7)
    const vnNow = new Date(nowMs + VN_OFFSET_MS)
    const y = vnNow.getUTCFullYear()
    const m = String(vnNow.getUTCMonth() + 1).padStart(2, '0')
    const d = String(vnNow.getUTCDate()).padStart(2, '0')
    const dateStr = `${y}-${m}-${d}`

    const filePath = join(reportsDir, `${dateStr}-evening.json`)
    if (!existsSync(filePath)) return false

    const raw = readFileSync(filePath, 'utf-8')
    const report = JSON.parse(raw) as {
      vnIndex?: { fetchedAt?: string }
      newsCount?: number
    }

    const fetchedAt = report.vnIndex?.fetchedAt
    if (!fetchedAt) return false

    const ageMs = nowMs - new Date(fetchedAt).getTime()
    const vnIndexFresh = ageMs < VN_INDEX_FRESHNESS_MS

    const newsCount = report.newsCount ?? 0

    return vnIndexFresh && newsCount > 0
  } catch {
    // Any parse / IO error → treat as no valid report (fail-open)
    return false
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// shouldRunCatchup — startup catch-up decision helper (task 1430)
//
// Returns true when:
//   (a) nowUtc is at or past the window threshold (windowUtcHour:windowUtcMin), AND
//   (b) cron_job_runs has no row for jobName with started_at >= date('now').
//
// On any DB error returns false (fail-safe — do not fire the job).
// nowUtc defaults to new Date() in production; inject a fixed Date in tests.
// ─────────────────────────────────────────────────────────────────────────────
export function shouldRunCatchup(
  db: Database,
  jobName: string,
  windowUtcHour: number,
  windowUtcMin: number,
  nowUtc: Date = new Date(),
  weekdayOnly: boolean = false,
  reportCheckFn?: () => boolean,
): boolean {
  if (weekdayOnly) {
    const day = nowUtc.getUTCDay()
    if (day === 0 || day === 6) {
      log(`[startup-catchup] ${jobName}: weekend — skipping (weekdayOnly)`)
      return false
    }
  }

  const utcHour = nowUtc.getUTCHours()
  const utcMin  = nowUtc.getUTCMinutes()
  const windowReached =
    utcHour > windowUtcHour ||
    (utcHour === windowUtcHour && utcMin >= windowUtcMin)

  if (!windowReached) {
    log(`[startup-catchup] ${jobName}: window not reached (utcHour=${utcHour})`)
    return false
  }

  try {
    const row = db
      .prepare<{ cnt: number }, [string]>(
        `SELECT COUNT(*) AS cnt FROM cron_job_runs
         WHERE job_name = ? AND started_at >= date('now')`,
      )
      .get(jobName)
    if ((row?.cnt ?? 0) > 0) {
      log(`[startup-catchup] ${jobName}: already ran today — skipping`)
      return false
    }
  } catch {
    log(`[startup-catchup] ${jobName}: DB error — skipping (fail-safe)`)
    return false
  }

  // Report-quality guard: if caller supplies a check function and it confirms a
  // valid (non-stale) report already exists for today, skip the catchup — it
  // would only overwrite a good report with potentially empty/stale data.
  if (reportCheckFn !== undefined) {
    try {
      if (reportCheckFn()) {
        log(`[startup-catchup] ${jobName}: valid report already exists — skipping`)
        return false
      }
    } catch {
      // fail-open: if the report check throws, do not suppress the catchup
    }
  }

  return true
}

// ─────────────────────────────────────────────────────────────────────────────
// shouldSkipRecoveryReplay — T4 idempotency dedup guard (T1-ARCH-CRON-T4-DEDUP-GUARDS)
//
// Returns true when a successful (status='success') run for `jobName` exists in
// cron_job_runs whose started_at is within the last `cadenceMs * 0.9` milliseconds.
//
// Design (per architect brief §4.2 Lever 2):
//   - Uses 90% of declared cadence as the safe-skip window.
//   - Only a 'success' status blocks replay; an 'error' row lets the job retry.
//   - On any DB error, returns false (fail-open) — the job proceeds and the
//     underlying idempotency at the SQL layer (T2 jobs) or business guard (T3)
//     provides the last line of defence.
//   - nowMsFn is injectable for deterministic unit tests.
//
// @idempotency T4 — cron_job_runs recency guard; replay skipped if last success < 90% cadence
// ─────────────────────────────────────────────────────────────────────────────
export function shouldSkipRecoveryReplay(
  db: Database,
  jobName: string,
  cadenceMs: number,
  nowMsFn: () => number = () => Date.now(),
): boolean {
  try {
    const windowMs = cadenceMs * 0.9
    const cutoffMs = nowMsFn() - windowMs
    const cutoffIso = new Date(cutoffMs).toISOString().replace('T', ' ').slice(0, 19)

    const row = db
      .prepare<{ cnt: number }, [string, string]>(
        `SELECT COUNT(*) AS cnt FROM cron_job_runs
         WHERE job_name = ?
           AND status = 'success'
           AND started_at >= ?`,
      )
      .get(jobName, cutoffIso)

    if ((row?.cnt ?? 0) > 0) {
      log(`[${jobName}] already ran within cadence window — skipping (recovery dedup)`)
      return true
    }
    return false
  } catch {
    // Table missing or schema mismatch — fail-open (let the job proceed)
    return false
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// scheduleCron — Lever B single-source wrapper (T2-ARCH-CRON-RECOVER-JITTER)
//
// Drop-in replacement for `cron.schedule()` that defaults
// `recoverMissedExecutions: true` across the entire scheduler fleet.
//
// Design rationale (architect brief §4.1):
//   - Applying the option at every individual call site creates drift (53d00955
//     pattern: 3 out of 55 calls patched; recurred on reputationComputeJob).
//   - A single wrapper is the only way to guarantee uniform coverage without
//     per-site drift.
//   - Callers that need to OPT OUT pass `recoverMissedExecutions: false` explicitly.
//     Current opt-outs:
//       * foreignFlowFetch (*/1 * * * *) — fires every 60s; recovery would
//         double-fetch within seconds; underlying job has its own freshness guard.
//       * monthlySignalQualityAudit (0 0 1 * *) — sends Telegram WORK alert;
//         lacks shouldSkipRecoveryReplay() guard; monthly frequency makes
//         recovery double-fire extremely low probability but not zero.
//
// Safety gate: every job covered by recoverMissedExecutions: true MUST satisfy
// at least one idempotency tier (T1/T2/T3/T4) — documented in architect brief §6.
// T1 (T1-ARCH-CRON-T4-DEDUP-GUARDS commit 60b48a9b) validated all fleet jobs
// before this wrapper was applied (T2 depends on T1 per migration plan §5.1).
// ─────────────────────────────────────────────────────────────────────────────
export function scheduleCron(
  expression: string,
  func: (now: Date | 'manual' | 'init') => void,
  options: Parameters<typeof cron.schedule>[2] & { recoverMissedExecutions?: boolean } = {},
): ScheduledTask {
  const opts = { recoverMissedExecutions: true, ...options }
  return cron.schedule(expression, func, opts)
}

// ─────────────────────────────────────────────────────────────────────────────
// scheduleForeignFlowCbReset — Task 1404
//
// After a container restart the foreignFlow circuit breaker is always CLOSED
// (in-memory state). However if the VPS pushes a batch BEFORE `runVnstockMigrations`
// has run (or while the DB is briefly locked during startup), 5 consecutive
// upsertForeignFlow failures can trip the breaker to OPEN.
//
// This helper schedules a one-shot reset of `breakers.foreignFlow` after a
// configurable delay (default 60 s). By T+60 s all startup migrations are
// guaranteed to have completed, so the reset gives the VPS a fair chance at
// its first successful push.
//
// Exported for testability. In tests, pass delayMs=0 and a custom CircuitBreaker
// instance so the state check and reset operate on the same object.
//
// @param delayMs   Milliseconds after startup before reset fires (default: 60_000)
// @param cb        Circuit breaker to check and reset (default: breakers.foreignFlow)
// @returns         The setTimeout handle (for teardown in tests)
// ─────────────────────────────────────────────────────────────────────────────
export function scheduleForeignFlowCbReset(
  delayMs: number = parseInt(Bun.env.FOREIGN_FLOW_CB_RESET_DELAY_MS ?? '60000', 10),
  cb: { stats: { state: string }; reset: () => void } = breakers.foreignFlow,
): ReturnType<typeof setTimeout> {
  return setTimeout(() => {
    try {
      const stateBefore = cb.stats.state;
      if (stateBefore !== 'closed') {
        cb.reset();
        log(`[foreign-flow-cb] startup reset fired (was ${stateBefore}) — breaker now CLOSED`);
      } else {
        log('[foreign-flow-cb] startup reset: breaker already CLOSED — no-op');
      }
    } catch (err) {
      log(`[foreign-flow-cb] startup reset error: ${err instanceof Error ? err.message : String(err)}`);
    }
  }, delayMs);
}

// ─────────────────────────────────────────────────────────────────────────────
// Testable cron-callback wrappers — task 1420
//
// Each wrapper calls recordJobRun(db, jobName, fn) so the job name always
// appears in cron_job_runs regardless of which DB is passed. Production cron
// callbacks call these with getDb(); tests inject an in-memory DB and a no-op
// fn to verify observability without running real business logic.
// ─────────────────────────────────────────────────────────────────────────────

/** dataAuditJob:weekly — task 157 */
export async function runWeeklyAuditWithDb(
  db: Database,
  fn: () => Promise<void> = async () => { await runWeeklyAudit() },
): Promise<void> {
  await recordJobRun(db, 'dataAuditJob:weekly', fn)
}

/** bctcReparseJob — task 1019 */
export async function runBctcReparseWithDb(
  db: Database,
  fn: () => Promise<void> = async () => { await runBctcReparseJob() },
): Promise<void> {
  await recordJobRun(db, 'bctcReparseJob', fn)
}

/** evidenceAccumulatorJob — task 1118
 *
 * Same-day dedup guard (EVIDENCE-ACCUM-SILENT-CRON fix): if recoverMissedExecutions
 * fires the callback twice on the same UTC day, the second call finds an existing
 * success row and skips — preventing double-work without any observable side-effect
 * (evidence_scores uses UPSERT so a second write is idempotent, but double
 * recordJobRun rows are noisy and the dedup prevents them).
 *
 * Double-wrap fix: fn defaults to runEvidenceAccumulator(db) — the core logic that
 * does NOT itself call recordJobRun. Previous default was runEvidenceAccumulatorJob()
 * which called recordJobRun internally, producing two cron_job_runs rows per tick.
 */
export async function runEvidenceAccumulatorWithDb(
  db: Database,
  fn: () => Promise<{ rowsWritten?: number } | void> = async () => {
    const result = await runEvidenceAccumulator(db)
    return { rowsWritten: result.stocks }
  },
): Promise<void> {
  // Same-day dedup: skip if a success or running row already exists for today UTC.
  // Prevents double-execution when recoverMissedExecutions replays a tick that
  // already ran earlier in the same UTC day.
  try {
    const existing = db
      .prepare<{ cnt: number }, []>(
        `SELECT COUNT(*) AS cnt FROM cron_job_runs
         WHERE job_name = 'evidenceAccumulatorJob'
           AND status IN ('success', 'running')
           AND started_at >= date('now')`,
      )
      .get()
    if ((existing?.cnt ?? 0) > 0) {
      log('[evidence-accumulator] already ran today — dedup skip (recoverMissedExecutions guard)')
      return
    }
  } catch {
    // Table missing in test env — proceed without dedup (fail-open)
  }
  await recordJobRun(db, 'evidenceAccumulatorJob', fn)
}

/** baseRateComputationJob — task 1122 */
export async function runBaseRateComputationWithDb(
  db: Database,
  fn: () => Promise<void> = async () => { await runBaseRateComputationJob() },
): Promise<void> {
  await recordJobRun(db, 'baseRateComputationJob', fn)
}

/** predictionResolutionJob — task 1125 */
export async function runPredictionResolutionWithDb(
  db: Database,
  fn: () => Promise<void> = async () => { await runPredictionResolutionJob() },
): Promise<void> {
  await recordJobRun(db, 'predictionResolutionJob', fn)
}

/** calibrationReportJob — task 1128 */
export async function runCalibrationReportWithDb(
  db: Database,
  fn: () => Promise<void> = async () => { await runCalibrationReportJob() },
): Promise<void> {
  await recordJobRun(db, 'calibrationReportJob', fn)
}
