#!/usr/bin/env python3
"""gen_traces_js.py — regenerate dashboard/traces.js from all existing trace JSON files.

Called by sandbox/rerun.sh after every runner.py invocation so that
index.html can read traces via <script src="traces.js"> rather than
fetch(), which is blocked under file:// in Chrome/Safari.

Output: dashboard/traces.js
  window.__TRACES = { "<card-id>": <trace-object>, ... };
  window.__TRACES_LOADED_AT = "<ISO-8601-timestamp>";

Card-id convention: trace filename without extension, underscores → hyphens.
  e.g. validate_financial_figures.json  →  "validate-financial-figures"
       financial_reports.json           →  "financial-reports"
       pdf_extractor.json               →  "pdf-extractor"

Missing trace file → card-id key is absent from __TRACES → dashboard shows NOT-RUN (honest default).

SI-2 BOUNDARY: pdf-extractor zone only — do not import or call from other services.
"""

import json
import os
import sys
from datetime import datetime, timezone


def main() -> int:
    # Resolve paths relative to this script's location:
    #   sandbox/gen_traces_js.py  →  ../dashboard/
    script_dir = os.path.dirname(os.path.abspath(__file__))
    service_root = os.path.dirname(script_dir)
    dashboard_dir = os.path.join(service_root, "dashboard")
    traces_dir = os.path.join(dashboard_dir, "traces")
    out_path = os.path.join(dashboard_dir, "traces.js")

    # Tier → list of expected trace basenames (snake_case, no extension).
    # Order matches TRACE_PATHS in index.html for readability.
    tier_files: list[tuple[str, str]] = [
        ("primitive", "validate_financial_figures"),
        ("primitive", "decimal_normalizer"),
        ("primitive", "confidence_scorer"),
        ("primitive", "low_confidence_gate"),
        ("primitive", "ratio_computer"),
        ("primitive", "field_extractor"),
        ("module", "financial_reports"),
        ("service", "pdf_extractor"),
    ]

    traces: dict[str, object] = {}
    errors: list[str] = []

    for tier, name in tier_files:
        json_path = os.path.join(traces_dir, tier, f"{name}.json")
        card_id = name.replace("_", "-")  # snake_case → kebab-case (matches index.html TRACE_PATHS ids)
        if not os.path.exists(json_path):
            # Honest: missing file → card will show NOT-RUN
            continue
        try:
            with open(json_path, encoding="utf-8") as fh:
                data = json.load(fh)
            traces[card_id] = data
        except (OSError, json.JSONDecodeError) as exc:
            errors.append(f"{json_path}: {exc}")

    if errors:
        for err in errors:
            print(f"[gen_traces_js] WARNING: {err}", file=sys.stderr)

    loaded_at = datetime.now(timezone.utc).isoformat()

    # Emit the sidecar JS.
    # Using JSON serialisation ensures correct escaping for all trace values.
    js_lines = [
        "// AUTO-GENERATED by sandbox/gen_traces_js.py — do not edit by hand.",
        "// Regenerated on every sandbox/rerun.sh invocation.",
        "// Loaded via <script src=\"traces.js\"> so index.html works under file:// without fetch().",
        "// SI-2 BOUNDARY: pdf-extractor zone only.",
        f"// Generated: {loaded_at}",
        "",
        f"window.__TRACES_LOADED_AT = {json.dumps(loaded_at)};",
        f"window.__TRACES = {json.dumps(traces, ensure_ascii=False, indent=2)};",
        "",
    ]
    js_content = "\n".join(js_lines)

    os.makedirs(dashboard_dir, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(js_content)

    n = len(traces)
    print(f"[gen_traces_js] wrote {out_path} ({n} trace(s))", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
