// emit.go — Dashboard file emission functions for sandbox runner.
// Extracted from main.go per FACTORY-KINHDICH-split-sandbox.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/vn-market-intelligence/kinh-dich-service/pkg/module/reading_composer"
)

// emitTracesFile writes sandbox-traces.js for dashboard loading
func emitTracesFile(primitives, modules []ScenarioTrace, passed, failed int) error {
	// Get commit hash
	commitHash := getCommitHash()

	traceOutput := TraceOutput{
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		CommitHash:  commitHash,
		Primitives:  primitives,
		Modules:     modules,
	}
	traceOutput.Summary.Total = passed + failed
	traceOutput.Summary.Passed = passed
	traceOutput.Summary.Failed = failed

	jsonBytes, err := json.MarshalIndent(traceOutput, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal trace output: %w", err)
	}

	// Find dashboard directory
	dashboardDir := findDashboardDir()
	if dashboardDir == "" {
		return fmt.Errorf("could not find dashboard directory")
	}

	// Write as JS const for file:// loading (CORS-safe)
	jsContent := fmt.Sprintf(`// AUTO-GENERATED by: CGO_ENABLED=0 go run ./cmd/sandbox -tier=all -scenario=all -emit-traces
// Generated at: %s
// Commit: %s
// DO NOT EDIT MANUALLY — re-run sandbox with -emit-traces to regenerate
// G8 honesty: this file reflects REAL sandbox execution results, not hardcoded values
window.__SANDBOX_TRACES__ = %s;
`, traceOutput.GeneratedAt, commitHash, string(jsonBytes))

	tracesPath := filepath.Join(dashboardDir, "sandbox-traces.js")
	if err := os.WriteFile(tracesPath, []byte(jsContent), 0644); err != nil {
		return fmt.Errorf("write traces file: %w", err)
	}

	fmt.Printf("\n=== TRACES EMITTED ===\n")
	fmt.Printf("File: %s\n", tracesPath)
	fmt.Printf("Scenarios: %d total (%d passed, %d failed)\n", passed+failed, passed, failed)
	fmt.Printf("Commit: %s\n", commitHash)
	fmt.Printf("Timestamp: %s\n", traceOutput.GeneratedAt)

	return nil
}

// emitReferenceFile writes que-reference.js for dashboard loading
func emitReferenceFile() error {
	// Get commit hash
	commitHash := getCommitHash()

	// Get all references
	refs := reading_composer.GetAllQueReferences()
	if len(refs) != 64 {
		return fmt.Errorf("expected 64 references, got %d", len(refs))
	}

	jsonBytes, err := json.MarshalIndent(refs, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal reference data: %w", err)
	}

	// Find dashboard directory
	dashboardDir := findDashboardDir()
	if dashboardDir == "" {
		return fmt.Errorf("could not find dashboard directory")
	}

	// Write as JS const for file:// loading (CORS-safe)
	generatedAt := time.Now().UTC().Format(time.RFC3339)
	jsContent := fmt.Sprintf(`// AUTO-GENERATED by: CGO_ENABLED=0 go run ./cmd/sandbox -emit-reference
// Generated at: %s
// Commit: %s
// DO NOT EDIT MANUALLY — re-run: CGO_ENABLED=0 go run ./cmd/sandbox -emit-reference
window.__QUE_REFERENCE__ = %s;
`, generatedAt, commitHash, string(jsonBytes))

	refPath := filepath.Join(dashboardDir, "que-reference.js")
	if err := os.WriteFile(refPath, []byte(jsContent), 0644); err != nil {
		return fmt.Errorf("write reference file: %w", err)
	}

	fmt.Printf("\n=== REFERENCE EMITTED ===\n")
	fmt.Printf("File: %s\n", refPath)
	fmt.Printf("Entries: %d hexagrams\n", len(refs))
	fmt.Printf("Commit: %s\n", commitHash)
	fmt.Printf("Timestamp: %s\n", generatedAt)

	return nil
}
