/**
 * AUTO-GENERATED from scripts/gen-que-descriptions.ts
 * Source: apps/kinh-dich-service/dashboard/que-reference.js
 *
 * Full Kinh Dịch reference set — all 64 hexagrams with extended Vietnamese detail.
 * DO NOT EDIT manually. Re-run: bun run gen:que
 */

export interface QueDetailDescription {
  id: number;
  name: string;
  chinese: string;
  upper: string;
  lower: string;
  upperElement: string;
  lowerElement: string;
  coreMeaning: string;
  marketTrendLabel: string;
  stateInterpretation: string;
  favorable: string;
  warning: string;
  phases: Array<{
    phase: number;
    action: string;
    outcome: string;
    gloss: string;
  }>;
}

export const QUE_DETAIL: Record<number, QueDetailDescription> = {
  1: {
    id: 1,
    name: `Kien`,
    chinese: `乾`,
    upper: `Qian`,
    lower: `Qian`,
    upperElement: `Kim`,
    lowerElement: `Kim`,
    coreMeaning: `Sức sáng tạo nguyên thủy, năng lượng dương cương kiện không ngừng vận hành`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Thời kỳ phát triển mạnh mẽ, thích hợp khởi nghiệp hoặc mở rộng. Cần giữ liêm chính, đừng kiêu ngạo.`,
    favorable: `Năng lượng dương cực mạnh, vạn sự hanh thông nếu giữ chính đạo.`,
    warning: `Dương cực sinh âm — ở đỉnh cao nhất thì suy thoái đã bắt đầu. Đừng kiêu căng tự mãn.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `CAT`, gloss: `Tích lũy năng lực, chưa nên xuất đầu lộ diện` },
      { phase: 2, action: `TIEN`, outcome: `CAT`, gloss: `Xuất hiện, kết nối với người có ảnh hưởng` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Làm việc chăm chỉ và luôn tự kiểm điểm` },
      { phase: 4, action: `TIEN`, outcome: `CAT`, gloss: `Linh hoạt lựa chọn, không bắt buộc phải tiến` },
      { phase: 5, action: `TIEN`, outcome: `CAT`, gloss: `Phát huy hết năng lực, dẫn dắt người khác` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Biết dừng lại, tránh cực đoan` }
    ],
  },
  2: {
    id: 2,
    name: `Khon`,
    chinese: `坤`,
    upper: `Kun`,
    lower: `Kun`,
    upperElement: `Tho`,
    lowerElement: `Tho`,
    coreMeaning: `Sức tiếp nhận vĩ đại, đức nhu thuận nuôi dưỡng vạn vật`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Phù hợp vai trò hỗ trợ, phó, cố vấn hơn là người dẫn đầu. Xây dựng nền tảng vững chắc, làm việc nhóm.`,
    favorable: `Thuận theo tự nhiên, đừng cố gắng đi đầu mà hãy hỗ trợ.`,
    warning: `Quá mềm mỏng thành nhu nhược. Cần có lập trường chính đạo, không phải chiều theo tất cả.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `CAT`, gloss: `Nhận diện dấu hiệu sớm, phòng ngừa từ đầu` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Hành động theo bản tính ngay thẳng tự nhiên` },
      { phase: 3, action: `GIU`, outcome: `VO CUU`, gloss: `Ẩn tài năng, hoàn thành nhiệm vụ không cầu danh` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Kín đáo, thận trọng, không phô trương` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Phát huy đức trung dung, khiêm tốn mà vẫn rực rỡ` },
      { phase: 6, action: `THAN`, outcome: `LE`, gloss: `Tránh xung đột, biết giới hạn của mình` }
    ],
  },
  3: {
    id: 3,
    name: `Truan`,
    chinese: `屯`,
    upper: `Kan`,
    lower: `Zhen`,
    upperElement: `Thuy`,
    lowerElement: `Moc`,
    coreMeaning: `Khó khăn ban đầu khi vạn vật mới sinh, như hạt mầm nảy từ đất`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
    stateInterpretation: `Khởi nghiệp gian nan, cần người hỗ trợ. Đừng làm một mình, hãy xây dựng đội ngũ.`,
    favorable: `Kiên nhẫn vượt qua giai đoạn khởi đầu sẽ hanh thông.`,
    warning: `Đừng vội vàng, đừng cố một mình. Giai đoạn này cần sự giúp đỡ và kiên nhẫn.`,
    phases: [
      { phase: 1, action: `CHO`, outcome: `LE`, gloss: `Đừng vội tiến, hãy xây nền móng và tìm đồng minh` },
      { phase: 2, action: `CHO`, outcome: `LE`, gloss: `Giữ lập trường, đợi đúng người đúng thời` },
      { phase: 3, action: `LUI`, outcome: `LE`, gloss: `Bỏ cuộc, đừng đuổi theo cơ hội không chắc chắn` },
      { phase: 4, action: `CHO`, outcome: `LE`, gloss: `Chủ động tìm kiếm hợp tác, kết nối` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Chỉ làm việc nhỏ, chưa đủ sức cho việc lớn` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Chấp nhận thất bại, nghỉ ngơi, chờ thời cơ mới` }
    ],
  },
  4: {
    id: 4,
    name: `Mong`,
    chinese: `蒙`,
    upper: `Gen`,
    lower: `Kan`,
    upperElement: `Tho`,
    lowerElement: `Thuy`,
    coreMeaning: `U mê non dại cần được khai sáng, như suối nước từ chân núi chảy ra`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Cần học hỏi và rèn luyện. Tìm thầy giỏi, kiên nhẫn tiếp thu.`,
    favorable: `Khiêm tốn học hỏi, tìm người hướng dẫn.`,
    warning: `Đừng cố chấp trong u mê. Biết mình chưa biết là bước đầu của trí tuệ.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `CAT`, gloss: `Kỷ luật là nền tảng, thiết lập nguyên tắc cơ bản` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Bao dung với người chưa hiểu, kiên nhẫn hướng dẫn` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Đừng chạy theo bề ngoài, sẽ bỏ lỡ bản chất` },
      { phase: 4, action: `CHO`, outcome: `LE`, gloss: `Bị mắc kẹt trong ảo tưởng, chờ thực tế sáng tỏ` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Cởi mở như trẻ thơ, cách tiếp cận hồn nhiên thành công` },
      { phase: 6, action: `GIU`, outcome: `VO CUU`, gloss: `Chấp nhận hậu quả và học hỏi từ sai lầm` }
    ],
  },
  5: {
    id: 5,
    name: `Nhu`,
    chinese: `需`,
    upper: `Kan`,
    lower: `Qian`,
    upperElement: `Thuy`,
    lowerElement: `Kim`,
    coreMeaning: `Chờ đợi đúng thời cơ với niềm tin vững chắc`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Điều kiện đang hình thành nhưng chưa chín muồi. Chờ đợi với sự tự tin, nuôi dưỡng bản thân trong khi cơ hội trưởng thành.`,
    favorable: `Kiên nhẫn chờ đợi với niềm tin mang lại thành công khi thời cơ đến.`,
    warning: `Lo lắng và thiếu kiên nhẫn khi chờ đợi dẫn đến quyết định sai lầm.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `CAT`, gloss: `Chờ ở vùng quen thuộc, giữ vị trí an toàn` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Chờ trên cát, có ma sát nhỏ nhưng an toàn` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Chờ trong bùn, dễ bị tấn công, cần thận trọng` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Chờ trong máu, nguy hiểm rất gần` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Chờ tại bữa tiệc, tận hưởng nhưng vẫn cảnh giác` },
      { phase: 6, action: `GIU`, outcome: `VO CUU`, gloss: `Rơi vào hố, khách không mời đến mang lại giải pháp` }
    ],
  },
  6: {
    id: 6,
    name: `Tung`,
    chinese: `訟`,
    upper: `Qian`,
    lower: `Kan`,
    upperElement: `Kim`,
    lowerElement: `Thuy`,
    coreMeaning: `Tranh chấp và kiện tụng cần được giải quyết`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
    stateInterpretation: `Tranh chấp tạo ra căng thẳng. Tránh kéo dài xung đột, tìm người hòa giải. Lui một phần thường tốt hơn thắng lợi cay đắng.`,
    favorable: `Thỏa hiệp sớm ngăn ngừa leo thang tốn kém.`,
    warning: `Cố chấp trong xung đột cuối cùng gây hại cho tất cả.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Từ bỏ tranh chấp, không kéo dài xung đột` },
      { phase: 2, action: `LUI`, outcome: `VO CUU`, gloss: `Không thể thắng, lui về bảo toàn những gì đang có` },
      { phase: 3, action: `GIU`, outcome: `CAT`, gloss: `Sống nhờ công đức xưa, phước tổ tiên bảo vệ` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Chấp nhận phán quyết, trở về con đường chính đạo` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Thắng kiện qua kênh chính đáng` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Thắng nhưng mất ba lần mỗi ngày, chiến thắng rỗng tuếch` }
    ],
  },
  7: {
    id: 7,
    name: `Su`,
    chinese: `師`,
    upper: `Kun`,
    lower: `Kan`,
    upperElement: `Tho`,
    lowerElement: `Thuy`,
    coreMeaning: `Lực lượng có tổ chức cần kỷ luật và lãnh đạo`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Cần hành động phối hợp quy mô lớn. Thành công phụ thuộc vào lãnh đạo đúng đắn và chuỗi chỉ huy rõ ràng.`,
    favorable: `Chiến thắng qua tổ chức, kỷ luật và lãnh đạo có kinh nghiệm.`,
    warning: `Lãnh đạo kém hoặc kỷ luật lỏng lẻo dẫn đến thất bại và lực lượng tan rã.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Quân đội cần kỷ luật, lực lượng hỗn loạn sẽ thất bại` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Ở giữa quân đội, vị trí trung tâm là may mắn` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Quân đội mang xác, tổn thất từ chỉ huy kém` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Quân đội rút lui có trật tự, rút lui chiến lược thành công` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Thú trong đồng, bắt lấy, hành động chính đáng thành công` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Phong thưởng sai người, sai vị trí` }
    ],
  },
  8: {
    id: 8,
    name: `Ty`,
    chinese: `比`,
    upper: `Kan`,
    lower: `Kun`,
    upperElement: `Thuy`,
    lowerElement: `Tho`,
    coreMeaning: `Liên kết và liên minh tìm kiếm lợi ích chung`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Thời điểm tìm kiếm liên minh và hợp lực. Xem xét kỹ đối tác tiềm năng trước khi cam kết.`,
    favorable: `Hình thành liên minh mạnh với đối tác đáng tin cậy mang lại lợi ích lâu dài.`,
    warning: `Liên kết với đối tác sai hoặc tham gia quá muộn dẫn đến thất vọng.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Liên minh chân thành, sự trung thực mang lại may mắn` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Kết nối từ bên trong, tự sửa mình mang lại vận may` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Đồng hành sai, liên kết với kẻ bất xứng sẽ thất bại` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Kết nối bên ngoài, ủng hộ lãnh đạo xứng đáng thành công` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Liên minh công khai, liên kết rõ ràng là may mắn` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Không có đầu cho liên minh, thiếu lãnh đạo đúng đắn` }
    ],
  },
  9: {
    id: 9,
    name: `Tieu Suc`,
    chinese: `小畜`,
    upper: `Xun`,
    lower: `Qian`,
    upperElement: `Moc`,
    lowerElement: `Kim`,
    coreMeaning: `Thu hoạch nhỏ qua sự kiềm chế nhẹ nhàng`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Tiến bộ lớn bị chặn, tập trung vào lợi ích nhỏ. Mây đen chưa mưa — điều kiện đang tích tụ nhưng chưa giải phóng.`,
    favorable: `Tích lũy nhỏ đều đặn cuối cùng sẽ cho phép đột phá.`,
    warning: `Vượt quá khả năng khi chỉ có thể bước nhỏ dẫn đến thất bại.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `CAT`, gloss: `Trở về con đường, giữ nguyên lối đi quen thuộc` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Kéo nhau trở lại, cùng quay về là may mắn` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Căm xe bung ra, căng thẳng giữa các đối tác` },
      { phase: 4, action: `LUI`, outcome: `HUNG`, gloss: `Thành thật, máu đã hết, sợ hãi cũng tan` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Liên kết chân thành, chia sẻ vận may với láng giềng` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Mưa đến, trăng gần tròn, nguy hiểm nếu thúc ép` }
    ],
  },
  10: {
    id: 10,
    name: `Ly`,
    chinese: `履`,
    upper: `Qian`,
    lower: `Dui`,
    upperElement: `Kim`,
    lowerElement: `Kim`,
    coreMeaning: `Hành xử cẩn thận như dẫm lên đuôi hổ`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Điều hướng địa hình nguy hiểm đòi hỏi cực kỳ cẩn thận. Hành vi đúng đắn và tôn trọng quyền lực giữ bạn an toàn.`,
    favorable: `Hành xử cẩn thận tôn trọng cho phép đi qua nguy hiểm an toàn.`,
    warning: `Hành vi bất cẩn hoặc thiếu tôn trọng kích hoạt sự trả đũa mạnh mẽ.`,
    phases: [
      { phase: 1, action: `TIEN`, outcome: `VO CUU`, gloss: `Hành xử đơn giản, tiến cẩn thận, không sai trong cách tiếp cận khiêm tốn` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Con đường bằng phẳng, người đi một mình thành công` },
      { phase: 3, action: `THAN`, outcome: `HUNG`, gloss: `Mắt một nhìn, chân khập khiễng đi, hổ cắn dù bạo dạn` },
      { phase: 4, action: `THAN`, outcome: `LE`, gloss: `Dẫm lên đuôi hổ, cần cẩn thận tối đa` },
      { phase: 5, action: `LUI`, outcome: `HUNG`, gloss: `Bước đi kiên quyết, kiên trì mang lại nguy hiểm` },
      { phase: 6, action: `GIU`, outcome: `CAT`, gloss: `Nhìn lại bước đi của mình, xem xét hành vi để có điềm tốt` }
    ],
  },
  11: {
    id: 11,
    name: `Thai`,
    chinese: `泰`,
    upper: `Kun`,
    lower: `Qian`,
    upperElement: `Tho`,
    lowerElement: `Kim`,
    coreMeaning: `Thịnh vượng và hài hòa trong mọi thứ`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Trời đất hài hòa, điều kiện tuyệt vời để mở rộng. Đà tăng trưởng mạnh. Hành động quyết đoán khi điều kiện thuận lợi.`,
    favorable: `Mọi nỗ lực đều thịnh vượng, đây là thời điểm hành động tự tin.`,
    warning: `Thịnh vượng ở đỉnh cao bắt đầu suy giảm — chuẩn bị cho sự đảo ngược.`,
    phases: [
      { phase: 1, action: `TIEN`, outcome: `CAT`, gloss: `Nhổ cỏ tận gốc, mở rộng cùng đồng minh` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Ôm lấy vùng hoang, bao dung rộng rãi thành công` },
      { phase: 3, action: `GIU`, outcome: `VO CUU`, gloss: `Không có đồng bằng nào không dốc, kiên định trong thay đổi` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Bay xuống, láng giềng tham gia chân thành` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Hôn nhân mang lại phúc lành, vận may tột đỉnh` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Tường đổ vào hào, hòa bình kết thúc, chuẩn bị cho thay đổi` }
    ],
  },
  12: {
    id: 12,
    name: `Bi`,
    chinese: `否`,
    upper: `Qian`,
    lower: `Kun`,
    upperElement: `Kim`,
    lowerElement: `Tho`,
    coreMeaning: `Trì trệ và cản trở chặn đứng tiến bộ`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
    stateInterpretation: `Giao tiếp bị chặn, nỗ lực gặp kháng cự. Rút lui và bảo tồn nguồn lực. Không phải lúc để mở rộng.`,
    favorable: `Rút lui và tu dưỡng sức mạnh nội tâm trong thời kỳ trì trệ.`,
    warning: `Ép buộc hành động khi bị chặn lãng phí nguồn lực và mời gọi tổn hại.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `CAT`, gloss: `Nhổ cỏ, rễ vướng, rút lui cùng đồng minh` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Ôm lấy và chịu đựng, kẻ tiểu nhân thịnh vượng ngắn ngủi` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Chịu đựng sỉ nhục, hành động sai mang lại hối tiếc` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Khi được gọi, hành động, phục vụ mục đích cao hơn không lỗi` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Trì trệ chấm dứt, người lớn thành công ngay bây giờ` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Lật đổ trì trệ, trước cản trở sau niềm vui` }
    ],
  },
  13: {
    id: 13,
    name: `Dong Nhan`,
    chinese: `同人`,
    upper: `Qian`,
    lower: `Li`,
    upperElement: `Kim`,
    lowerElement: `Hoa`,
    coreMeaning: `Tình bằng hữu và mục đích chung đoàn kết mọi người`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Thành công qua việc hợp nhất với mục tiêu chung. Tụ họp công khai thành công, phe phái bí mật thất bại.`,
    favorable: `Tình bằng hữu minh bạch quanh mục đích chung mang lại thành công tập thể.`,
    warning: `Âm mưu riêng và bè phái độc quyền phá hoại sự đoàn kết.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Tình bạn ở cổng, không lỗi trong khởi đầu công khai` },
      { phase: 2, action: `LUI`, outcome: `HUNG`, gloss: `Tình bạn trong gia tộc, phe phái không dẫn đến đâu tốt` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Giấu vũ khí, nghi ngờ ngăn cản hài hòa` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Leo lên tường, không thể tấn công, trở về hòa bình` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Tình bạn trước khóc sau cười, cuối cùng gặp gỡ` },
      { phase: 6, action: `GIU`, outcome: `VO CUU`, gloss: `Tình bạn ở đồng cỏ, không hối tiếc trong liên minh công khai` }
    ],
  },
  14: {
    id: 14,
    name: `Dai Huu`,
    chinese: `大有`,
    upper: `Li`,
    lower: `Qian`,
    upperElement: `Hoa`,
    lowerElement: `Kim`,
    coreMeaning: `Dồi dào lớn lao và thành công tột đỉnh`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Thịnh vượng đỉnh cao với nguồn lực dồi dào. Vận may tột đỉnh ủng hộ mở rộng táo bạo. Giữ khiêm tốn dù thành công lớn.`,
    favorable: `Trời ủng hộ mọi nỗ lực, hành động táo bạo khi vận may chiếu sáng.`,
    warning: `Kiêu ngạo trong thịnh vượng đẩy nhanh suy thoái không thể tránh.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Không tương tác với hại, tránh vướng víu có hại` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Xe lớn để chất hàng, năng lực cho việc lớn` },
      { phase: 3, action: `GIU`, outcome: `CAT`, gloss: `Hoàng tử dâng lên Thiên tử, kẻ tiểu nhân không thể` },
      { phase: 4, action: `THAN`, outcome: `LE`, gloss: `Không kiêu ngạo, phân biệt bản thân với sự dư thừa` },
      { phase: 5, action: `TIEN`, outcome: `CAT`, gloss: `Thành thật lẫn nhau, trang nghiêm và đáng kính` },
      { phase: 6, action: `TIEN`, outcome: `CAT`, gloss: `Trời ban phúc, vận may tột đỉnh` }
    ],
  },
  15: {
    id: 15,
    name: `Khiem`,
    chinese: `謙`,
    upper: `Kun`,
    lower: `Gen`,
    upperElement: `Tho`,
    lowerElement: `Tho`,
    coreMeaning: `Khiêm tốn và nhún nhường mang lại hoàn thành`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Cách tiếp cận khiêm tốn thành công nơi kiêu ngạo thất bại. Núi hạ xuống đất — giảm dư thừa, bổ sung thiếu hụt.`,
    favorable: `Khiêm tốn mang lại thành công trong mọi nỗ lực và giành được sự tôn trọng lâu dài.`,
    warning: `Ngay cả kiêu ngạo quá mức ẩn giấu cuối cùng cũng lộ ra và gây sụp đổ.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `CAT`, gloss: `Khiêm tốn trong khiêm nhường, vượt sông lớn với sự khiêm tốn` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Khiêm tốn vang vọng, trái tim chính đạo mang lại may mắn` },
      { phase: 3, action: `GIU`, outcome: `CAT`, gloss: `Khiêm tốn có công, hoàn thành đến cùng` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Không gì bất lợi, thể hiện khiêm tốn đúng mức` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Không giàu từ láng giềng, tấn công chính đáng và thành công` },
      { phase: 6, action: `GIU`, outcome: `CAT`, gloss: `Khiêm tốn vang vọng, điều động quân đội đúng cách` }
    ],
  },
  16: {
    id: 16,
    name: `Du`,
    chinese: `豫`,
    upper: `Zhen`,
    lower: `Kun`,
    upperElement: `Moc`,
    lowerElement: `Tho`,
    coreMeaning: `Nhiệt huyết và sẵn sàng vui vẻ cho hành động`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Năng lượng tích tụ cho chuyển động lớn. Thiết lập người giúp đỡ và điều động quân đội. Thời điểm thuận lợi cho hành động nhiệt huyết.`,
    favorable: `Hướng nhiệt huyết vào hành động có tổ chức mang lại kết quả mạnh mẽ.`,
    warning: `Nhiệt huyết rỗng tuếch không chuẩn bị đúng cách dẫn đến thất vọng.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Tuyên bố nhiệt huyết, khoe khoang mời gọi thất bại` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Vững như đá, nhận ra thực tế, hành động trong ngày` },
      { phase: 3, action: `THAN`, outcome: `HOI`, gloss: `Ngước lên tìm nhiệt huyết, hối tiếc nếu chậm trễ` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Nguồn nhiệt huyết, tập hợp đồng minh, thành tựu lớn` },
      { phase: 5, action: `THAN`, outcome: `LE`, gloss: `Bệnh dai dẳng, nhưng không chết, kiên trì` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Nhiệt huyết lầm lạc, đổi hướng nếu tỉnh ngộ` }
    ],
  },
  17: {
    id: 17,
    name: `Tuy`,
    chinese: `隨`,
    upper: `Dui`,
    lower: `Zhen`,
    upperElement: `Kim`,
    lowerElement: `Moc`,
    coreMeaning: `Theo dõi và thích ứng với hoàn cảnh`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Thích ứng với xu hướng thịnh hành thay vì chống lại. Thành công qua sự linh hoạt và đáp ứng.`,
    favorable: `Theo dõi thích ứng các xu hướng xứng đáng mang lại lợi ích không lỗi.`,
    warning: `Theo dõi mù quáng không phân biệt dẫn đến kết quả kém.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `CAT`, gloss: `Thay đổi lãnh đạo, ra ngoài, gặp thành công` },
      { phase: 2, action: `THAN`, outcome: `LE`, gloss: `Bám vào trẻ nhỏ, mất người trưởng thành` },
      { phase: 3, action: `GIU`, outcome: `CAT`, gloss: `Bám vào người trưởng thành, mất trẻ nhỏ, tìm được điều tìm kiếm` },
      { phase: 4, action: `LUI`, outcome: `HUNG`, gloss: `Theo dõi có bắt được, thành thật giữ đường rõ ràng` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Thành thật trong xuất sắc, sắp xếp may mắn` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Bị trói buộc, cần hiến tế núi phía tây` }
    ],
  },
  18: {
    id: 18,
    name: `Co`,
    chinese: `蠱`,
    upper: `Gen`,
    lower: `Xun`,
    upperElement: `Tho`,
    lowerElement: `Moc`,
    coreMeaning: `Sửa chữa sự mục nát và lỗi lầm quá khứ`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Thời điểm sửa chữa vấn đề kế thừa hoặc vị trí bị bỏ quên. Ba ngày trước và sau điểm chuyển đổi — cần chuẩn bị cẩn thận.`,
    favorable: `Sửa chữa quyết tâm các lỗi lầm quá khứ tạo ra cơ hội mới.`,
    warning: `Để tham nhũng không được giải quyết lan rộng thiệt hại hơn nữa.`,
    phases: [
      { phase: 1, action: `THAN`, outcome: `LE`, gloss: `Sự mục nát của cha, con sửa chữa, nguy hiểm rồi thành công` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Sự mục nát của mẹ, cần kiên trì nhẹ nhàng` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Sự mục nát của cha, hối tiếc nhỏ, không lỗi lớn` },
      { phase: 4, action: `THAN`, outcome: `LE`, gloss: `Chịu đựng sự mục nát của cha, đi sẽ mang lại nhục nhã` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Sự mục nát của cha, được khen, công nhận cho sự sửa chữa` },
      { phase: 6, action: `GIU`, outcome: `VO CUU`, gloss: `Không phục vụ vua, đặt tầm nhìn cao hơn chính trị` }
    ],
  },
  19: {
    id: 19,
    name: `Lam`,
    chinese: `臨`,
    upper: `Kun`,
    lower: `Dui`,
    upperElement: `Tho`,
    lowerElement: `Kim`,
    coreMeaning: `Tiếp cận tăng trưởng với đà thuận lợi`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Điều kiện thuận lợi cho tiến bộ và mở rộng. Tiến lên tự tin trong khi đà hỗ trợ. Đến tháng tám, điều kiện thay đổi.`,
    favorable: `Tiến lên quyết đoán trong thời kỳ tiếp cận thuận lợi mang lại thành công lớn.`,
    warning: `Chậm trễ quá lâu bỏ lỡ cửa sổ cơ hội.`,
    phases: [
      { phase: 1, action: `TIEN`, outcome: `CAT`, gloss: `Tiếp cận chung, kiên trì chính đạo mang lại may mắn` },
      { phase: 2, action: `TIEN`, outcome: `CAT`, gloss: `Tiếp cận chung, mọi thứ thuận lợi` },
      { phase: 3, action: `GIU`, outcome: `VO CUU`, gloss: `Tiếp cận thoải mái, không gì bất lợi nếu lo lắng` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Tiếp cận hoàn toàn, không lỗi trong cam kết toàn bộ` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Tiếp cận khôn ngoan, hành vi của hoàng tử lớn thành công` },
      { phase: 6, action: `GIU`, outcome: `CAT`, gloss: `Tiếp cận hào phóng, vận may tốt, không lỗi` }
    ],
  },
  20: {
    id: 20,
    name: `Quan`,
    chinese: `觀`,
    upper: `Xun`,
    lower: `Kun`,
    upperElement: `Moc`,
    lowerElement: `Tho`,
    coreMeaning: `Quan sát và chiêm nghiệm từ vị trí cao`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Thời điểm quan sát cẩn thận trước khi hành động. Nhìn tình hình từ góc nhìn cao. Rửa tay trước khi dâng lễ — chuẩn bị đúng cách.`,
    favorable: `Quan sát rõ ràng cho phép quyết định khôn ngoan khi đến lúc hành động.`,
    warning: `Hành động không hiểu đúng tình hình dẫn đến sai lầm.`,
    phases: [
      { phase: 1, action: `THAN`, outcome: `LE`, gloss: `Nhìn như trẻ con, có thể tha thứ cho kẻ tiểu nhân` },
      { phase: 2, action: `THAN`, outcome: `LE`, gloss: `Nhìn trộm qua cửa, chỉ phù hợp với sự kiên trì của phụ nữ` },
      { phase: 3, action: `GIU`, outcome: `VO CUU`, gloss: `Nhìn cuộc sống của mình, chọn tiến hoặc lùi` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Nhìn vinh quang vương quốc, xứng đáng làm khách của vương quốc` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Nhìn cuộc sống của mình, người quân tử không lỗi` },
      { phase: 6, action: `GIU`, outcome: `CAT`, gloss: `Nhìn cuộc sống của họ, người quân tử không lỗi` }
    ],
  },
  21: {
    id: 21,
    name: `Phe Hap`,
    chinese: `嚙嗑`,
    upper: `Li`,
    lower: `Zhen`,
    upperElement: `Hoa`,
    lowerElement: `Moc`,
    coreMeaning: `Hành động quyết đoán cắn xuyên qua chướng ngại`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Chướng ngại phải được loại bỏ quyết đoán. Như cắn xuyên thịt để hàm hợp lại — cần sửa chữa mạnh mẽ.`,
    favorable: `Hành động quyết đoán quyết tâm dọn sạch chướng ngại và khôi phục trật tự.`,
    warning: `Biện pháp nửa vời để chướng ngại tại chỗ, kéo dài vấn đề.`,
    phases: [
      { phase: 1, action: `THAN`, outcome: `LE`, gloss: `Chân trong gông, hạn chế nhỏ ngăn ngừa sai lầm` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Cắn da, phá mũi trong quá trình, không lỗi` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Cắn thịt khô, gặp độc, hối tiếc nhỏ` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Cắn thịt khô có xương, mũi tên kim loại, kiên trì được đền đáp` },
      { phase: 5, action: `THAN`, outcome: `LE`, gloss: `Cắn thịt khô, tìm thấy vàng, nguy hiểm nhưng không lỗi` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Cổ trong gông, tai biến mất, điếc với cảnh báo` }
    ],
  },
  22: {
    id: 22,
    name: `Bi`,
    chinese: `賌`,
    upper: `Gen`,
    lower: `Li`,
    upperElement: `Tho`,
    lowerElement: `Hoa`,
    coreMeaning: `Vẻ đẹp và trang trí tăng cường bản chất`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Chú ý đến hình thức và trình bày. Vẻ bề ngoài quan trọng nhưng phải bổ sung cho bản chất.`,
    favorable: `Tinh chế có gu từ nền tảng vững chắc tạo ra sức hấp dẫn.`,
    warning: `Trang trí bề ngoài che giấu bản chất yếu cuối cùng thất bại.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Trang trí chân, rời xe và đi bộ khiêm tốn` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Trang trí râu, phong cách theo bản chất` },
      { phase: 3, action: `GIU`, outcome: `CAT`, gloss: `Duyên dáng và ẩm ướt, kiên trì mãi mãi may mắn` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Duyên dáng và trắng, ngựa trắng đến, không phải kẻ cướp` },
      { phase: 5, action: `THAN`, outcome: `LE`, gloss: `Duyên dáng trong vườn, cuộn lụa nhỏ, cuối cùng may mắn` },
      { phase: 6, action: `GIU`, outcome: `VO CUU`, gloss: `Duyên dáng đơn giản, không lỗi trong sự chân thành không trang trí` }
    ],
  },
  23: {
    id: 23,
    name: `Bac`,
    chinese: `剥`,
    upper: `Gen`,
    lower: `Kun`,
    upperElement: `Tho`,
    lowerElement: `Tho`,
    coreMeaning: `Tách rời và xói mòn vị thế`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
    stateInterpretation: `Nền tảng đang sụp đổ, rút lui và bảo tồn những gì còn lại. Hành động bây giờ đẩy nhanh tổn thất.`,
    favorable: `Rút lui và bảo tồn trong thời kỳ tan rã bảo vệ tài sản cốt lõi.`,
    warning: `Cố gắng tiến lên khi đang tan rã phóng đại tổn thất.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Chân giường tách ra, phá hủy sự kiên trì, xui xẻo` },
      { phase: 2, action: `LUI`, outcome: `HUNG`, gloss: `Khung giường tách ra, phá hủy sự kiên trì, xui xẻo` },
      { phase: 3, action: `GIU`, outcome: `VO CUU`, gloss: `Tách ra khỏi họ, không lỗi trong sự chia ly` },
      { phase: 4, action: `LUI`, outcome: `HUNG`, gloss: `Giường tách đến da, gần với thảm họa` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Chuỗi cá, được phụ nữ cung điện ưu ái, mọi thứ có lợi` },
      { phase: 6, action: `GIU`, outcome: `CAT`, gloss: `Quả lớn không ăn, người quý tộc cưỡi, lều nhỏ bị phá` }
    ],
  },
  24: {
    id: 24,
    name: `Phuc`,
    chinese: `復`,
    upper: `Kun`,
    lower: `Zhen`,
    upperElement: `Tho`,
    lowerElement: `Moc`,
    coreMeaning: `Trở về và đổi mới sau khi chạm đáy`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Điểm chuyển đổi đã đạt, ánh sáng trở lại sau bóng tối. Chu kỳ bảy ngày hoàn thành. Khởi đầu mới có thể.`,
    favorable: `Trở về nguyên tắc cơ bản cho phép chu kỳ sản xuất mới.`,
    warning: `Bỏ lỡ cơ hội trở về kéo dài thời kỳ tối tăm không cần thiết.`,
    phases: [
      { phase: 1, action: `TIEN`, outcome: `VO CUU`, gloss: `Trở về từ khoảng cách ngắn, không hối tiếc sâu` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Trở về yên nghỉ, may mắn qua lòng nhân từ` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Trở về lặp lại, nguy hiểm nhưng không lỗi` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Đi giữa người khác, trở về một mình trên đường` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Trở về hào phóng, không hối tiếc trong tự xét mình` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Trở về lạc lối, thảm họa cho quân đội và đất nước` }
    ],
  },
  25: {
    id: 25,
    name: `Vo Vong`,
    chinese: `無妄`,
    upper: `Qian`,
    lower: `Zhen`,
    upperElement: `Kim`,
    lowerElement: `Moc`,
    coreMeaning: `Ngây thơ và những sự việc bất ngờ`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Hành động với sự chân thành không có động cơ ẩn. Sự kiện bất ngờ thử thách sự chính trực của bạn.`,
    favorable: `Hành động ngây thơ chân thành hài hòa với tự nhiên mang lại may mắn.`,
    warning: `Chương trình nghị sự ẩn và kỳ vọng ép buộc mời gọi thảm họa không lường trước.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `CAT`, gloss: `Đi ngây thơ, may mắn qua sự chân thành` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Không đếm thu hoạch, rồi cày mang lại lợi ích` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Thảm họa ngây thơ, bò buộc, người qua đường được lợi` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Có thể kiên trì, không lỗi trong sự kiên định` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Bệnh ngây thơ, không thuốc, hồi phục tự nhiên` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Đi ngây thơ, có thảm họa, không gì thuận lợi` }
    ],
  },
  26: {
    id: 26,
    name: `Dai Suc`,
    chinese: `大畜`,
    upper: `Gen`,
    lower: `Qian`,
    upperElement: `Tho`,
    lowerElement: `Kim`,
    coreMeaning: `Tích lũy lớn quyền lực và nguồn lực`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Nguồn lực đáng kể đã được thu thập, bây giờ triển khai khôn ngoan. Không ăn ở nhà — ra ngoài phục vụ mục đích lớn hơn.`,
    favorable: `Quyền lực tích lũy được triển khai cho mục đích xứng đáng mang lại thành tựu lớn.`,
    warning: `Tích trữ nguồn lực không sử dụng hiệu quả dẫn đến trì trệ.`,
    phases: [
      { phase: 1, action: `THAN`, outcome: `LE`, gloss: `Nguy hiểm hiện diện, dừng lại và tránh tổn hại` },
      { phase: 2, action: `THAN`, outcome: `LE`, gloss: `Dây trục bị tháo, xe không thể tiến` },
      { phase: 3, action: `TIEN`, outcome: `CAT`, gloss: `Theo đuổi ngựa tốt, luyện tập hàng ngày, kiên trì được đền đáp` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Ván đầu bò non, vận may tột đỉnh` },
      { phase: 5, action: `TIEN`, outcome: `CAT`, gloss: `Ngà heo thiến, may mắn qua kiềm chế` },
      { phase: 6, action: `TIEN`, outcome: `CAT`, gloss: `Mang theo đạo trời, thành công và thâm nhập` }
    ],
  },
  27: {
    id: 27,
    name: `Di`,
    chinese: `頤`,
    upper: `Gen`,
    lower: `Zhen`,
    upperElement: `Tho`,
    lowerElement: `Moc`,
    coreMeaning: `Nuôi dưỡng và sinh kế đúng đắn`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Xem xét bạn nuôi dưỡng gì và bạn được nuôi dưỡng như thế nào. Chất lượng đầu vào quyết định chất lượng đầu ra.`,
    favorable: `Nuôi dưỡng đúng đắn cơ thể, tâm trí và vị thế duy trì sức mạnh.`,
    warning: `Lựa chọn nuôi dưỡng kém làm yếu vị thế và mời gọi rắc rối.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Bỏ qua rùa thần, xem người khác ăn, xui xẻo` },
      { phase: 2, action: `LUI`, outcome: `HUNG`, gloss: `Được nuôi dưỡng từ trên, lệch lạc dẫn đến thảm họa viễn chinh` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Quay lưng với nuôi dưỡng, mười năm không kết quả` },
      { phase: 4, action: `LUI`, outcome: `HUNG`, gloss: `Nhìn xuống tìm nuôi dưỡng, hổ nhìn chằm chằm, không lỗi` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Lệch khỏi nguyên tắc, ở nhà may mắn` },
      { phase: 6, action: `THAN`, outcome: `LE`, gloss: `Nguồn nuôi dưỡng, nguy hiểm, vượt sông may mắn` }
    ],
  },
  28: {
    id: 28,
    name: `Dai Qua`,
    chinese: `大過`,
    upper: `Dui`,
    lower: `Xun`,
    upperElement: `Kim`,
    lowerElement: `Moc`,
    coreMeaning: `Gánh nặng phi thường vượt quá năng lực bình thường`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
    stateInterpretation: `Đòn nóc võng xuống từ trọng lượng quá mức. Cần biện pháp phi thường cho tình huống phi thường.`,
    favorable: `Hành động phi thường quyết đoán trong hoàn cảnh đặc biệt thành công.`,
    warning: `Bỏ qua quá tải nghiêm trọng dẫn đến sụp đổ cấu trúc.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Tranh trắng bên dưới, không lỗi trong nền tảng cẩn thận` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Liễu khô nảy mầm, ông già lấy vợ trẻ` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Đòn nóc võng, xui xẻo từ dư thừa` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Đòn nóc được nâng, ý định khác mang lại hối tiếc` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Liễu khô nở hoa, bà già lấy chồng trẻ` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Lội nước chìm đầu, xui xẻo nhưng không lỗi` }
    ],
  },
  29: {
    id: 29,
    name: `Tap Kham`,
    chinese: `坎`,
    upper: `Kan`,
    lower: `Kan`,
    upperElement: `Thuy`,
    lowerElement: `Thuy`,
    coreMeaning: `Hiểm trở chồng hiểm trở, hố sâu nối hố sâu`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
    stateInterpretation: `Nguy hiểm chồng nguy hiểm, hố trong hố. Giữ lòng thành tín bên trong khi điều hướng nguy hiểm. Chảy như nước — đổ đầy từng hố rồi đi tiếp.`,
    favorable: `Kiên trì qua nguy hiểm với sự thật bên trong cuối cùng tìm thấy lối đi.`,
    warning: `Hoảng loạn hoặc liều lĩnh trong nguy hiểm làm xấu đi tình hình nghiêm trọng.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Hố lặp lại, rơi vào lỗ, lạc trong vực sâu` },
      { phase: 2, action: `LUI`, outcome: `HUNG`, gloss: `Hố có nguy hiểm, chỉ có thể đạt được thành quả nhỏ` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Đến đi, hố chồng hố, nghỉ trước khi chìm` },
      { phase: 4, action: `THAN`, outcome: `LE`, gloss: `Bình rượu, hai bát, sự chân thành đơn giản kết nối` },
      { phase: 5, action: `LUI`, outcome: `HUNG`, gloss: `Hố chưa tràn, gần bằng, không lỗi` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Bị trói bằng dây, ba năm bị giam, xui xẻo` }
    ],
  },
  30: {
    id: 30,
    name: `Ly`,
    chinese: `離`,
    upper: `Li`,
    lower: `Li`,
    upperElement: `Hoa`,
    lowerElement: `Hoa`,
    coreMeaning: `Bám víu vào ánh sáng và sự rõ ràng`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Lửa bám vào nhiên liệu — phụ thuộc vào hỗ trợ đúng đắn. Sự rõ ràng chiếu sáng nhưng cũng phơi bày.`,
    favorable: `Bám víu vào hỗ trợ đúng đắn và duy trì sự rõ ràng mang lại may mắn.`,
    warning: `Bám víu vào hỗ trợ sai hoặc ánh sáng chói tạo ra kiệt sức.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Bước đi bối rối, tôn trọng tránh bị đổ lỗi` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Ánh sáng vàng, vận may tột đỉnh ở trung tâm` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Ánh sáng mặt trời lặn, không có bài hát trống, tuổi già thở dài` },
      { phase: 4, action: `LUI`, outcome: `HUNG`, gloss: `Đến đột ngột, cháy, chết, bị bỏ` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Nước mắt chảy, thở dài và than khóc, may mắn` },
      { phase: 6, action: `GIU`, outcome: `CAT`, gloss: `Cuộc viễn chinh trừng phạt của vua, khen ngợi vì đập đầu` }
    ],
  },
  31: {
    id: 31,
    name: `Ham`,
    chinese: `咸`,
    upper: `Dui`,
    lower: `Gen`,
    upperElement: `Kim`,
    lowerElement: `Tho`,
    coreMeaning: `Ảnh hưởng và thu hút lẫn nhau`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Hồ trên núi — tiếp nhận bên dưới, vững chắc bên trên tạo ra sức hút. Thành công qua cầu hôn đúng cách.`,
    favorable: `Thu hút và đáp ứng lẫn nhau chân chính tạo ra mối quan hệ lâu dài.`,
    warning: `Theo đuổi một chiều không có sự đáp lại dẫn đến thất vọng.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Ảnh hưởng ở ngón chân cái, mới bắt đầu khuấy động` },
      { phase: 2, action: `LUI`, outcome: `HUNG`, gloss: `Ảnh hưởng ở bắp chân, ở lại là may mắn` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Ảnh hưởng ở đùi, theo người khác, hối tiếc` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Kiên trì may mắn, suy nghĩ dao động tan tác` },
      { phase: 5, action: `GIU`, outcome: `VO CUU`, gloss: `Ảnh hưởng ở lưng, không hối tiếc trong quyết tâm vững chắc` },
      { phase: 6, action: `THAN`, outcome: `LE`, gloss: `Ảnh hưởng ở hàm, lời nói rỗng không đạt được gì` }
    ],
  },
  32: {
    id: 32,
    name: `Hang`,
    chinese: `恆`,
    upper: `Zhen`,
    lower: `Xun`,
    upperElement: `Moc`,
    lowerElement: `Moc`,
    coreMeaning: `Sự bền bỉ và kiên trì lâu dài`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Sấm và gió củng cố lẫn nhau trong mô hình lâu dài. Thành công qua cam kết vững chắc.`,
    favorable: `Cam kết kiên trì với con đường xứng đáng mang lại thành công lâu dài.`,
    warning: `Bồn chồn và thay đổi liên tục ngăn cản thành tựu có ý nghĩa.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Tìm kiếm độ bền sâu, xui xẻo dai dẳng` },
      { phase: 2, action: `THAN`, outcome: `LE`, gloss: `Hối tiếc biến mất, rút lui khỏi vượt quá` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Không làm đức hạnh bền, có thể xấu hổ` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Không có thú trong đồng, không có gì để săn` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Làm đức hạnh bền, vợ may mắn, chồng xui xẻo` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Độ bền bồn chồn, không gì thuận lợi trong biến đổi` }
    ],
  },
  33: {
    id: 33,
    name: `Don`,
    chinese: `遁`,
    upper: `Qian`,
    lower: `Gen`,
    upperElement: `Kim`,
    lowerElement: `Tho`,
    coreMeaning: `Rút lui chiến lược và rút lui`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Núi dưới trời — người quân tử xa cách kẻ tiểu nhân. Rút lui có trật tự bảo tồn sức mạnh.`,
    favorable: `Rút lui chiến lược kịp thời bảo tồn nguồn lực cho tiến bước tương lai.`,
    warning: `Không rút lui khi được chỉ định dẫn đến vướng víu và mất mát.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Đuôi rút lui, nguy hiểm, không đuổi theo` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Bị trói bằng da bò vàng, không thể nới lỏng` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Rút lui vướng víu, kiệt sức và nguy hiểm` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Rút lui tốt, người quân tử may mắn` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Rút lui xuất sắc, kiên trì may mắn` },
      { phase: 6, action: `GIU`, outcome: `CAT`, gloss: `Rút lui giàu có, không gì bất lợi` }
    ],
  },
  34: {
    id: 34,
    name: `Dai Trang`,
    chinese: `大壯`,
    upper: `Zhen`,
    lower: `Qian`,
    upperElement: `Moc`,
    lowerElement: `Kim`,
    coreMeaning: `Quyền lực lớn và sức mạnh áp đảo`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Sấm trên trời — quyền lực thể hiện mạnh mẽ. Chính đạo phải hướng dẫn quyền lực.`,
    favorable: `Quyền lực lớn áp dụng chính đạo đạt được thành tựu lớn.`,
    warning: `Quyền lực áp dụng kiêu ngạo hoặc bất cẩn trở nên tự hủy.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Quyền lực ở ngón chân, tiến về phía trước mời gọi thảm họa` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Kiên trì may mắn, quyền lực chính đạo thành công` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Kẻ tiểu nhân sử dụng quyền lực, người quân tử kiêng cữ` },
      { phase: 4, action: `TIEN`, outcome: `CAT`, gloss: `Kiên trì may mắn, hàng rào mở, dê cừu được tự do` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Mất dê dễ dàng, không hối tiếc trong sự tách rời` },
      { phase: 6, action: `THAN`, outcome: `LE`, gloss: `Dê húc hàng rào, không thể rút lui hay tiến` }
    ],
  },
  35: {
    id: 35,
    name: `Tan`,
    chinese: `晉`,
    upper: `Li`,
    lower: `Kun`,
    upperElement: `Hoa`,
    lowerElement: `Tho`,
    coreMeaning: `Tiến bộ và tiến vào ánh sáng`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Mặt trời mọc trên đất — chiếu sáng nhanh chóng và được công nhận. Tiến bộ được ưa chuộng trên nhiều mặt trận.`,
    favorable: `Tiến vào sự rõ ràng mang lại sự công nhận và phần thưởng.`,
    warning: `Chống lại tiến bộ tự nhiên hoặc ẩn trong bóng tối lãng phí cơ hội.`,
    phases: [
      { phase: 1, action: `THAN`, outcome: `LE`, gloss: `Tiến lên, bị đẩy lùi, kiên trì may mắn` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Tiến lên, đau buồn, kiên trì may mắn qua kiên nhẫn` },
      { phase: 3, action: `GIU`, outcome: `CAT`, gloss: `Mọi hối tiếc biến mất, được đám đông tin tưởng` },
      { phase: 4, action: `THAN`, outcome: `LE`, gloss: `Tiến như chuột hamster, kiên trì nguy hiểm` },
      { phase: 5, action: `GIU`, outcome: `VO CUU`, gloss: `Hối tiếc biến mất, được mất không liên quan` },
      { phase: 6, action: `THAN`, outcome: `LE`, gloss: `Tiến với sừng, chỉ để khuất phục thành phố` }
    ],
  },
  36: {
    id: 36,
    name: `Minh Di`,
    chinese: `明夷`,
    upper: `Kun`,
    lower: `Li`,
    upperElement: `Tho`,
    lowerElement: `Hoa`,
    coreMeaning: `Ánh sáng bị thương và che giấu`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
    stateInterpretation: `Ánh sáng bị đẩy xuống ngầm — trí tuệ phải ẩn trong thời kỳ tối tăm. Kiên trì bên trong trong khi bề ngoài bình thường.`,
    favorable: `Che giấu sự rực rỡ trong thời kỳ tối tăm bảo tồn khả năng hành động sau.`,
    warning: `Thể hiện sự rực rỡ trong môi trường thù địch mời gọi sự đàn áp.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Ánh sáng tối trong chuyến bay, cánh rũ xuống, nhịn ăn` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Ánh sáng tối, đùi trái, cứu ngựa thành công` },
      { phase: 3, action: `GIU`, outcome: `CAT`, gloss: `Ánh sáng tối săn phía nam, bắt được lãnh đạo lớn` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Vào bụng trái, lấy trái tim của ánh sáng tối` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Ánh sáng tối của Cơ Tử, kiên trì có lợi` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Không sáng mà tối, trước lên sau rơi` }
    ],
  },
  37: {
    id: 37,
    name: `Gia Nhan`,
    chinese: `家人`,
    upper: `Xun`,
    lower: `Li`,
    upperElement: `Moc`,
    lowerElement: `Hoa`,
    coreMeaning: `Trật tự gia đình và mối quan hệ đúng đắn`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Gió từ lửa — lời nói phải có thực chất. Trật tự bên trong cho phép hiệu quả bên ngoài.`,
    favorable: `Tổ chức nội bộ đúng đắn tạo nền tảng cho thành công bên ngoài.`,
    warning: `Rối loạn ở nhà phá hoại mọi nỗ lực bên ngoài.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Bao quanh trong nhà, hối tiếc biến mất qua trật tự` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Không có gì để theo đuổi, chăm sóc tiếp tế bên trong` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Thành viên gia đình càu nhàu, hối tiếc nhưng nguy hiểm qua` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Làm giàu gia đình, vận may lớn` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Vua tiếp cận gia đình, không lo lắng, yêu thương lẫn nhau` },
      { phase: 6, action: `GIU`, outcome: `CAT`, gloss: `Chân thành và có uy quyền, kết luận may mắn` }
    ],
  },
  38: {
    id: 38,
    name: `Khue`,
    chinese: `睡`,
    upper: `Li`,
    lower: `Dui`,
    upperElement: `Hoa`,
    lowerElement: `Kim`,
    coreMeaning: `Đối lập và xa cách`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Lửa trên hồ — các yếu tố phân kỳ. Việc nhỏ có thể dù đối lập. Hoàn cảnh lạ đòi hỏi phản ứng không thông thường.`,
    favorable: `Quản lý đối lập qua các bước nhỏ và phương pháp gián tiếp.`,
    warning: `Ép buộc giải quyết đối lập sâu tạo ra xung đột lớn hơn.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Hối tiếc biến mất, ngựa lạc trở về tự nhiên` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Gặp thầy trong ngõ, không lỗi trong cuộc gặp không chính thức` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Xe bị kéo, bò dừng, đàn ông xăm, khởi đầu xấu kết thúc tốt` },
      { phase: 4, action: `THAN`, outcome: `LE`, gloss: `Cô lập trong đối lập, gặp người lớn, trao đổi chân thành` },
      { phase: 5, action: `THAN`, outcome: `LE`, gloss: `Hối tiếc biến mất, tổ tiên cắn da, không lỗi khi đi` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Cô lập trong đối lập, lợn với bùn, ma trong xe` }
    ],
  },
  39: {
    id: 39,
    name: `Kien`,
    chinese: `蹇`,
    upper: `Kan`,
    lower: `Gen`,
    upperElement: `Thuy`,
    lowerElement: `Tho`,
    coreMeaning: `Chướng ngại và khó khăn phía trước`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
    stateInterpretation: `Nước trên núi — con đường nguy hiểm. Tây nam thuận lợi, đông bắc bất lợi. Gặp người lớn để được hướng dẫn.`,
    favorable: `Nhận ra chướng ngại sớm cho phép tái định vị chiến lược.`,
    warning: `Đẩy về phía trước vào chướng ngại rõ ràng phóng đại khó khăn.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Đi chướng ngại, đến khen ngợi, chờ con đường tốt hơn` },
      { phase: 2, action: `LUI`, outcome: `HUNG`, gloss: `Người hầu của vua: chướng ngại chồng chướng ngại, không phải việc của mình` },
      { phase: 3, action: `GIU`, outcome: `CAT`, gloss: `Đi chướng ngại, đến trở về, niềm vui nội tâm khi quay lại` },
      { phase: 4, action: `LUI`, outcome: `HUNG`, gloss: `Đi chướng ngại, đến kết nối, hợp lực` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Chướng ngại lớn, bạn bè đến, đồng minh đến` },
      { phase: 6, action: `GIU`, outcome: `CAT`, gloss: `Đi chướng ngại, đến sự vĩ đại, may mắn gặp người lớn` }
    ],
  },
  40: {
    id: 40,
    name: `Giai`,
    chinese: `解`,
    upper: `Zhen`,
    lower: `Kan`,
    upperElement: `Moc`,
    lowerElement: `Thuy`,
    coreMeaning: `Giải phóng và giải thoát khỏi căng thẳng`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Sấm và mưa — sự giải thoát đến. Tây nam thuận lợi; trở về nhanh nếu không có gì để theo đuổi.`,
    favorable: `Hành động quyết đoán nhanh chóng khi cơ hội xuất hiện hoàn thành giải phóng.`,
    warning: `Trì hoãn hành động khi có thể giải phóng cho phép vướng víu lại.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Không lỗi, giải phóng đơn giản không phức tạp` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Bắt ba con cáo, mũi tên vàng, vận may chính đạo` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Mang và cưỡi, thu hút cướp, hối tiếc` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Giải phóng ngón cái, bạn đến với sự tin tưởng` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Giải phóng của người quý tộc, kẻ tiểu nhân rút lui, may mắn` },
      { phase: 6, action: `GIU`, outcome: `CAT`, gloss: `Hoàng tử bắn diều hâu trên tường, bắt được, mọi thứ thuận lợi` }
    ],
  },
  41: {
    id: 41,
    name: `Ton`,
    chinese: `損`,
    upper: `Gen`,
    lower: `Dui`,
    upperElement: `Tho`,
    lowerElement: `Kim`,
    coreMeaning: `Giảm bớt và cắt giảm chiến lược`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Hồ ở chân núi — giảm trên làm giàu dưới. Dâng lễ chân thành với đồ đơn giản thành công.`,
    favorable: `Cắt giảm chiến lược ở các khu vực đúng củng cố vị thế cốt lõi.`,
    warning: `Bám víu vào dư thừa cạn kiệt nguồn lực cần thiết cho những thứ thiết yếu.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Hoàn thành nhiệm vụ nhanh, đi, không lỗi, xem xét giảm` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Kiên trì có lợi, đi là xui xẻo` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Ba người đi, một người lạc, một người đi được bạn` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Giảm bệnh tật của mình, mang lại niềm vui nhanh, không lỗi` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Ai đó thêm mười cặp, không thể chống lại, vận may tột đỉnh` },
      { phase: 6, action: `TIEN`, outcome: `CAT`, gloss: `Không giảm, tăng, không lỗi, kiên trì may mắn` }
    ],
  },
  42: {
    id: 42,
    name: `Ich`,
    chinese: `益`,
    upper: `Xun`,
    lower: `Zhen`,
    upperElement: `Moc`,
    lowerElement: `Moc`,
    coreMeaning: `Tăng trưởng và phát triển có lợi`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Gió và sấm — tăng trưởng qua chuyển động. Thuận lợi để vượt sông lớn. Lợi ích chảy xuống từ trên.`,
    favorable: `Tận dụng sự tăng trưởng thuận lợi cho phép đạt được thành tựu lớn.`,
    warning: `Không sử dụng sự tăng trưởng hiệu quả lãng phí cơ hội.`,
    phases: [
      { phase: 1, action: `TIEN`, outcome: `CAT`, gloss: `Có lợi cho công trình lớn, vận may tột đỉnh, không lỗi` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Ai đó thêm mười cặp, kiên trì vĩnh cửu may mắn` },
      { phase: 3, action: `GIU`, outcome: `CAT`, gloss: `Được tăng bởi sự kiện xấu, không lỗi, chân thành ở giữa` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Con đường giữa, thông báo cho hoàng tử, có lợi cho việc di chuyển thủ đô` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Lòng tốt chân thành, không cần hỏi, vận may tột đỉnh` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Không ai tăng, một số tấn công nó, trái tim không kiên định` }
    ],
  },
  43: {
    id: 43,
    name: `Quai`,
    chinese: `夬`,
    upper: `Dui`,
    lower: `Qian`,
    upperElement: `Kim`,
    lowerElement: `Kim`,
    coreMeaning: `Đột phá quyết định và giải quyết`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Hồ dâng lên trời — đột phá phải đến. Thông báo tại triều đình; nguy hiểm phải được nêu rõ.`,
    favorable: `Đột phá quyết định thay thế những gì phải được loại bỏ.`,
    warning: `Đột phá không hoàn chỉnh cho phép đối lập phục hồi.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Quyền lực ở ngón chân tiến lên, đi mà không thành thạo thất bại` },
      { phase: 2, action: `THAN`, outcome: `LE`, gloss: `Tiếng kêu báo động, vũ khí sẵn sàng, không sợ dù buổi tối` },
      { phase: 3, action: `GIU`, outcome: `CAT`, gloss: `Quyền lực ở gò má, xui xẻo, người quý tộc quyết tâm` },
      { phase: 4, action: `THAN`, outcome: `LE`, gloss: `Mông bị lột da, đi khó khăn, dẫn cừu, hối tiếc biến mất` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Cỏ dại bị gãy, con đường giữa, không lỗi` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Không khóc, cuối cùng xui xẻo đến` }
    ],
  },
  44: {
    id: 44,
    name: `Cau`,
    chinese: `姤`,
    upper: `Qian`,
    lower: `Xun`,
    upperElement: `Kim`,
    lowerElement: `Moc`,
    coreMeaning: `Cuộc gặp gỡ bất ngờ và cám dỗ`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
    stateInterpretation: `Gió dưới trời — cuộc gặp gỡ dâng lên bất ngờ. Âm đột ngột xâm nhập vào dương.`,
    favorable: `Phản ứng thận trọng với cuộc gặp gỡ bất ngờ tránh bị bẫy.`,
    warning: `Nhượng bộ trước vẻ ngoài quyến rũ dẫn đến vướng víu bất lợi.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Bị trói bằng phanh kim loại, kiên trì may mắn` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Cá trong túi, không lỗi, không dành cho khách` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Mông bị lột da, đi khó khăn, nhận thức nguy hiểm` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Không có cá trong túi, xui xẻo dâng lên từ sự vắng mặt` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Liễu bọc dưa, được chứa, rơi từ trời` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Đến gặp với sừng, hối tiếc nhưng không lỗi` }
    ],
  },
  45: {
    id: 45,
    name: `Tuy`,
    chinese: `萃`,
    upper: `Dui`,
    lower: `Kun`,
    upperElement: `Kim`,
    lowerElement: `Tho`,
    coreMeaning: `Tụ họp và hội họp`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Hồ trên đất — nước tụ họp. Vua tiếp cận đền; gặp người lớn. Dâng lễ lớn mang lại thành công.`,
    favorable: `Tụ họp đúng đắn dưới lãnh đạo đúng hoàn thành những việc lớn.`,
    warning: `Tụ họp không có tổ chức không có mục đích dẫn đến hỗn loạn.`,
    phases: [
      { phase: 1, action: `THAN`, outcome: `LE`, gloss: `Chân thành nhưng không hoàn chỉnh, rối loạn rồi tụ họp` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Bị kéo, may mắn, không lỗi, chân thành trong dâng lễ` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Tụ họp thở dài, không gì thuận lợi, đi không lỗi` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Vận may lớn, không lỗi ở vị trí trung tâm` },
      { phase: 5, action: `GIU`, outcome: `VO CUU`, gloss: `Tụ họp có vị trí, không lỗi, chưa được tin` },
      { phase: 6, action: `THAN`, outcome: `LE`, gloss: `Thở dài và khóc, không lỗi trong nước mắt cuối cùng` }
    ],
  },
  46: {
    id: 46,
    name: `Thang`,
    chinese: `升`,
    upper: `Kun`,
    lower: `Xun`,
    upperElement: `Tho`,
    lowerElement: `Moc`,
    coreMeaning: `Leo lên dần dần và tiến bộ`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Cây mọc từ đất — tăng trưởng đi lên ổn định. Gặp người lớn không sợ. Viễn chinh về phía nam mang lại may mắn.`,
    favorable: `Nỗ lực kiên trì ổn định đạt được tiến bộ lâu dài.`,
    warning: `Vội vàng leo lên trước khi sẵn sàng dẫn đến thất bại.`,
    phases: [
      { phase: 1, action: `TIEN`, outcome: `CAT`, gloss: `Được chào đón đi lên, vận may lớn` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Chân thành làm cho dâng lễ có giá trị, không lỗi` },
      { phase: 3, action: `TIEN`, outcome: `CAT`, gloss: `Leo lên thành phố trống, không có kháng cự` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Vua dâng lễ tại Núi Kỳ, may mắn, không lỗi` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Kiên trì may mắn, leo cầu thang từng bước` },
      { phase: 6, action: `GIU`, outcome: `VO CUU`, gloss: `Leo lên trong bóng tối, kiên trì không ngừng có lợi` }
    ],
  },
  47: {
    id: 47,
    name: `Khon`,
    chinese: `困`,
    upper: `Dui`,
    lower: `Kan`,
    upperElement: `Kim`,
    lowerElement: `Thuy`,
    coreMeaning: `Kiệt sức và giam cầm`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
    stateInterpretation: `Hồ không có nước — cạn kiệt và bị giam cầm. Lời nói không được tin. Kiệt sức thử thách nhân cách.`,
    favorable: `Duy trì sự chính trực trong thời kỳ áp bức bảo tồn cơ hội tương lai.`,
    warning: `Tuyệt vọng hoặc thỏa hiệp sự chính trực trong thời kỳ áp bức phá hủy triển vọng.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Mông bị đè bởi gốc cây, ba năm không thấy` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Bị đè bởi rượu và thức ăn, băng đầu gối đỏ tươi đến` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Bị đè bởi đá, nghỉ trên gai, không thấy vợ` },
      { phase: 4, action: `LUI`, outcome: `HUNG`, gloss: `Đến chậm, bị đè trong xe vàng, hối tiếc, kết thúc` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Mũi và chân bị cắt, bị đè bởi băng đầu gối đỏ, từ từ vui` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Bị đè bởi dây leo, nói di chuyển mang lại hối tiếc` }
    ],
  },
  48: {
    id: 48,
    name: `Tinh`,
    chinese: `井`,
    upper: `Kan`,
    lower: `Xun`,
    upperElement: `Thuy`,
    lowerElement: `Moc`,
    coreMeaning: `Nguồn vô tận và nền tảng`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Gỗ trên nước — giếng kéo từ sâu. Thị trấn có thể thay đổi, giếng vẫn không đổi.`,
    favorable: `Phát triển nguồn lực cơ bản duy trì hoạt động liên tục.`,
    warning: `Bỏ quên nguồn thiết yếu trong khi đuổi theo bề mặt cạn kiệt năng lực.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Giếng bùn, không ăn, giếng cũ, không có sinh vật` },
      { phase: 2, action: `LUI`, outcome: `HUNG`, gloss: `Thung lũng giếng, cá bị bắt, bình vỡ, rò rỉ` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Giếng được dọn sạch, không uống, trái tim đau, có thể được sử dụng` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Lót giếng, không lỗi trong bảo trì` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Giếng trong, suối lạnh, có thể uống` },
      { phase: 6, action: `GIU`, outcome: `CAT`, gloss: `Giếng thu thập, không che, chân thành, vận may tột đỉnh` }
    ],
  },
  49: {
    id: 49,
    name: `Cach`,
    chinese: `革`,
    upper: `Dui`,
    lower: `Li`,
    upperElement: `Kim`,
    lowerElement: `Hoa`,
    coreMeaning: `Thay đổi căn bản và biến đổi`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Lửa trong hồ — các yếu tố biến đổi lẫn nhau. Được tin vào ngày hoàn thành. Thành công tột đỉnh qua chính đạo.`,
    favorable: `Biến đổi quyết đoán khi thời điểm đúng đạt được đổi mới.`,
    warning: `Cách mạng sớm thất bại; cách mạng trì hoãn bỏ lỡ cơ hội.`,
    phases: [
      { phase: 1, action: `THAN`, outcome: `LE`, gloss: `Bị trói bằng da bò vàng, ổn định trước khi thay đổi` },
      { phase: 2, action: `TIEN`, outcome: `CAT`, gloss: `Cách mạng ngày hoàn thành, đi may mắn` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Đi xui xẻo, kiên trì nguy hiểm, nói cách mạng ba lần, rồi tin` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Hối tiếc biến mất, niềm tin cho phép thay đổi, may mắn` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Người lớn thay đổi như hổ, chưa bói, đã được tin` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Người quý tộc thay đổi như báo, kẻ tiểu nhân đổi mặt` }
    ],
  },
  50: {
    id: 50,
    name: `Dinh`,
    chinese: `鼎`,
    upper: `Li`,
    lower: `Xun`,
    upperElement: `Hoa`,
    lowerElement: `Moc`,
    coreMeaning: `Bình thiêng và thành tựu tột đỉnh`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Lửa trên gỗ — bình biến đổi. Thành công tột đỉnh. Đỉnh đổ ra cái cũ, nhận vào cái mới.`,
    favorable: `Biến đổi nguồn lực qua phương pháp đúng tạo ra giá trị tột đỉnh.`,
    warning: `Sử dụng bình thiêng không đúng cách làm giảm sức mạnh của chúng.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Đỉnh lật úp, thuận lợi để đuổi xấu` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Đỉnh có nội dung, bạn tôi bệnh, không thể tiếp cận` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Tai đỉnh thay đổi, gà lôi béo không ăn, mưa kết thúc hối tiếc` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Chân đỉnh gãy, bữa ăn của hoàng tử bị lật, nghiêm trọng` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Đỉnh tai vàng vòng vàng, kiên trì có lợi` },
      { phase: 6, action: `GIU`, outcome: `CAT`, gloss: `Đỉnh vòng ngọc, vận may lớn, mọi thứ thuận lợi` }
    ],
  },
  51: {
    id: 51,
    name: `Chan`,
    chinese: `震`,
    upper: `Zhen`,
    lower: `Zhen`,
    upperElement: `Moc`,
    lowerElement: `Moc`,
    coreMeaning: `Sốc và sấm mang lại chuyển động`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Sấm lặp đi lặp lại — sốc chồng sốc. Sốc mang lại thành công; nói cười sau khi sợ hãi.`,
    favorable: `Duy trì bình tĩnh qua sốc cho phép phản ứng đúng đắn.`,
    warning: `Hoảng loạn trong sốc dẫn đến mất những gì quan trọng nhất.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Sốc đến, rồi nói cười, may mắn` },
      { phase: 2, action: `THAN`, outcome: `LE`, gloss: `Sốc đến nguy hiểm, mất kho báu, leo cao` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Sốc hồi sinh, hành động gây sốc không lỗi` },
      { phase: 4, action: `LUI`, outcome: `HUNG`, gloss: `Sốc mắc kẹt trong bùn, chuyển động bị sa lầy` },
      { phase: 5, action: `THAN`, outcome: `LE`, gloss: `Sốc đi và đến, nguy hiểm, không mất gì` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Sốc mang lại nhầm lẫn, láng giềng cảnh báo, không lỗi nếu cẩn thận` }
    ],
  },
  52: {
    id: 52,
    name: `Can`,
    chinese: `艮`,
    upper: `Gen`,
    lower: `Gen`,
    upperElement: `Tho`,
    lowerElement: `Tho`,
    coreMeaning: `Yên tĩnh và thiền định dừng chuyển động`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Núi chồng núi — yên tĩnh hoàn toàn. Giữ lưng yên, không cảm thấy cơ thể. Đi trong sân, không thấy người.`,
    favorable: `Yên tĩnh đúng lúc tập trung và củng cố.`,
    warning: `Bồn chồn không thể dừng tiêu tán năng lượng vô ích.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Giữ chân yên, không lỗi, kiên trì tiếp tục có lợi` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Giữ bắp chân yên, không cứu những gì theo sau, trái tim không vui` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Giữ eo yên, tách sườn, nguy hiểm nghẹt trái tim` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Giữ thân yên, không lỗi trong sự yên tĩnh của thân` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Giữ hàm yên, lời nói có trật tự, hối tiếc biến mất` },
      { phase: 6, action: `GIU`, outcome: `CAT`, gloss: `Giữ yên giàu có, hoàn thành may mắn` }
    ],
  },
  53: {
    id: 53,
    name: `Tiem`,
    chinese: `漸`,
    upper: `Xun`,
    lower: `Gen`,
    upperElement: `Moc`,
    lowerElement: `Tho`,
    coreMeaning: `Tiến bộ dần dần và phát triển ổn định`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Cây trên núi — mọc dần dần. Thiếu nữ kết hôn; may mắn qua các giai đoạn đúng đắn.`,
    favorable: `Phát triển từng bước kiên nhẫn đạt được kết quả lâu dài.`,
    warning: `Vội vã trước sự phát triển tự nhiên tạo ra bất ổn.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Ngỗng tiếp cận bờ, kẻ tiểu nhân nguy hiểm, không lỗi` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Ngỗng tiếp cận vách đá, ăn uống vui vẻ, may mắn` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Ngỗng tiếp cận cao nguyên, chồng đi không trở về` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Ngỗng tiếp cận cây, có lẽ được xà, không lỗi` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Ngỗng tiếp cận gò, vợ ba năm không thụ thai` },
      { phase: 6, action: `GIU`, outcome: `CAT`, gloss: `Ngỗng tiếp cận độ cao, lông cho nghi lễ, may mắn` }
    ],
  },
  54: {
    id: 54,
    name: `Qui Muoi`,
    chinese: `歸妹`,
    upper: `Zhen`,
    lower: `Dui`,
    upperElement: `Moc`,
    lowerElement: `Kim`,
    coreMeaning: `Vị trí không đúng mang lại xui xẻo`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
    stateInterpretation: `Sấm trên hồ — chuyển động không theo trình tự đúng. Đi mang lại xui xẻo. Không gì thuận lợi theo hướng nào.`,
    favorable: `Hành động từ vị trí không đúng hoặc thời gian sớm mang lại vấn đề.`,
    warning: `Kiên nhẫn cho đến khi vị trí đúng có sẵn tránh lãng phí nỗ lực.`,
    phases: [
      { phase: 1, action: `THAN`, outcome: `LE`, gloss: `Thiếu nữ kết hôn làm thiếp, què có thể đi, đi may mắn` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Nheo mắt có thể thấy, sự kiên trì của người cô đơn có lợi` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Thiếu nữ kết hôn làm nô lệ, trở về làm thiếp` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Thiếu nữ trì hoãn hôn nhân, hôn nhân muộn có thời gian` },
      { phase: 5, action: `GIU`, outcome: `VO CUU`, gloss: `Hoàng đế Ất kết hôn em gái, tay áo công chúa kém đẹp` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Phụ nữ cầm giỏ trống, đàn ông đâm cừu, không có máu` }
    ],
  },
  55: {
    id: 55,
    name: `Phong`,
    chinese: `豐`,
    upper: `Zhen`,
    lower: `Li`,
    upperElement: `Moc`,
    lowerElement: `Hoa`,
    coreMeaning: `Đầy đủ và dồi dào đỉnh cao`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Sấm và sét — dồi dào ở đỉnh cao. Vua đạt mức độ lớn nhất. Mặt trời giữa trưa phải suy giảm.`,
    favorable: `Triển khai tối đa trong điều kiện đỉnh cao đạt được kết quả lớn.`,
    warning: `Bám víu vào vị trí đỉnh cao đẩy nhanh suy giảm không thể tránh.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Gặp chúa phù hợp, mười ngày không lỗi, đi được tôn vinh` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Che chắn sự dồi dào, giữa trưa thấy Sao Bắc Đẩu, đi được nghi ngờ` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Che chắn tán, giữa trưa thấy bọt, gãy tay` },
      { phase: 4, action: `LUI`, outcome: `HUNG`, gloss: `Che chắn sự dồi dào, giữa trưa thấy Sao Bắc Đẩu, gặp chúa ẩn` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Mang lại sự rực rỡ, khen ngợi và may mắn đến` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Dồi dào trong nhà, che chắn gia đình, nhìn trộm cổng, ba năm cô đơn` }
    ],
  },
  56: {
    id: 56,
    name: `Lu`,
    chinese: `旅`,
    upper: `Li`,
    lower: `Gen`,
    upperElement: `Hoa`,
    lowerElement: `Tho`,
    coreMeaning: `Du hành và tạm trú ở vùng đất xa lạ`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Lửa trên núi — người lữ hành đi qua. Thành công nhỏ qua hành vi đúng đắn khi du hành.`,
    favorable: `Hành xử khiêm tốn cẩn thận trong thời kỳ chuyển đổi duy trì an toàn.`,
    warning: `Kiêu ngạo hoặc bất cẩn khi dễ bị tổn thương mời gọi thảm họa.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Người lữ hành về những điều nhỏ nhặt, mang thảm họa cho bản thân` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Người lữ hành đến quán trọ, có nguồn lực, được người hầu trẻ` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Người lữ hành đốt quán trọ, mất người hầu trẻ, nguy hiểm` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Người lữ hành tại nơi, có hàng hóa và rìu, trái tim không vui` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Bắn gà lôi, một mũi tên, cuối cùng khen ngợi và ủy quyền` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Chim đốt tổ, người lữ hành trước cười sau khóc` }
    ],
  },
  57: {
    id: 57,
    name: `Ton`,
    chinese: `巽`,
    upper: `Xun`,
    lower: `Xun`,
    upperElement: `Moc`,
    lowerElement: `Moc`,
    coreMeaning: `Thấm nhập nhẹ nhàng và ảnh hưởng dần dần`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Gió theo gió — kiên trì nhẹ nhàng. Thành công nhỏ qua ảnh hưởng tinh tế.`,
    favorable: `Ảnh hưởng nhẹ nhàng kiên trì đạt được những gì sức mạnh không thể.`,
    warning: `Quá nhẹ nhàng không có hướng trở thành yếu đuối.`,
    phases: [
      { phase: 1, action: `THAN`, outcome: `LE`, gloss: `Tiến và lùi, sự kiên trì của người lính có lợi` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Thấm nhập dưới giường, sử dụng nhiều thầy bói, may mắn` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Thấm nhập lặp lại, hối tiếc từ do dự` },
      { phase: 4, action: `THAN`, outcome: `HOI`, gloss: `Hối tiếc biến mất, bắt ba loại trong săn bắn` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Kiên trì may mắn, hối tiếc biến mất, không gì bất lợi` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Thấm nhập dưới giường, mất hàng hóa và rìu, kiên trì xui xẻo` }
    ],
  },
  58: {
    id: 58,
    name: `Doai`,
    chinese: `兌`,
    upper: `Dui`,
    lower: `Dui`,
    upperElement: `Kim`,
    lowerElement: `Kim`,
    coreMeaning: `Niềm vui và giao tiếp hài hòa`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Hồ cùng nhau — niềm vui qua trao đổi. Thành công qua kiên trì. Bạn bè thảo luận và thực hành cùng nhau.`,
    favorable: `Niềm vui và trao đổi lẫn nhau chân chính tạo ra lợi ích lâu dài.`,
    warning: `Tìm kiếm khoái lạc quá mức hoặc nịnh hót làm hư hỏng và yếu đi.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `CAT`, gloss: `Niềm vui hài hòa, chân thành may mắn` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Niềm vui chân thành, may mắn, hối tiếc biến mất` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Niềm vui đến, xui xẻo từ tìm kiếm khoái lạc` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Niềm vui suy nghĩ, chưa nghỉ ngơi, xua đuổi bệnh hạnh phúc` },
      { phase: 5, action: `THAN`, outcome: `LE`, gloss: `Chân thành với kẻ lột, nguy hiểm tồn tại` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Dẫn dắt niềm vui, quyến rũ và không thỏa mãn` }
    ],
  },
  59: {
    id: 59,
    name: `Hoan`,
    chinese: `渙`,
    upper: `Xun`,
    lower: `Kan`,
    upperElement: `Moc`,
    lowerElement: `Thuy`,
    coreMeaning: `Tan rã và phân tán chướng ngại`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Gió trên nước — phân tán sự trì trệ. Vua tiếp cận đền. Thuận lợi để vượt sông lớn và kiên trì.`,
    favorable: `Hòa tan sự cứng nhắc và chướng ngại cho phép dòng chảy mới.`,
    warning: `Phân tán quá mức không tập hợp lại dẫn đến tan tác.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `CAT`, gloss: `Cứu với sức ngựa, hỗ trợ may mắn` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Phân tán chạy để hỗ trợ, hối tiếc biến mất` },
      { phase: 3, action: `GIU`, outcome: `VO CUU`, gloss: `Phân tán bản thân, không hối tiếc khi buông bỏ` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Phân tán nhóm của mình, vận may tột đỉnh, tụ họp trên đồi` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Phân tán mồ hôi, tiếng kêu lớn, phân tán nơi ở của vua` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Phân tán máu, ra đi, không lỗi khi xa lánh tổn hại` }
    ],
  },
  60: {
    id: 60,
    name: `Tiet`,
    chinese: `節`,
    upper: `Kan`,
    lower: `Dui`,
    upperElement: `Thuy`,
    lowerElement: `Kim`,
    coreMeaning: `Tiết chế và giới hạn đúng mức`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Nước trên đầm — đo lường đúng mức. Thành công nhưng tiết chế đắng khổ không thể giữ bền. Đốt tre tạo cấu trúc.`,
    favorable: `Tiết chế thích hợp tạo ra cấu trúc và bền vững.`,
    warning: `Tiết chế quá mức trở thành áp bức và thất bại.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `VO CUU`, gloss: `Không ra khỏi sân nhà, không lỗi khi ở trong` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Không ra khỏi cổng sân, xui xẻo vì lỡ thời cơ` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Không tiết chế thì than thở, không lỗi` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Tiết chế an nhiên, thành công qua an phận` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Tiết chế ngọt ngào, đi tới được tôn trọng` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Tiết chế đắng khổ, kiên trì xui xẻo, hối tiếc biến mất` }
    ],
  },
  61: {
    id: 61,
    name: `Trung Phu`,
    chinese: `中孚`,
    upper: `Xun`,
    lower: `Dui`,
    upperElement: `Moc`,
    lowerElement: `Kim`,
    coreMeaning: `Lòng thành tín từ bên trong lan tỏa ra ngoài`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Gió trên đầm — sự thật bên trong ảnh hưởng tất cả. Cá heo may mắn. Thuận lợi vượt sông lớn và kiên trì.`,
    favorable: `Lòng chân thành sâu sắc truyền đạt ra ngoài tạo niềm tin và ảnh hưởng.`,
    warning: `Chân thành bề ngoài không có sự thật bên trong cuối cùng sẽ bị phát hiện.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `CAT`, gloss: `Chuẩn bị thì tốt, có ý khác thì không yên` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Hạc kêu trong bóng râm, con nó hưởng ứng, ta có chén rượu ngon` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Gặp đối thủ, lúc đánh trống lúc ngừng` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Trăng gần tròn, ngựa đôi mất một con, không lỗi` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Có lòng thành tín ràng buộc, không lỗi` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Tiếng gà bay lên tận trời, kiên trì xui xẻo` }
    ],
  },
  62: {
    id: 62,
    name: `Tieu Qua`,
    chinese: `小過`,
    upper: `Zhen`,
    lower: `Gen`,
    upperElement: `Moc`,
    lowerElement: `Tho`,
    coreMeaning: `Việc nhỏ vượt quá; việc lớn chờ đợi`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Sấm trên núi — vượt quá nhỏ. Thành công nhỏ qua kiên trì. Việc lớn không nên thử bây giờ.`,
    favorable: `Thành công trong việc nhỏ; kiềm chế trong công việc lớn.`,
    warning: `Cố gắng việc lớn trong thời vượt quá nhỏ mời gọi thất bại.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Chim bay mang xui xẻo, không làm gì được` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Đi quá ông gặp bà, không đến được vua` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Không quá cẩn thận phòng bị, theo đó mà bị hại, xui xẻo` },
      { phase: 4, action: `GIU`, outcome: `VO CUU`, gloss: `Không lỗi, gặp mà không quá, đi tới nguy hiểm, thận trọng` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Mây dày từ phía tây, công hầu bắn tên bắt trong hang` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Không gặp mà đi quá, chim bay xa, xui xẻo` }
    ],
  },
  63: {
    id: 63,
    name: `Ky Te`,
    chinese: `既濟`,
    upper: `Kan`,
    lower: `Li`,
    upperElement: `Thuy`,
    lowerElement: `Hoa`,
    coreMeaning: `Trật tự đạt được nhưng cần duy trì`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
    stateInterpretation: `Nước trên lửa — hoàn thành nhưng bấp bênh. Ban đầu thành công nhỏ. Kiên trì có lợi nhưng hỗn loạn đe dọa.`,
    favorable: `Duy trì cảnh giác bảo toàn trật tự đã đạt được.`,
    warning: `Thư giãn sau khi hoàn thành mời gọi hỗn loạn quay lại.`,
    phases: [
      { phase: 1, action: `GIU`, outcome: `CAT`, gloss: `Kéo lại bánh xe, ướt đuôi, không lỗi khi chậm` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Phụ nữ mất tấm che, đừng đuổi theo, bảy ngày lại được` },
      { phase: 3, action: `THAN`, outcome: `LE`, gloss: `Vua Cao Tông đánh nước Quỷ Phương, ba năm thắng` },
      { phase: 4, action: `THAN`, outcome: `LE`, gloss: `Áo lụa có giẻ rách, suốt ngày cảnh giác` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Láng giềng phía đông mổ trâu, không bằng lễ đạm bạc phía tây` },
      { phase: 6, action: `LUI`, outcome: `HUNG`, gloss: `Ướt đầu, nguy hiểm dù đã hoàn thành` }
    ],
  },
  64: {
    id: 64,
    name: `Vi Te`,
    chinese: `未濟`,
    upper: `Li`,
    lower: `Kan`,
    upperElement: `Hoa`,
    lowerElement: `Thuy`,
    coreMeaning: `Chưa hoàn thành với tiềm năng phía trước`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
    stateInterpretation: `Lửa trên nước — chưa hòa lẫn. Cáo nhỏ sắp qua sông ướt đuôi. Chưa gì thuận lợi. Cần kiên trì để cuối cùng thành công.`,
    favorable: `Nỗ lực tiếp tục hướng tới hoàn thành bất chấp chướng ngại.`,
    warning: `Bỏ cuộc ở ngưỡng cửa lãng phí mọi công sức trước đó.`,
    phases: [
      { phase: 1, action: `LUI`, outcome: `HUNG`, gloss: `Ướt đuôi, hối tiếc vội vàng` },
      { phase: 2, action: `GIU`, outcome: `CAT`, gloss: `Kéo lại bánh xe, kiên trì may mắn` },
      { phase: 3, action: `LUI`, outcome: `HUNG`, gloss: `Chưa hoàn thành, tiến tới xui xẻo, thuận lợi vượt sông` },
      { phase: 4, action: `GIU`, outcome: `CAT`, gloss: `Kiên trì may mắn, hối tiếc biến mất, đánh nước Quỷ Phương` },
      { phase: 5, action: `GIU`, outcome: `CAT`, gloss: `Kiên trì may mắn, không hối tiếc, ánh sáng quân tử, chân thành may mắn` },
      { phase: 6, action: `TIEN`, outcome: `CAT`, gloss: `Chân thành uống rượu, ướt đầu mất đi sự đúng đắn` }
    ],
  },
};
