// AUTO-GENERATED by scripts/gen-que-descriptions.ts — DO NOT EDIT.
// Run: bun run gen:que  (from apps/frontend/ directory)
// Source: apps/kinh-dich-service/dashboard/que-reference.js
// Re-run this script when que-reference.js is regenerated via:
//   CGO_ENABLED=0 go run ./cmd/sandbox -emit-reference

export interface QueDescription {
  /** Primary hover text — core meaning of the hexagram (1 clause, plain Vietnamese). */
  coreMeaning: string;
  /** Secondary label — market trend label in Vietnamese (e.g. "Thuận lợi (THUẬN LỢI)"). */
  marketTrendLabel: string;
}

export const QUE_DESCRIPTIONS: Record<number, QueDescription> = {
  1: {
    coreMeaning: `Sức sáng tạo nguyên thủy, năng lượng dương cương kiện không ngừng vận hành`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  2: {
    coreMeaning: `Sức tiếp nhận vĩ đại, đức nhu thuận nuôi dưỡng vạn vật`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  3: {
    coreMeaning: `Khó khăn ban đầu khi vạn vật mới sinh, như hạt mầm nảy từ đất`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
  },
  4: {
    coreMeaning: `U mê non dại cần được khai sáng, như suối nước từ chân núi chảy ra`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  5: {
    coreMeaning: `Chờ đợi đúng thời cơ với niềm tin vững chắc`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  6: {
    coreMeaning: `Tranh chấp và kiện tụng cần được giải quyết`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
  },
  7: {
    coreMeaning: `Lực lượng có tổ chức cần kỷ luật và lãnh đạo`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  8: {
    coreMeaning: `Liên kết và liên minh tìm kiếm lợi ích chung`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  9: {
    coreMeaning: `Thu hoạch nhỏ qua sự kiềm chế nhẹ nhàng`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  10: {
    coreMeaning: `Hành xử cẩn thận như dẫm lên đuôi hổ`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  11: {
    coreMeaning: `Thịnh vượng và hài hòa trong mọi thứ`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  12: {
    coreMeaning: `Trì trệ và cản trở chặn đứng tiến bộ`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
  },
  13: {
    coreMeaning: `Tình bằng hữu và mục đích chung đoàn kết mọi người`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  14: {
    coreMeaning: `Dồi dào lớn lao và thành công tột đỉnh`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  15: {
    coreMeaning: `Khiêm tốn và nhún nhường mang lại hoàn thành`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  16: {
    coreMeaning: `Nhiệt huyết và sẵn sàng vui vẻ cho hành động`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  17: {
    coreMeaning: `Theo dõi và thích ứng với hoàn cảnh`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  18: {
    coreMeaning: `Sửa chữa sự mục nát và lỗi lầm quá khứ`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  19: {
    coreMeaning: `Tiếp cận tăng trưởng với đà thuận lợi`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  20: {
    coreMeaning: `Quan sát và chiêm nghiệm từ vị trí cao`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  21: {
    coreMeaning: `Hành động quyết đoán cắn xuyên qua chướng ngại`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  22: {
    coreMeaning: `Vẻ đẹp và trang trí tăng cường bản chất`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  23: {
    coreMeaning: `Tách rời và xói mòn vị thế`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
  },
  24: {
    coreMeaning: `Trở về và đổi mới sau khi chạm đáy`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  25: {
    coreMeaning: `Ngây thơ và những sự việc bất ngờ`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  26: {
    coreMeaning: `Tích lũy lớn quyền lực và nguồn lực`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  27: {
    coreMeaning: `Nuôi dưỡng và sinh kế đúng đắn`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  28: {
    coreMeaning: `Gánh nặng phi thường vượt quá năng lực bình thường`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
  },
  29: {
    coreMeaning: `Hiểm trở chồng hiểm trở, hố sâu nối hố sâu`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
  },
  30: {
    coreMeaning: `Bám víu vào ánh sáng và sự rõ ràng`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  31: {
    coreMeaning: `Ảnh hưởng và thu hút lẫn nhau`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  32: {
    coreMeaning: `Sự bền bỉ và kiên trì lâu dài`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  33: {
    coreMeaning: `Rút lui chiến lược và rút lui`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  34: {
    coreMeaning: `Quyền lực lớn và sức mạnh áp đảo`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  35: {
    coreMeaning: `Tiến bộ và tiến vào ánh sáng`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  36: {
    coreMeaning: `Ánh sáng bị thương và che giấu`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
  },
  37: {
    coreMeaning: `Trật tự gia đình và mối quan hệ đúng đắn`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  38: {
    coreMeaning: `Đối lập và xa cách`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  39: {
    coreMeaning: `Chướng ngại và khó khăn phía trước`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
  },
  40: {
    coreMeaning: `Giải phóng và giải thoát khỏi căng thẳng`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  41: {
    coreMeaning: `Giảm bớt và cắt giảm chiến lược`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  42: {
    coreMeaning: `Tăng trưởng và phát triển có lợi`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  43: {
    coreMeaning: `Đột phá quyết định và giải quyết`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  44: {
    coreMeaning: `Cuộc gặp gỡ bất ngờ và cám dỗ`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
  },
  45: {
    coreMeaning: `Tụ họp và hội họp`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  46: {
    coreMeaning: `Leo lên dần dần và tiến bộ`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  47: {
    coreMeaning: `Kiệt sức và giam cầm`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
  },
  48: {
    coreMeaning: `Nguồn vô tận và nền tảng`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  49: {
    coreMeaning: `Thay đổi căn bản và biến đổi`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  50: {
    coreMeaning: `Bình thiêng và thành tựu tột đỉnh`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  51: {
    coreMeaning: `Sốc và sấm mang lại chuyển động`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  52: {
    coreMeaning: `Yên tĩnh và thiền định dừng chuyển động`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  53: {
    coreMeaning: `Tiến bộ dần dần và phát triển ổn định`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  54: {
    coreMeaning: `Vị trí không đúng mang lại xui xẻo`,
    marketTrendLabel: `Bất lợi (BẤT LỢI)`,
  },
  55: {
    coreMeaning: `Đầy đủ và dồi dào đỉnh cao`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  56: {
    coreMeaning: `Du hành và tạm trú ở vùng đất xa lạ`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  57: {
    coreMeaning: `Thấm nhập nhẹ nhàng và ảnh hưởng dần dần`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  58: {
    coreMeaning: `Niềm vui và giao tiếp hài hòa`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  59: {
    coreMeaning: `Tan rã và phân tán chướng ngại`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  60: {
    coreMeaning: `Tiết chế và giới hạn đúng mức`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  61: {
    coreMeaning: `Lòng thành tín từ bên trong lan tỏa ra ngoài`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  62: {
    coreMeaning: `Việc nhỏ vượt quá; việc lớn chờ đợi`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
  63: {
    coreMeaning: `Trật tự đạt được nhưng cần duy trì`,
    marketTrendLabel: `Thuận lợi (THUẬN LỢI)`,
  },
  64: {
    coreMeaning: `Chưa hoàn thành với tiềm năng phía trước`,
    marketTrendLabel: `Trung tính (TRUNG TÍNH)`,
  },
};
