// AUTO-GENERATED by scripts/gen-que-descriptions.ts — DO NOT EDIT.
// Run: bun run gen:que  (from apps/frontend/ directory)
// Source: apps/mcp-server/src/domain/services/kinhDich/hexagramLibrary.ts
// Re-run this script when hexagramLibrary.ts is updated.

export interface QueDescription {
  /** Primary hover text — core meaning of the hexagram. */
  coreMeaning: string;
  /** Secondary — trading judgment / interpretation. */
  judgment_interpretation: string;
  /** Action guidance from the image/action field. */
  image_action: string;
  /** Market trend state. */
  state_trend: string;
}

export const QUE_DESCRIPTIONS: Record<number, QueDescription> = {
  1: {
    coreMeaning: `Sức sáng tạo nguyên thủy, năng lượng dương cương kiện không ngừng vận hành. Trời vận hành mạnh mẽ — người quân tử tự cường không nghỉ.`,
    judgment_interpretation: `Bốn đức lớn của trời: Nguyên (khởi đầu sáng tạo), Hanh (hanh thông suôn sẻ), Lợi (thuận lợi hòa hợp), Trinh (chính bền vững chắc). Đây là quẻ của năng lượng sáng tạo thuần khiết — mọi việc đều hanh thông nếu giữ được chính đạo. Không phải lúc nào cũng nên tiến mạnh; sức mạnh thật sự nằm ở chỗ biết tự cường bền bỉ.`,
    image_action: `Người quân tử tự cường không nghỉ. Hãy nỗ lực liên tục, phát huy năng lực bản thân, không ỷ lại vào hoàn cảnh.`,
    state_trend: `THUẬN LỢI — năng lượng dương cực mạnh, vạn sự hanh thông nếu giữ chính đạo`,
  },
  2: {
    coreMeaning: `Sức tiếp nhận vĩ đại, đức nhu thuận nuôi dưỡng vạn vật. Đất dày chở muôn loài — người quân tử lấy đức dày chứa đựng muôn vật.`,
    judgment_interpretation: `Khôn là sức mạnh của sự tiếp nhận và nuôi dưỡng — không phải yếu mà là khác. Ngựa cái biểu trưng cho sức bền và sự nhu thuận. Đừng cố dẫn đầu, hãy hỗ trợ và theo sự dẫn dắt đúng. Sức mạnh của Khôn nằm ở khả năng chứa đựng và kiên nhẫn.`,
    image_action: `Bồi đắp đức hạnh, rộng lượng bao dung, phục vụ và hỗ trợ thay vì tranh giành dẫn đầu.`,
    state_trend: `THUẬN LỢI — thuận theo tự nhiên, đừng cố gắng đi đầu mà hãy hỗ trợ`,
  },
  3: {
    coreMeaning: `Khó khăn ban đầu khi vạn vật mới sinh. Như hạt mầm nảy từ đất, gian nan nhưng chứa đầy tiềm năng phát triển.`,
    judgment_interpretation: `Khởi đầu nào cũng khó khăn — như mầm cây đội đất mà lên. Đừng vội vã lao vào mà hãy xây dựng đội ngũ, tìm người giúp đỡ. Giữ vững phương hướng chính đạo thì cuối cùng sẽ hanh thông.`,
    image_action: `Mây và sấm chưa thành mưa — cần sắp xếp, kinh luân. Hãy lập kế hoạch kỹ lưỡng, tổ chức nguồn lực trước khi hành động.`,
    state_trend: `BẤT LỢI ban đầu nhưng THUẬN LỢI về lâu dài — kiên nhẫn vượt qua giai đoạn khởi đầu`,
  },
  4: {
    coreMeaning: `Mông muội cần được khai sáng. Không phải ta tìm trẻ thơ mà trẻ thơ tìm đến ta — giáo dục đúng lúc, đúng cách.`,
    judgment_interpretation: `Giáo dục cần tôn trọng: học trò phải chủ động tìm thầy, không phải ngược lại. Hỏi một lần thì trả lời, hỏi lặp đi lặp lại là thiếu thành tâm. Người dạy cần nghiêm, người học cần kính — đó mới là giáo dục thật sự.`,
    image_action: `Nuôi dưỡng đức hạnh, tu dưỡng hành vi. Như suối từ núi — bắt đầu nhỏ nhưng dần trở thành sông lớn.`,
    state_trend: `TRUNG TÍNH — cần học hỏi để chuyển hóa từ mê sang ngộ`,
  },
  5: {
    coreMeaning: `Chờ đợi đúng lúc với niềm tin vững chắc. Mây bốc lên trời, mưa chưa rơi — kiên nhẫn nuôi dưỡng bản thân trong khi chờ thời.`,
    judgment_interpretation: `Chờ đợi không phải thụ động mà là chuẩn bị tích cực. Khi có niềm tin vững chắc vào chính đạo, sự chờ đợi trở thành quá trình nuôi dưỡng sức mạnh. Đủ nội lực rồi thì có thể vượt qua mọi khó khăn.`,
    image_action: `Ăn uống yến tiệc — nuôi dưỡng thể chất tinh thần trong khi chờ đợi. Đừng lo lắng, hãy tận hưởng quá trình chuẩn bị.`,
    state_trend: `THUẬN LỢI — nhưng cần kiên nhẫn, chưa phải lúc hành động lớn`,
  },
  6: {
    coreMeaning: `Xung đột và tranh chấp. Trời đi lên, nước chảy xuống — hai bên đối nghịch. Nên tìm người phân xử, tránh đi đến cùng.`,
    judgment_interpretation: `Khi xung đột xảy ra, có lý lẽ của mình nhưng bị cản trở. Đừng đẩy tranh chấp đến cùng — hòa giải ở giữa đường là tốt nhất. Tìm người có uy tín phân xử, đừng tự mình mạo hiểm.`,
    image_action: `Làm việc gì cũng cần suy xét kỹ từ đầu, phòng ngừa tranh chấp. Hãy rõ ràng trong hợp đồng và thỏa thuận.`,
    state_trend: `BẤT LỢI — tranh chấp không có người thắng thật sự, nên hòa giải`,
  },
  7: {
    coreMeaning: `Quân đội — tập hợp lực lượng, tổ chức kỷ luật. Nước chứa trong lòng đất: sức mạnh tiềm tàng cần người chỉ huy đúng đắn.`,
    judgment_interpretation: `Tập hợp lực lượng cần lý do chính đáng và người lãnh đạo có kinh nghiệm, đức độ. Chiến tranh hay cạnh tranh chỉ nên khi có chính nghĩa. Kỷ luật và người chỉ huy giỏi là chìa khóa thành bại.`,
    image_action: `Dung chứa dân chúng, nuôi dưỡng lực lượng. Người lãnh đạo cần biết thu phục lòng người.`,
    state_trend: `TRUNG TÍNH — cần tổ chức kỷ luật và người lãnh đạo đúng đắn mới thuận lợi`,
  },
  8: {
    coreMeaning: `Thân cận, liên kết, hợp tác. Nước trên đất — tự nhiên hòa vào nhau. Tìm người lãnh đạo xứng đáng mà theo.`,
    judgment_interpretation: `Liên kết là tốt nhưng phải chọn đúng người đúng lúc. Hãy xét kỹ trước khi cam kết — một khi đã quyết thì phải bền lâu. Ai chần chừ quá lâu sẽ mất cơ hội hòa nhập.`,
    image_action: `Các vua đời xưa lập vạn quốc thân chư hầu. Hãy xây dựng mạng lưới quan hệ, liên kết chặt chẽ với đồng minh.`,
    state_trend: `THUẬN LỢI — thời kỳ kết nối, hợp tác, gia nhập tổ chức`,
  },
  9: {
    coreMeaning: `Tích lũy nhỏ, kiềm chế nhẹ nhàng. Gió thổi trên trời — mây tụ nhưng chưa đủ để mưa. Sức kiềm chế còn yếu, chỉ đủ cho việc nhỏ.`,
    judgment_interpretation: `Năng lượng đang tích tụ nhưng chưa đủ để bùng phát. Mây dày nhưng chưa mưa — mọi thứ đang ở giai đoạn chuẩn bị. Hãy tiếp tục tích lũy, đừng nóng vội. Sức mềm (âm) kiềm chế sức mạnh (dương) chỉ tạm thời.`,
    image_action: `Tu dưỡng văn đức. Dùng sự tế nhị, mềm mỏng để cảm hóa — chưa đủ sức ép buộc trực tiếp.`,
    state_trend: `TRUNG TÍNH — tích lũy chưa đủ, chỉ làm được việc nhỏ`,
  },
  10: {
    coreMeaning: `Bước đi, lễ nghi, cách ứng xử. Giẫm lên đuôi cọp mà cọp không cắn — nhờ biết cách hành xử đúng mực.`,
    judgment_interpretation: `Đối mặt nguy hiểm nhưng nhờ cách ứng xử đúng đắn mà an toàn. Lễ nghĩa không phải hình thức mà là trí tuệ ứng xử — biết vị trí của mình, hành động đúng mực thì dù ở tình huống nguy hiểm cũng vượt qua.`,
    image_action: `Phân biệt trên dưới, định rõ chí hướng của dân. Xác định rõ vai trò, vị trí, hành xử đúng phận sự.`,
    state_trend: `THUẬN LỢI — nếu biết cách ứng xử, nguy hiểm sẽ qua`,
  },
  11: {
    coreMeaning: `Thái bình, hanh thông. Đất ở trên trời ở dưới — âm dương giao hòa, trên dưới thông suốt. Thời kỳ thịnh vượng nhất.`,
    judgment_interpretation: `Âm (nhỏ) đi ra, dương (lớn) đi vào — thế giao hòa hoàn hảo. Trên (Khôn) khiêm tốn hạ mình, dưới (Kiền) mạnh mẽ nâng lên — giao thoa tạo hòa bình thịnh vượng. Đây là thời kỳ tốt đẹp nhất nhưng không bền vĩnh viễn.`,
    image_action: `Tài thành trời đất đạo, giúp trời đất nuôi dưỡng. Người lãnh đạo kết nối trên dưới, tạo điều kiện cho mọi người phát triển.`,
    state_trend: `THUẬN LỢI — thời kỳ hoàng kim, vạn sự hanh thông`,
  },
  12: {
    coreMeaning: `Bế tắc, trì trệ. Trời ở trên đất ở dưới — mỗi bên một ngả, không giao thoa. Tiểu nhân thịnh, quân tử suy.`,
    judgment_interpretation: `Trái ngược với Thái: dương đi ra, âm đi vào — trên dưới cách biệt, trời đất không giao. Tiểu nhân lên ngôi, quân tử phải ẩn mình. Thời kỳ đen tối nhưng sẽ không kéo dài mãi.`,
    image_action: `Người quân tử kiệm đức tránh nạn, không thể vinh hiển bằng bổng lộc. Thu mình, giảm chi tiêu, tránh phô trương.`,
    state_trend: `BẤT LỢI — bế tắc toàn diện, cần thu mình chờ thời`,
  },
  13: {
    coreMeaning: `Đoàn kết, hòa đồng với người. Lửa bốc lên trời — sáng soi khắp nơi, kết nối mọi người bằng ánh sáng chung.`,
    judgment_interpretation: `Đoàn kết phải rộng rãi — không phải cục bộ phe nhóm mà là với mọi người ngoài cánh đồng rộng. Khi đoàn kết trên nền tảng chính nghĩa, mọi khó khăn đều vượt qua được.`,
    image_action: `Phân biệt sự vật, phân loại tộc loại. Tìm điểm chung giữa sự khác biệt, đoàn kết trên nền tảng giá trị chung.`,
    state_trend: `THUẬN LỢI — hợp tác, liên minh, đoàn kết sẽ thành công`,
  },
  14: {
    coreMeaning: `Sở hữu lớn, thịnh vượng. Lửa sáng trên trời cao — chiếu soi vạn vật, phúc lộc dồi dào. Nhưng cần biết chia sẻ và giữ khiêm cung.`,
    judgment_interpretation: `Một hào âm ở vị trí tôn quý (Lục Ngũ) được năm hào dương phục tùng — tượng trưng cho người lãnh đạo khiêm nhường được mọi người ủng hộ. Sở hữu lớn nhờ đức chứ không nhờ sức mạnh. Mọi việc đều hanh thông.`,
    image_action: `Ngăn chặn cái ác, phát huy cái thiện, thuận mệnh trời. Dùng sự thịnh vượng để làm điều tốt.`,
    state_trend: `THUẬN LỢI — thịnh vượng, dồi dào, mọi sự thuận lợi`,
  },
  15: {
    coreMeaning: `Khiêm nhường — đức cao nhất trong Kinh Dịch. Núi ở dưới đất — có cao mà tự hạ mình. Khiêm nhường là quẻ duy nhất mà cả sáu hào đều tốt.`,
    judgment_interpretation: `Khiêm nhường là con đường duy nhất đi đến cuối mà không gặp họa. Trời đạo là bớt đầy thêm khiếm, địa đạo là bớt cao thêm thấp, quỷ thần là hại đầy phúc khiêm, nhân đạo là ghét đầy thích khiêm. Khiêm nhường được tất cả ưu ái.`,
    image_action: `Bớt nhiều bù ít, cân bằng công bằng. San bớt chỗ thừa đắp vào chỗ thiếu.`,
    state_trend: `THUẬN LỢI — khiêm nhường thì mọi sự hanh thông, quẻ duy nhất toàn cát`,
  },
  16: {
    coreMeaning: `Vui vẻ, phấn khởi, sẵn sàng. Sấm vang trên đất — sức sống bùng nổ, tạo cảm hứng hành động. Nhưng vui mà không buông thả.`,
    judgment_interpretation: `Khi mọi người phấn khởi đồng lòng là lúc tốt nhất để lập lãnh đạo và khởi sự lớn. Âm nhạc, niềm vui, tinh thần cao là sức mạnh tập hợp. Nhưng phải biến cảm hứng thành hành động cụ thể.`,
    image_action: `Tiên vương dùng nhạc để thờ Thượng Đế, tôn thờ tổ tiên. Dùng nghệ thuật và cảm hứng để gắn kết cộng đồng.`,
    state_trend: `THUẬN LỢI — thời kỳ phấn khởi, hành động lớn thuận lợi`,
  },
  17: {
    coreMeaning: `Thuận theo thời thế, thích ứng linh hoạt — sấm động trong đầm, vui vẻ mà thuận theo, biết đi theo điều đúng đắn thì hanh thông.`,
    judgment_interpretation: `Quẻ Tùy dạy rằng biết thuận theo thời thế một cách chính đáng sẽ đạt hanh thông lớn. Không phải a dua xu nịnh, mà là nhận ra xu hướng đúng và hòa mình vào đó. Điều kiện tiên quyết là giữ chính đạo — theo đúng thì không lỗi, theo sai thì mất mình.`,
    image_action: `Người quân tử thấy trời tối thì vào nhà nghỉ ngơi. Biết lúc nào nên hành động, lúc nào nên dừng lại, thuận theo nhịp tự nhiên mà sống.`,
    state_trend: `THUẬN LỢI — thời thế đang chuyển, biết thích ứng sẽ được lợi lớn`,
  },
  18: {
    coreMeaning: `Sửa chữa hư hỏng, cải cách điều mục nát — gió bị núi chặn lại sinh trùng độc, cần dọn dẹp và chấn chỉnh lại từ gốc.`,
    judgment_interpretation: `Quẻ Cổ chỉ tình trạng mục nát cần được sửa chữa — nhưng đây là cơ hội lớn chứ không phải thảm họa. Việc cải cách cần chuẩn bị kỹ lưỡng (trước Giáp ba ngày) và theo dõi sát sau khi thực hiện (sau Giáp ba ngày). Dám đối mặt với vấn đề tích tụ lâu ngày sẽ mở ra hanh thông.`,
    image_action: `Người quân tử lấy đó mà chấn hưng dân chúng, bồi dưỡng đức hạnh. Thấy điều hư nát phải chủ động sửa chữa, không để tình trạng kéo dài.`,
    state_trend: `TRUNG TÍNH — có vấn đề tích tụ cần giải quyết, nhưng chính vì vậy mà cơ hội cải cách rất lớn`,
  },
  19: {
    coreMeaning: `Đến gần, tiến lại — hai dương đang lớn dần từ dưới lên, thế lực đang hưng thịnh, thời cơ đang đến. Cần tận dụng nhưng biết rằng thịnh rồi sẽ suy.`,
    judgment_interpretation: `Quẻ Lâm báo hiệu thời kỳ hưng thịnh đang đến — dương khí tăng trưởng, vạn sự hanh thông. Nhưng lời cảnh báo 'tháng tám có hung' nhắc nhở rằng thịnh cực tất suy. Khi mọi thứ đang thuận lợi, hãy chuẩn bị cho lúc khó khăn, đừng chủ quan.`,
    image_action: `Người quân tử dạy dỗ và suy nghĩ không giới hạn, bao dung che chở dân chúng không bờ bến. Lãnh đạo bằng sự gần gũi và quan tâm thực sự.`,
    state_trend: `THUẬN LỢI — thế lực đang lên, thời cơ tốt, nhưng cần biết giới hạn thời gian`,
  },
  20: {
    coreMeaning: `Quan sát, chiêm nghiệm — gió thổi trên đất, nhìn xa trông rộng. Vừa là nhìn ngắm thế giới, vừa là được thế giới nhìn ngắm.`,
    judgment_interpretation: `Quẻ Quán lấy hình ảnh nghi lễ tế trời — khoảnh khắc thiêng liêng nhất là lúc đã trai giới rửa tay mà chưa dâng đồ cúng, lòng thành ở đỉnh điểm. Quan sát thế giới cần tâm thế trang nghiêm như vậy — không vội vàng phán xét, mà lặng lẽ chiêm nghiệm.`,
    image_action: `Bậc tiên vương lấy đó mà đi tuần bốn phương, quan sát dân tình, ban hành giáo hóa. Lãnh đạo phải biết nhìn xa trông rộng, hiểu thấu thực tế.`,
    state_trend: `TRUNG TÍNH — thời kỳ quan sát, chưa nên hành động vội, cần thu thập thông tin và chiêm nghiệm`,
  },
  21: {
    coreMeaning: `Cắn để khớp — sấm và lửa cùng hành, dùng hình phạt để khôi phục trật tự. Khi có chướng ngại giữa đường, phải quyết liệt loại bỏ.`,
    judgment_interpretation: `Quẻ Phệ Hạp như hàm răng có vật cản giữa — phải cắn mạnh cho nát mới khớp lại được. Khi trật tự bị phá vỡ, cần dùng luật pháp nghiêm minh để xử lý. Không phải tàn nhẫn mà là công bằng — hình phạt đúng lúc, đúng mức sẽ khôi phục hài hòa.`,
    image_action: `Bậc tiên vương lấy đó mà minh bạch hình phạt, ban bố pháp luật. Luật pháp phải vừa sáng tỏ (Ly) vừa oai nghiêm (Chấn).`,
    state_trend: `THUẬN LỢI — có chướng ngại phải loại bỏ, hành động quyết liệt sẽ khai thông`,
  },
  22: {
    coreMeaning: `Trang sức, văn vẻ — lửa sáng dưới chân núi, chiếu rọi vẻ đẹp tự nhiên. Hình thức tô điểm cho nội dung, nhưng đừng để hình thức lấn át bản chất.`,
    judgment_interpretation: `Quẻ Bí nói về vẻ đẹp và sự trang sức. Hanh thông nhưng chỉ 'có chút lợi' — vì hình thức đẹp đẽ giúp ích nhưng không phải yếu tố quyết định. Văn hóa, nghệ thuật, lễ nghi là cần thiết cho xã hội, nhưng đừng để cái đẹp bề ngoài che lấp sự trống rỗng bên trong.`,
    image_action: `Người quân tử lấy đó mà xử lý chính sự rõ ràng, nhưng không dám dùng hình thức bên ngoài để xét xử. Phân biệt rõ giữa vẻ đẹp thật và sự giả tạo.`,
    state_trend: `THUẬN LỢI nhưng hạn chế — thuận lợi cho việc nhỏ, trang trí, hoàn thiện, không phải cho việc lớn mang tính đột phá`,
  },
  23: {
    coreMeaning: `Bóc mòn, sụp đổ — năm âm bóc dần một dương còn sót, tiểu nhân đắc thế, quân tử co cụm. Thời suy tàn, cần nhẫn nại chờ đợi.`,
    judgment_interpretation: `Quẻ Bác cảnh báo thời kỳ suy thoái nghiêm trọng — nền tảng bị bóc mòn từ dưới lên, chỉ còn một chút dương ở trên cùng. Không nên hành động, không nên tiến tới. Đây là lúc cần co cụm, bảo toàn lực lượng, chờ thời cơ mới.`,
    image_action: `Người trên lấy đó mà hậu đãi kẻ dưới để giữ vững nền nhà. Muốn bền vững phải chăm lo nền tảng, đừng chỉ nhìn lên đỉnh.`,
    state_trend: `BẤT LỢI — thế suy rõ ràng, tiểu nhân đang lên, không phải lúc hành động`,
  },
  24: {
    coreMeaning: `Trở lại, phục hồi — một dương quay lại từ dưới cùng, ánh sáng le lói giữa bóng tối. Sau suy tàn là khởi đầu mới, vòng tuần hoàn của tạo hóa.`,
    judgment_interpretation: `Quẻ Phục là sự hồi sinh sau thời kỳ đen tối của quẻ Bác. Một hào dương trở lại ở dưới cùng — như mầm non nhú lên từ đất đông. 'Bảy ngày quay lại' nói lên quy luật tuần hoàn tất yếu: suy cực thì phục sinh. Đây là thời điểm đầy hy vọng, nên khởi hành.`,
    image_action: `Bậc tiên vương lấy đó mà ngày đông chí đóng cửa quan ải, thương nhân không đi lại, vua không tuần hành. Lúc dương mới phục, cần bảo vệ, nuôi dưỡng, không được xáo trộn.`,
    state_trend: `THUẬN LỢI — đang phục hồi, hy vọng mới, nhưng cần kiên nhẫn vì mới chỉ là khởi đầu`,
  },
  25: {
    coreMeaning: `Không vọng tưởng, chân thật tự nhiên — trời trên sấm dưới, vạn vật vận hành theo đạo tự nhiên, không giả dối, không mong cầu hão huyền.`,
    judgment_interpretation: `Quẻ Vô Vọng nói về sự chân thật thuần khiết — hành động thuận theo tự nhiên, không tính toán vụ lợi. Khi lòng ngay thẳng, mọi việc hanh thông. Nhưng nếu hành động sai lệch, dù nhỏ cũng gây họa. Đây không phải sự thụ động mà là sự hợp nhất hoàn hảo giữa ý chí và đạo trời.`,
    image_action: `Bậc tiên vương lấy đó mà phù hợp thời tiết, nuôi dưỡng muôn vật. Thuận theo tự nhiên, không ép buộc, không bóp méo.`,
    state_trend: `THUẬN LỢI — nếu hành động chân thành, thuận tự nhiên thì đại hanh. Nếu tính toán vụ lợi thì gặp họa`,
  },
  26: {
    coreMeaning: `Tích chứa lớn — núi chứa trời, sức mạnh cương kiện được tích lũy và kiềm chế bởi sự tĩnh lặng. Tích đức, tích tài, tích trí để chờ ngày bùng phát.`,
    judgment_interpretation: `Quẻ Đại Súc nói về sự tích lũy lớn lao — cả vật chất lẫn tinh thần. 'Không ăn ở nhà' nghĩa là người tài phải ra phụng sự thiên hạ, không nên ẩn giấu tài năng. Khi đã tích lũy đủ, có thể vượt qua mọi thử thách lớn.`,
    image_action: `Người quân tử lấy đó mà học nhiều về lời nói và việc làm của người xưa, để tích lũy đức hạnh cho mình.`,
    state_trend: `THUẬN LỢI — đang trong giai đoạn tích lũy sức mạnh, sẵn sàng cho bước đột phá lớn`,
  },
  27: {
    coreMeaning: `Nuôi dưỡng — núi trên sấm dưới, như hàm miệng nhai thức ăn. Cả nghĩa nuôi thân lẫn nuôi tâm, cần chọn lọc điều gì đưa vào và cho ra.`,
    judgment_interpretation: `Quẻ Di nhắc nhở về cách nuôi dưỡng — cả thể xác lẫn tinh thần. Nhìn cách người ta ăn uống (tiêu thụ) sẽ hiểu bản chất con người đó. Tự lực cánh sinh, tự mình lo cái ăn cho mình, không ỷ lại. Chọn lọc kỹ những gì đưa vào thân và tâm.`,
    image_action: `Người quân tử lấy đó mà cẩn thận lời nói, tiết chế ăn uống. Lời ra khỏi miệng và thức ăn vào miệng đều cần chọn lọc.`,
    state_trend: `TRUNG TÍNH — tùy thuộc vào cách nuôi dưỡng: đúng thì tốt, sai thì xấu`,
  },
  28: {
    coreMeaning: `Vượt quá mức lớn — cột kèo cong vì quá tải, tình hình phi thường đòi hỏi hành động phi thường. Dám làm điều lớn lao trong hoàn cảnh bất thường.`,
    judgment_interpretation: `Quẻ Đại Quá báo hiệu tình trạng quá tải — cột kèo nhà bị cong vì gánh nặng quá sức. Nhưng chính trong hoàn cảnh cực đoan này, hành động quyết liệt mới là đúng đắn. Đây là lúc cần người phi thường làm việc phi thường, không thể dùng biện pháp thường.`,
    image_action: `Người quân tử dù đứng một mình cũng không sợ, dù rời bỏ thế gian cũng không buồn. Có dũng khí vượt lên trên thông thường.`,
    state_trend: `BẤT LỢI cho cách làm thông thường — nhưng THUẬN LỢI cho hành động phi thường, đột phá`,
  },
  29: {
    coreMeaning: `Hiểm trở chồng hiểm trở — nước chảy liên tục, hố sâu nối hố sâu. Đối mặt với nguy nan bằng lòng thành tín và đức cương trung, như nước luôn tìm đường chảy qua.`,
    judgment_interpretation: `Tập Khảm — hiểm nạn chồng chất, nhưng bên trong vẫn giữ được lòng thành tín thì tâm vẫn hanh thông. Như nước dù gặp hố sâu vẫn chảy đầy rồi tràn qua — không né tránh mà đối mặt trực diện. Hành động dũng cảm trong nguy nan là đáng trọng.`,
    image_action: `Người quân tử lấy đó mà giữ đức hạnh bền bỉ, tập luyện việc dạy dỗ liên tục. Kiên trì như nước — mềm mà mạnh, không gì cản nổi.`,
    state_trend: `BẤT LỢI — nguy hiểm trùng trùng, nhưng nếu giữ vững lòng tin và hành động đúng vẫn vượt qua được`,
  },
  30: {
    coreMeaning: `Bám víu, sáng chói — lửa chồng lửa, cần có vật để bám mới cháy. Sự sáng suốt cần nương vào chính đạo, phụ thuộc vào điều đúng đắn để tỏa sáng.`,
    judgment_interpretation: `Quẻ Ly nói về ánh sáng và sự bám víu. Lửa cần nhiên liệu mới cháy — con người cần bám vào chính đạo mới sáng. 'Nuôi bò cái' tượng trưng cho sự nhu thuận, kiên nhẫn. Người sáng suốt mà kiêm thêm đức nhu thuận sẽ hanh thông lâu dài.`,
    image_action: `Bậc đại nhân lấy đó mà nối tiếp ánh sáng chiếu soi bốn cõi. Truyền bá văn minh, giáo dục, khai sáng liên tục không ngừng.`,
    state_trend: `THUẬN LỢI — sáng suốt và minh mẫn, nhưng cần bám vào chính đạo mới bền`,
  },
  31: {
    coreMeaning: `Cảm ứng, giao cảm — đầm trên núi, thiếu nữ và thiếu nam gặp gỡ. Sự cảm thông tự nhiên giữa hai bên, không cần lời nói mà tâm đã thông.`,
    judgment_interpretation: `Quẻ Hàm mở đầu Hạ Kinh với chủ đề quan hệ nam nữ, vợ chồng — nền tảng của nhân luân. Thiếu nam (Cấn) khiêm nhường ở dưới, thiếu nữ (Đoài) vui vẻ ở trên — nam cầu nữ theo đúng lễ. Sự cảm ứng chân thành giữa hai tâm hồn mang lại hanh thông.`,
    image_action: `Người quân tử lấy đó mà rỗng lòng tiếp nhận người khác. Mở rộng tấm lòng, khiêm nhường lắng nghe, thì tự nhiên người khác cảm mến.`,
    state_trend: `THUẬN LỢI — đặc biệt tốt cho quan hệ, hợp tác, kết nối mới`,
  },
  32: {
    coreMeaning: `Bền bỉ, hằng cửu — sấm gió cùng đi, vợ chồng gắn bó lâu dài. Không phải bất biến mà là biến đổi trong sự nhất quán, giữ đạo lâu bền giữa muôn thay đổi.`,
    judgment_interpretation: `Quẻ Hằng nói về sự bền bỉ — không phải đứng yên một chỗ mà là kiên trì theo đạo giữa muôn biến đổi. Sấm (Chấn) động bên trên, gió (Tốn) nhập bên dưới — động mà thuận, biến mà hằng. Giữ vững nguyên tắc cốt lõi trong khi linh hoạt thích ứng, đó mới là bền thật.`,
    image_action: `Người quân tử lấy đó mà đứng vững không đổi phương hướng. Kiên định mục tiêu, nhất quán trong nguyên tắc, dù hoàn cảnh thay đổi.`,
    state_trend: `THUẬN LỢI — bền bỉ theo đúng đạo thì hanh thông, nửa chừng bỏ dở thì thất bại`,
  },
  33: {
    coreMeaning: `Lui ẩn chiến lược — biết rút lui đúng lúc là sức mạnh, không phải yếu đuối. Núi dưới Trời: kẻ tiểu nhân đang tiến lên, người quân tử cần tránh xa.`,
    judgment_interpretation: `Khi hoàn cảnh bất lợi, rút lui là hành động sáng suốt nhất. Không cố chấp giữ vị trí khi thế lực tiêu cực đang lên — biết lui mới có thể bảo toàn và chờ thời. Dù phải lui, vẫn giữ vững nguyên tắc đạo đức.`,
    image_action: `Hãy tự tạo khoảng cách với người tiểu nhân, không đối đầu trực tiếp mà dùng sự xa cách để tự bảo vệ.`,
    state_trend: `BẤT LỢI — Thế lực tiêu cực đang lớn mạnh, cần rút lui để bảo toàn`,
  },
  34: {
    coreMeaning: `Sức mạnh lớn lao — dương khí đang cực thịnh, nhưng sức mạnh phải đi đôi với chính đạo. Sấm vang trên Trời: năng lượng bùng nổ, cần kiểm soát.`,
    judgment_interpretation: `Khi sức mạnh đang ở đỉnh cao, điều quan trọng nhất là dùng sức mạnh đó đúng đắn. Sức mạnh không kiềm chế sẽ trở thành bạo lực. Chỉ khi sức mạnh phục vụ chính nghĩa mới thật sự vĩ đại.`,
    image_action: `Hành xử đúng lễ nghĩa, không dựa vào sức mạnh để ức hiếp. Có sức mạnh mà biết tự kiềm chế mới là người quân tử.`,
    state_trend: `THUẬN LỢI — Đang ở thế mạnh, nhưng cần dùng sức mạnh đúng cách`,
  },
  35: {
    coreMeaning: `Tiến lên sáng tỏ — mặt trời mọc trên mặt đất, ánh sáng lan tỏa. Thời kỳ thăng tiến, được cấp trên tin dùng, tài năng được công nhận.`,
    judgment_interpretation: `Như vị chư hầu hiền đức được nhà vua trọng dụng — ban cho ngựa tốt, ngày tiếp kiến ba lần. Đây là thời điểm tài năng và đức hạnh được công nhận, sự nghiệp thăng tiến rõ rệt. Quan trọng là giữ đức khiêm cung trong vinh hoa.`,
    image_action: `Tự mình sáng tỏ đức hạnh, dùng ánh sáng nội tại để chiếu rọi và ảnh hưởng tích cực đến người khác.`,
    state_trend: `THUẬN LỢI — Thời kỳ thăng tiến, ánh sáng đang lên`,
  },
  36: {
    coreMeaning: `Ánh sáng bị thương — mặt trời lặn vào lòng đất, kẻ sáng suốt phải che giấu tài năng trong thời tăm tối. Nghệ thuật sinh tồn khi tiểu nhân nắm quyền.`,
    judgment_interpretation: `Trong thời buổi tăm tối, người tài phải chịu gian khổ mà vẫn giữ chính đạo. Không lộ tài năng ra ngoài, ẩn mình chờ đợi. Như Cơ Tử phải giả điên để sống sót dưới triều Trụ Vương — đau khổ nhưng không đánh mất bản thân.`,
    image_action: `Giấu ánh sáng nội tại, tỏ ra bình thường bên ngoài. Dùng trí tuệ để sinh tồn, không phô trương tài năng.`,
    state_trend: `BẤT LỢI — Thời tăm tối, người sáng bị đè nén, cần ẩn nhẫn`,
  },
  37: {
    coreMeaning: `Gia đình — nền tảng của mọi trật tự xã hội. Gió từ Lửa sinh ra: hơi ấm từ bếp lửa gia đình lan tỏa khắp nơi. Quản lý gia đình tốt là cơ sở để quản lý thiên hạ.`,
    judgment_interpretation: `Gia đình vận hành tốt khi mỗi người giữ đúng vai trò của mình. Người phụ nữ (nội trợ) giữ chính đạo bên trong, người đàn ông lo bên ngoài — đây là nói về phân công hợp lý, không phải phân biệt giới. Trong tổ chức hiện đại: mỗi thành viên có trách nhiệm rõ ràng.`,
    image_action: `Lời nói phải có thực chất (lửa), hành động phải nhất quán (gió). Nói được phải làm được.`,
    state_trend: `THUẬN LỢI — Gia đạo hanh thông khi có kỷ cương và tình thương`,
  },
  38: {
    coreMeaning: `Trái ngược, bất đồng — Lửa bốc lên, Đầm chảy xuống, hai chiều ngược nhau. Trong sự khác biệt vẫn tìm được điểm chung, hòa giải trong đối lập.`,
    judgment_interpretation: `Khi có sự bất đồng, không nên cố làm việc lớn mà hãy bắt đầu từ việc nhỏ. Hai bên khác biệt quan điểm nhưng vẫn có thể hợp tác ở những điều cụ thể, nhỏ bé. Từ những thỏa thuận nhỏ, dần dần xây dựng lại sự tin tưởng.`,
    image_action: `Trong sự đồng nhất, giữ bản sắc riêng. Trong sự khác biệt, tìm mục tiêu chung.`,
    state_trend: `TRUNG TÍNH — Có mâu thuẫn nhưng vẫn có thể giải quyết nếu khéo léo`,
  },
  39: {
    coreMeaning: `Trắc trở hiểm nghèo — phía trước là vực nước sâu, phía sau là núi chắn. Tiến thoái đều khó, cần dừng lại suy xét, tìm người giúp đỡ.`,
    judgment_interpretation: `Gặp trắc trở nên đi theo hướng dễ (Tây Nam = Khôn = bằng phẳng), tránh hướng khó (Đông Bắc = Cấn = núi non). Tìm người có đức có tài để xin chỉ dẫn. Trong khó khăn, giữ vững chính đạo là chìa khóa.`,
    image_action: `Quay về tự xét mình, tu sửa đức hạnh. Khó khăn bên ngoài là cơ hội nhìn lại bên trong.`,
    state_trend: `BẤT LỢI — Đang gặp trắc trở, không nên cố tiến mà nên tìm trợ giúp`,
  },
  40: {
    coreMeaning: `Giải thoát, tháo gỡ — Sấm động trên Nước: mưa giông giải tỏa sức nóng ngột ngạt. Khó khăn đã qua, bế tắc được khai thông, cần nhanh chóng ổn định.`,
    judgment_interpretation: `Khi khó khăn đã được giải tỏa, nên đi hướng dễ dàng (Tây Nam). Nếu không có việc gì gấp thì về nhà nghỉ ngơi. Nếu có việc phải làm thì làm cho sớm, đừng trì hoãn. Sau giải phóng, nhanh chóng khôi phục trật tự.`,
    image_action: `Tha thứ lỗi lầm, giảm nhẹ hình phạt. Sau khó khăn nên khoan hồng, cho mọi người cơ hội làm lại.`,
    state_trend: `THUẬN LỢI — Khó khăn đang được gỡ bỏ, cần hành động nhanh để ổn định`,
  },
  41: {
    coreMeaning: `Giảm bớt — bớt phần dưới thêm phần trên, hy sinh lợi ích cá nhân để phụng sự mục tiêu lớn hơn. Núi dưới Đầm: núi bị bào mòn làm đầm thêm sâu.`,
    judgment_interpretation: `Giảm bớt không phải mất mát — khi lòng chân thành, dù lễ vật đơn sơ (hai giỏ cơm) cũng đủ. Hy sinh phần vật chất để nuôi dưỡng phần tinh thần. Thời kỳ cần tiết kiệm, giản dị, nhưng giàu có về tâm hồn.`,
    image_action: `Kiềm chế dục vọng, bớt giận dữ, giảm ham muốn. Tự mình giảm bớt để tinh thần thăng hoa.`,
    state_trend: `TRUNG TÍNH — Giảm bớt vật chất nhưng tăng giá trị tinh thần, cần sự chân thành`,
  },
  42: {
    coreMeaning: `Tăng thêm — bớt trên thêm dưới, người lãnh đạo hy sinh cho dân chúng. Gió và Sấm tăng cường lẫn nhau: thời kỳ phát triển, mở rộng, ban ơn.`,
    judgment_interpretation: `Thời kỳ thuận lợi để hành động lớn — vượt sông lớn (dấn thân vào việc khó) sẽ thành công. Trên hy sinh cho dưới, lãnh đạo ban phúc cho dân, nên được lòng người, làm gì cũng hanh thông.`,
    image_action: `Thấy điều tốt thì theo, thấy lỗi lầm thì sửa. Luôn tự cải thiện bản thân.`,
    state_trend: `THUẬN LỢI — Thời kỳ phát triển, được hỗ trợ, nên mở rộng`,
  },
  43: {
    coreMeaning: `Quyết đoán, quét sạch — năm hào dương quyết liệt loại bỏ một hào âm cuối cùng. Đầm lên Trời: nước dâng lên trời sẽ trút xuống, quyết liệt và triệt để.`,
    judgment_interpretation: `Loại bỏ kẻ xấu phải công khai minh bạch (tuyên bố ở triều), không dùng bạo lực (bất lợi dùng binh) mà dùng chính nghĩa. Phải bắt đầu từ nội bộ (thông báo từ thành ấp) — tự sửa mình trước khi sửa người.`,
    image_action: `Ban phúc cho người dưới, phân phát tài lộc. Như nước trên trời phải trút xuống — của cải tích lũy phải được chia sẻ.`,
    state_trend: `THUẬN LỢI nhưng NGUY — Đang ở thế áp đảo, cần quyết đoán nhưng cẩn thận`,
  },
  44: {
    coreMeaning: `Gặp gỡ bất ngờ — một hào âm lén vào dưới năm hào dương, âm bắt đầu xâm nhập. Gió dưới Trời: gió mang theo mầm mống thay đổi, cần cảnh giác.`,
    judgment_interpretation: `Sự xuất hiện bất ngờ của yếu tố âm (yếu tố mới, lạ) trong thế giới dương. Thoạt nhìn hấp dẫn nhưng ẩn chứa nguy cơ — như gặp người lạ quyến rũ nhưng không nên cam kết lâu dài. Cần tỉnh táo trước cái mới mẻ, không bị mê hoặc.`,
    image_action: `Ban bố chính lệnh rõ ràng cho bốn phương. Khi phát hiện mầm mống tiêu cực, phải xử lý ngay từ đầu.`,
    state_trend: `BẤT LỢI — Có yếu tố xấu đang lén xâm nhập, cần cảnh giác từ sớm`,
  },
  45: {
    coreMeaning: `Tụ hội, quần tụ — Đầm trên Đất: nước tụ lại thành đầm. Mọi người tụ họp quanh lãnh đạo có đức, cần chuẩn bị chu đáo và phòng ngừa bất trắc.`,
    judgment_interpretation: `Khi nhiều người tụ họp, cần có lãnh đạo (vua), có trung tâm tinh thần (miếu), và có mục đích chung. Tụ hội mà không có trật tự sẽ thành hỗn loạn. Dùng lễ vật lớn — đầu tư nghiêm túc cho sự kiện tập thể.`,
    image_action: `Sửa soạn vũ khí phòng bị bất trắc. Nơi đông người cần phòng ngừa — chuẩn bị cho mọi tình huống.`,
    state_trend: `THUẬN LỢI — Thời kỳ tập hợp lực lượng, đoàn kết, cần lãnh đạo mạnh`,
  },
  46: {
    coreMeaning: `Đi lên, thăng tiến — cây mọc trong lòng đất, từ từ vươn lên không ngừng. Sự phát triển âm thầm, bền bỉ, dựa trên nội lực chứ không phô trương.`,
    judgment_interpretation: `Thăng tiến từ từ và bền vững — như cây mọc lên, không ồn ào nhưng không ngừng. Gặp người có đức có tài (đại nhân) để được dẫn dắt. Tiến về phương Nam (hướng sáng, hướng Ly) là đúng đắn.`,
    image_action: `Tích lũy từng chút một, thuận theo tự nhiên mà phát triển. Như cây mọc — không ép tốc độ, nhưng không bao giờ ngừng.`,
    state_trend: `THUẬN LỢI — Thời kỳ thăng tiến bền vững, phát triển từ từ nhưng chắc chắn`,
  },
  47: {
    coreMeaning: `Khốn cùng, bế tắc — Đầm không có nước, cạn kiệt. Nước chảy xuống dưới để Đầm trên trống rỗng. Thử thách cực độ rèn luyện ý chí — qua khốn cùng mới thấy bản lĩnh.`,
    judgment_interpretation: `Nghịch lý: khốn cùng mà vẫn hanh thông — nhưng chỉ với bậc đại nhân biết giữ chính đạo. Trong khốn cùng, lời nói không có giá trị (không ai tin) — chỉ hành động và nhẫn nại mới chứng minh bản thân. Đây là lò luyện kim: qua lửa mới thành vàng.`,
    image_action: `Dùng mạng sống (ý chí) để thực hiện chí hướng. Khi tài nguyên cạn kiệt, chỉ còn ý chí là vũ khí cuối cùng.`,
    state_trend: `BẤT LỢI — Đang ở đáy khó khăn, kiệt quệ, nhưng giữ vững sẽ qua`,
  },
  48: {
    coreMeaning: `Giếng nước — nguồn tài nguyên bất biến, nuôi dưỡng vạn vật. Thành ấp có thể dời, giếng không thể dời. Giá trị cốt lõi không thay đổi dù hoàn cảnh đổi thay.`,
    judgment_interpretation: `Giếng là biểu tượng cho nguồn lực bất biến — đạo đức, tri thức, tài nguyên thiên nhiên. Dù xã hội thay đổi, giếng vẫn vậy. Nhưng nếu gần đến mà dây quá ngắn (công phu chưa đủ) hoặc vỡ bình (thiếu phương tiện), thì trước mắt có nước mà không uống được — đáng tiếc nhất.`,
    image_action: `Khuyến khích dân chúng cùng giúp đỡ lẫn nhau. Như giếng nuôi tất cả — hãy là nguồn lực cho cộng đồng.`,
    state_trend: `TRUNG TÍNH — Nguồn lực có sẵn nhưng cần phương tiện đúng để khai thác`,
  },
  49: {
    coreMeaning: `Cách mạng, biến đổi triệt để. Khi thời cơ chín muồi, sự thay đổi lớn là tất yếu và cần thiết.`,
    judgment_interpretation: `Cách mạng không thể vội vàng — phải đợi đến lúc lòng người đã tin tưởng mới nên tiến hành. Khi thời cơ đến, sự thay đổi sẽ hanh thông lớn lao. Giữ vững chính đạo thì mọi hối hận đều tan biến.`,
    image_action: `Quân tử theo đó mà trị lịch, làm sáng tỏ thời tiết — nắm bắt quy luật thay đổi để hành động đúng thời.`,
    state_trend: `THUẬN LỢI — Thời cơ đổi mới đã chín, thay đổi triệt để sẽ đem lại kết quả tốt`,
  },
  50: {
    coreMeaning: `Cái đỉnh — biểu tượng của sự chuyển hóa, nuôi dưỡng hiền tài và thiết lập trật tự mới sau cách mạng.`,
    judgment_interpretation: `Cái đỉnh dùng để nấu chín thức ăn tế lễ — tượng trưng cho việc nuôi dưỡng hiền tài và thờ phụng Thượng Đế. Sau cách mạng (quẻ Cách), cần đỉnh để thiết lập trật tự mới. Mọi việc hanh thông lớn.`,
    image_action: `Quân tử theo đó mà chính vị ngưng mệnh — giữ vững vị trí chính đáng, vâng theo thiên mệnh.`,
    state_trend: `THUẬN LỢI — Thời kỳ thiết lập và xây dựng, nuôi dưỡng nhân tài, mọi việc hanh thông`,
  },
  51: {
    coreMeaning: `Sấm sét chấn động — cú sốc mạnh mẽ mang tính thức tỉnh. Biết kính sợ thì chuyển họa thành phúc.`,
    judgment_interpretation: `Sấm sét gây chấn động mạnh khiến người ta sợ hãi — nhưng chính sự kính sợ đó giúp tỉnh giác và tự sửa mình. Sau cơn sợ sẽ đến niềm vui. Người quân tử dù chấn động trăm dặm vẫn giữ bình tĩnh, không đánh rơi đồ tế lễ thiêng liêng.`,
    image_action: `Quân tử theo đó mà sợ hãi tự xét mình — lấy sự kính sợ làm động lực tu dưỡng bản thân.`,
    state_trend: `TRUNG TÍNH — Cú sốc ban đầu gây bất an nhưng nếu biết kính sợ sẽ chuyển thành hanh thông`,
  },
  52: {
    coreMeaning: `Dừng lại, tĩnh lặng. Biết dừng đúng lúc là trí tuệ — núi đứng vững không lay động.`,
    judgment_interpretation: `Dừng lại ở phía sau lưng — không theo đuổi dục vọng trước mắt. Khi đi trong sân mà không thấy ai, tức là tâm đã tĩnh lặng đến mức không bị ngoại cảnh chi phối. Biết dừng đúng chỗ thì không lỗi.`,
    image_action: `Quân tử theo đó mà suy nghĩ không vượt ra ngoài vị trí của mình — an phận, tập trung vào việc của mình.`,
    state_trend: `TRUNG TÍNH — Thời điểm cần dừng lại, tĩnh tâm, không nên hành động vội vàng`,
  },
  53: {
    coreMeaning: `Tiến dần dần, từng bước vững chắc. Như chim hồng bay từ bờ nước lên đỉnh núi — mỗi bước đều đúng lúc.`,
    judgment_interpretation: `Việc gả con gái phải theo lễ nghi, từng bước từng bước — không thể vội vàng. Cũng như mọi sự phát triển chân chính đều cần thời gian và trình tự đúng đắn. Giữ chính đạo thì mọi việc tốt lành.`,
    image_action: `Quân tử theo đó mà ở nơi hiền đức, thiện lương để cải hóa phong tục — kiên trì giáo hóa, từ từ thay đổi.`,
    state_trend: `THUẬN LỢI — Tiến bộ từ từ nhưng chắc chắn, đừng nóng vội`,
  },
  54: {
    coreMeaning: `Em gái về nhà chồng — mối quan hệ không cân xứng, hành động vội vàng không theo đúng đạo sẽ gặp hung.`,
    judgment_interpretation: `Con gái em (muội) về nhà chồng — vị trí không chính, quan hệ không cân xứng. Sấm (Chấn) ở trên Đầm (Đoài) — hành động mạnh mẽ dựa trên niềm vui nhất thời, không theo đúng lễ nghĩa. Tiến tới sẽ gặp hung hiểm, không có gì lợi.`,
    image_action: `Quân tử theo đó mà biết sự tệ hại lâu dài — nhìn xa trông rộng, đừng vì cái vui trước mắt.`,
    state_trend: `BẤT LỢI — Hành động vội vàng, quan hệ không cân bằng, kết quả không tốt`,
  },
  55: {
    coreMeaning: `Phong phú, thịnh đại cực điểm. Như mặt trời giữa trưa — rực rỡ nhất nhưng cũng bắt đầu ngả về chiều.`,
    judgment_interpretation: `Thời kỳ cực thịnh, mọi việc hanh thông, vua chúa đạt được sự vĩ đại. Đừng lo lắng về sự suy tàn tất yếu — hãy tận dụng lúc mặt trời đang ở đỉnh cao nhất. Mặt trời giữa trưa tuy sắp ngả nhưng đó là lúc sáng nhất.`,
    image_action: `Quân tử theo đó mà xử kiện và thi hành hình phạt — dùng sự sáng suốt và quyết đoán trong lúc quyền lực sung mãn.`,
    state_trend: `THUẬN LỢI — Đỉnh cao thịnh vượng, nhưng cần ý thức sẽ không kéo dài mãi`,
  },
  56: {
    coreMeaning: `Lữ khách, người đi đường — tạm bợ, không có chỗ dựa vững chắc. Cần khiêm tốn và cẩn thận nơi đất khách.`,
    judgment_interpretation: `Người lữ hành chỉ có thể đạt được hanh thông nhỏ — vì thân ở đất khách, không có nền tảng vững. Nhưng nếu giữ chính đạo, khiêm tốn và thận trọng, thì lữ khách vẫn được tốt lành.`,
    image_action: `Quân tử theo đó mà sáng suốt cẩn thận khi dùng hình phạt, không giam giữ lâu — xử lý nhanh gọn, đừng kéo dài.`,
    state_trend: `TRUNG TÍNH — Không ổn định, tạm bợ, nhưng khiêm tốn cẩn thận thì qua được`,
  },
  57: {
    coreMeaning: `Gió nhẹ thâm nhập khắp nơi — sự mềm mại kiên trì, thuận theo mà dần dần thấm sâu.`,
    judgment_interpretation: `Gió không mạnh như sấm nhưng thâm nhập khắp nơi — sức mạnh của sự mềm mại và kiên trì. Hanh thông tuy nhỏ nhưng bền bỉ. Nên theo người lãnh đạo sáng suốt và có hướng đi rõ ràng.`,
    image_action: `Quân tử theo đó mà ban bố mệnh lệnh, thi hành công việc — lệnh phải rõ ràng, nhắc đi nhắc lại cho thấm.`,
    state_trend: `THUẬN LỢI NHỎ — Mọi việc tiến triển từ từ bằng sự mềm mỏng và kiên nhẫn`,
  },
  58: {
    coreMeaning: `Vui vẻ, hòa duyệt. Đầm nước trong vui tươi — niềm vui chân thành cảm hóa được lòng người.`,
    judgment_interpretation: `Niềm vui chân chính mang lại hanh thông. Đầm nước liên thông, vui vẻ mà không buông thả — giữ chính đạo thì niềm vui bền lâu. Vui mà vẫn giữ được đạo lý mới là vui thật sự.`,
    image_action: `Quân tử theo đó mà cùng bạn bè giảng tập thảo luận — niềm vui của việc học hỏi cùng nhau.`,
    state_trend: `THUẬN LỢI — Niềm vui chân thành mang lại may mắn, mọi việc hanh thông`,
  },
  59: {
    coreMeaning: `Tan rã, phân tán — nhưng cũng là giải tỏa ứ đọng. Gió thổi trên nước, phá tan băng giá để vạn vật lưu thông.`,
    judgment_interpretation: `Khi sự ứ đọng, bế tắc được phá vỡ thì hanh thông. Vua đến tông miếu — dùng đức tín ngưỡng để tập hợp lòng người đang tản mát. Thời điểm thuận lợi để vượt qua khó khăn lớn, miễn giữ chính đạo.`,
    image_action: `Tiên vương theo đó mà thờ Thượng Đế lập tông miếu — dùng tín ngưỡng và lý tưởng chung để quy tụ lòng người.`,
    state_trend: `THUẬN LỢI — Phá vỡ bế tắc, giải tỏa ứ đọng, mở ra cục diện mới`,
  },
  60: {
    coreMeaning: `Tiết chế, giới hạn. Nước trong đầm có giới hạn — tiết độ đúng mức thì tốt, quá mức thì khổ.`,
    judgment_interpretation: `Tiết chế giúp vạn vật có trật tự — bốn mùa luân chuyển đều có tiết. Nhưng tiết chế quá đáng, khắc khổ quá mức thì không ai chịu nổi lâu dài. Giới hạn phải vừa phải, hợp lý mới bền được.`,
    image_action: `Quân tử theo đó mà chế định số lượng, bàn luận đức hạnh hành vi — đặt ra quy tắc hợp lý.`,
    state_trend: `THUẬN LỢI — Tiết chế đúng mức sẽ hanh thông, nhưng đừng quá khắt khe`,
  },
  61: {
    coreMeaning: `Lòng thành tín từ bên trong — chân thành đến tận xương tủy, cảm hóa được cả cá heo dưới nước.`,
    judgment_interpretation: `Lòng thành tín chân thật từ bên trong — đến cá heo (loài khó cảm hóa nhất) cũng bị cảm động. Với lòng thành như vậy, vượt qua mọi khó khăn lớn đều thuận lợi. Giữ chính đạo thì thành tín mới bền.`,
    image_action: `Quân tử theo đó mà bàn luận hình phạt, trì hoãn tử hình — lấy lòng nhân ái và thận trọng trong việc xét xử.`,
    state_trend: `THUẬN LỢI — Lòng thành tín là sức mạnh lớn nhất, mọi việc sẽ hanh thông`,
  },
  62: {
    coreMeaning: `Vượt quá nhỏ — như chim nhỏ bay, nên hạ không nên lên. Làm việc nhỏ nên hơi quá, việc lớn thì không nên.`,
    judgment_interpretation: `Thời kỳ vượt quá nhỏ — âm vượt quá dương một chút. Việc nhỏ thì hơi quá cũng được (khiêm tốn quá, tiết kiệm quá, cẩn thận quá). Nhưng việc lớn thì không nên vượt quá. Như chim nhỏ nên bay thấp, không nên bay cao.`,
    image_action: `Quân tử theo đó mà hành vi quá cung kính, tang sự quá bi ai, chi tiêu quá tiết kiệm — trong việc nhỏ nên hơi quá một chút.`,
    state_trend: `THUẬN LỢI NHỎ — Việc nhỏ thuận lợi, việc lớn không nên; khiêm tốn quá mức cũng tốt`,
  },
  63: {
    coreMeaning: `Đã hoàn thành — mọi việc đã xong, trật tự hoàn hảo. Nhưng chính lúc hoàn hảo nhất là lúc bắt đầu suy.`,
    judgment_interpretation: `Mọi hào đều đắc vị — trật tự hoàn hảo nhất trong 64 quẻ. Nhưng chính vì đã hoàn thành nên chỉ hanh thông nhỏ (không còn gì để phát triển). Ban đầu tốt nhưng nếu không cảnh giác, cuối cùng sẽ loạn. Đỉnh cao nào cũng dẫn đến suy tàn.`,
    image_action: `Quân tử theo đó mà lo nghĩ đến họa hoạn và phòng bị trước — thịnh cực tất suy, phải chuẩn bị.`,
    state_trend: `TRUNG TÍNH — Đã thành công nhưng đỉnh cao chính là khởi đầu của suy tàn, cần cảnh giác`,
  },
  64: {
    coreMeaning: `Chưa hoàn thành — vạn vật chưa bao giờ kết thúc, luôn có sự khởi đầu mới. Quẻ cuối cùng mà mang ý nghĩa chưa xong.`,
    judgment_interpretation: `Chưa hoàn thành — mọi hào đều bất chính nhưng lại hanh thông vì còn tiềm năng phát triển. Con cáo nhỏ sắp qua sông mà ướt đuôi — gần thành công mà thất bại ở bước cuối. Cần cẩn thận và kiên trì cho đến khi thực sự xong.`,
    image_action: `Quân tử theo đó mà cẩn thận phân biệt sự vật, đặt đúng vị trí — cần sắp xếp lại trật tự.`,
    state_trend: `TRUNG TÍNH — Chưa xong nhưng đầy tiềm năng, cần kiên trì và cẩn thận đến phút cuối`,
  },
};
