# scripts/architect-20260823-orch-prose-ceiling-row-handoff.jq
# Task: FIX-ORCH-PROSE-CEILING-BLOCKS-NUMERIC-OCCURRENCE-BUMP-ON-OVER-CEILING-ROWS
# Architect handoff -> pm. Brief:
#   docs/architecture-briefs/2026-08-23-orch-row-prose-ceiling-value-shape-measure-and-frozen-cohort-paydown.md
# Usage: jq -f scripts/architect-20260823-orch-prose-ceiling-row-handoff.jq \
#          docs/data/orch/orch-state.json | bash scripts/orch-apply.sh
.task_board.ready |= map(
  if .id == "FIX-ORCH-PROSE-CEILING-BLOCKS-NUMERIC-OCCURRENCE-BUMP-ON-OVER-CEILING-ROWS"
  then . + {
    next_agent: "pm",
    architect_design_complete: true,
    architect_completed_at: "2026-08-23T11:45:00Z",
    architect_handoff: "docs/architecture-briefs/2026-08-23-orch-row-prose-ceiling-value-shape-measure-and-frozen-cohort-paydown.md",
    architect_review_note: "DESIGN COMPLETE 2026-08-23 -> brief (8 sections, all figures measured live, ACs replayed on a live-data prototype). FROZEN COHORT = 23, NOT 1 (backlog 11 / ready 12 / review 0 of 585); +15 MORE over-ceiling rows sit in UNGUARDED lanes. Cohort trend 33->35->38->38->36 over 08-09..08-22 while row count FELL 615->549; today's 23 is a review[] paydown, not decay. FOUR DEFECTS, not one. D1 STRUCTURAL_FIELDS is a closed name-allowlist over an open namespace (846 field names live, 33 excluded, 813 counted as prose) - 3rd identical instance in 8d, and instance #1's own AC-5 already ordered the enumeration. D2 predicate is byte-exact not information-aware. D3 NEW/UNREPORTED: live baseline is looked up only in the 3 guarded lanes, so a row arriving from in_progress[]/qa[]/active_sprints[] gets liveBytes=0 and a zero-change lane-move HARD-REJECTS (proven live: UC-CCA-P3 in_progress->review, 'live=0B -> candidate=12161B', exit 1); dev-standards.md over-claims lane-agnosticism and the LANE-AGNOSTIC-MOVE test only covers backlog->review. D4 ROOT CAUSE: the 2026-08-09 brief chose (c)=3 parts in dependency order and only part 3 (the gate) shipped - the §2.3 paydown never ran on backlog[]/ready[], so the guard has run 14d in the exact brick-mode its own author ruled out. DECISION: measure the ceiling over VALUE-SHAPE-derived prose (prose iff string >200B or non-empty container), UNION'd with the existing name set - monotone, so no write that passes today can start failing. Measured: 22/23 rows STAY over ceiling (guard not disarmed); short strings hold 43,875B vs 1,616,447B for long ones, so they are not the bloat channel. REJECTED: adding occurrence_count/po_manual_dispatch_* to the name list (turn #4 of a 3-turn loop), raising the ceiling, bypass env var, integer-increment special-case (measured: same-length increments ALREADY pass, so it fixes neither of PO's blocks). RETURN PATH: orch-backlog-stub.sh has NO id/threshold filter anywhere - it is a whole-lane bulk migrator, which is why PO correctly refused it twice; add --over-ceiling-only/--ids and align STUB_FIELDS to the complement of the new measure. Projected: 22 rows touched, 426KB cold, hot file -14.5%, largest surviving row 1839B, cohort -> 0. PAYDOWN LANDMINE FOUND: today's STUB_FIELDS would strip po_manual_dispatch_flagged_at, which manual-dispatch-sweep Step 1's flag_reentrant reads INLINE with no detail_ref fallback - alignment MUST land before any run. SCOPE REDUCTION: po/flow/manual-dispatch-sweep.md needs NO edit (the stamp just lands) - drop it from the sibling row's file list, no agent-father hop. Owner: developer (zone-detect Tier-1, scripts/ + docs/policies/). Ship §3 FIRST and ALONE - it is a read-only predicate change, unblocks PO's next tick, depends on nothing open."
  }
  else . end
)
