/**
 * gen-que-descriptions.ts
 * Codegen script: reads QUE_DATA + QUE_META from mcp-server domain and emits
 * apps/frontend/app/lib/que-descriptions.generated.ts.
 *
 * Run: bun run scripts/gen-que-descriptions.ts
 * (from repo root, e.g. via `bun run gen:que` in apps/frontend/package.json)
 *
 * Re-run whenever apps/mcp-server/src/domain/services/kinhDich/hexagramLibrary.ts
 * is updated (it is itself auto-generated from Python source).
 */
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

// Cross-package relative import — script runs from repo root via bun
import {
  QUE_DATA,
  QUE_META,
} from "../apps/mcp-server/src/domain/services/kinhDich/hexagramLibrary.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const outPath = resolve(
  __dirname,
  "../apps/frontend/app/lib/que-descriptions.generated.ts"
);

// Build the entries map from QUE_META (id lookup) + QUE_DATA (descriptions)
const entries: string[] = [];

for (const meta of QUE_META) {
  const data = QUE_DATA[meta.id];
  if (!data) continue;

  const coreMeaning = data.coreMeaning.replace(/`/g, "\\`");
  const judgment_interpretation = data.judgment.interpretation.replace(
    /`/g,
    "\\`"
  );
  const image_action = data.image.action.replace(/`/g, "\\`");
  const state_trend = data.state.trend.replace(/`/g, "\\`");

  entries.push(
    `  ${meta.id}: {
    coreMeaning: \`${coreMeaning}\`,
    judgment_interpretation: \`${judgment_interpretation}\`,
    image_action: \`${image_action}\`,
    state_trend: \`${state_trend}\`,
  }`
  );
}

const output = `// AUTO-GENERATED by scripts/gen-que-descriptions.ts — DO NOT EDIT.
// Run: bun run gen:que  (from apps/frontend/ directory)
// Source: apps/mcp-server/src/domain/services/kinhDich/hexagramLibrary.ts
// Re-run this script when hexagramLibrary.ts is updated.

export interface QueDescription {
  /** Primary hover text — core meaning of the hexagram. */
  coreMeaning: string;
  /** Secondary — trading judgment / interpretation. */
  judgment_interpretation: string;
  /** Action guidance from the image/action field. */
  image_action: string;
  /** Market trend state. */
  state_trend: string;
}

export const QUE_DESCRIPTIONS: Record<number, QueDescription> = {
${entries.join(",\n")},
};
`;

writeFileSync(outPath, output, "utf-8");
console.log(`[gen-que-descriptions] Written ${entries.length} entries → ${outPath}`);
