/**
 * gen-que-descriptions.ts
 * Codegen script: reads que-reference.js from kinh-dich-service and emits
 * apps/frontend/app/lib/que-descriptions.generated.ts.
 *
 * Run: bun run scripts/gen-que-descriptions.ts
 * (from repo root, e.g. via `bun run gen:que` in apps/frontend/package.json)
 *
 * Source of truth: apps/kinh-dich-service/dashboard/que-reference.js
 * Re-run whenever que-reference.js is regenerated via:
 *   CGO_ENABLED=0 go run ./cmd/sandbox -emit-reference
 *
 * Field mapping:
 *   queReference[i].coreMeaning.vi     → QueDescription.coreMeaning
 *   queReference[i].marketTrendLabel.vi → QueDescription.marketTrendLabel
 */
import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Read que-reference.js — static file committed in the repo, no network call needed.
const queRefPath = resolve(
  __dirname,
  "../apps/kinh-dich-service/dashboard/que-reference.js"
);
const queRefContent = readFileSync(queRefPath, "utf-8");

// Strip the JS assignment wrapper: window.__QUE_REFERENCE__ = [...];
// The file has comment lines before the assignment, so we extract from the '[' onwards.
const assignIdx = queRefContent.indexOf("window.__QUE_REFERENCE__");
if (assignIdx === -1) {
  throw new Error(
    `[gen-que-descriptions] Could not find window.__QUE_REFERENCE__ in ${queRefPath}`
  );
}
const afterAssign = queRefContent.slice(assignIdx);
const stripped = afterAssign
  .replace(/^window\.__QUE_REFERENCE__\s*=\s*/, "")
  .replace(/;\s*$/, "")
  .trim();

interface QueRefEntry {
  id: number;
  coreMeaning: { vi: string; en: string };
  marketTrendLabel: { vi: string; en: string };
  [key: string]: unknown;
}

const queReference: QueRefEntry[] = JSON.parse(stripped);

const outPath = resolve(
  __dirname,
  "../apps/frontend/app/lib/que-descriptions.generated.ts"
);

// Build the entries map from que-reference.js
const entries: string[] = [];

for (const entry of queReference) {
  if (!entry || !entry.id) continue;

  const coreMeaning = entry.coreMeaning.vi.replace(/`/g, "\\`");
  const marketTrendLabel = entry.marketTrendLabel.vi.replace(/`/g, "\\`");

  entries.push(
    `  ${entry.id}: {
    coreMeaning: \`${coreMeaning}\`,
    marketTrendLabel: \`${marketTrendLabel}\`,
  }`
  );
}

const output = `// AUTO-GENERATED by scripts/gen-que-descriptions.ts — DO NOT EDIT.
// Run: bun run gen:que  (from apps/frontend/ directory)
// Source: apps/kinh-dich-service/dashboard/que-reference.js
// Re-run this script when que-reference.js is regenerated via:
//   CGO_ENABLED=0 go run ./cmd/sandbox -emit-reference

export interface QueDescription {
  /** Primary hover text — core meaning of the hexagram (1 clause, plain Vietnamese). */
  coreMeaning: string;
  /** Secondary label — market trend label in Vietnamese (e.g. "Thuận lợi (THUẬN LỢI)"). */
  marketTrendLabel: string;
}

export const QUE_DESCRIPTIONS: Record<number, QueDescription> = {
${entries.join(",\n")},
};
`;

writeFileSync(outPath, output, "utf-8");
console.log(
  `[gen-que-descriptions] Written ${entries.length} entries → ${outPath}`
);
