#!/usr/bin/env bash
# scripts/pm-emit-handoff-from-row.sh — emit docs/handoffs/<ID>.md from a live
# task_board row, in the docs/agents/pm/flow/main.md Step 3b template shape.
#
# WHY A SCRIPT: pm's Step 3b is `handoff_file_mandatory: true`, and a
# decomposition pass mints 10-20 children at a time. Hand-writing each one
# drifts the template and silently drops the mandatory `zone:` field that
# dev-team Step 3 routes on. Generating from the row itself makes the handoff
# and the board row structurally incapable of disagreeing.
#
# The row's own `note` is the design payload (architect brief pointers, AC,
# risk flags) — it is emitted verbatim under [PM] Planning Context, never
# paraphrased.
#
# NOTE ON `branch:`: flow Step 3b's template still mandates
# `branch: task/NNN-kebab-name`, which contradicts CLAUDE.md's project-wide
# NO-BRANCHES rule (all work stays on main). Emitting `branch: none` with the
# reason inline, same as every pm handoff since 2026-08-23. The flow-doc
# defect is agent-father-owned; tracked, not worked around silently.
#
# Usage:
#   bash scripts/pm-emit-handoff-from-row.sh <TASK_ID> [<TASK_ID> ...]
#   bash scripts/pm-emit-handoff-from-row.sh --stdin   # ids on stdin, one/line

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ORCH="$PROJECT_ROOT/docs/data/orch/orch-state.json"
OUT_DIR="$PROJECT_ROOT/docs/handoffs"

[ -f "$ORCH" ] || { echo "[pm-emit-handoff] FATAL: $ORCH not found" >&2; exit 1; }
mkdir -p "$OUT_DIR"

emit_one() {
  local id="$1"
  local row
  row="$(jq -c --arg id "$id" '
    [ .task_board | to_entries[] | (.value | if type=="array" then . else [] end)[]
      | select(type=="object" and .id? == $id) ] | .[0] // empty' "$ORCH")"

  if [ -z "$row" ]; then
    echo "[pm-emit-handoff] SKIP $id — not found in any task_board lane" >&2
    return 1
  fi

  local out="$OUT_DIR/$id.md"
  jq -r '
    def nz($v; $d): if ($v == null) or ($v == "") or ($v == []) then $d else $v end;
    def lst($v): if ($v|type) == "array" and (($v|length) > 0)
                 then ($v | map("  - `" + . + "`") | join("\n"))
                 else "  - none" end;
    "---\n"
    + "sprint: " + (nz(.sprint; .id) | tostring) + "\n"
    + "branch: none   # CLAUDE.md: NO branches — all work stays on main (flow Step 3b template is stale)\n"
    + "size: " + (nz(.size; "S") | tostring) + "\n"
    + "zone: " + (nz(.zone; "cross-service/") | tostring) + "\n"
    + "owner: " + (nz(.owner; "developer") | tostring) + "\n"
    + "next_agent: " + (nz(.next_agent; .owner) | tostring) + "\n"
    + "depends_on: " + ((.depends_on // []) | tostring) + "\n"
    + "blocks: []\n"
    + "---\n\n"
    + "# " + .id + " — " + (.title // "(untitled)") + "\n\n"
    + "## TLDR\n"
    + (.title // "(untitled)") + ". Zone `" + (nz(.zone; "cross-service/")|tostring)
    + "`, owner `" + (nz(.owner; "developer")|tostring) + "`, size "
    + (nz(.size; "S")|tostring) + ". "
    + (if ((.depends_on // []) | length) > 0
       then "BLOCKED until " + ((.depends_on) | join(" + ")) + " reach DONE_VERIFIED — `deps_satisfied()` enforces this mechanically at dispatch, do not start early."
       else "No dependencies — dispatchable now." end) + "\n\n"
    + "## [PM] Planning Context\n"
    + "- **Zone:** `" + (nz(.zone; "cross-service/")|tostring) + "`\n"
    + "- **Priority:** " + (nz(.priority; "P2")|tostring) + "\n"
    + "- **Dependencies:** " + (if ((.depends_on // []) | length) > 0
                                then ((.depends_on) | map("`"+.+"`") | join(", "))
                                else "none" end) + "\n"
    + "- **Files in scope:**\n" + lst(.files) + "\n"
    + "- **Acceptance criteria / design payload** (verbatim from the board row `note` — the architect brief it cites is the SSOT, this is the pointer):\n\n"
    + "  > " + ((nz(.note; "See the board row.") | tostring) | gsub("\n"; "\n  > ")) + "\n\n"
    + "- **Knowledge needed:** `docs/policies/dev-standards.md`, `docs/ARCHITECTURE.md`, "
    + "`docs/policies/commit-convention.md` (AC trailer), `.claude/skills/commit-boundary/SKILL.md`\n\n"
    + "## Definition of Done\n"
    + "- [ ] Every acceptance criterion above is satisfied AND demonstrated by a test or a live run — narration is a rejection.\n"
    + "- [ ] Commit carries the `AC:` trailer per `docs/policies/commit-convention.md`.\n"
    + "- [ ] Decision-journal entry written, stamped with task-id `" + .id + "` (DJ-GATE-1 blocks the DONE flip without it).\n"
    + "- [ ] Board row moved to `review[]` with `next_agent: qa`.\n\n"
    + "---\n"
    + "_Generated by `scripts/pm-emit-handoff-from-row.sh` from the live `" + .id
    + "` board row. Re-run after any row edit — do not hand-edit this file._\n"
  ' <<<"$row" > "$out"

  echo "[pm-emit-handoff] wrote $out"
}

ids=()
if [ "${1:-}" = "--stdin" ]; then
  while IFS= read -r line; do [ -n "$line" ] && ids+=("$line"); done
else
  ids=("$@")
fi
[ "${#ids[@]}" -gt 0 ] || { echo "[pm-emit-handoff] USAGE: $0 <TASK_ID>... | --stdin" >&2; exit 2; }

rc=0
for id in "${ids[@]}"; do emit_one "$id" || rc=1; done
exit "$rc"
