# po-triage-20260809T0248Z-cron-fire-gap-refute-and-mint.jq
# PO escalation disposition — "23/90 crons stopped firing 2026-08-07T08:50Z" (system-auditor A-29 CRITICAL, ops root-cause 02b456b4d)
# 1. MINT FIX-CRON-STATUS-LAYERA-SCHEDULE-BLIND-FALSE-CRITICAL (P2) — the real defect
# 2. REPRICE + RESCOPE FIX-MONTHLYSIGNALQUALITYAUDITJOB-MISSED-JULY-RECOVER-GUARD (P3 -> P2, 2nd consecutive miss verified live)
# Usage: jq -f scripts/po-triage-20260809T0248Z-cron-fire-gap-refute-and-mint.jq docs/data/orch/orch-state.json | bash scripts/orch-apply.sh

def NOW: "2026-08-09T02:48:45Z";

# ---- 1. MINT (idempotent) ----
.task_board.backlog |= (
  if (map(.id) | index("FIX-CRON-STATUS-LAYERA-SCHEDULE-BLIND-FALSE-CRITICAL")) then .
  else . + [{
    id: "FIX-CRON-STATUS-LAYERA-SCHEDULE-BLIND-FALSE-CRITICAL",
    title: "GET /api/cron-status Layer-A misreports 23 healthy crons as MISSED/STALE every weekend: classifyCronLiveness() ignores the expected_last_fire it already computes and ladders on raw age vs cadence; Layer-A also enumerates the CRONS config table instead of the registered scheduler table",
    type: "FIX",
    priority: "P2",
    status: "BACKLOG",
    zone: "apps/mcp-server/",
    size: "M",
    owner: "dev-mcp-server",
    next_agent: "dev-mcp-server",
    created_by: "po",
    created_at: NOW,
    updated_at: NOW,
    supervised: false,
    depends_on: null,
    blocks: null,
    root_cause: "apps/mcp-server/src/domain/cron/cronLivenessClassifier.ts classifyCronLiveness(nowMs, lastFireMs, cadenceMs, thresholdMultiplier) is a pure age ladder (ON_TIME<=cadence, LATE<=cadence*mult, MISSED<=cadence*3, else STALE) — FR-1.6 verbatim. cronStatusCompute.ts computes expected_last_fire / expected_next_fire per row via cron-parser and ships them in the payload, but NEVER feeds them to the classifier (line ~339 passes only cadenceMs+thresholdMultiplier). For any job whose cron restricts day-of-week or hour-of-day, real inter-fire gap != cadenceMs: '*/10 2-8 * * 1-5' has cadenceMs=10min but a Fri-08:50 -> Mon-02:00 gap of 65h, so every such job is GUARANTEED to classify STALE/MISSED every single weekend. Four further defects compound it: (b) expected_last_fire/expected_next_fire are computed in UTC ignoring each job's options.timezone, so all Asia/Ho_Chi_Minh jobs are skewed exactly 7h (morningBriefing/alertDigest/eveningSummary all show delta -25198..-25199s); (c) cron-parser applies POSIX dom/dow OR semantics while node-cron@3.0.3 TimeMatcher.match() ANDs all six fields, so brokerSanctionsSweep '0 8 25-31 * 5' gets expected_last_fire=2026-08-07 (a Friday not in 25-31) instead of its real 2026-07-31 fire; (d) Layer-A enumerates cronConfig.ts CRONS keys and name-joins <key>Job, so config keys with no registration are reported dead forever (taAlertScan/bbAlertScan last_fire 2026-04-24 — they were merged into the registered alertScanParallelJob at schedulerJobTable.ts:447-458, which itself never appears in Layer-A because it has no CRONS key of its own), and env-gated-off registrations are reported dead (ragFtsRebuildCron, CRON_RAG_FTS_REBUILD_ENABLED default-false, schedulerJobTable.ts:132-140,673-681, deliberate per ALPHA-S2-RAG-FTS-CRON-SAFETY-GATE).",
    evidence: "LIVE-VERIFIED 2026-08-09T02:45Z against http://localhost:3000/api/cron-status (layer_a_count=90; 57 ON_TIME, 12 MISSED, 8 STALE, 4 LATE, 9 NEVER_FIRED). Per-row delta (last_fire minus the endpoint's OWN expected_last_fire) for all 24 non-ON_TIME/non-NEVER_FIRED rows: 15 rows delta in [0s,+2s] — i.e. the job fired EXACTLY on its own computed schedule and was still labelled MISSED or STALE (vpsProxyWatchdog 0s STALE, foreignFlowAlert 0s MISSED, franceSummary +2s MISSED, taAlertNotifier +1s STALE, signalOutcomeJob +1s MISSED, ohlcvDailyAggregator 0s LATE, ohlcvStalenessCheck 0s MISSED, priceUpdateWatchdog +1s STALE, vnIndexRefresh +1s STALE, marketEarningYield +1s MISSED, alertOutcomeJob +1s MISSED, vnstockTradingStatsRefresh +1s MISSED, breadthHistoryPersister 0s MISSED, ohlcvSanityCheck 0s LATE, ohlcvSanityCheckEarly +2s MISSED); 3 rows delta exactly -7h = timezone skew, fired on time in Asia/Ho_Chi_Minh (morningBriefing, alertDigest, eveningSummary); 1 row dom/dow-semantics skew (brokerSanctionsSweep, real last fire 2026-07-31 08:00:01, real next fire 2026-08-28 not the reported 2026-08-14); 2 rows merged-job name-join (taAlertScan/bbAlertScan); 1 row deliberate env-gate (ragFtsRebuildCron); 1 benign sub-cadence jitter (intelligenceCycle -898s LATE); leaving exactly ONE genuine gap in the whole set (monthlySignalQualityAudit, already tracked by FIX-MONTHLYSIGNALQUALITYAUDITJOB-MISSED-JULY-RECOVER-GUARD).",
    refuted_premise: "This row REPLACES, not corroborates, the escalated container-crash narrative. system-auditor Tier-2 reported 23/90 crons 'stopped firing simultaneously at 2026-08-07T08:50:00Z, 41.6h overdue'; ops (docs/agent-memory/notebooks/ops.md, commit 02b456b4d) concluded HIGH CONFIDENCE that the mcp-server container died at that exact instant and that node-cron cannot replay across a restart. The node-cron claim is TRUE at source (node-cron@3.0.3 src/scheduler.js re-seeds lastExecution=timeMatcher.apply(new Date()) inside start(), so recovery only ever walks back the in-process event-loop stall since the last 1s tick — never anything before process start), but it is IRRELEVANT here because no crash occurred. Refutation from the same cron_job_runs data ops read: marketEarningYield fired 2026-08-07 09:30:01 (40 min AFTER the alleged death), alertDigest 14:00:01, ohlcvDailyAggregator 15:03:00, ohlcvSanityCheck 15:05:00, eveningSummary 15:30:01 — the process was alive and firing all Friday. 08:50 is simply the last slot of the '*/10 2-8 * * 1-5' market-hours window on a Friday; ops's own notebook states 'next scheduled fires would have been 09:00+ UTC (outside market-hours window for these jobs), so wouldn't fire anyway' and 'weekday-only jobs correctly did NOT fire on Sat/Sun', which already contradicts the crash conclusion in the same paragraph. Docker corroborates: the running container has RestartCount=0, FinishedAt=0001-01-01 (never exited), StartedAt=2026-08-08T19:06:16Z — a deliberate ops rebuild/recreate for the separate scheduler double-registration fix, not a crash-restart.",
    acceptance_criteria: "AC-1: classification is schedule-derived — a job whose last_fire >= its own expected_last_fire (minus a documented grace, e.g. 120s) classifies ON_TIME regardless of wall-clock age; the age ladder survives ONLY as the fallback when the cron expression is unparseable, and that fallback must be labelled as such in .reason. AC-2: expected_last_fire/expected_next_fire honour each job's registered options.timezone — regression asserts morningBriefing/alertDigest/eveningSummary expected fires land at 01:00/14:00/15:30 UTC, not 08:00/21:00/22:30 UTC. AC-3: dom/dow matching mirrors node-cron TimeMatcher AND-semantics, not cron-parser POSIX OR — regression asserts brokerSanctionsSweep next fire = 2026-08-28. AC-4: Layer-A is enumerated from the REGISTERED job table (buildJobTable + registerBespokeJobs), not from CRONS keys — alertScanParallelJob appears, taAlertScan/bbAlertScan do not appear as separate dead rows, and env-gated-off registrations (ragFtsRebuildCron) report a distinct DISARMED status, never STALE. AC-5: replay the 2026-08-09T02:45Z snapshot through the fixed classifier — exactly one row (monthlySignalQualityAudit) may remain non-ON_TIME; any of the other 23 still flagged is a fail. AC-6: a weekend-clock regression test pins now=Sunday and asserts zero MISSED/STALE among the weekday-windowed jobs.",
    consumer_impact: "system-auditor A-29 (docs/agents/system-auditor/flow/main.md:342) consumes this endpoint's .status and .reason VERBATIM and emits CRITICAL/WARN signals from them — so this defect manufactures a recurring weekend CRITICAL storm (~23 rows) that then costs a full ops investigation cycle and buries the one real gap in the noise (same shape as feedback_composite_score_masks_dead_detector_pruned_table). No auditor-side change is needed once the endpoint is correct; do NOT patch A-29 to compensate.",
    not_blocking: "P2 not P1 — pure observability/detector defect, zero production data loss: every job it maligns is in fact firing on schedule. Severity is the false-alarm cost and the masking of real gaps.",
    origin: "PO escalation triage 2026-08-09 (router session 165f4245), from system-auditor Tier-2 A-29 CRITICAL + ops investigation commit 02b456b4d"
  }] end)

# ---- 2. REPRICE + RESCOPE the one genuine gap ----
| .task_board.backlog |= map(
    if .id == "FIX-MONTHLYSIGNALQUALITYAUDITJOB-MISSED-JULY-RECOVER-GUARD" then
      .priority = "P2"
      | .updated_at = NOW
      | .title = "monthlySignalQualityAuditJob (cron 0 0 1 * *) has now missed TWO consecutive fires — 2026-07-01 and 2026-08-01 — with zero recovery and zero alert; recoverMissedExecutions:false (schedulerJobTable.ts:229) is the opt-out, but flipping it alone is a PROVEN no-op"
      | .escalation_20260809 = "SECOND CONSECUTIVE MISS VERIFIED LIVE 2026-08-09T02:45Z via GET /api/cron-status: monthlySignalQualityAudit cron_expr='0 0 1 * *', expected_last_fire=2026-08-01T00:00:00Z, last_fire=2026-06-01 00:00:00, status=MISSED — delta -5,270,400s (61 days). The row previously recorded only the 2026-07-01 miss; August is now also gone. This is the ONLY genuine cron gap among the 24 non-healthy rows in that snapshot (the other 23 are detector false positives — see FIX-CRON-STATUS-LAYERA-SCHEDULE-BLIND-FALSE-CRITICAL). Repriced P3 -> P2 on recurrence, not on blast radius: a monthly audit that silently skips two months running is no longer a one-off completeness gap."
      | .mechanism_correction = "The row's recommended_action (add a T4 dedup guard, then flip recoverMissedExecutions:false -> true) is NECESSARY BUT NOT SUFFICIENT and must not be shipped alone. Confirmed at source in node-cron@3.0.3 src/scheduler.js: Scheduler.start() sets lastExecution = timeMatcher.apply(new Date()) and lastCheck = process.hrtime() at start time, and the recovery loop only walks back Math.floor(elapsedMs/1000) seconds since the previous in-process 1s tick. Therefore recoverMissedExecutions:true recovers ONLY event-loop stalls inside a living process — it can NEVER replay a fire that fell during a process restart or downtime window. Any restart spanning 1st-of-month 00:00 UTC still loses the audit with the flag set to true. Real fix must be a startup catch-up: apps/mcp-server/src/scheduler/startupHelpers.ts already ships shouldRunCatchup() (task 1430) with a DB-backed 'already ran today' guard, weekdayOnly / requiredUtcDay / utcHour window gating, and fail-safe-on-DB-error semantics. Scope this row as: generalise that helper's dedup window from per-day to per-cadence-period (per-month for this job), enrol monthlySignalQualityAuditJob in it, THEN flip the flag as defence-in-depth."
      | .stale_action_note = "recommended_action's June-backfill escape hatch has EXPIRED — it was conditioned on pickup before 2026-08-01. Both the July and August target months are now unrecoverable through natural cadence; if the two reports are wanted they need an explicit one-shot historical query over signal_rejections, which should be an AC on this row rather than an implicit assumption."
      | .escalation_source = "PO escalation triage 2026-08-09 (router session 165f4245). Note for whoever picks this up: the 'Aug-7 23-cron simultaneous stop' incident that escalated this row is NOT corroborating evidence for it — that incident was refuted (no container crash; 23/23 of those jobs fired exactly on their own schedules). Do not widen this row's scope on the strength of it."
    else . end)
