# po-triage-20260825T1345Z-mint.jq — PO triage batch mint, 2026-08-25T13:45Z cycle.
#
# Owning flow doc: docs/agents/po/flow/triage-signals.md (mint discipline) +
#                  docs/agents/po/flow/main.md § Reusable triage scripts
# Registry pointer: docs/agents/po/flow/scripts-registry.md
#
# Usage (NEVER raw mv/cp/> — CLAUDE.md § Orch-State Hot File Write Contract):
#   jq -f scripts/po-triage-20260825T1345Z-mint.jq docs/data/orch/orch-state.json \
#     | bash scripts/orch-apply.sh
#
# Idempotent: every append is guarded on the row id not already existing in backlog[].
# status MUST be "BACKLOG" (LANE_ALLOWED_STATUSES.backlog = {BACKLOG, BLOCKED}).

def add_row($row):
  if ([.task_board.backlog[] | select(.id == $row.id)] | length) > 0
  then .
  else .task_board.backlog += [$row]
  end;

("2026-08-25T13:45:50Z") as $now
| ("po/triage-20260825T1345Z") as $by

# ── 1. THE row that actually captures the user's BCTC-quality goal ────────────
| add_row({
    id: "FIX-PDFX-TESSERACT-CONFIDENCE-MEAN-OVER-NONEMPTY-MASKS-TOTAL-PAGE-MISS",
    type: "FIX", size: "S", priority: "P1", status: "BACKLOG",
    zone: "apps/pdf-extractor/", owner: "po", next_agent: "dev-pdf-extractor",
    created_at: $now, created_by: $by, updated_at: $now, updated_by: "po",
    dedup_key: "pdfx-ocr:tesseract-confidence-mean-over-nonempty-rows",
    files: ["apps/pdf-extractor/infrastructure/ocr_backends.py"],
    title: "TesseractVieBackend reports confidence as mean(conf) over ONLY the rows it managed to recognise, so a page it almost entirely MISSED self-reports high confidence — this is why AutoFallbackOcrBackend's 0.5 threshold never fires and `auto` mode is byte-identical to tesseract-vie on 30/30 units",
    root_cause: "apps/pdf-extractor/infrastructure/ocr_backends.py, TesseractVieBackend.recognize_text(): `valid_rows = data[(data['conf'] > 0) & (data['text'].str.strip() != '')]` then `mean_conf = float(valid_rows['conf'].mean()) / 100.0`. The denominator is the SUCCESSFULLY-RECOGNISED rows, not the rows that should have been recognised. A page where tesseract picks up three header words at conf 92 and loses all forty data rows therefore returns 0.92 — indistinguishable from a clean full-page read. Recall is invisible to the score by construction; only precision-on-what-was-found is measured. PO re-derived this at source 2026-08-25, independent of the reporting specialist.",
    evidence: "Measured by dev-pdf-extractor on FPT Q4 2025 (report_id e71f845d-ffa5-48f9-8f09-30ac2cd09c65, 46 pages), 4 real sentinel extractions in ephemeral `docker compose run --rm` containers, zero code changes, every result verified by direct readonly bun:sqlite row counts against market.db (NOT push-handler echo). OCR_TEXT_BACKEND=auto produced output BYTE-IDENTICAL to tesseract-vie on all 30/30 table units INCLUDING page 9 — the rescue never fired even once. Page 9 (quarterly income statement) is the proof case: tesseract extracted headers plus a stray '178%' and lost 100% of the revenue/profit figures, while PaddleOCR on the same page returned the full row correctly. So a genuine catastrophic per-page miss exists, a working rescue backend exists, and the confidence signal is the ONLY thing standing between them.",
    ac: "(AC-1) Confidence must fall on a near-total page miss. Build a discriminator that accounts for what was NOT recognised — candidates to evaluate and choose between explicitly: recognised-area / table-region-area coverage ratio; recognised row count vs the row count the layout detector found in the same region; mean(conf) weighted by character count with a floor for empty regions. Do not simply lower the 0.5 threshold — that trades one arbitrary constant for another and is an automatic rejection. (AC-2) POSITIVE CONTROL, mandatory and non-substitutable: re-run FPT Q4 2025 page 9 under OCR_TEXT_BACKEND=auto and show the rescue FIRES and the revenue/profit figures land. A unit test on synthetic input does not satisfy this. (AC-3) NEGATIVE CONTROL: re-run the other 29 units under auto and show the rescue does NOT fire on any of them — a discriminator that rescues everything reintroduces PaddleOCR's diacritic regression fleet-wide (see PO ruling in docs/agent-memory/decisions/triage-20260825T1345Z-po.md) and is a rejection. (AC-4) Report the auto-mode wall-clock and peak ru_maxrss for the corrected run; the table phase must stay under the 2.5 GiB per-container cap with the same headroom tesseract-vie has today (peak 1543 MiB, ~60%).",
    status_note: "PO RULING 2026-08-25: this row — not a backend swap — is the correct response to the standing 'improve BCTC extraction quality' goal. PaddleOCR adoption was measured and REJECTED (it strips Vietnamese diacritics on nearly every word, runs 1.8x slower, and peaks at 2790 MiB against a 2560 MiB cap). PaddleOCR's single genuine win was page 9, and `auto` already has the mechanism to capture exactly that win without paying the diacritic regression — it is only the confidence signal that is broken. Full ruling + method + what would reopen the backend question: docs/agent-memory/decisions/triage-20260825T1345Z-po.md.",
    dedup_checked: "2026-08-25T13:40Z via scripts/po-board-dedup-search.sh over NON-TERMINAL lanes and --all-lanes for /TesseractVie|AutoFallback|confidence.*heuristic|mean.*conf/ and /paddle|PaddleOCR|tesseract|OCR/ and /PEK-IMPL-OCR|ocr.?backend|OCR_BACKEND/. No row on any lane covers the confidence heuristic or the backend-selection question. Nearest neighbours read and rejected: PERF-PEK-PER-PAGE-LATENCY (throughput, not quality), FIX-BCTC-REFINE-DIACRITIC-COLLAPSE-A-BREVE-ACUTE (refine-stage diacritic collapse downstream of OCR), FIX-PDFX-GENERIC-MD-TABLE-OCR-UNROUTED-GATEWAY (a different extractor's pytesseract call sites).",
    related: ["FIX-PDFX-PEK-TABLE-REGION-COLLAPSED-TO-ONE-CELL-DISCARDS-PER-LINE-BBOXES", "FIX-BCTC-REFINE-DIACRITIC-COLLAPSE-A-BREVE-ACUTE"],
    baseline_pass: null
  })

# ── 2. Structural table-flattening regression, ALL backends, since PEK-IMPL-OCR ─
| add_row({
    id: "FIX-PDFX-PEK-TABLE-REGION-COLLAPSED-TO-ONE-CELL-DISCARDS-PER-LINE-BBOXES",
    type: "FIX", size: "M", priority: "P1", status: "BACKLOG",
    zone: "apps/pdf-extractor/", owner: "po", next_agent: "architect",
    created_at: $now, created_by: $by, updated_at: $now, updated_by: "po",
    dedup_key: "pdfx-pek:table-region-single-cell-discards-per-line-bboxes",
    files: ["apps/pdf-extractor/infrastructure/pek_engine_adapter.py", "apps/pdf-extractor/infrastructure/ocr_backends.py"],
    title: "Since PEK-IMPL-OCR the pluggable OCR path wraps an ENTIRE table region into ONE cell dict carrying the whole-region bbox, so per-line bboxes are discarded and table row/column structure is flattened for EVERY backend, tesseract included — the legacy paddle_table path it replaced did preserve them",
    root_cause: "apps/pdf-extractor/infrastructure/pek_engine_adapter.py, _run_table_extraction (~lines 1146-1165). When `self._ocr_backend is not None` — which is the live configuration for every backend value of OCR_TEXT_BACKEND — the code calls `self._ocr_backend.recognize_text(crop)` on the whole cropped table region and appends exactly ONE cell: `{bbox: [x0, y0, x1, y1], text: cell_text, score: cell_score}`. That bbox is the REGION bbox, not a line bbox, and cell_text is every recognised line joined into a single string. The `else` branch — the backward-compatible path taken only when no backend is injected — calls `paddle_table.ocr(crop, cls=False)` and iterates the per-line results, which is where the structure used to come from. So the pluggable-backend refactor silently traded table structure for backend pluggability, and _assemble_unit_markdown / _cells_to_row_bands downstream receive one band per region regardless of how many rows the table actually has. PO re-derived this at source 2026-08-25.",
    evidence: "Read directly from apps/pdf-extractor/infrastructure/pek_engine_adapter.py at the cited lines: the `if self._ocr_backend is not None` branch appends a single dict whose bbox is the same [x0, y0, x1, y1] used to make the crop. Corroborated behaviourally by dev-pdf-extractor's 2026-08-25 sentinel run: OCR_TEXT_BACKEND=auto and OCR_TEXT_BACKEND=tesseract-vie produced BYTE-IDENTICAL output on 30/30 table units, which is only possible if the downstream assembly is insensitive to per-line geometry. This is a strictly larger quality lever for BCTC than the backend choice was, and it is why a backend swap could never have delivered the goal on its own.",
    ac: "(AC-1) Decide and record the contract before touching code: does OcrBackendPort return (text, confidence) or a list of (bbox, text, confidence) lines? The current port signature is the actual root cause — it cannot express what the caller needs — so a fix that keeps the signature and reconstructs geometry downstream must be argued for explicitly, not defaulted into. (AC-2) All three backends (TesseractVieBackend, PaddleOcrBackend, AutoFallbackOcrBackend) must satisfy the chosen contract; a fix that only restores structure for paddle re-creates the exact asymmetry this row is about. (AC-3) POSITIVE CONTROL on real data, not fixtures: extract a known multi-row BCTC table (FPT Q4 2025, report_id e71f845d-ffa5-48f9-8f09-30ac2cd09c65) and show the produced markdown has one row per source row, verified by direct readonly bun:sqlite query against market.db, never by a push-handler echo. (AC-4) Regression fence: assert the legacy `else` branch and the pluggable branch now produce the same row COUNT on the same region — the two paths silently diverging is the defect class itself.",
    status_note: "Routed to architect, not developer: AC-1 is a port-contract decision across three adapters plus two downstream assemblers, not a local edit. Found during the PaddleOCR adoption measurement 2026-08-25; it is pre-existing and independent of that decision — it affects tesseract-vie, which is and remains the live backend.",
    dedup_checked: "2026-08-25T13:40Z via scripts/po-board-dedup-search.sh for /_run_table_extraction|pek_engine_adapter|combined.?text|per-line bbox/ -> NO MATCH on non-terminal lanes, and /PEK-IMPL-OCR|ocr.?backend|OCR_BACKEND|backend swap|ocr engine/ --all-lanes -> NO MATCH on any lane.",
    related: ["FIX-PDFX-TESSERACT-CONFIDENCE-MEAN-OVER-NONEMPTY-MASKS-TOTAL-PAGE-MISS", "SPIKE-BCTC-COLUMN-SEPARATED-LAYOUT", "FIX-BCTC-FPT-PAGE8-EPS-BLEED-ROWCOUNT"],
    baseline_pass: null
  })

# ── 3. Market-hours guard covers 1 of 5 OCR-driving routes ────────────────────
| add_row({
    id: "FIX-PDFX-MARKET-HOURS-GUARD-ONLY-ON-PEK-EXTRACT-FOUR-OCR-ROUTES-UNGUARDED",
    type: "FIX", size: "S", priority: "P2", status: "BACKLOG",
    zone: "apps/pdf-extractor/", owner: "po", next_agent: "dev-pdf-extractor",
    created_at: $now, created_by: $by, updated_at: $now, updated_by: "po",
    dedup_key: "pdfx-market-hours-guard:only-pek-extract-route-guarded",
    files: ["apps/pdf-extractor/interface/routes_pek.py", "apps/pdf-extractor/interface/routes_extract.py", "apps/pdf-extractor/interface/routes_extract_tables.py", "apps/pdf-extractor/interface/routes_md_tables.py", "apps/pdf-extractor/interface/routes_layout_first.py"],
    title: "The VN market-hours 503 guard is wired into exactly ONE of the five OCR-driving routes — /extract, /extract-tables, /extract-md-tables and /extract-layout-first can all start a multi-GiB OCR burst during market hours on a container that already runs at 88-98% of its 2.5 GiB cap",
    root_cause: "is_vn_market_open_utc() is imported and called at apps/pdf-extractor/interface/routes_pek.py:17 and :64 and NOWHERE else in apps/pdf-extractor outside __tests__/ and scenarios/. PO enumerated every registered route: routes_pek.py:29 /pek-extract (GUARDED), routes_extract.py:36 /extract, routes_extract_tables.py:22 /extract-tables, routes_md_tables.py:55 /extract-md-tables, routes_layout_first.py:56 /extract-layout-first (all UNGUARDED), plus /page-text, /rasterize, /health which do not drive OCR. The guard was added for REQ-PEK-11 / AC-PEK-NEW-1 against the pek route only and was never swept across the sibling routes that reach the same engine.",
    evidence: "grep -rn 'is_vn_market_open_utc' apps/pdf-extractor -> 1 production call site (routes_pek.py:64). Route enumeration by grep over @router.post/@router.get across apps/pdf-extractor/interface/ -> 8 routes, 5 OCR-driving, 1 guarded. Pre-existing, not introduced by any 2026-08-25 change. Impact is real and already-measured on this container: FIX-PDFX-PARENT-PROCESS-MEMORY-BURST-HEADROOM (review[]) and FIX-AUDITOR-EMIT-SEVERITY-LABEL-FLAT-ESCALATION-BYPASS-NEVER-FIRES both record pdf-extractor at 88-98.87% of its 2.5 GiB cap under ordinary traffic.",
    ac: "(AC-1) Every OCR-driving route honours the same market-hours policy as /pek-extract, applied through ONE shared dependency/middleware — five copies of the same `if` is a rejection, it is the exact copy-paste-drift shape that produced this gap. (AC-2) The three non-OCR routes (/page-text, /rasterize, /health) must stay UNGUARDED and a test must assert that — guarding /health would break the container healthcheck and cause restart churn. (AC-3) Test coverage mirrors apps/pdf-extractor/__tests__/test_market_hours_guard.py for each newly-guarded route: 503 inside market hours, 202/200 outside, with is_vn_market_open_utc patched at its definition module (see routes_pek.py:8-9 on why the patch target must not be indirected). (AC-4) Enumerate the callers of the four routes before changing them and name any that would newly receive a 503 during market hours; a caller that breaks is a scoping question for PO, not a silent regression.",
    status_note: "Found while measuring the OCR backend question 2026-08-25; unrelated to that decision. P2 rather than P1: it is a latent capacity risk with no recorded incident yet, but the container's measured headroom makes it a plausible OOM trigger.",
    dedup_checked: "2026-08-25T13:40Z via scripts/po-board-dedup-search.sh for /is_vn_market_open_utc|routes_pek|market-hours guard/ -> NO MATCH on non-terminal board rows.",
    related: ["FIX-PDFX-PARENT-PROCESS-MEMORY-BURST-HEADROOM", "FIX-PDFX-PRECURSOR-TELEMETRY-98PCT-VMHWM-PINNED-15MIN-BEFORE-THE-OOM-KILL"],
    baseline_pass: null
  })

# ── 4. task_release Rung B is inert — PROBED, with control ────────────────────
| add_row({
    id: "FIX-TASKRELEASE-ORIGINAL-OWNER-CLIENT-SESSION-INERT-RUNGB-NEVER-RELEASES",
    type: "FIX", size: "S", priority: "P0", status: "BACKLOG",
    zone: "cross-service/", owner: "po", next_agent: "architect",
    created_at: $now, created_by: $by, updated_at: $now, updated_by: "po",
    dedup_key: "tasklock:task-release-original-owner-client-session-param-inert",
    files: ["docs/agents/dev-team/flow/orphan-adoption.md", "apps/mcp-server/src/interface/mcp/tools/"],
    title: "task_release's original_owner_client_session parameter grants NO release authority — PO probed it live with a positive control: the FR-2 Rung B call shape returns released:0 and leaves the lock held, while releasing under the dead session's own id returns released:1. All 3 orphan-signal release call sites are therefore permanently no-ops, and FIX-ORPHAN-FR4-FR5 subtask 4 is unsatisfiable as written",
    root_cause: "task_release authorises solely on owner_client_session matching the lock's own owner_client_session. original_owner_client_session is accepted by the schema and then ignored. The FR-2 Rung B design assumed the server would treat it as a delegated-release credential; it does not. The doc-side half of subtask 4 DID land — docs/agents/dev-team/flow/orphan-adoption.md :61-66, :128-136 and :169-174 all now pass owner_agent + original_owner_client_session — so the row looks complete on inspection while remaining functionally dead, which is why 15 days of review never caught it.",
    evidence: "PO live probe 2026-08-25T13:52Z via mcp__gateway__call_tool(server='vn-market'), full sequence: (1) task_claim(task_id='orphan-signal:PO-SYNTHETIC-FR2-RUNGB-PROBE-20260825', task_kind='orphan-signal', owner_agent='dev-team', owner_client_session='dead-session-00000000-0000-0000-0000-000000000000') -> {claimed:true}. (2) TEST — the exact orphan-adoption.md:61-66 shape: task_release(task_id=<same>, owner_client_session='036ceaf1-...' (the CALLER), owner_agent='dev-team', original_owner_client_session='dead-session-...') -> {ok:true, released:0}. (3) task_list_held(kind='orphan-signal') -> count:1, lock STILL HELD — released:0 is a genuine non-release, not an already-gone no-op. (4) POSITIVE CONTROL — same lock, owner_client_session='dead-session-...' (the lock's own owner): -> {ok:true, released:1}. (5) task_list_held(kind='orphan-signal') -> count:0, clean, no probe residue. The control proves release itself works and isolates the fault to Rung B specifically. This FALSIFIES the standing note feedback_orphan_signal_unreleasable_null_client_session_and_activesprints_only_flip, which recorded that orphan-signals ARE releasable by passing owner_agent + original_owner_client_session.",
    ac: "(AC-1) Choose ONE and record why in a brief before editing: (a) CALLER-SIDE — change the 3 call sites in docs/agents/dev-team/flow/orphan-adoption.md to pass `owner_client_session: dead_session` (the value is already in scope at all 3 sites, it is currently being passed as original_owner_client_session), which the control above proves works today with zero server change; or (b) SERVER-SIDE — implement original_owner_client_session as a real delegated-release credential. (b) is the larger blast radius: it makes any caller able to release any lock by naming its owner, so it needs an argued authorisation story, not just an OR in the WHERE clause. (AC-2) Replay the exact 5-step probe above and show step (2) now returns released:1 with the lock gone at step (3). A unit test does not satisfy this — the defect is server behaviour reached through the gateway. (AC-3) If (a) is chosen, task_release's original_owner_client_session parameter must be removed from the tool schema or documented as inert in docs/standards/mcp-tools.md — leaving an accepted-and-ignored parameter in place is what manufactured this false-green. (AC-4) FIX-ORPHAN-FR4-FR5-FLOW-DEVTEAM-ADOPTION-GUARD subtask 4's acceptance must be restated as a SYNTHETIC-fixture probe (claim a throwaway orphan-signal under a dead session, then release it) — its current wording requires 'a real NULL-owner orphan-signal row', and PO measured task_list_held(kind='orphan-signal') = 0 live rows, so as written it can only be satisfied opportunistically after a genuine mid-task agent death. That is a structural stall on a P0, not an acceptance criterion.",
    status_note: "P0 because it blocks FIX-ORPHAN-FR4-FR5-FLOW-DEVTEAM-ADOPTION-GUARD (P0, review[], QA CHANGES_REQUESTED) and because a permanently-no-op orphan release means every adopted orphan-signal leaks its lock until TTL expiry. Routed to architect for the AC-1 caller-vs-server decision, which must be made before any file is touched.",
    dedup_checked: "2026-08-25T13:50Z via scripts/po-board-dedup-search.sh for /ORPHAN-FR4|FR-4|FR-5|orphan.*signal.*released/ and /dispatch-claim|FR-3|CARD\\.md/ -> the only related open row is FIX-ORPHAN-FR4-FR5-FLOW-DEVTEAM-ADOPTION-GUARD (review[26]), which is the CONSUMER of this fix, not a duplicate of it: that row owns the flow-doc changes, this row owns the release-authorisation mechanism its subtask 4 depends on.",
    related: ["FIX-ORPHAN-FR4-FR5-FLOW-DEVTEAM-ADOPTION-GUARD", "FIX-DISPATCHCLAIM-CARD-PAYLOAD-OBJECT-REJECTED-AND-PHASEA-OMITS-OWNER-AGENT"],
    baseline_pass: null
  })

# ── 5. dispatch-claim doc corrections (CARD.md + SKILL.md FR-3 retrofit) ──────
| add_row({
    id: "FIX-DISPATCHCLAIM-CARD-PAYLOAD-OBJECT-REJECTED-AND-PHASEA-OMITS-OWNER-AGENT",
    type: "FIX", size: "S", priority: "P1", status: "BACKLOG",
    zone: "cross-service/", owner: "po", next_agent: "agent-father",
    created_at: $now, created_by: $by, updated_at: $now, updated_by: "po",
    dedup_key: "dispatch-claim-card:payload-object-and-missing-owner-agent",
    files: [".claude/skills/dispatch-claim/CARD.md", ".claude/skills/dispatch-claim/SKILL.md"],
    title: "dispatch-claim/CARD.md — the router's hot-path card, executed before EVERY spawn — shows task_claim payload as a JSON OBJECT at both Phase A and Phase B, but the live tool requires a serialized STRING; Phase A additionally omits owner_agent, which the schema marks required. Both make the card's copy-executable snippets fail as written",
    root_cause: ".claude/skills/dispatch-claim/CARD.md:17 (Phase A) and :29 (Phase B) both write `payload={...}`. The live vn-market task_claim schema declares payload as a string. CARD.md:16-17 also calls task_claim with task_id/task_kind/owner_client_session/ttl/payload and NO owner_agent, which the schema marks required (Phase B at :28 does pass it). docs/agents/dev-team/flow/drain-signals.md already documents the string form correctly — CARD.md is the stale copy, and it is the one the router actually reads on the hot path.",
    evidence: "PO probed the live schema 2026-08-25T13:47Z via mcp__gateway__call_tool(server='vn-market', tool='task_claim') with payload passed as an object. The server returned a Zod validation error naming three problems at once: path ['payload'] {expected:'string', received:'object'}, path ['owner_agent'] {expected:'string', received:'undefined', message:'Required'}, and the task_kind enum (which is exactly ['cowork-slot','sprint-task','dashboard-row','commit-mutex','intent','orphan-signal','session-presence'] — CARD.md does not enumerate it). Not relayed: PO made the call and read the error. CORRECTION RECORDED FOR THE IMPLEMENTER, do not 'fix' this too: CARD.md:11's `task_list_held(kind=...)` is CORRECT — PO separately verified that task_list_held filters on `kind` (kind='cowork-slot' -> 4 locks) and silently IGNORES `task_kind` (task_kind='zzz-nonexistent' -> all 13 locks, identical to unfiltered). The input parameter is `kind` while the response field is `task_kind`; that asymmetry is a real ergonomics trap but the card is on the right side of it.",
    ac: "(AC-1) Both payload sites become serialized JSON strings, and Phase A gains owner_agent. (AC-2) The corrected snippets are EXECUTED once each against the live gateway and the result pasted into the commit message — this card is copy-executable by construction, so inspection is not acceptance. (AC-3) Sweep, do not point-fix: grep every skill/flow doc for `payload={` or `payload = {` on a task_claim/task_heartbeat line and fix the whole set; report the count. (AC-4) Same row also carries the dispatch-claim/SKILL.md FR-3 retrofit that FIX-ORPHAN-FR4-FR5-FLOW-DEVTEAM-ADOPTION-GUARD's record claims exists as a 'separate row' — PO grep-verified 2026-08-25 that no such row existed anywhere on board or archive. This row is now that row; the FR-3 retrofit is in scope here and the reference in that record resolves to this id.",
    status_note: "P1 despite being a doc change: CARD.md is on the router's pre-spawn hot path (CLAUDE.md § BEFORE spawning any agent, step 2.5) and a router that follows it literally gets a hard validation error instead of a claim. Routed to agent-father per the 2026-07-21 PO artifact-class routing ruling — .claude/skills/** is instruction-prose an agent loads and executes.",
    dedup_checked: "2026-08-25T13:50Z via scripts/po-board-dedup-search.sh for /dispatch-claim|FR-3|CARD\\.md/ -> 6 hits, all read and rejected: UC-RDL-P4B-DOC-CUTOVER (FR-7 dispatch_preflight cutover, a different retrofit), STYLE-SKILL-FRONTMATTER-ALIGN (YAML frontmatter), FIX-PO-MANUAL-DISPATCH-SKIP-STAMP-FIELD-MISMATCH, FIX-CHEF-INTRADAY-MARKER-KEY-UTC-HOUR-BASIS-MIGRATION, FIX-REENTRANT-BRANCH-SHARED-SESSION-UUID-DOUBLE-DISPATCH, FIX-ORCH-SENTINEL-OH4. None is about the payload type or a missing owner_agent.",
    related: ["FIX-ORPHAN-FR4-FR5-FLOW-DEVTEAM-ADOPTION-GUARD", "UC-RDL-P4B-DOC-CUTOVER", "FIX-TASKRELEASE-ORIGINAL-OWNER-CLIENT-SESSION-INERT-RUNGB-NEVER-RELEASES"],
    baseline_pass: null
  })

# ── 6. A-30 debounce keyed on container NAME ──────────────────────────────────
| add_row({
    id: "FIX-AUDITOR-A30-DEBOUNCE-KEYED-ON-CONTAINER-NAME-EPHEMERAL-UNBOUNDED-CARDINALITY",
    type: "FIX", size: "S", priority: "P1", status: "BACKLOG",
    zone: "apps/mcp-server/", owner: "po", next_agent: "developer",
    created_at: $now, created_by: $by, updated_at: $now, updated_by: "po",
    dedup_key: "auditor:a30-mem-creep|defect:no-ephemeral-container-discriminator",
    files: ["docs/agents/system-auditor/probe.sh", "docs/data/auditor-tier1-spawn-debounce.json"],
    title: "A-30 mem_creep has no ephemeral-container discriminator and its spawn debounce is keyed on container NAME, so every `docker compose run --rm` container is a brand-new key and therefore a guaranteed first-sighting SPAWN — 3 distinct throwaway names paged the auditor in 13 minutes",
    root_cause: "The tier-1 spawn debounce ledger (docs/data/auditor-tier1-spawn-debounce.json) records first_seen_at/spawn_count per container NAME. Names produced by `docker compose run --rm` are generated per invocation and never repeat, so their key cardinality is unbounded and the debounce can never suppress them by construction: N throwaway containers produce N first-sightings and N spawns. A-30 additionally has no predicate distinguishing a long-lived service container (where rising RSS over time IS the signal) from a short-lived batch container (where high RSS is the expected shape of the job and says nothing about a leak).",
    evidence: "system-auditor signal sys-20260825T133632-2f9d, drained to PO's durable inbox as envelope 786b3b37...: 'A-30 mem_creep pre-gate has no ephemeral-container discriminator - 3 test harnesses paged the auditor in 13 min'. The 3 harnesses were the ephemeral `docker compose run --rm` containers dev-pdf-extractor used for the 2026-08-25 OCR sentinel measurement — i.e. sanctioned, bounded, throwaway work, each correctly at high RSS for the duration of a 46-page OCR job.",
    ac: "(AC-1) A-30 must classify container lifecycle before it evaluates creep, and skip (or evaluate under a different rule) containers that are not long-lived services. Derive the class from something durable — membership in docker-compose.yml's service set, or the container's own labels — never from a name-shape regex, which is the same unbounded-string trap one layer down. (AC-2) DO NOT 'fix' this by resetting spawn_count/first_seen_at or GC-ing the debounce ledger: that regresses QA-verified AC-4 and is test-locked at auditor-tier1-probe.test.sh T-DEBOUNCE-3. A change that makes that test fail is a rejection. (AC-3) POSITIVE CONTROL: with the fix in place, run three ephemeral `docker compose run --rm` containers at high RSS and show ZERO A-30 spawns. (AC-4) NEGATIVE CONTROL, non-substitutable: show A-30 still fires on a genuine long-lived-service creep — a discriminator that silences the check is strictly worse than the noise it removes (feedback_composite_score_masks_dead_detector_pruned_table).",
    status_note: "Triaged from PO durable-inbox envelope 786b3b37... (Pipeline B signal_feedback, WARN). Distinct from the three neighbouring A-30 rows: FIX-AUDITOR-A30-PROBE-SH-MISSES-RAG-SERVICE-CONTAINER is about which containers are scanned, FIX-AUDITOR-A30-CRASHCLIFF-BRANCH-CANNOT-BE-A-CRASH-BY-CONSTRUCTION is about verdict-branch labelling, FIX-AUDITOR-PREGATE-VERDICT-DIVERGENCE-MEMCREEP-NO-OWNING-CHECK is about pre-gate/cycle-verdict divergence. This row is about container-lifecycle classification and debounce key cardinality.",
    dedup_checked: "2026-08-25T13:40Z via scripts/po-board-dedup-search.sh for /mem_creep|A-30|ephemeral.*container/ -> 8 hits, all read; the 3 A-30 rows above were compared field-by-field and none covers lifecycle classification or key cardinality.",
    related: ["FIX-AUDITOR-A30-PROBE-SH-MISSES-RAG-SERVICE-CONTAINER", "FIX-AUDITOR-A30-CRASHCLIFF-BRANCH-CANNOT-BE-A-CRASH-BY-CONSTRUCTION", "FIX-AUDITOR-PREGATE-VERDICT-DIVERGENCE-MEMCREEP-NO-OWNING-CHECK", "FIX-AUDITOR-TIER1-FOLD-VERDICT-NOT-DURABLE-RESPAWNS-AUDITOR-EVERY-TICK"],
    baseline_pass: null
  })

# ── 7. bctc-discover stale pending backlog ────────────────────────────────────
| add_row({
    id: "FIX-BCTC-DISCOVER-513-STALE-PENDING-RECORDS-OVER-72H",
    type: "FIX", size: "M", priority: "P1", status: "BACKLOG",
    zone: "apps/mcp-server/", owner: "po", next_agent: "dev-mcp-server",
    created_at: $now, created_by: $by, updated_at: $now, updated_by: "po",
    dedup_key: "data_stale:bctc-discover|513-pending-over-72h",
    files: ["apps/mcp-server/src/"],
    title: "bctc-discover has 513 pending records older than 72h — a discovery queue that admits work faster than anything drains it, with no age-based escalation or terminal disposition",
    root_cause: "UNDIAGNOSED — this row exists to get it diagnosed, not to assert a cause. The auditor reports the symptom only. Candidate mechanisms to discriminate between, in order of cheapness: (a) the drain consumer is dead or throttled; (b) the drain runs but every attempt fails and the records are re-queued as pending rather than terminalised; (c) discovery admits records for reports that can never be fetched (geo-blocked / delisted / no PDF) and nothing ever marks them terminal. These have different fixes and (b) vs (c) are distinguishable purely from the records' own retry/error columns.",
    evidence: "system-auditor signal, PO durable inbox envelope b2827e04..., 2026-08-25T12:16:06Z, severity WARN: 'bctc-discover: 513 stale pending records (>72h)'. PO dedup-searched all non-terminal lanes for /bctc.?discover/ and /stale pending/ -> NO MATCH: this feed has never had a board row, so the 513 is a floor with no owner, not a known-and-tracked backlog.",
    ac: "(AC-1) FIRST re-measure independently against the live container DB, not the host DB file — the host copy is a known stale decoy that has already manufactured one false CRITICAL on this board (see FIX-AUDITOR-C01-DAILY-OHLCV-MEASURES-STALE-HOST-DB-DECOY-FALSE-CRITICAL). If the live count is materially different, correct the premise in this row before doing anything else. (AC-2) Report the age histogram and the distinct error/retry states of the 513, and name which of (a)/(b)/(c) above the data supports. A fix proposed before this is stated is a rejection. (AC-3) Whatever the cause, the queue must gain a terminal disposition for records that cannot succeed, so the pending count is bounded rather than monotonic. (AC-4) POSITIVE CONTROL: after the fix, the >72h pending count is measured again from the live container DB and is materially lower, with the drop attributed to real completions vs terminalisations separately — collapsing both into one number would let a mass-terminalisation masquerade as recovery (that exact shape is on record in SPIKE-BCTC-EXTRACTION-DORMANT-MASS-ENRICHFAIL-FLOOD).",
    status_note: "Triaged from PO durable inbox 2026-08-25T13:45Z. WARN severity but P1: 513 records over 72h is a standing coverage hole in the BCTC pipeline, which is the pipeline the standing user goal is about.",
    dedup_checked: "2026-08-25T13:40Z via scripts/po-board-dedup-search.sh for /bctc.?discover/ and /stale pending/ -> NO MATCH on non-terminal board rows.",
    related: ["FIX-AUDITOR-C01-DAILY-OHLCV-MEASURES-STALE-HOST-DB-DECOY-FALSE-CRITICAL", "FIX-REFINEBCTC-SKIPSET-NO-STATUS-FILTER-FAILED-UNITS-PERMANENTLY-TERMINAL"],
    baseline_pass: null
  })

# ── 8. CADRAT-3 pre-check gate window is commit-counted ───────────────────────
| add_row({
    id: "FIX-CADRAT3-PRECHECK-GATE-WINDOW-COMMIT-COUNTED-NOT-TIME-BOUNDED",
    type: "FIX", size: "S", priority: "P1", status: "BACKLOG",
    zone: "cross-service/", owner: "po", next_agent: "agent-father",
    created_at: $now, created_by: $by, updated_at: $now, updated_by: "po",
    dedup_key: "cadrat3:pre-check-gate-window-commit-counted-head3",
    files: ["docs/agents/agent-father/flow/main.md"],
    title: "Every CADRAT-3 Pre-Check gate asks 'did an in-scope file change in git diff HEAD~3..HEAD' — a COMMIT-count window, not a time window. At 266 commits/day that spans ~2 minutes, so a once-daily cron is really asking 'did this change in the last two minutes?' and near-always gets no, making the gated primary function effectively dead code",
    root_cause: "HEAD~3 is a fixed commit count. Its wall-clock span is inversely proportional to repo commit rate, and this repo's rate is high and rising (266 commits on 2026-08-25 alone). The gate was presumably written when three commits meant hours. At the observed rate the window measured 14:46:14 -> 14:48:10 = 116 seconds at agent-father's own gate-eval moment. Any cron whose cadence exceeds that window is structurally guaranteed to see 'no in-scope change' and skip its own primary function on nearly every run.",
    evidence: "Router signal router-20260825T131500-gatewindow, observed by router session c6581d0a-1104-40e4-8b55-16c563969d28 during agent-father keep-cycle 2026-08-25T13:01Z, delivered to PO's durable inbox twice (envelopes 28ec4ef5... file-sourced and d0474cf6... dashboard-sourced — one incident, two transports). The 116-second window and the 266-commit day are both stated as measured at gate-eval time.",
    ac: "(AC-1) Enumerate EVERY CADRAT-3 Pre-Check gate before changing any of them and report the count — the signal says 'all' of them, and a point-fix on the one gate that happened to be observed leaves the class open, which is a rejection. (AC-2) Replace the commit-count window with a window whose span is a function of the CRON'S OWN CADENCE, not of repo commit rate: `git log --since` against the cadence period, or the gate's own last-run timestamp. State which and why. (AC-3) POSITIVE CONTROL: with the fix in place and a matching in-scope file changed 12h before the run, a once-daily cron's gate must OPEN. (AC-4) NEGATIVE CONTROL: with no in-scope change inside the cadence period, it must still SKIP — this fix must not degrade into an always-open gate, which would just move the waste rather than remove it. (AC-5) Report, for each gate found in AC-1, how many of its recent runs would have flipped outcome under the fix — that number is the actual cost of the bug and belongs on the record.",
    status_note: "Triaged from PO durable inbox 2026-08-25T13:45Z (2 duplicate envelopes, one incident). Routed to agent-father: docs/agents/**/flow/*.md is instruction-prose per the 2026-07-21 PO artifact-class routing ruling. WARN severity but P1 — a silently-skipped primary function on a daily cron is invisible by construction and this is the first time it has been measured rather than assumed.",
    dedup_checked: "2026-08-25T13:40Z via scripts/po-board-dedup-search.sh for /CADRAT|HEAD~3|gate window/ -> NO MATCH on non-terminal board rows.",
    related: [],
    baseline_pass: null
  })

| .task_board._updated_at = $now
| .task_board._updated_by = "po"
| .task_board.last_triaged_at = $now
| .task_board.last_triaged_by = "po/triage-20260825T1345Z"
