# PO triage 2026-07-30T21:48Z (4th pass, dev-team tick 21:37Z)
#
# ONE transform, 6 edits:
#  1. FLIP   FIX-COMMIT-PATH-PEER-INDEX-SWEEP-GUARD-LAYER2  DONE -> DONE_VERIFIED (PO sign-off,
#            evidence = its OWN po_closure_20260730 RAW-verify record, re-read at source this tick)
#  2. MINT   FIX-DONELANE-NO-DONEVERIFIED-PRODUCER-DEP-STARVATION (P0, backlog, next=architect)
#  3. ANNOT  FIX-COMMIT-PATH-PEER-INDEX-SWEEP-GUARD                (occurrence 5 + dep-starvation cleared)
#  4. ANNOT  FIX-SIGNALQUALITYAUDIT-WRITE-GATE-UNREACHABLE-...     (rebuild_required + verification_gate)
#  5. ANNOT  FIX-MCP-SERVER-DEPLOY-LANE-STALL-REBUILD-REQUIRED-INERT (fresh RAW instance, restart != rebuild)
#  6. ANNOT  FIX-COWORK-SIGNAL-FILENAME-CYCLEID-KEYING             (4x8 re-fire + schema instability)
#
# Usage (from project root):
#   jq -f scripts/po-triage-20260730T2148-donelane-doneverified-producer-starvation.jq \
#      docs/data/orch/orch-state.json | bash scripts/orch-apply.sh

def annot($id; $key; $val):
  (.task_board.backlog, .task_board.ready, .task_board.in_progress,
   .task_board.review, .task_board.qa, .task_board.done)
  |= map(if (.id // .task_id) == $id then . + {($key): $val} else . end);

# ---- 1. LAYER2 DONE -> DONE_VERIFIED -------------------------------------
(.task_board.done |= map(
  if (.id // .task_id) == "FIX-COMMIT-PATH-PEER-INDEX-SWEEP-GUARD-LAYER2" then
    . + {
      status: "DONE_VERIFIED",
      updated_at: "2026-07-30T21:48:55Z",
      updated_by: "po/triage-20260730T2148",
      po_status_token_correction_20260730T2148: "STATUS TOKEN DONE -> DONE_VERIFIED. Not new work and not a fresh verification: this row was already closed by PO at 2026-07-30T09:05:59Z with every AC RAW-verified AT SOURCE and recorded file:line-precise in its own po_closure_20260730 field (4 skill sites carrying explicit pathspecs; 3 init.md commit_discipline lines reading 'RULE 1-3 (incl. 2.5)'; commit aa6c044ba confirmed in git log). PO re-read that field at source this tick before stamping. The ONLY thing that was wrong was the token: scripts/lib/devteam-eligibility.jq deps_satisfied() requires EVERY dep to resolve to the exact string DONE_VERIFIED and states verbatim 'plain DONE is NOT sufficient', so a PO-verified closure recorded as DONE starves every successor forever. MEASURED CONSEQUENCE of this one token, live this tick: FIX-COMMIT-SWEEP-GUARD-SCRIPT-ACTUATOR-AND-NOTEBOOK-LONGTAIL (P0) returned is_bounded1_eligible=false with deps_satisfied=false as its SOLE failing predicate (supervised/epic_wrapper/detail_deferred/nondev_owner/plan_only/nondev_next_agent/unbacked_prose ALL passed) - and that P0 is the sole unblock condition of the 5x-recurring P0 parent. Predicate must return true after this flip. The systemic gap (nothing ever PRODUCES this token) is minted separately as FIX-DONELANE-NO-DONEVERIFIED-PRODUCER-DEP-STARVATION - this flip fixes one row, not the class."
    }
  else . end
))

# ---- 2. MINT the systemic row --------------------------------------------
| .task_board.backlog += [{
    id: "FIX-DONELANE-NO-DONEVERIFIED-PRODUCER-DEP-STARVATION",
    type: "FIX",
    size: "M",
    priority: "P0",
    status: "BACKLOG",
    zone: "cross-service/",
    owner: "po",
    next_agent: "architect",
    created_at: "2026-07-30T21:48:55Z",
    created_by: "po/triage-20260730T2148",
    updated_at: "2026-07-30T21:48:55Z",
    title: "task_board.done[] has ZERO consumers and nothing systematically produces the DONE_VERIFIED token, so deps_satisfied() (which requires the exact string DONE_VERIFIED and rejects plain DONE) permanently starves every successor of a finished-but-unverified row - 8 rows measured starved right now, 4 of them P0",
    desc: "THIRD instance of this repo's documented-consumer-with-no-documented-producer class (siblings: FIX-BOUNDED1-SUPERVISED-LANE-NO-SWEEPER, which idled a P0 6+ days; FIX-WF2-SUPERVISED-HOLD-NO-PO-SIDE-GOAHEAD-PRODUCER, review). MECHANISM, all three legs RAW-verified 2026-07-30T21:48Z: (leg 1) scripts/lib/devteam-eligibility.jq deps_satisfied() is satisfied only when EVERY dep resolves to the exact string DONE_VERIFIED - its own comment says verbatim 'plain DONE is NOT sufficient'. (leg 2) NOTHING sweeps task_board.done[]. `grep -rn 'task_board.done'` across scripts/devteam-*.jq, scripts/agents-flow/*.sh and docs/agents/dev-team/flow/*.md returns ZERO hits excluding done_verified - all four/five dev-team pickers (BOUNDED-1, SLS, RLC, Review QA-Drain, DRS) read backlog[]/ready[]/review[], never done[]. (leg 3) consequently DONE_VERIFIED is only ever written by hand-minted one-off jq files (scripts/po-*.jq, scripts/router-*.jq, scripts/qa-*.jq - 25+ distinct such scripts exist), i.e. it is produced only when a human-driven actor happens to remember. NET EFFECT: done[] is a terminal-LOOKING lane that is actually a dead-letter queue. 11 rows sit in it, 10 at status DONE; 4 of those carry a next_agent (qa/architect/developer/agent-father) that no sweeper ever reads, so the address is dead mail.",
    evidence_raw_verified_20260730T2148: [
      "MEASURED STARVATION SET (predicate RE-RUN, not eyeballed - is_bounded1_eligible from scripts/lib/devteam-eligibility.jq with --slurpfile detail backlog-detail.json --slurpfile archive <(bash scripts/lib/archive-glob-cat.sh)): 8 backlog/ready rows are BOUNDED-1-ineligible with deps_satisfied=false as the SOLE failing gate AND every dep already terminal. P0 FIX-COMMIT-SWEEP-GUARD-SCRIPT-ACTUATOR-AND-NOTEBOOK-LONGTAIL (dep LAYER2=DONE); P0 TASK-COWORK-CATCHUP-3, -4, -5 (dep TASK-COWORK-CATCHUP-2=DONE); P1 FACTORY-APP-split-assembleEveningSummary (dep FACTORY-APP-split-assembleBriefing=DONE); P2 FIX-COMMIT-SWEEP-VICTIM-SELF-DETECT (dep ..-SKILLS=DONE); P3 FU-FPT-2025Q4-STAGE4-DUP (dep FIX-BCTC-TABLE-COLUMN-FPT-OVERFIT=DONE); medium FIX-CYCLEJOB-1294-FOLLOWUP-SWEEP-UNMOCKED-LIVE-FETCH (dep ..-MACRO-TEST-UNMOCKED-LIVE-FETCH=DONE).",
      "done[] LANE DUMP (11 rows, 10 at DONE): SPIKE-COWORK-DRAIN-BODY-NOT-EXECUTING-ON-WORK-TICKS next=developer since 07-21; FIX-COMMIT-PATH-PEER-INDEX-SWEEP-GUARD-SKILLS next=MISSING since 07-21; TRACK-CRON-AUDIT-VPS-PLANE / TRACK-CRON-AUDIT-SERVER-PLANE next=MISSING since 07-22; FIX-AUDITOR-A12A20A30-FP-REEMIT-CONVERGE next=MISSING; UNBLOCK-AGENT-MODELS-SWITCH-COMMIT-DISPOSITION next=agent-father; TASK-COWORK-CATCHUP-2 next=qa since 07-28; FACTORY-APP-split-assembleBriefing next=qa since 07-28; SPIKE-DASHBOARD-TIER-HEALTH-CURL-ERR-FLAP next=architect. TASK-COWORK-CATCHUP-2 and FACTORY-APP-split-assembleBriefing have been addressed to qa for 2 days with no lane that reads them.",
      "GREP (leg 2): `grep -rn 'task_board\\.done\\b' scripts/devteam-*.jq scripts/agents-flow/*.sh docs/agents/dev-team/flow/*.md | grep -v done_verified` -> 0 hits. The only two done-lane mentions anywhere in dev-team flow are post-cycle.md:69 and :107, both about cold-EVICTION, not verification promotion.",
      "LIVE HARM, this tick: the P0 chain FIX-COMMIT-PATH-PEER-INDEX-SWEEP-GUARD (recurring_bug_count=4, occurrence 5 fired 21:30:47Z as commit-sweep-guard signal ...T213047Z-59042.json against commit 43e0d7ddc) -> unblock condition FIX-COMMIT-SWEEP-GUARD-SCRIPT-ACTUATOR-AND-NOTEBOOK-LONGTAIL (P0) -> starved solely because LAYER2 said DONE not DONE_VERIFIED. A P0 was blocked on a P0 that was blocked on a STRING, for 12h, while the defect it prevents fired again."
    ],
    po_scope_calls_NOT_design: [
      "RULED OUT - loosening deps_satisfied() to accept plain DONE. That deletes the distinction the strict token exists to enforce (landed != verified) and would silently auto-dispatch successors of genuinely unverified work. Do not re-scope the gate as the fix (feedback_gate_widening_recommendation_requires_actuator_dry_run) - the gate is correct; the PRODUCER is missing.",
      "RULED OUT as a SOLE fix - another flow-doc line telling agents to remember to write DONE_VERIFIED. 25+ hand-minted one-off jq scripts already prove that vigilance-shaped control does not hold, and this is the same disposition that failed 3x on the commit-pathspec class.",
      "IN SCOPE for architect - WHICH mechanism produces the token, and its failure-safety. Candidates the architect chooses between, not a pre-made decision: (a) a done[]-lane sweeper on the dev-team idle chain, symmetric with the existing Review QA-Drain, that routes a DONE row to its next_agent (qa where set) and lets QA promote the token; (b) making DONE a lane-illegal terminal state so a row must land as DONE_VERIFIED, CANCELLED etc. and any DONE row is loud; (c) both. Whichever is chosen must NOT auto-promote DONE -> DONE_VERIFIED without a verifier - that would make the token vacuous and is strictly worse than the current starvation (feedback_reader_writes_its_own_trigger_field_check_is_vacuous)."
    ],
    acceptance: "(1) A named, executable producer for the DONE_VERIFIED token exists and is wired into a lane that actually runs (the dev-team idle chain rotation, or an equivalent the architect justifies), so a finished row reaching done[] cannot sit there indefinitely. (2) A DONE row carrying next_agent is REACHED by that producer - demonstrate on the two live 2-day-old cases (TASK-COWORK-CATCHUP-2, FACTORY-APP-split-assembleBriefing, both next=qa). (3) The producer NEVER promotes DONE -> DONE_VERIFIED on its own authority; promotion requires the verifier the token denotes. A row it cannot verify must become LOUDER (surfaced), not silently promoted. (4) A row that lands in done[] with NO next_agent is not silently invisible - it is surfaced to PO/router rather than defaulting to permanent residence. (5) The 8 currently-starved rows are re-measured with the ACTUAL predicate after the fix; the count must drop, and any row still starved must have a named reason. (6) Regression instrument: a script that re-runs is_bounded1_eligible over backlog[]+ready[] and reports the sole-deps_satisfied-failure set, so this class is detectable next time instead of being re-derived by hand.",
    verification_gate: "Re-run the exact measurement in evidence_raw_verified_20260730T2148 leg 1 (is_bounded1_eligible with deps_satisfied isolated as the sole failing gate, threaded through the REAL scripts/lib/devteam-eligibility.jq, not a reimplementation) against the live board AFTER the fix, and show the starved-set count with each remaining member's named reason. PLUS: show a done[] row transitioning to DONE_VERIFIED through the new producer with real command output - not asserted from flow-doc prose (feedback_fix_landed_in_the_pregate_not_the_probe_the_agent_actually_runs).",
    note: "Do NOT hand-flip the remaining DONE rows to clear the measurement. PO deliberately flipped exactly ONE (FIX-COMMIT-PATH-PEER-INDEX-SWEEP-GUARD-LAYER2) because that row's own po_closure_20260730 field already carried a file:line-precise PO RAW-verification from 09:05:59Z - the token was the only thing missing. TASK-COWORK-CATCHUP-2 and FACTORY-APP-split-assembleBriefing carry next_agent=qa and have NOT been verified by anyone; flipping them would be PO ratifying work it never checked, which is the exact vacuous-gate failure this row exists to prevent. They stay DONE as live evidence."
  }]

# ---- 3..6 annotations ----------------------------------------------------
| annot("FIX-COMMIT-PATH-PEER-INDEX-SWEEP-GUARD";
      "po_occurrence_5_and_dep_unstarve_20260730T2148";
      "OCCURRENCE 5, RAW-verified this tick, and the reason the fix for it could not move. (A) THE SWEEP: commit-sweep-guard signal docs/signals/processed/commit-sweep-guard-2026-07-30T213047Z-59042.json fired at 21:30:47Z, mode=warn, actor=64c7c677-0f0f-4cee-a3ce-dba79d70b7ae (the dev-team ROUTER session), naming 11 staged files. Matched to commit 43e0d7ddc 'fix(mcp-server/signal-quality-audit): wire write gate to urgent_news real emitter field' (23:30:47+02:00 == 21:30:47Z, exact). That commit's stated scope is one mcp-server fix; it also carried docs/agent-memory/notebooks/dev-mcp-server.md, docs/agent-memory/decisions/sprint-COWORK-GUARANTEED-SLOT-CATCHUP-dev-mcp-server.md and docs/data/orch/orch-state.json. Same attribution-corruption shape as occurrences 1-4; FIRST one where the ROUTER is the sweeper on a hand-issued (non-preflight) commit - so arm (1) of FIX-COMMIT-SWEEP-GUARD-SCRIPT-ACTUATOR-AND-NOTEBOOK-LONGTAIL (dev-team-tick-preflight.sh:454-455) would NOT have caught this instance; scope it accordingly. recurring_bug_count left at 4 deliberately: same already-tracked class, counted once. (B) WHY NOTHING MOVED - NEW ROOT CAUSE, the actionable part: the unblock condition PO set this morning (FIX-COMMIT-SWEEP-GUARD-SCRIPT-ACTUATOR-AND-NOTEBOOK-LONGTAIL reaches DONE) was itself STRUCTURALLY UNPICKABLE. PO ran scripts/lib/devteam-eligibility.jq is_bounded1_eligible against the live board: false, with deps_satisfied=false the SOLE failing gate; its one dep FIX-COMMIT-PATH-PEER-INDEX-SWEEP-GUARD-LAYER2 resolved to 'DONE' and deps_satisfied() requires the exact token 'DONE_VERIFIED'. A P0 was blocked on a P0 that was blocked on a STRING. LAYER2 flipped to DONE_VERIFIED this tick on its own already-recorded RAW-verify evidence, so the actuator row is now BOUNDED-1-eligible. DO NOT read that as the class being fixed - 7 other rows are still starved the same way, see FIX-DONELANE-NO-DONEVERIFIED-PRODUCER-DEP-STARVATION.")

| annot("FIX-SIGNALQUALITYAUDIT-WRITE-GATE-UNREACHABLE-BY-EMITTER-CONTRACT";
      "po_deploy_gate_20260730T2148";
      "NOT DEPLOYED - QA MUST NOT VERIFY THIS AGAINST THE RUNNING SERVER YET. RAW-verified 2026-07-30T21:48Z, both planes read: `docker exec vn-market-intelligence-mcp-mcp-server-1 grep -c deriveAuditConfidence /app/src/domain/services/signalValidator.ts` returns 0; the same grep on the host working tree returns 1. The running image (sha256:1bba4e58c9d2, created 2026-07-30T08:27:58Z) PREDATES commit 43e0d7ddc (21:30:47Z) by 13h, and apps/mcp-server/src is BAKED INTO THE IMAGE - docker inspect Mounts shows no src bind-mount (only docs/data, docs/agent-memory, docs/signals, reports, data/live, data/pdfs are bound). The container WAS restarted at ~21:31Z, immediately after the commit; a restart re-runs the SAME image and deploys nothing. ALSO: this row landed in review[] with verification_gate=null AND acceptance=null, so QA had no gate and would have improvised against whichever plane it happened to read - host source = false GREEN, live container = false RED, both wrong for the same reason. Gate now installed at po_verification_gate_20260730T2148. Telegram report 4220 ('[sla-monitor] CRITICAL breach: signal_quality_audit stale 79277min, threshold 43200min') is CORRECT and will keep firing: the table is 55d stale, the fix that would end it is not in the running binary, and the monthly producer cron (0 0 1 * *) does not fire until 2026-08-01 regardless.")

| annot("FIX-SIGNALQUALITYAUDIT-WRITE-GATE-UNREACHABLE-BY-EMITTER-CONTRACT";
      "rebuild_required"; true)

| annot("FIX-SIGNALQUALITYAUDIT-WRITE-GATE-UNREACHABLE-BY-EMITTER-CONTRACT";
      "po_verification_gate_20260730T2148";
      "VERIFICATION GATE (was null - installed by PO 2026-07-30T21:48Z). Ordered, all three required, each RAW. (1) DEPLOY FIRST - single-service rebuild of mcp-server ONLY (never `down && up`), then assert the code is actually in the runtime: `docker exec vn-market-intelligence-mcp-mcp-server-1 grep -c deriveAuditConfidence /app/src/domain/services/signalValidator.ts` returns >=1 AND `docker image inspect` Created is LATER than 2026-07-30T21:30:47Z. A restart does NOT satisfy this. (2) BEHAVIOUR, not source - post a real urgent_news signal carrying regime_adjusted_score and NO confidence field via post_agent_signal, then read signal_quality_audit directly from the live DB and assert a NEW row exists whose created_at is AFTER the rebuild and whose confidence == regime_adjusted_score/10 clamped to [0,1]. Reading the TS source or the unit test is NOT this gate. (3) NEGATIVE CONTROL - post a signal carrying NEITHER confidence NOR regime_adjusted_score and assert NO row is written (the fix's own contract returns null there; a fabricated constant would be worse than the original bug). Do NOT accept the sla-monitor alert going quiet as evidence for any of the three: threshold 43200min vs 79277min measured staleness means it keeps firing until a write lands, regardless of whether the gate is wired.")

| annot("FIX-MCP-SERVER-DEPLOY-LANE-STALL-REBUILD-REQUIRED-INERT";
      "po_live_instance_20260730T2148";
      "FRESH LIVE INSTANCE + a new sub-shape. RAW 2026-07-30T21:48Z: running mcp-server image sha256:1bba4e58c9d2 created 2026-07-30T08:27:58Z; commit 43e0d7ddc landed 21:30:47Z; container grep for the new symbol deriveAuditConfidence returns 0 inside /app/src while the host tree returns 1. apps/mcp-server/src has NO bind-mount (docker inspect Mounts confirms only docs/data, docs/agent-memory, docs/signals, reports, data/live, data/pdfs are bound), so source-on-host is never source-in-runtime for this service. NEW SUB-SHAPE worth scoping into this row: the container shows `Up 18 minutes` (restarted ~21:31Z, immediately after the commit) while CreatedAt is 08:28 - an actor RESTARTED the service believing that deployed the fix. Restart re-runs the same image. So a deploy-lane fix must make restart-vs-rebuild DISTINGUISHABLE at the point of use, not merely add another rebuild_required flag to rows: a flag nobody can tell has been honoured is the same defect one layer up. Directly relevant and cheap: OPS-MCP-SERVER-REACQUIRE-GIT-SHA-LABEL (P2 backlog) - the container carries no vn.market.git_sha label, which is exactly the missing primitive that would turn 'is this fix deployed' into a one-command answer instead of a grep-into-the-container. Consider folding it in as the first arm.")

| annot("FIX-COWORK-SIGNAL-FILENAME-CYCLEID-KEYING";
      "po_measurement_20260730T2148";
      "MEASURED CORROBORATION + a second, worse symptom than filename collision. (A) FREQUENCY: the identical 8-file set bctc_signal_{BID,FPT,FRT,GEX,HPG,MWG,VCB,VIX}_20260730_routine.json was drained and routed-to-po FOUR times on 2026-07-30 alone - commits c0cbb756f, 236310900 (18:07Z), 23aeea6ed (21:07Z), 072541471 (21:37Z) - i.e. 32 PO-triage routing events for 8 distinct facts, plus a 5th earlier drain (4737c562d 01:17Z) on a different ticker set. Date-only keying is the mechanism: the filename carries no time/cycle component, so every cycle rewrites the same path. (B) THE WORSE SYMPTOM, not previously on this row: the re-written files are NOT byte-identical re-emissions - they are DIFFERENT ANALYSES WITH A DIFFERENT FIELD SCHEMA overwriting each other at the same path. `git diff 236310900 23aeea6ed -- docs/signals/processed/bctc_signal_HPG_20260730_routine.json` shows the 18:07Z revision carrying esc3_guard_held/esc4_result/esc5_result/e3_cache/trick_summary/trick_confidence/kd_reading/cycle_id/generated_at and the 21:07Z revision carrying NONE of them (different prose, different keys, only esc3_status survives); the BID pair shows the same instability (quarantine/kd_durability replaced by roe_pct/pe/valuation_verdict/kinhdich{}/report_overdue/cycle_tick_utc/slot). Any downstream consumer parsing these fields breaks non-deterministically depending on which cycle last wrote the file, and the prior cycle's analysis survives only in git. Fix scope should therefore cover the emitter's field CONTRACT (a stable schema) alongside the filename keying - cycle-id keying alone preserves every revision but leaves consumers unable to parse them. next_agent=ba is still right.")
