# PO retraction 2026-07-29T11:48Z — the page-cache hypothesis is REFUTED.
# The anon/file cgroup split I named as the decisive un-run test was already
# run (by accident, 10:12Z) and reads anon-dominant. Retracts the reclaimable-
# page-cache reading, discharges the cap-sizing gate, and un-couples the disk
# fact from the memory fact on all three rows that carried the conflation.
# Idempotent (marker-key guarded). No mints, no lane moves, no priority change.
#
# Usage:
#   NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
#   jq --arg now "$NOW" -f scripts/po-triage-20260729T1148-rag-anon-dominant-retraction.jq \
#     docs/data/orch/orch-state.json | bash scripts/orch-apply.sh

def addend($lane; $id; $key; $val):
  .task_board[$lane] |= map(
    if (.id? // "") == $id and (has($key) | not)
    then . + { ($key): $val, "updated_at": $now, "updated_by": "po/triage-20260729T1148-retraction" }
    else . end
  );

addend("ready"; "FIX-RAG-SERVICE-CLEAN-EXIT-RESTART-LOOP"; "po_RETRACTION_pagecache_20260729T1148";
  "RETRACTION — supersedes the page-cache reading in po_allocation_mechanism_20260729T1140. That note argued the 94-98% plateau was cgroup-charged file cache from a 786 MiB LanceDB dataset exceeding a 768 MiB cap, i.e. reclaimable, i.e. no death clock. THAT IS WRONG. THE DECISIVE TEST WAS ALREADY RUN, 90 MINUTES BEFORE I NAMED IT AS UN-RUN — by accident, and destructively. At 10:12Z a dev-rag-service agent ran `docker exec ... python3 -c \"import lancedb, pyarrow, pandas\"` into ~1.56 MiB of headroom; the interpreter allocated inside the target cgroup and SIGKILLed the container (exec exit 137). The kill produced the reading: cgroup anon = 761716736 B (726.4 MiB) immediately pre-restart, against a total usage of ~767 MiB at the ceiling, dropping to anon = 32272384 B (30.8 MiB) immediately post-restart. ANON IS ~95% OF THE CGROUP; FILE-BACKED IS AT MOST ~40 MiB. The LanceDB corpus is NOT resident in this cgroup — if it were, file would dominate, and the measurement says the opposite. PROVENANCE, STATED PLAINLY: those two anon figures are ROUTER-SUPPLIED and I did NOT independently re-derive them; re-deriving requires reading the VM cgroup tree, and the only route PO has is the exec that caused this. WHAT I DID VERIFY MYSELF, and why I accept the conclusion anyway: (1) docker inspect corroborates the incident exactly — FinishedAt 2026-07-29T10:12:00.633695956Z, StartedAt 10:12:01.011509189Z, RestartCount 22, OOMKilled=false, ExitCode=0, the documented clean-exit signature. (2) INDEPENDENT MECHANISTIC CORROBORATION THAT WAS ALREADY ON THIS ROW BEFORE I STARTED: cold RSS 50.7 MiB rising to 749.9 MiB after exactly ONE POST /index, with the model load logged 10:24:28.5Z-10:24:48.9Z. A 699 MiB step from a single embed CANNOT be page cache — loading model weights into process heap is anonymous by construction. That fact alone settles anon-dominance, it was in this row's own root_cause field, and I read it and then built the opposite hypothesis anyway. WHAT I GOT WRONG AND WHY IT IS WORTH RECORDING: 786 MiB on disk versus a 768 MiB cap is a NUMERIC COINCIDENCE, not a mechanism. I let two numbers of similar magnitude stand in for a causal story, and the seduction of the coincidence was strong enough to override a direct measurement I had already read. WHAT SURVIVES: this row is UNCHANGED and CORRECT as written — the fixed anonymous baseline from the no-release-path model singleton is the whole magnitude, and the compaction-burst mechanism is the trigger. WHAT CHANGES: the mitigating branch is CLOSED. There is no reclaim to rescue this container; ~726 MiB is process-resident and the ~11 MiB of headroom is genuinely all there is. Priority still P2 on the stated rate bar (RestartCount 22, unmoved ~2h15m), but the risk framing is now the un-mitigated one.")

| addend("backlog"; "FIX-RAG-COMPACTION-DISK-AMPLIFICATION"; "po_UNCOUPLE_disk_from_memory_20260729T1148";
  "SCOPE UN-COUPLING — corrects po_evidence_and_priority_20260729T1140 on this row. That note justified the P3->P2 raise partly on the claim that 786 MiB of on-disk LanceDB exceeding a 768 MiB memory cap means no read workload can have its working set resident, so fragment count drives cgroup pressure. THE MEMORY HALF OF THAT ARGUMENT IS RETRACTED. The cgroup anon/file split measured at the 10:12Z restart reads ~726 MiB anon against at most ~40 MiB file-backed, so the corpus is NOT resident in this cgroup and fragment fan-out is NOT what pins it at 98%. That is the model singleton, owned by FIX-RAG-SERVICE-CLEAN-EXIT-RESTART-LOOP and FU-RAG-DEPLOY-MEMORY. THE DISK FACTS ARE UNAFFECTED AND STILL CARRY THE RAISE ON THEIR OWN: du -sm data/live/lancedb = 786 MiB for a corpus of ~11243 rows; rag_entries.lance/data holds 3137 fragment files / 596 MiB (roughly one fragment per 3-4 rows, each POST /index landing a fresh ~6.7-6.9 KiB fragment); _versions 3091 manifests / 32 MiB and _transactions 3091 files / 12 MiB, so version metadata alone is 44 MiB and grows one pair per write; _indices 145 MiB / 745 files. Unbounded fragment and version accumulation is a real defect with real disk and real query-planning cost, and this repo has an ENOSPC incident on record. P2 STANDS. WHAT DOES NOT STAND is the causal link to the memory ceiling, and a future reader must not inherit it: fixing compaction will reclaim DISK and reduce fragment fan-out, and should NOT be expected to move the 98% memory figure. The still-true coupling to the sibling row is narrower and worth keeping: the compaction failure-path counter defect is WHY 3137 fragments accumulated, so that row is upstream of this one on cause. It is not upstream on the memory symptom.")

| addend("backlog"; "FU-RAG-DEPLOY-MEMORY"; "po_GATE_DISCHARGED_anon_dominant_20260729T1148";
  "CAP-SIZING GATE DISCHARGED — supersedes the closing paragraph of po_dataset_exceeds_cap_20260729T1140, which said do not size a cap change before the anon-vs-file split is measured. IT IS MEASURED AND IT SAYS PROCESS-RESIDENT. At the 10:12Z restart the cgroup read anon = 761716736 B (726.4 MiB) pre-restart against ~767 MiB total, falling to anon = 32272384 B (30.8 MiB) post-restart — anon ~95%, file-backed at most ~40 MiB. (Router-supplied figures, not independently re-derived by PO; re-deriving needs the exec that caused the kill. Independently corroborated in mechanism by this row's own po_measured_input_20260729: cold RSS 50.7 MiB to 749.9 MiB on a SINGLE embed, which can only be anonymous heap.) WHAT THIS CHANGES FOR THE TRADE THIS ROW OWNS. (1) The branch I raised as a reason to hesitate — that the memory might be reclaimable file cache, in which case a cap raise buys throughput rather than safety — IS CLOSED. The process genuinely needs ~726 MiB resident, so a cap raise buys REAL headroom. Option (a) is live, not deferred. (2) Option (c), shrink the dataset footprint, is DEMOTED as a memory remedy: the corpus is not resident in the cgroup, so compaction will not move the 98%. It remains worth doing on disk grounds (FIX-RAG-COMPACTION-DISK-AMPLIFICATION, P2) but must not be sold to this row as a memory fix. (3) Option (b), shrink the fixed baseline via a model release path or a smaller/quantised model, is now the ONLY structural alternative to raising the cap, because ~726 MiB of anon on a 768 MiB limit is the entire problem stated in one line. THE SIZING ARITHMETIC THIS ROW NEEDS, no longer blocked: ~726 MiB resident + ~20 MiB peak compaction burst + operating slack. Today's 768 MiB leaves ~11 MiB, which does not cover one burst. STILL NOT AUTHORISED BY PO: the cap change itself and any rebuild — user-gated infra, and the 16GB host budget this row owns is a real constraint that a blind revert to 1.5g does not respect (the 2026-06-10 cut 2dc1d8c4e answered a genuine host panic). Discharging the measurement gate is not approving the change.")
