# po-triage-20260814T0926Z-cronjobruns-adhoc-query-mint.jq
# Mints FIX-AUDITOR-DATATIER-CRONJOBRUNS-ADHOC-COUNT-NONDETERMINISTIC into .task_board.backlog.
# Idempotent: no-op if the id already exists anywhere on the board.
# Usage: jq -f scripts/po-triage-20260814T0926Z-cronjobruns-adhoc-query-mint.jq \
#          docs/data/orch/orch-state.json | bash scripts/orch-apply.sh

def already_present:
  [ (.task_board | to_entries[] | select(.value | type == "array") | .value[]? | .id? ) ]
  | any(. == "FIX-AUDITOR-DATATIER-CRONJOBRUNS-ADHOC-COUNT-NONDETERMINISTIC");

if already_present then .
else
  .task_board.backlog += [{
    "id": "FIX-AUDITOR-DATATIER-CRONJOBRUNS-ADHOC-COUNT-NONDETERMINISTIC",
    "type": "FIX",
    "title": "DATA-tier sweep hand-authors its cron_job_runs failure query per run and filtered on status='failed' — a value the table CHECK constraint forbids — silently omitting all 205 'crashed' rows and flipping the SAME static table from REAL/HIGH to NOISE/no-signal across two spawns 30min apart",
    "status": "BACKLOG",
    "priority": "P2",
    "size": "S",
    "zone": "cross-service/",
    "next_agent": "developer",
    "created_at": "2026-08-14T09:26:21Z",
    "created_by": "po",
    "source": "router bug report 2026-08-14, session 6194fe17-df8a-4b04-ad52-072efab100ee; memory feedback_auditor_cronjobruns_adhoc_query_missing_crashed_status_false_negative.md",
    "detail_ref": null,
    "depends": null,
    "related": [
      "FIX-CRON-RUNS-NULL-ERRORMSG",
      "UC-ASL-P3",
      "FIX-AUDITOR-DATATIER-REINVOKES-STATEFUL-PREGATE-SELF-DEFEATS-ROUTER-SPAWN"
    ],
    "evidence": "TWO DATA-tier spawns, same static/historical table, 30min apart on 2026-08-14, opposite verdicts. Spawn a9970e00ad40993d7 (scan_ts 08:52:26Z): '212 total error/crashed runs, most recent 2026-08-11' -> REAL/HIGH, dedup'd to already-open FIX-CRON-RUNS-NULL-ERRORMSG. Spawn ae3fa34f454119ea3 (scan_ts 09:22:11Z): '7 rows with status=failed or error, most recent 2026-07-19, no active failures in last 7 days' -> NOISE/WARN, signal_id null, no dedup, no routing. GROUND TRUTH (PO re-verified independently 2026-08-14T09:2xZ, host-bind WAL-safe read via scripts/lib/sqlite-wal-guard.sh): success|206023, crashed|205|max 2026-08-11 14:00:02, error|7|max 2026-07-19 12:40:08. First scan correct (212=205+7). Second scan undercounted by 205 rows and misdated the most-recent failure by 23 days.\n\nPO ADDITION — THE DECISIVE FACT NEITHER SCAN NOR THE BUG REPORT HAD: the live schema is `status TEXT NOT NULL CHECK(status IN ('running','success','error','crashed'))`. 'failed' is NOT a legal value and can NEVER match a row. The second scan did not merely pick a narrow keyword subset; it filtered on a status the CHECK constraint makes unreachable, so one of its two disjuncts was dead by construction. Any hand-authored keyword list is guessing against an enum that is already declared in the schema.\n\nWHY NO HARM THIS TIME (and why that is luck, not a control): the sibling scan 30min earlier had already routed the finding. A future sweep running without a luckily-correct sibling suppresses an active 205-row, 3-day-old failure pattern with zero routing.",
    "root_cause": ".claude/commands/crons/cron-db-data-integrity.md specifies cron_job_runs failure detection as FREEFORM PROSE only — line 96 lists cron_job_runs among the watched tables and line 101 says 'cron_job_runs last run errored' under ANOMALY CLASS 1, with no query attached. The file's own NO HALLUCINATED COUNTS guard (line 162-181) covers exactly four counts and then explicitly licenses the gap: 'Use your own ad-hoc sidecar queries ONLY for discovering NEW anomalies + classification, not for re-counting the known four.' cron_job_runs failure state is a RECURRING watched metric being processed through the ad-hoc DISCOVERY path, so it is re-derived by an LLM on every run and is free to drift. The other 4 counts are byte-identical run-to-run precisely because scripts/db-integrity-counts.sh owns them. Same defect class, same remedy, one table short.",
    "acceptance": "AC-1 scripts/db-integrity-counts.sh emits cron_job_runs status counts DERIVED FROM THE DATA, not from a hand-authored keyword list. REQUIRED SHAPE: a `GROUP BY status` that emits EVERY bucket present (plus MAX(started_at) per bucket), so a status value the author did not think of cannot be silently dropped and a future 5th enum value appears automatically. A hardcoded IN-list of status literals is REJECTED in review even if today's list is complete — enumerating by hand is the defect, not the particular list chosen.\n\nAC-2 REJECT THE BUG REPORT'S OWN PROPOSED PREDICATE. The filed root-cause candidate said 'enumerate ALL non-success status values via status != \"success\"'. That is wrong: it folds `running` into the failure count, and `running` is a legal in-flight state, so every sweep that lands mid-run would manufacture a phantom failure. Failure = status IN ('error','crashed') per the schema CHECK. `running` MUST be reported as its own bucket, never summed into failures. (A long-stuck `running` row IS a distinct real anomaly — stuck/never-finished job — and AC-1's GROUP BY surfaces it without conflating it. Do not build a staleness threshold for it in this row; out of scope, note it for a follow-up.)\n\nAC-3 ADDITIVE CONTRACT ONLY. New key(s) go under the existing `counts` (or a sibling `context`) object; the four existing key names and values are unchanged byte-for-byte. Verified consumers at mint time: scripts/db-integrity-counts.test.sh, .claude/commands/crons/cron-db-data-integrity.md, scripts/developer-fix-auditor-emptytable-writer-discriminator-to-review.jq. scripts/db-integrity-history-append.sh:146 passes `$counts.counts` through generically and needs no edit — confirm this still holds rather than assuming it.\n\nAC-4 scripts/db-integrity-counts.test.sh gains a case that is RED against unmodified HEAD: a fixture DB carrying rows in ALL FOUR status values must produce a crashed-inclusive failure figure, and a fixture whose only non-success rows are `crashed` must NOT report zero failures. A test that was never RED proves nothing.\n\nAC-5 .claude/commands/crons/cron-db-data-integrity.md moves cron_job_runs failure state OUT of the ad-hoc/discovery bucket and INTO the NO HALLUCINATED COUNTS mandate: the sweep MUST copy the helper's numbers verbatim and is FORBIDDEN from authoring its own cron_job_runs SQL. Update the 'the known four' wording (line ~176) — leaving it at 'four' re-licenses the exact gap this row closes.\n\nAC-6 VERIFY AGAINST THE LIVE DB, not only the fixture: the helper's cron_job_runs output must equal the ground truth in this row's evidence field at run time (crashed and error buckets both present, crashed max_started_at = 2026-08-11 14:00:02 or later). Read-only via scripts/lib/sqlite-wal-guard.sh — never `sqlite3 -readonly`, never a bare `?immutable=1`.",
    "non_goals": "Does NOT fix FIX-CRON-RUNS-NULL-ERRORMSG (the NULL error_msg defect on those same rows) — that row stays open and unmodified; this row only makes the DETECTOR that finds it deterministic. Does NOT touch the Tier-2/3 C-01..C-16 predicate family — that is UC-ASL-P3's separate scripts/auditor-db-checks.sh scope; do not merge the two. Does NOT add a stuck-`running` staleness threshold (see AC-2). Does NOT change any of the 4 existing canonical counts.",
    "po_rescope_note": "FILED AS DIRECT-FIX, NOT THE FULL BA->ARCHITECT->PM CHAIN THE REPORTER REQUESTED. Rationale, so this is auditable rather than a silent downgrade: the design is fully determined before any architect touches it — the schema CHECK constraint hands us the enum, the remedy pattern is already shipped and proven in this exact file for 4 sibling counts, an existing regression test file is already in place, and PO verified the consumer set is 3 files with a generic passthrough at the 4th. Blast radius is additive-only. The one genuine design trap (running vs failure, see AC-2) is resolved in the ACs above rather than deferred. Sending a 3-file additive change with a written predicate through 3 planning agents is process cost with no design left to buy. If the implementer disagrees and finds a real contract break in AC-3, escalate back to PO and this reroutes to architect — do not silently widen scope.",
    "consumer_impact": "Detector-reliability gap in a DATA-integrity safety net. Not urgent: currently masked because the sibling scan routed the finding via FIX-CRON-RUNS-NULL-ERRORMSG. Must not be deprioritized indefinitely — the masking is coincidence between two spawns, not a control, and the failure mode is SILENT suppression (verdict NOISE, signal_id null) which leaves no trace to detect later."
  }]
end
