# scripts/po-triage-20260807T0540Z-cowork-filename-adjudication.jq
# PO adjudication of the architect brief for FIX-COWORK-SIGNAL-FILENAME-CYCLEID-KEYING
# (docs/architecture-briefs/2026-08-07-cowork-signal-filename-cycleid-keying.md, commit 0767d463d).
# Advances architect -> pm, stamps po_goahead, records 3 BINDING scope amendments, syncs .head.
# Invoke: jq -f <this> docs/data/orch/orch-state.json | bash scripts/orch-apply.sh

def amend:
  . + {
    next_agent: "pm",
    po_goahead_20260807T054500: "RATIFIED 2026-08-07T05:45Z by po (architect-brief sign-off, stage 2 of 2 on this row). Brief read in full at source; both open items in its Section 10 adjudicated below. plan_only+supervised DELIBERATELY PRESERVED — pm decomposes, no code ships without returning here. Design APPROVED as written EXCEPT the three binding amendments in po_architect_signoff_20260807T0545 — pm MUST carry all three into decomposition; they are acceptance-bearing, not advisory.",
    po_architect_signoff_20260807T0545: {
      verdict: "GO with 3 binding amendments — brief approved, not returned to architect. FR-1/FR-2/FR-3/FR-5/FR-6/FR-7 designs accepted as written; the source-verification recap (Section 1) was spot-checked and holds.",
      amendment_1_FR4_DESCOPE: "FR-4 (tran-ngoc-bau write-serialization) is DESCOPED from this row entirely — and NEITHER of the architect's two offered options is the right call, because both assume FR-4 is unowned. It is not. RAW-verified against the live board this tick, a three-row chain already owns this exact mechanism: (a) GUARD-NOTEBOOK-CONCURRENT-EDIT-COLLISION-DATA-LOSS (in_progress, P1, next_agent=pm, owner=po) — the tracking row, minted from the SAME tnb Edit-collision the architect analysed, and scope-widened by po on 2026-08-06T17:39:33Z to also cover the Write-full-overwrite path; (b) FIX-NOTEBOOK-WRITE-TASK-KIND-ENUM-EXTENSION (backlog, P1, dev-mcp-server) — adds task_kind='notebook-write' to the Zod enum, the enabling prerequisite; (c) FIX-NOTEBOOK-WRITE-AC7-SKILL (BLOCKED on (b), P1, agent-father) — which ALREADY SPECIFIES, verbatim, the mechanism the architect asked whether to commission: task_claim(task_id='notebook:<agent-id>', task_kind='notebook-write', ttl_seconds=120) bracketing ONLY the mechanical fresh-read-merge-write span, with the TTL-hazard carve-out for LLM authoring time. Commissioning it here would be a duplicate design. FACTUAL CORRECTION to brief Section 5, recorded so it is not inherited: the architect's RAW-verify was scoped to tran-ngoc-bau.md's own file only and concluded 'no recurrence in the available evidence window'. The MECHANISM did recur inside that window — 2026-08-06T17:21:01Z, qa.md lost 2 peer cycle entries (cycle-522, cycle-523) to a full-overwrite race; router-detected, po-triaged as occurrence 2 (signal_queue row dev-20260806T172101-qanb). So option 1's premise ('unreproduced') is false at the mechanism level and option 2's premise ('no design exists yet') is false at the board level. Correct disposition is the third one: FOLD, do not re-mint, do not re-design. Zero FR-4 file changes in this row's eventual developer handoff; the brief's own Section 9 already maps no AC to FR-4, so this descope changes no acceptance criterion.",
      amendment_2_EC2_FOLLOWON: "CONFIRM the architect's separate-row recommendation, OVERRIDE its timing. Folding the chef-intraday multi-fire MARKER_KEY UTC-hour migration into this row is correctly refused — it reopens scope FIX-CHEF-MARKER-KEY-WINDOW-ANCHOR deliberately excluded, it is gated on a dependency that has not shipped, and a live publish-mutex basis change carries its own double-publish/suppressed-publish risk that deserves its own AC. BUT 'PO mints a follow-on row once scheduled_utc_time lands on the live-match path' is a consumer with no producer — nobody is watching for that landing, and that is the precise defect class that idled FIX-WF2-SUPERVISED-HOLD-NO-PO-SIDE-GOAHEAD-PRODUCER and left FIX-BOUNDED1-SUPERVISED-LANE-NO-SWEEPER's P0 dormant 6+ days. Therefore the row is minted NOW, this tick, in backlog[] as status=BLOCKED with an explicit blocked_by, so the dependency is visible to the board's own machinery instead of living as prose in an architecture brief's Section 10: FIX-CHEF-INTRADAY-MARKER-KEY-UTC-HOUR-BASIS-MIGRATION. Phase 1 of THIS row ships VN_HOUR verbatim per brief Section 4.1 — unchanged, correct under NFR-3, and the migration row inherits the residual EC-2 hazard.",
      amendment_3_FR1_WINDOWKEY_MIDNIGHT_STRADDLE: "BINDING CORRECTION to brief Section 2, fallback branch 2 (the ACTIVE day-one path, per the brief's own Section 1). As written, WINDOW_KEY = <date portion of live_mcp_fetched_at> + 'T' + CRON_HOUR + '00Z' unconditionally pairs the RUN's UTC calendar date with the SLOT's cron hour. That re-introduces this row's own collision class at the UTC day boundary for any fire that is not same-UTC-day as its own nominal window. Two reachable cases, both live: (a) bctc-analyst-slot-4's cron is '0 0 * * *' = exactly 00:00Z — a backstop/catch-up fire a few minutes EARLY (23:5xZ) keys to the PREVIOUS day's slot-4 window and clobbers a 24h-old file; (b) a slot-3 ('0 21 * * *') run delayed past midnight, or an ordinary operator re-run of slot-3 the following morning, keys to a FUTURE window (D+1 21:00Z) that the real D+1 fire will then collide with. Neither is exotic: FIX-GUARANTEED-SLOT-FIRER-FANOUT-TRUNCATION documents live off-nominal re-fires, and EC-1 manual re-runs are explicitly in scope. FIX (deterministic, pure, no extra I/O, does not change the function's signature): branch 2 must select the occurrence of CRON_HOUR:00Z NEAREST to live_mcp_fetched_at — evaluate the candidate set {yesterday, today, tomorrow} at CRON_HOUR:00Z and take min |delta| — rather than unconditionally concatenating today's UTC date. 'Nearest' (not 'most recent at-or-before') is required because it is the only rule correct for BOTH the early-fire and late-fire directions. Add to the brief's own Section 8 test strategy a 4th unit case: slot-4 with live_mcp_fetched_at = D at 23:57Z must resolve to (D+1)T0000Z, and slot-3 with live_mcp_fetched_at = (D+1) at 08:00Z must resolve to (D)T2100Z.",
      binding_on: "pm decomposition and the eventual developer handoff. Amendments 1 and 3 are acceptance-bearing: amendment 1 removes FR-4 from scope (no tnb files touched), amendment 3 adds a required branch-2 behaviour plus 2 unit cases to FR-1. Amendment 2 is discharged by this same write (row minted below).",
      verified_at_source_this_tick: "board rows (a)/(b)/(c) of amendment 1 read live from .task_board; signal_queue row dev-20260806T172101-qanb read live; cowork-schedule.json slot crons read live (bctc slots 1-4 = 15/18/21/0 UTC, confirming the 00:00Z boundary case in amendment 3); pre-commit _check_notebook_immutability read at scripts/git-hooks/pre-commit:310-382 (warn-mode, fleet-scoped, exempts only po.md/market-watcher.md/orch-sentinel.md — an authorized whole-section DROP is NOT flagged, which is why that guard alone is not a sufficient monitor for FR-4 and the fold onto the guard row is the right answer)."
    },
    updated_by: "po (architect-brief adjudication)"
  };

.task_board.in_progress |= map(
  if .id == "FIX-COWORK-SIGNAL-FILENAME-CYCLEID-KEYING" then amend else . end
)
| .head = (.head + {
    status: "in_progress",
    active_task_id: "FIX-COWORK-SIGNAL-FILENAME-CYCLEID-KEYING",
    next_agent: "pm",
    next_action: "architect brief SIGNED OFF by po 2026-08-07T05:45Z (po_goahead_20260807T054500). pm to decompose docs/architecture-briefs/2026-08-07-cowork-signal-filename-cycleid-keying.md into implementation tasks, carrying ALL THREE binding amendments in the row's po_architect_signoff_20260807T0545 field: (1) FR-4/tran-ngoc-bau DESCOPED — folded onto GUARD-NOTEBOOK-CONCURRENT-EDIT-COLLISION-DATA-LOSS, touch no tnb files; (2) EC-2 Phase 2 split out to FIX-CHEF-INTRADAY-MARKER-KEY-UTC-HOUR-BASIS-MIGRATION (minted BLOCKED this tick) — Phase 1 ships VN_HOUR verbatim; (3) FR-1 fallback branch 2 must snap to the NEAREST CRON_HOUR occurrence, not today's UTC date + cron hour, plus 2 new unit cases. supervised/plan_only PRESERVED — do not clear, no code ships without returning to po.",
    updated_at: "2026-08-07T05:45:00Z",
    updated_by: "po (architect-brief adjudication)"
  })
