# PO triage 2026-07-29T11:26Z — rag-service acknowledged-degraded ACK scope mismatch
# + carried cowork signals + sweep-guard priority disposition.
#
# Single atomic pass. All mutations idempotent (mint = id-guard across ALL lanes;
# in-place annotations = marker-key guard; priority bump = value guard).
# Conservation: backlog += 2 (two mints), every other lane LENGTH byte-stable.
#
# Usage:
#   NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
#   jq --arg now "$NOW" -f scripts/po-triage-20260729T1126-rag-ack-scope-mismatch.jq \
#     docs/data/orch/orch-state.json | bash scripts/orch-apply.sh

def all_ids:
  [ .task_board | to_entries[] | select(.value|type=="array") | .value[] | .id? // empty ];

def has_id($id): (all_ids | index($id)) != null;

def annotate($lane; $id; $key; $val):
  .task_board[$lane] |= map(
    if (.id? // "") == $id and (has($key) | not)
    then . + { ($key): $val, "updated_at": $now, "updated_by": "po/triage-20260729T1126" }
    else . end
  );

. as $root
| .

# ─────────────────────────────────────────────────────────────────────────────
# M1 — MINT: the ACK ledger's two safety guarantees are asymmetric. Guarantee (1)
# mixed-case-never-suppresses IS implemented. Guarantee (2) the STALENESS RULE is
# implemented by NOTHING: _check_mem_creep reads only `.acked_memory[].container`.
# Plus the deferred absolute-headroom predicate, whose trigger condition has now
# been met.
# ─────────────────────────────────────────────────────────────────────────────
| if has_id("FIX-AUDITOR-MEMACK-HEADROOM-FLOOR-AND-DEAD-TRACKEDBY") then . else
  .task_board.backlog += [{
    "id": "FIX-AUDITOR-MEMACK-HEADROOM-FLOOR-AND-DEAD-TRACKEDBY",
    "type": "FIX",
    "status": "BACKLOG",
    "priority": "P1",
    "size": "S",
    "zone": "cross-service/",
    "owner": "developer",
    "next_agent": "developer",
    "supervised": false,
    "plan_only": false,
    "sprint": "INFRA-AUDIT",
    "created_at": $now,
    "created_by": "po/triage-20260729T1126-rag-ack-scope-mismatch",
    "title": "auditor-tier1-probe _check_mem_creep memory-ACK is all-or-nothing and its STALENESS RULE is enforced by nothing — acked_memory[].tracked_by is never read, so an ACK cannot expire and cannot be narrowed; add an absolute-headroom floor that the ACK may not swallow",
    "root_cause": "TWO defects in the same 6-line ACK path, both MEASURED by PO 2026-07-29T11:20-11:26Z by reading scripts/agents-flow/auditor-tier1-probe.sh. (1) DEAD FIELD: :275 is the ONLY read of the ledger and it is `jq -r '.acked_memory[]?.container // empty'`. `tracked_by` is extracted by nothing, compared against nothing, and never resolved against task_board. The ledger _comment and the probe comment block :263-264 both assert a STALENESS RULE ('remove the entry once its tracked_by row reaches DONE_VERIFIED') that is pure prose — no code reads it, no cron checks it, no test covers it. The suppression therefore persists until a human/agent happens to hand-edit the JSON. This is the reader-writes-its-own-trigger / veto-in-a-comment class: the guarantee that makes the ACK safe to ship is documented and not executed. (2) ALL-OR-NOTHING PREDICATE: :302-307 is a single `pct >= WARN_PCT` test, so an ACK'd container is suppressed at 85.01% and at 99.99% identically. There is no expressible middle state — the operator's only two options are 'suppress everything' or 'remove the entry and re-churn the auditor ~48x/day', which is the exact churn FIX-AUDITOR-TIER1-PROBE-ACKED-LAUNCHD-DEATH-SUPPRESSION was minted to kill. LIVE CONSEQUENCE 2026-07-29T11:08-11:26Z: rag-service sat at 97.11% of its 768 MiB cap = 22.2 MiB absolute headroom, and Tier-1 at the 11:00Z tick returned HEALTHY / ALL_GREEN / 0 signals / 0 dashboard rows.",
    "trigger_precondition_met": "NOT a new idea — this is the follow-on the parent row PRE-AUTHORIZED and deferred. FIX-AUDITOR-TIER1-A30-MEM-SINGLE-CONTAINER-SCOPE.note says verbatim: 'OUT OF SCOPE (do NOT fold in): an absolute-headroom secondary predicate. 11.9MiB free on a 768m cap is thin in absolute terms and a pure percentage genuinely is not comparable across a 512m and a 3g cap, but adding a second predicate in the same change would confound the FP evidence for the first; mint it separately later IF THE LOOP PROVES THE PERCENTAGE VIEW INSUFFICIENT.' The loop has now proven it insufficient: the percentage view cannot distinguish rag-service's acknowledged 94-98% set-point from a NEW excursion toward the ceiling, because both are 'one number >= 85'. Minting now satisfies the parent's own stated condition; it does not re-open the parent's rejected options (per-container threshold overrides and moving WARN_PCT globally stay REJECTED).",
    "fix_spec": "(a) HEADROOM FLOOR — add a SECOND predicate computed from the values docker stats already returns: absolute free bytes = cap - usage. If a container is memory-ACK'd but its absolute headroom is below a floor (propose MEM_FLOOR_MIB, default 32, single global constant — NOT per-container), the ACK does NOT suppress: it is a NEW signature and the verdict FAILS naming the container, its percentage AND its absolute headroom. Above the floor the ACK suppresses exactly as today. This makes 'acked at 94-98% is fine, crossing into <32 MiB free is not' expressible, which is precisely what the ledger cannot say today. (b) TRACKED_BY MUST BE LIVE — the probe must READ acked_memory[].tracked_by and resolve it against docs/data/orch/orch-state.json. An entry whose tracked_by is absent from every task_board lane, or whose status is DONE_VERIFIED, MUST NOT suppress; it must be reported as a STALE ACK and fail the check so the ledger self-expires as its own comment already promises. Fail-loud on an unreadable orch-state (do NOT adopt `2>/dev/null || true` — same idiom UC-CRITIC-HOOKS-ENFORCEMENT flags). (c) Apply (b) to the `acked[]` launchd arm too — identical dead-field defect, identical prose promise, three entries currently riding on it.",
    "acceptance": [
      "AC1: rag-service ACK'd, forced to 97% with >= MEM_FLOOR_MIB absolute headroom -> ALL_GREEN, named on the acknowledged-degraded line (today's behaviour preserved; no new churn).",
      "AC2: rag-service ACK'd, forced BELOW MEM_FLOOR_MIB absolute headroom -> verdict FAILURE, detail names the container with BOTH its percentage and its MiB-free. This is the case the current code cannot express and it is the whole point of the row.",
      "AC3: an acked_memory entry whose tracked_by resolves to DONE_VERIFIED -> verdict FAILURE with a STALE-ACK detail, not silent suppression. Same for a tracked_by that matches no row in any lane.",
      "AC4: the mixed-case invariant is UNCHANGED — an unacknowledged breach alongside acked ones still FAILS and names the unacked container (regression-guard the existing T41).",
      "AC5: uncapped containers (HostConfig.Memory == 0, today mcp-gateway) still skipped — absolute headroom is undefined for them, do NOT compute it from host memory.",
      "AC6: evidence is a RAW captured probe run (verdict line + detail line + the docker inspect/stats snapshot it was evaluated against, `date -u` timestamped), not prose. Same bar the parent row set."
    ],
    "files_hint": "scripts/agents-flow/auditor-tier1-probe.sh (_check_mem_creep :265-320, _mem_container_acked :326-336, ledger read :275, launchd arm :340-430); scripts/agents-flow/auditor-tier1-probe.test.sh (extend T40-T43 + the launchd ack tests); docs/data/auditor-launchd-ack.json (schema gains nothing new — tracked_by ALREADY exists on every entry, it is simply never read).",
    "prior_art_checked": "PO full-text jq over all 12 task_board lanes 2026-07-29T11:22Z for headroom|acked_memory|auditor-launchd-ack|STALENESS RULE. 6 rows inspected, NONE covers this: FIX-AUDITOR-TIER1-A30-MEM-SINGLE-CONTAINER-SCOPE (REVIEW — shipped the multi-container loop + the ledger itself, and explicitly deferred THIS predicate), FIX-AUDITOR-TIER1-PROBE-ACKED-LAUNCHD-DEATH-SUPPRESSION (REVIEW — shipped the launchd arm, carries the same dead tracked_by), FIX-AUDITOR-T1-PREGATE-MEMCREEP-SINGLE-POINT-SAMPLE (BACKLOG P2 — sampling FREQUENCY, N>=2 samples; orthogonal, a second sample of the same all-or-nothing predicate still cannot see this), FIX-AUDITOR-A30-VMHWM-VETO-TAUTOLOGY-FALSE-NEGATIVE (BACKLOG P1 — mcp-server VmHWM veto, different check), FIX-PDFX-PARENT-PROCESS-MEMORY-BURST-HEADROOM (BACKLOG P1 — pdf-extractor's own memory, not the detector), FIX-PRESSURE-HOST-HEADROOM-WRONG-MACHINE-WRONG-QUANTITY (REVIEW P1 — pressure-state emit field, different plane entirely).",
    "does_not_cover": "This row fixes the DETECTOR's blindness. It does NOT reduce rag-service's memory by one byte — that is FU-RAG-DEPLOY-MEMORY (resident set / cap trade, user-gated infra) and FIX-RAG-SERVICE-CLEAN-EXIT-RESTART-LOOP (the compaction counter defect). Do not fold either in.",
    "sequencing_note": "Coordinate with FIX-AUDITOR-T1-PREGATE-MEMCREEP-SINGLE-POINT-SAMPLE — both edit _check_mem_creep. Land this one first (predicate shape) then the sampling change, or land them together; do not let two agents rewrite the same function in parallel."
  }]
  end

# ─────────────────────────────────────────────────────────────────────────────
# M2 — MINT: refine_bctc_md diacritic collapse. 2nd occurrence, different ticker,
# different OCR run => systemic. Standing rule: recurring 2+ => block.
# ─────────────────────────────────────────────────────────────────────────────
| if has_id("FIX-BCTC-REFINE-DIACRITIC-COLLAPSE-A-BREVE-ACUTE") then . else
  .task_board.backlog += [{
    "id": "FIX-BCTC-REFINE-DIACRITIC-COLLAPSE-A-BREVE-ACUTE",
    "type": "FIX",
    "status": "BACKLOG",
    "priority": "P1",
    "size": "M",
    "zone": "multi",
    "owner": "architect",
    "next_agent": "architect",
    "supervised": false,
    "plan_only": false,
    "recurring_bug_count": 2,
    "sprint": "BCTC-DATA-QUALITY",
    "created_at": $now,
    "created_by": "po/triage-20260729T1126-rag-ack-scope-mismatch",
    "title": "BCTC refine pipeline collapses Vietnamese 'ắ' to bare 'ă' in label text ('ngắn hạn' -> 'ngăn hạn') across unrelated reports — 2 occurrences, 2 tickers, 2 OCR runs; corrupted units carry confidence 0.45-0.75 (mostly ABOVE the 0.50 ESC-5 floor) and no flag names the corruption",
    "evidence": "OCCURRENCE 1 — cowork-team 09:12Z tick, REE_2025_Q4.pdf, docs/signals/cowork-team-2026-07-29T0912Z-refine-bctc-diacritic-corruption.json. OCCURRENCE 2 — cowork-team 11:00Z tick, slot refine-bctc-slot-3, DPM_2026_Q1.pdf (report_id 3e2a26d9-525a-4dba-8ebe-fcaecc0cb28e, 47 pages), raw-verified via get_bctc_refined, docs/signals/cowork-team-2026-07-29T1110Z-refine-bctc-diacritic-corruption-2nd-report.json. Corrupted samples with confidence: unit-0024 0.50 'Phai thu ngan han khac' (a-breve, not a-breve-acute); unit-0030 0.70 'Chi phi ngan han'; unit-0031 0.75 'A. Ngan han'; unit-0032 0.60 'Vay ngan han co moi lien hong ngan hang lon nhat' (second-order corruption of 'quan he'); unit-0033 0.55 'Phai tra nguoi ban ngan han'. Units 0000-0022 of the SAME report were refined 2026-07-25/07-28 and units 0023-0034 on 2026-07-29 — the defect spans refine dates as well as reports.",
    "why_this_is_a_row": "Two occurrences across two different tickers, two different source PDFs and two different OCR runs rules out a single-document artifact. Standing recurring-bug rule (2+ => block). Severity was escalated MED->HIGH by the reporting dispatcher on exactly that basis.",
    "mandated_first_step_do_not_skip": "LOCALISE BEFORE FIXING — this is cheap and it decides the zone. For the named unit_ids on report_id 3e2a26d9-525a-4dba-8ebe-fcaecc0cb28e, read the STORED OCR text plane (get_bctc_page_text for the source page) and compare it byte-for-byte against the REFINED output plane (get_bctc_refined). Exactly one of two things is true and the evidence distinguishes them: (A) the OCR text ALREADY says 'ngan han' -> root cause is upstream in apps/pdf-extractor (tesseract lang pack / psm / preprocessing), the refine step is faithfully copying corrupt input, and this row re-zones to apps/pdf-extractor; or (B) the OCR text says 'ngan han' correctly and the refined output does not -> root cause is a character-normalisation/encoding step in the refine path (NFC/NFD normalisation, a lossy transliteration, or a model transcription), and this row re-zones to apps/mcp-server. DO NOT write a substitution table or a post-hoc 'ngan han'->'ngan han' repair before this comparison — a repair applied on the wrong side of the boundary hides the real defect and will not generalise past this one bigram.",
    "acceptance": [
      "AC1: the OCR-plane vs refine-plane comparison above is EXECUTED and its result recorded verbatim in the task report, with the winning branch (A or B) named. This is the deliverable even if the fix itself lands in a follow-on row.",
      "AC2: the two known-corrupt reports (REE_2025_Q4, DPM_2026_Q1) re-render the affected labels correctly after the fix, verified through get_bctc_refined, not from source prose.",
      "AC3: NO blanket find/replace repair table ships as the primary fix. If a backfill repair of already-stored corrupt rows is needed it is a SEPARATE, explicitly-scoped migration justified against the localisation result.",
      "AC4: a detector exists — the refine step flags label text containing a diacritic-collapse signature so a future occurrence does not depend on a human reading a cowork tick. Today's flags[] (OCR_quality_variable/critical, image_unavailable, table_structure_complex) are generic and did NOT fire on any corrupted unit.",
      "AC5: confirm/refute the ESC-5 interaction — corrupted units scored 0.45-0.75, mostly ABOVE the 0.50 auto-escalation floor, so confidence scoring is blind to this corruption class. Record whether that is by design."
    ],
    "not_established": "NOT MEASURED, do not treat as fact: (a) that numeric values are unaffected — both reports' numerics 'appear structurally intact' per the reporter, which is an eyeball not a reconciliation; if branch (A) wins, digit-level OCR error is in-scope to re-check. (b) that ONLY the 'a-breve-acute' codepoint is affected — two samples of one bigram is not a characterised substitution class. (c) 'mối liên hẻng' vs 'quan hệ' is a whole-token divergence, not a diacritic collapse; it may be a DIFFERENT defect riding along and must not be assumed to share a root cause.",
    "distinct_from": "NOT CLEAN-CHEF-SYNTHESIS-TEXT-CORRUPTION (chef synthesis causal_chains, French/nonsense tokens, explicitly logged as one-off, different producer and different plane). NOT FIX-BCTC-REPARSE-BATCH-CORRUPTION (numeric/field corruption). PO checked all 12 lanes 2026-07-29T11:24Z for diacritic|ngan-han — zero prior art."
  }]
  end

# ─────────────────────────────────────────────────────────────────────────────
# M3 — LAYER2 P1 -> P0. It is the SOLE remaining dependency of a P0 parent, and
# the guard it unblocks is WARN-only until it lands.
# ─────────────────────────────────────────────────────────────────────────────
| .task_board.backlog |= map(
    if (.id? // "") == "FIX-COMMIT-PATH-PEER-INDEX-SWEEP-GUARD-LAYER2"
       and (has("po_priority_20260729T1126") | not)
    then . + {
      "priority": "P0",
      "po_priority_20260729T1126": "PRIORITY P1 -> P0 (PO decision 2026-07-29T11:26Z). THREE reasons, all measured. (1) CRITICAL PATH: FIX-COMMIT-PATH-PEER-INDEX-SWEEP-GUARD (P0, BLOCKED, recurring_bug_count=4) states its UNBLOCK CONDITION verbatim as 'LAYER2 reaches DONE, then PO closes this parent'. Its two sibling arms are finished (..-HOOK DONE_VERIFIED, ..-SKILLS DONE). LAYER2 is now the ONLY thing standing between a 4x-recurring P0 and closeout, so holding it at P1 holds a P0 open by proxy. (2) THE SHIPPED GUARD IS INERT UNTIL IT LANDS: Layer 0 ships WARN-by-default deliberately, and can only escalate to GIT_SWEEP_GUARD_MODE=reject once the remaining call sites carry explicit pathspecs. Until LAYER2 lands the fleet gets warnings and zero enforcement — MEASURED 2026-07-29: 28 commit-sweep-guard signals fired in ONE day across 8 distinct notebooks (system-auditor 4, main 4, architect 3, developer 2, dev-mcp-server 2, dev-stock-price 1, dev-pdf-extractor 1, agent-father 1). A detector firing 28 times a day into an actuator that cannot act is the detector-right/actuator-blind shape. (3) SCOPE CORRECTION — this row's own title says '4 remaining bare git-commit sites'. The 07-29 evidence contradicts that count: 8 distinct agent commit paths produced sweeps in one day, and at least one (system-auditor, commit dbbd8a0fa 10:35:52Z) BYPASSED a mandated pathspec actuator that already exists — scripts/auditor-notebook-commit.sh:161 `git add -- \"${PATHS[@]}\"` / :202 `git commit -m \"$COMMIT_MSG\" -- \"${PATHS[@]}\"`, which docs/agents/system-auditor/flow/main.md:810-812 already requires. So the remaining work is NOT only 'edit 4 call sites': it is 'make the existing pathspec actuator the only reachable commit path for each agent that has one'. Re-scope before implementing; treat the 4-site count as a floor, not the spec. DO NOT bump FIX-AUDITOR-COMMIT-NONEXPLICIT-PATHSPEC instead — see that row's po_disposition_20260729T1126."
    }
    else . end
  )

# ─────────────────────────────────────────────────────────────────────────────
# M4..M11 — in-place dispositions / corroborations. No lane moves.
# ─────────────────────────────────────────────────────────────────────────────
| annotate("backlog"; "FIX-AUDITOR-COMMIT-NONEXPLICIT-PATHSPEC"; "po_disposition_20260729T1126";
    "PRIORITY DISPOSITION: NO BUMP. DECIDED, do not re-litigate next tick. The router carried this row up for a priority decision on the strength of 28 sweep-guard signals across 8 notebooks on 2026-07-29 — the signals are real, but this is the wrong row to raise. This row was SUPERSEDED by FIX-COMMIT-PATH-PEER-INDEX-SWEEP-GUARD on 2026-07-21T16:35:12Z and its own po_supersede note says 'DO NOT WORK THIS ROW — work the successor'. Raising a superseded row's priority makes it competitive for dispatch again and re-creates the duplicate the supersede was minted to prevent; it would also re-instate this row's REFUTED scope (one agent's flow doc, disposition DEFERRED-OUT-OF-DEV-SCOPE) against a defect that has since fired from the router, cowork-team, PO itself and 8 notebooks in a single day. The 28-signal evidence has instead been recorded where it changes an outcome: FIX-COMMIT-PATH-PEER-INDEX-SWEEP-GUARD-LAYER2 raised P1 -> P0 this tick (see its po_priority_20260729T1126), because LAYER2 is the sole remaining dependency of the P0 parent and the shipped Layer-0 guard stays WARN-only until LAYER2 lands. This row's correct end state is closeout-by-supersession when the parent closes — priority stays 'medium' and it stays non-dispatchable.")

| annotate("ready"; "FIX-RAG-SERVICE-CLEAN-EXIT-RESTART-LOOP"; "po_index_provenance_20260729T1126";
    "POST /index PROVENANCE — MEASURED, recorded so the next auditor/router does NOT re-litigate this as a suspected agent-improvised write. QUESTION ASKED: a router tick at 11:08-11:15Z observed 199 POST /index in one container lifetime, most from 192.168.65.1, and flagged it as a possible recurrence of feedback_ops_readonly_diagnostic_wrote_to_live_index_and_burned_the_headroom (2026-07-25, an ops agent POSTing /index on a read-only diagnostic). ANSWER: NO, it is not that. Method — `docker logs -t --since 2026-07-28T11:00:00Z`, source-IP bucketed hourly. RESULT: POST /index from 192.168.65.1 is a CONTINUOUS 24h+ stream, present in essentially every hour including overnight, at 51-258 calls/hour (e.g. 07-28T14=247, 07-28T17=258, 07-29T02=149, 07-29T04=136, 07-29T06=239, 07-29T10=216). An improvised diagnostic produces a bounded burst; this is diurnal-invariant steady-state traffic. It is corroborated on a second plane: the rag corpus grows ~103 rows/h (PO measurement on RAG-FTS-BUILD-MEMORY-BOUND, 10183 rows @07-28T19:00Z -> 11243 @07-29T05:20Z), the same order as the observed write rate, which only holds if these writes are real ingestion. Every call returns 200 OK. IP DECODING (this is the part that misleads readers, hence recording it): 192.168.65.1 is the Docker Desktop vpnkit forwarder — it is the source address of ANY connection that arrives via the PUBLISHED host port 5002, not evidence of a hand-run command. 172.18.0.12 is the mcp-server container on the compose network, which is correctly wired (RAG_SERVICE_URL=http://rag-service:5002) and accounts for the small in-network share (8/199 this lifetime). The host-port share is consistent with a caller falling back to the `http://localhost:5002` default in apps/mcp-server/src/infrastructure/rag/ragHttpClient.ts:18 / clients.ts:24 when RAG_SERVICE_URL is unset. NOT ESTABLISHED — I did NOT identify the specific host-side process; cloudflared runs on this host with a dashboard-managed token whose routes are not readable locally, so a tunnel-borne caller cannot be excluded by local inspection. The provenance question 'which process' is OPEN; the question 'is this an agent burning headroom' is CLOSED-NO on the 24h evidence. MEMORY IMPACT — MEASURED, and it refutes a leak: 749.9 MiB after exactly ONE embed at 10:25Z vs 745.8 MiB after 199 /index calls at 11:19Z. Memory went DOWN 4.1 MiB across ~199 writes. The /index path is NOT accumulating; the ~700 MiB is the sentence-transformers singleton this row already documents, and the residual ceiling problem belongs to FU-RAG-DEPLOY-MEMORY exactly as this row's AC6 already says.")

| annotate("review"; "RAG-FTS-BUILD-MEMORY-BOUND"; "po_ack_scope_correction_20260729T1126";
    "ACK-LEDGER SCOPE CORRECTION — this row is NO LONGER the tracked_by for the rag-service memory ACK. It never should have been, and the falsification was already sitting inside this row. FINDING (router-raised 2026-07-29T11:08Z, PO-confirmed 11:20-11:26Z): docs/data/auditor-launchd-ack.json .acked_memory[0] named THIS row as what 'root-causes' rag-service's 94-98% steady-state, and Tier-1 has been suppressing the breach on that basis since 2026-07-25T15:48:56Z. This row bounds _build_fts_index(); the live memory is the embedder's lazy model singleton — cold RSS 50.7 MiB -> 749.9 MiB after ONE embed, with ZERO FTS activity (PO measurement 2026-07-29T10:20-10:28Z, recorded on FIX-RAG-SERVICE-CLEAN-EXIT-RESTART-LOOP). Shipping this row would not move the number. THE FALSIFICATION PREDATES THE ACK BY TEN DAYS: this row's own qa_result.idle_baseline_flag, written 2026-07-15T16:01:23Z, reads 'rag-service idle mem already ~92% of 768m bound with ZERO FTS activity (tight margin, pre-existing)'. The ledger was seeded 2026-07-25 asserting the opposite, against a row that already contained the disproof. SECOND AND SHARPER PROBLEM — SELF-EXPIRY WAS UNREACHABLE: the ACK's safety argument is its STALENESS RULE ('remove once tracked_by reaches DONE_VERIFIED'). This row is blocked_on rag-corpus-repopulation-to-representative-scale with po_timegate_next_recheck_after 2026-08-12 and a PO-projected testable date ~2026-08-16. Binding the ACK here guaranteed >=18 days of suppression BY CONSTRUCTION on the fleet's only memory detector for this container. ACTION TAKEN: ledger tracked_by re-pointed to FU-RAG-DEPLOY-MEMORY (the row that actually owns the resident-set/cap trade and whose DONE_VERIFIED would genuinely mean rag-service no longer sits at 97% of its cap), with FIX-RAG-SERVICE-CLEAN-EXIT-RESTART-LOOP recorded as the secondary. THIS ROW'S OWN DISPOSITION IS UNCHANGED — still REVIEW, still legitimately TIME-GATED, done_verified still WITHHELD, next re-check still ~2026-08-12. Nothing here reopens it.")

| annotate("backlog"; "FU-RAG-DEPLOY-MEMORY"; "po_ack_retarget_20260729T1126";
    "THIS ROW IS NOW THE tracked_by FOR THE rag-service MEMORY ACK (docs/data/auditor-launchd-ack.json .acked_memory[0]), re-pointed from RAG-FTS-BUILD-MEMORY-BOUND by PO 2026-07-29T11:26Z. Rationale: the ACK suppresses a MEMORY breach, so its tracked_by must be the row whose completion would actually clear that breach. RAG-FTS-BUILD-MEMORY-BOUND bounds an FTS rebuild that is not running and is not the driver (see its po_ack_scope_correction_20260729T1126); FIX-RAG-SERVICE-CLEAN-EXIT-RESTART-LOOP explicitly disclaims closing it (its AC6: 'Does NOT claim to close the restart loop... the residual belongs to FU-RAG-DEPLOY-MEMORY'). That leaves this row. CONSEQUENCE YOU SHOULD KNOW ABOUT, not a new obligation: while this row is open, Tier-1's memory check does not fire on rag-service. TWO THINGS DO NOT CHANGE. (1) No status/priority change is made here — this is an INFRA row owning a user-gated 16GB host trade and PO is not self-approving a cap change. (2) The re-point is DOCUMENTARY ONLY at the code level: scripts/agents-flow/auditor-tier1-probe.sh:275 reads ONLY `.acked_memory[].container` and never reads tracked_by, so no probe behaviour changes today in either direction. Making tracked_by load-bearing is FIX-AUDITOR-MEMACK-HEADROOM-FLOOR-AND-DEAD-TRACKEDBY (minted this tick, P1). FRESH MEASUREMENT for the resident-set trade, 2026-07-29T11:19Z: 745.8 MiB / 768 MiB = 97.11%, 22.2 MiB absolute headroom, CPU 0.13% at rest, RestartCount 22, StartedAt 2026-07-29T10:12:01Z, OOMKilled=false ExitCode=0. Consistent with the 749.9 MiB @10:25Z already on this row (memory is flat-to-slightly-down under ~199 index writes, i.e. a fixed baseline, not a leak).")

| annotate("backlog"; "FIX-CHEF-MIDFLOW-BAIL-DETERMINISM"; "po_corroboration_20260729T0722";
    "CORROBORATION, NOT A NEW ROW — routed here by PO 2026-07-29T11:26Z from an unrouted cowork signal. Source: docs/signals/cowork-signal-2026-07-29T0722Z-chef-intraday-tokenbudget-marker-leak.json (tick 2026-07-29T07:15:00Z, slot chef-intraday, agent a096fc86e7d45cc64, window 14). NEW TRIGGER for this row's defect: the mid-flow bail was caused by RESOURCE EXHAUSTION, not by the 'needs scope clarification' logic branch this row was minted against. Sequence: Step 0.5 claimed published:chef-intraday:2026-07-29:14 (ttl 3600s) -> Step 0 GATHER completed -> Step 1 CLUSTER found 5 qualifying convergence clusters -> the convergence rule QUALIFIED, so publication was REQUIRED by flow spec -> agent self-reported 'token budget reached during Layer analysis phase' and returned without executing Steps 2-8. Raw-verified no publish: get_market_message_digest(hours_back=3) newest mcp-user ids [1056,1061,1062,1063], none attributable to the window. The dispatcher correctly released the leaked marker per feedback_chef_leaks_published_marker_on_silent_exit (task_release released:1) — the leak half was handled at the tick; only the determinism half is open here. WHY IT BELONGS ON THIS ROW AND NOT A NEW ONE: the failure is 'agent exits mid-flow with a qualifying result and no deterministic degraded output', which is exactly this row's scope; the trigger differs, the defect does not. WIDEN THE SPEC: an anti-bail/degrade path that only catches logic branches will not catch this — the budget wall can land at ANY step, so the degraded-output contract has to be reachable from a partial state, not just from a named branch. UNRESOLVED RISK carried from the signal, worth an explicit answer: if chef-intraday re-spawns on later ticks against a similar convergence set it may hit the same wall repeatedly and silently lose the window every time. Marker-lifecycle half stays with UC-CCA-P3 (P0) — not duplicated here.")

| annotate("backlog"; "FIX-COWORK-DISPATCH-ROUTER-INTENT-MUTEX-BYPASS"; "po_corroboration_20260729T0858";
    "CORROBORATION, NOT A NEW ROW — routed here by PO 2026-07-29T11:26Z from an unrouted cowork signal. Source: docs/signals/cowork-team-2026-07-29T0858Z-chef-eod-router-race-nearmiss.json. THIS IS THE FIRST TWO-SIDED CONCRETE EVIDENCE for this row's premise; every prior instance was inferred after the fact from a stray extra claim. Both sides captured: cowork-cron spawned chef-eod (agent a69593e83d6792247, dispatcher session a2161c5c-c4e1-4696-834e-d73fbbbbad81, last_fired 08:53:12Z) and got claimed:false on published:chef-eod:2026-07-29, exiting cleanly 'DONE: duplicate-publish blocked'; the marker was held by session b5fdaa7f-e239-42a0-942a-dd688e927ad9, claimed 08:53:45Z ttl 100800s, whose session-presence record reads owner_agent 'router', host 'main-server', started_at 08:51:00Z, current_task 'dispatch-init'. So a router-seat session reached chef.md Step 0.5 ~33s ahead of the cron spawn, ~2.5 min after that session started, via a path outside the cowork fire-election lock cron:cowork:<TICK> — precisely the shared-namespace gap this row names. OUTCOME: safe. get_unreviewed_market_messages confirms exactly ONE chef-eod dish for 2026-07-29 (id 1066, sent_at 08:55:13). IT WAS SAFE BY ORDERING LUCK, NOT BY CONTROL — had the cron spawn won the 33s it would have published and the router seat would then have been the loser; the marker is the only thing that arbitrated, and the marker is claimed AFTER the expensive work begins. COST EVEN ON THE GOOD PATH: the losing cowork spawn burned a full unified-agent run (58673 tokens, 9 tool calls, 76s) to reach a blocked exit. Consistent with feedback_router_intent_path_double_dispatches_cowork_slots and feedback_router_demand_dispatch_cowork_slot_double_publish. Related but NOT duplicated: FIX-ROUTER-COWORK-SLOT-DEMAND-DISPATCH-BLIND (P1, slot-tick blindness on the router side) and FIX-COWORK-FIRE-ELECTION-TICK-TOMBSTONE (P2). No new row minted.")

| annotate("review"; "FIX-PRESSURE-HOST-HEADROOM-WRONG-MACHINE-WRONG-QUANTITY"; "po_deploygap_20260729T0813";
    "DEPLOY GAP ON THIS ROW'S OWN FIX — routed here by PO 2026-07-29T11:26Z from docs/signals/cowork-signal-2026-07-29T0813Z-pressure-headroom-field-stale-container.json. NOT a new defect and NOT a re-open: the SOURCE carries this row's rename (apps/mcp-server/src/interface/mcp/tools/system/emitPressureStateTool.ts defines/writes container_vm_headroom_mb at ~:69, :393-394, :411) but the RUNNING mcp-server image does not — docs/data/pressure-state.json still emits the OLD key host_headroom_mb across 3 separate emit_pressure_state calls on 2026-07-29 (07:35:41Z, 07:50:37Z=5015, 08:13:08Z=4819). Classic stale-image drift, feedback_mcp_server_stale_image_mem_leak_rebuild_fixes. LIVE CONSUMER IMPACT: docs/agents/cowork-team/flow/spawn-fanout.md Step 5.1 reads PRESSURE_STATE.container_vm_headroom_mb; the key is absent from the live file so HEADROOM_MB resolves null, DEGRADED is forced true unconditionally, and MAX_PARALLEL has been pinned at max_parallel_degraded (2) instead of the adaptive default (4) since 2026-07-28 regardless of actual headroom. Not correctness-breaking — fan-out still completes, serialized into more batches with inter-batch waits — but it has been silently running below its designed ceiling and every tick with >2 due slots pays an extra batch-wait. WHAT THIS CHANGES FOR THIS ROW: its close-out gate must be satisfied against the DEPLOYED image, not the source. A qa verdict read from source here would be a false-green of exactly the kind this project keeps re-learning (feedback_verify_deploy_sha_benign_doc_drift). Add to the gate: assert the live docs/data/pressure-state.json emits container_vm_headroom_mb after a fresh emit_pressure_state call. NO REBUILD DISPATCHED — a single-service mcp-server rebuild is USER-GATED and PO is not authorising one; recording the gate, not the action. Do NOT down/up the stack (feedback_rebuild_recreate_destroys_peers).")

| annotate("review"; "FIX-DEVTEAM-BACKGROUND-SPAWN-LOCK-RELEASED-AT-SPAWN-NOT-COMPLETION"; "po_still_reproducing_20260729T1049";
    "STILL REPRODUCING WHILE IN REVIEW — routed here by PO 2026-07-29T11:26Z from signal_queue row dev-20260729T104938 (dev-team self-report, MED, 2026-07-29T10:49:38Z, payload_ref docs/agent-memory/notebooks/main.md). dev-team reports it violated its own LOCK-LIFETIME invariant (dev-team/flow/main.md:503) by releasing the sprint-task lock AT SPAWN on its last 3 dispatches, risking duplicate-spawn on a live in-flight task. That is this row's defect verbatim: the mutex released in a `finally` bound to a run_in_background=true spawn, so the lock frees within milliseconds while the work is still running. THE MATERIAL FACT FOR QA: this row is already in REVIEW awaiting sign-off, and the behaviour reproduced 3 times on 2026-07-29. Either the fix has not been applied to the live dispatch path, or it landed in the flow doc and the executing agent is not bound by it — the second shape is the one this project keeps hitting (documentation-as-enforcement, cf. FIX-COMMIT-PATH-PEER-INDEX-SWEEP-GUARD, 3 doc-level dispositions then 4 recurrences). qa MUST verify against an observed dispatch's actual claim/release ORDER, not against flow-doc prose asserting the correct order — reading the doc cannot distinguish the two hypotheses (feedback_known_failure_shape_pattern_matched_without_reading_call_order). NO NEW ROW MINTED: PO checked all lanes 2026-07-29T11:25Z for LOCK-LIFETIME|released at spawn|duplicate-spawn; this row and FIX-DEVTEAM-STEP0B-RESUME-SUPERVISED-HOLD-GATE are the only hits and the second is a different gate.")

# ─────────────────────────────────────────────────────────────────────────────
# M12 — ACK the two NEW po-addressed signal rows (NEW -> READ, not RESOLVED:
# the fixes have not shipped).
# ─────────────────────────────────────────────────────────────────────────────
| .signal_queue.rows |= map(
    if (.id? // "") == "dev-20260729T104938" and .status == "NEW"
    then . + { "status": "READ",
               "triage_note": "PO 2026-07-29T11:26Z — routed as corroboration onto FIX-DEVTEAM-BACKGROUND-SPAWN-LOCK-RELEASED-AT-SPAWN-NOT-COMPLETION (review, P1, next_agent=qa). No new row: same defect, and the fact that it reproduced 3x while the row sits in REVIEW is now a qa gate condition on that row (verify observed claim/release ORDER, not flow-doc prose). READ not RESOLVED — fix has not shipped." }
    elif (.id? // "") == "cow-20260729T111055Z" and .status == "NEW"
    then . + { "status": "READ",
               "triage_note": "PO 2026-07-29T11:26Z — MINTED FIX-BCTC-REFINE-DIACRITIC-COLLAPSE-A-BREVE-ACUTE (backlog, P1, zone=multi, next_agent=architect, recurring_bug_count=2). 2 occurrences across 2 tickers / 2 OCR runs => systemic, standing recurring-bug rule applies. Row mandates an OCR-plane vs refine-plane comparison BEFORE any fix, so the zone resolves to apps/pdf-extractor or apps/mcp-server on evidence rather than assumption; explicitly forbids shipping a substitution/repair table as the primary fix. Covers occurrence 1 (cow-20260729T091200Z, REE_2025_Q4) as well. READ not RESOLVED — fix has not shipped." }
    else . end
  )

| .task_board.last_triaged_at = $now
| .task_board.last_triaged_by = "po/triage-20260729T1126-rag-ack-scope-mismatch"
