# PO triage 2026-08-23T12:10Z — defect found by EXECUTING PO's own flow doc
# this tick, not by reading it. The documented Durable-inbox CLEAR block in
# docs/agents/po/flow/triage-signals.md fails under zsh and the failure is
# swallowed by its own trailing `|| true`.
def NOW: "2026-08-23T12:10:00Z";
def BY: "po/triage-20260823T1157Z";
.task_board.backlog += [{
  id: "FIX-PO-TRIAGE-INBOX-CLEAR-ECHO-PIPE-MANGLES-JSON-UNDER-ZSH-SILENT-NOOP",
  type: "FIX", status: "BACKLOG", priority: "P0", size: "S",
  zone: "docs/agents/po/flow/", owner: "agent-father", next_agent: "agent-father",
  title: "PO's documented durable-inbox CLEAR block uses `echo \"$json\" | jq`, which zsh's echo corrupts on any payload containing a \\n escape — the CLEAR then silently no-ops behind its own `|| true` and the inbox never drains",
  created_at: NOW, created_by: BY,
  dedup_key: "flow-actuator-defect:docs/agents/po/flow/triage-signals.md|durable-inbox-clear|echo-pipe",
  dedup_checked: "backlog+ready+in_progress+review+qa scanned for /TRIAGE-INBOX|INBOX-CLEAR|ZSH|ECHO/. No match — FIX-TRIAGE-INBOX-CLEAR-OWNERSHIP-PO-SELF-READ (the row that AUTHORED this block) is closed and concerned ownership, not the actuator's correctness. Minted.",
  files: ["docs/agents/po/flow/triage-signals.md"],
  desc: "FOUND BY EXECUTION, NOT BY REVIEW — this fired live on PO's 2026-08-23T11:57Z tick and cost a retry. docs/agents/po/flow/triage-signals.md § 'Durable-inbox CLEAR (executable ...)' prescribes verbatim:\n  pendingSignals=$(jq -c '.dev_team_idle_chain.pending_triage_inbox // []' docs/data/orch/orch-state.json)\n  consumed_ids=$(echo \"$pendingSignals\" | jq -c '[.[].envelope_id]')\n  consumed_ids_csv=$(echo \"$consumed_ids\" | jq -r 'join(\",\")')\n  jq --argjson ids \"$consumed_ids\" ... | ORCH_APPLY_DECLARED_INBOX_TRIAGED=\"$consumed_ids_csv\" bash scripts/orch-apply.sh || true\nThe agent shell on this host is /bin/zsh 5.9 (ZSH_VERSION=5.9, BASH_VERSION unset). zsh's `echo` builtin interprets backslash escapes BY DEFAULT (unlike bash's), so `echo \"$pendingSignals\"` rewrites every JSON-escaped \\n inside a payload string into a REAL newline, producing invalid JSON.\n\nMEASURED THIS TICK against the live 10-envelope inbox (fixture copy retained): `jq -c` on the file returns rc=0 and a 15234-char SINGLE line; `echo \"$pendingSignals\" | wc -l` returns 33 — the shell turned 1 line into 33. `echo \"$pendingSignals\" | jq -c '[.[].envelope_id]'` then exits 5 with 'Invalid string: control characters from U+0000 through U+001F must be escaped at line 17, column 98'. Minimal isolated repro: `V='{\"a\":\"x\\ny\"}'; echo \"$V\" | jq -c .` FAILS while `printf '%s' \"$V\" | jq -c .` SUCCEEDS.\n\nWHY IT IS SILENT — THIS IS THE REAL SEVERITY: with consumed_ids empty, `jq --argjson` aborts, the pipeline's jq emits nothing, orch-apply.sh prints 'ERROR: stdin produced empty candidate — aborting (no write)' and exits non-zero, and the block's trailing `|| true` swallows exactly that. A doc-faithful PO tick therefore reports the inbox CLEARED while the envelopes are all still there. That is the narrated-but-never-landed class this fleet has 4+ confirmed instances of, sitting inside the very step that is supposed to be PO's own durable actuator. It also fully explains a re-delivery/backlog-growth pattern that has previously been attributed to drain lag.\n\nWHY IT HAS NOT ALWAYS FIRED: it needs at least one payload containing a \\n escape. This tick, the flow_actuator_fix envelope (agents-architect -> agent-father) carried multi-line jq patch code in payload.proposed_patch, which is the first payload shape large enough to guarantee it. So the defect is INTERMITTENT BY INPUT, not by luck — richer payloads make it certain.",
  ac: ["AC-1 REGRESSION (must FAIL before, PASS after): replay the documented block verbatim against a fixture orch-state.json whose inbox contains one payload with a \\n escape, under zsh. Pre-fix it must leave the inbox UNCHANGED while the block exits 0 (that combination — no write, exit 0 — is the whole bug). Post-fix the inbox must be empty.", "AC-2 remove the `echo \"$var\" | jq` round-trip entirely: read the ids straight out of the file with `jq -c '[.dev_team_idle_chain.pending_triage_inbox[].envelope_id]' docs/data/orch/orch-state.json`. Never round-trip full payloads through a shell variable — they are attacker-shaped free text from arbitrary emitters. If any round-trip must remain, it uses `printf '%s'`, never `echo`.", "AC-3 DELETE the trailing `|| true` on the orch-apply pipe, or replace it with an explicit non-zero-exit handler that fails LOUD per docs/protocols/fail-loud-protocol.md. A CLEAR that did not land must never be reportable as success. This AC is independent of AC-2 and must not be dropped if AC-2 alone makes the current input pass.", "AC-4 the block gains a post-write self-verification re-reading the file (`jq '.dev_team_idle_chain.pending_triage_inbox|length'` == 0, or == the count of envelopes that arrived mid-tick), matching the AC-3 persistence-gate shape already in docs/agents/po/flow/main.md. RETURN may not assert 'inbox cleared' without it.", "AC-5 FLEETWIDE AUDIT, opt-IN allowlist (feedback_fleetwide_gate_validated_on_one_file_optout_allowlist): grep every docs/agents/**/flow/*.md and .claude/skills/**/SKILL.md for the `echo \"$...\" | jq` idiom and report the full hit list. The shell is zsh for every agent on this host, so any other flow doc using it has the same latent corruption. Fix or explicitly waive each hit; do not validate this on triage-signals.md alone."],
  baseline_pass: "under zsh: run the documented CLEAR block against a fixture whose inbox holds a payload containing a \\n escape; post-fix `jq '.dev_team_idle_chain.pending_triage_inbox|length'` == 0 AND the block exits non-zero if orch-apply.sh refused the write",
  related: ["FIX-SIGNAL-TYPE-ROUTING-GAP-cowork-fire", "FIX-QA-VC-LANEMOVE-PROSE-ONLY-NO-ORCHAPPLY-ACTUATOR"],
  status_note: "SAME FILE as the umbrella row FIX-SIGNAL-TYPE-ROUTING-GAP-cowork-fire (docs/agents/po/flow/triage-signals.md) and the same owner (agent-father) — dispatch both in ONE agent-father hop, they do not conflict (routing table vs the CLEAR block, different sections). PO worked around it this tick by reading ids directly from the file, so the 10 envelopes DID clear (verified inbox_len 10 -> 0, _updated_by=po); the doc, however, is still wrong and the next agent to follow it verbatim will silently fail again. Sibling in kind, not in cause: FIX-QA-VC-LANEMOVE-PROSE-ONLY-NO-ORCHAPPLY-ACTUATOR is prose-with-no-actuator; this one is an actuator that EXISTS, looks executable, and lies about its exit status — arguably worse, because a reviewer greps for the orch-apply.sh pipe, finds it, and moves on."
}]
