.task_board.review |= map(
  if .id == "FACTORY-DOMAIN-split-cascade-engine" then
    .next_agent = "po"
    | .qa_verify_at = "2026-07-09T10:22:00Z"
    | .qa_verify_by = "qa"
    | .qa_note = "Step 5 PASS. docker inspect vn-market-intelligence-mcp-mcp-server-1 myself: git_sha label f5b9b1f9f9bc88a7ddfbd43071a99a6949733f09 exact match ops's claim, state running/healthy -- independent re-derivation, not relayed. Live composite GET :4000/health = 200, all 9 services ok (mcp latency 3ms). mcp gateway interactive connector confirmed pending-approval this session (per dispatch note) -- used the established scripts/agents-flow/mcp-call.sh direct-HTTP bridge for every tool call instead (same mechanism dev-team-tick-preflight.sh already uses). run_impact_chain called live with newsText containing sector-rule trigger keywords (\"gói hỗ trợ\", \"quỹ bình ổn\") returned 24 real chain entries incl. 4 domain-level hits with exact unique title strings sourced from the split cascade/rules/sectorRules.ts file (\"Chính phủ can thiệp hỗ trợ thị trường — bullish reversal catalyst (CTCK hưởng lợi trực tiếp)\" / \"Gói hỗ trợ thị trường — thanh khoản hệ thống cải thiện, tích cực cho ngân hàng\" / \"Gói hỗ trợ — kỳ vọng dòng tiền chảy lại BĐS\" / \"Gói hỗ trợ — tâm lý tiêu dùng cải thiện, tích cực bán lẻ\") across securities/banking/real_estate/retail domains, plus a live \"[Macro: goldUSDPerOz>4000=4116.7 -> -0.06 securities]\" adjustment line proving cascade/macroAdjustments.ts is wired against a real live gold price, plus 19 correctly-attributed watchlist-stock action entries (BID/EIB/MBB/ACB/CTG/VPB/VRE/VIC/VHM/D2D/VCI/SSI/HCM/VDC/NVL/KBC/TCH/MWG/VCB) -- a genuine populated result, not an error/empty response. Second probe (war+gói kích thích combo text) reproduced the sectorRules.ts-documented policy-intervention-override (bullish stimulus rule wins over bearish \"chiến tranh\" keyword), exercising findKeyword/detectPolicyInterventionCombo in the split cascade/comboDetectors.ts. Spot-checked 2 unrelated peer tools for collateral regression from the rebuild: get_market_snapshot (real live VN-Index 1840.70/-0.70%, breadth 91 up/203 down/66 flat, HOSE turnover 14643 tỷ) and get_alerts (20 real live alerts incl. news_mention/volume_spike signals). Both healthy, zero regression, zero error/empty responses. DJ: sprint-SYSTEMIC-REMAKE-P1-qa.md STEP qa-S39."
  else . end
)
| if .head.active_task_id == "FACTORY-DOMAIN-split-cascade-engine" then
    .head.next_agent = "po"
    | .head.next_action = "PO Step 6 sign-off: FACTORY-DOMAIN-split-cascade-engine QA Step 5 PASS. Live run_impact_chain against the rebuilt container (git_sha f5b9b1f9f9bc88a7ddfbd43071a99a6949733f09, docker-inspect-confirmed) returned real sector-rule (cascade/rules/sectorRules.ts) + macro-adjustment (cascade/macroAdjustments.ts) + combo-detector (cascade/comboDetectors.ts) output -- buildCausalChain end-to-end confirmed live, not error/empty. 2 peer tools (get_market_snapshot, get_alerts) spot-checked healthy, zero collateral regression from the rebuild. Full detail: sprint-SYSTEMIC-REMAKE-P1-qa.md STEP qa-S39."
    | .head.updated_at = "2026-07-09T10:22:00Z"
    | .head.updated_by = "qa"
  else . end
