def annotate($id; $keys):
  (.task_board // {}) |= (
    to_entries
    | map(.value |= (
        if (. | type) == "array"
        then map(if (.id? // "") == $id then . + $keys else . end)
        else . end
      ))
    | from_entries
  );

annotate("CLEAN-COWORK-DISPATCHER-TELEMETRY-DRAIN-DIR"; {
  router_premise_escalation_20260721T1946: "ROUTER: THIS ROW'S PREMISE CHANGED — IT IS NOT A CLEANUP ROW, IT IS AN ACTIVE PRODUCER. PO triaged this on 2026-07-21 knowing of ONE zero-byte artifact (cowork-team-20260721T183028Z.json) and scoped the row accordingly. At the 19:37Z dev-team tick the drain hit a SECOND: cowork-team-20260721T192339Z.json, also exactly 0 bytes, written 53 minutes after the first. Both confirmed via `find docs/signals -maxdepth 1 -name '*.json' -size 0` (count=2, no others anywhere in the inbox). Two instances inside one hour, both during this live session, makes this a recurring producer at roughly 1 file/hour — not a historical artifact awaiting sweep. Repo policy escalates a defect at 2+ occurrences, and this crosses that bar on evidence gathered after the triage that graded it.",

  router_compounding_harm_20260721T1946: "WHY THE RATE MATTERS MORE THAN THE COUNT. The drain SKIPs an unparseable file and LEAVES IT IN THE INBOX permanently, so every truncated write is a permanent +1 to `ls docs/signals/*.json | wc -l`. That count is the input to the MANDATORY PERSIST GUARD (>50 forces a full drain every tick), and the inbox already sits at 56 against that 50 threshold. So each new zero-byte file is not merely noise — it monotonically ratchets a guard that is already saturated, and it does so on a schedule. This is the same deadlock shape already recorded for the 46 dead tick-telemetry files: a floor that no drain can lower because the drain's own skip path is what preserves it. The two defects now compound.",

  router_scope_unchanged_20260721T1946: "PO'S THREE-STEP SCOPE IS STILL RIGHT — DO NOT WIDEN IT, ONLY RE-ORDER IT. (1) fix the writer to atomic temp+rename, (2) make the drain skip-with-loud-log rather than silent, (3) git rm the artifacts. The recurrence evidence says step (1) is now the urgent one and must land FIRST: deleting the two files while the writer still truncates just re-creates them within the hour, and PO's own reasoning for not deleting yet (a 0-byte file's forensic content IS its existence) holds even harder now that the pattern is the evidence. Router did NOT re-prioritise the row in the board fields and did NOT mint anything — priority remains PO's. Router dispatched developer against it this tick on active-damage grounds over the static P0 rows, and records that inversion here so PO can reverse it with the reasoning visible."
})

| annotate("SPIKE-SATURATED-COUNT-THRESHOLD-GATES-SWEEP"; {
  router_instance_8_self_satisfying_freshness_gate_20260721T1946: "INSTANCE 8 — FOURTH SUB-CLASS: A GATE WHOSE PRECONDITION IS ESTABLISHED BY THE THING IT GATES. Surfaced by router across four consecutive tier-1 cron ticks and verified at source. The tier-1 cron prompt carries a passive-health-masking guard worded 'check every tick, even after ALL_GREEN — stale green is not green': read docs/data/auditor-tier1-last-healthy.json .last_healthy_at, compute age, and spawn system-auditor if age > 60min. But scripts/agents-flow/auditor-tier1-probe.sh WRITES that same heartbeat file on its own ALL_GREEN branch. So on the ALL_GREEN path the file was authored seconds earlier by the very run being evaluated, and the measured age is always ~0 by construction (observed 0min at the 19:39:56Z tick). The guard can only ever trip on the FAILURE path, where the verdict already forces a spawn unaided. It therefore contributes exactly nothing on every path it can take, while reading as a satisfied staleness check in the tick log.",

  router_instance_8_distinction_20260721T1946: "HOW THIS DIFFERS FROM INSTANCE 7, so the sweep does not collapse them. Instance 7 (mock-guard empty scanset) is a gate that examines an EMPTY INPUT and reports PASS. Instance 8 examines a NON-empty input and reports PASS, but the input is a value the gate's own subject just wrote — the scan set is fine, the OBSERVATION IS NOT INDEPENDENT OF THE OBSERVED. Same false-green surface, different mechanism, and they need different repairs: instance 7 wants a distinct SKIPPED/empty-set exit, instance 8 wants either an independent freshness source or deletion of the branch. Tiers 2 and 3 reportedly carry a suppression that tier-1 lacks; porting it is one candidate fix, but router did NOT verify that suppression at source and it must not be assumed to exist.",

  router_instance_8_fix_boundary_20260721T1946: "ROUTER DID NOT CHOOSE THE REMEDY. Honest options: [a] delete the heartbeat-age branch from the tier-1 cron prompt and stop advertising a staleness check that cannot fire — smallest change, loses nothing real; [b] have the probe write the heartbeat ONLY on a path distinct from the one the guard reads, so age reflects health persistence rather than probe recency; [c] port whatever suppression tiers 2/3 use, AFTER verifying it exists and is not the same self-satisfying shape one level up. What is NOT acceptable is leaving a prompt that instructs an operator to check staleness against a value the check's own subject authored moments before."
})

| annotate("FIX-SIGNALQUEUE-RECEIVER-DELIVERY-CONTRACT"; {
  router_fileplane_lock_asymmetry_20260721T1946: "ROUTER — RELATED GAP ON THE FILE PLANE, UNROUTED ACROSS SEVERAL TICKS, RECORDED HERE BECAUSE THIS ROW OWNS DELIVERY SEMANTICS. docs/agents/dev-team/flow/drain-signals.md step 0a-D claims a per-row `dashboard-row` lock (row_key = 'dash:signal_queue:' + row.id, ttl 1800) and SKIPS on collision, so the DB plane is guarded against a concurrent peer. The file plane at step 0a-1 has NO equivalent peer-collision guard: it can `mv` a signal file out of docs/signals/ while a live peer is mid-read on that exact path. The two planes of one drain therefore run at different isolation levels, and the unguarded one is the one that mutates the filesystem. This is adjacent to but distinct from the undeliverable-orphan problem this row already covers — same subsystem, and a receiver contract that does not state which plane holds what lock will not close it. PO to decide whether it folds here or needs its own row; router did not mint."
})
