def annotate($id; $keys):
  (.task_board // {}) |= (
    to_entries
    | map(.value |= (
        if (. | type) == "array"
        then map(if (.id? // "") == $id then . + $keys else . end)
        else . end
      ))
    | from_entries
  );

annotate("FIX-DRAIN-TEST-HARNESS-ORCH-HELPER-COPY-LIST"; {
  router_harness_green_verified_independently_20260721T2022: "ROUTER RAN THE SUITE ITSELF — NOT TAKEN ON THE AGENT'S WORD, BECAUSE THE WHOLE POINT OF THIS ROW IS THAT A REPORTED PASS COUNT CAN COME FROM A SUITE THAT NEVER FINISHED. `node scripts/agents-flow/drain-signals.test.js` at 20:21:58Z → 28/28 passed, 0 failed, OVERALL: PASS, and the tail of the output shows execution CONTINUING PAST line 273 into all three previously-dark groups: FIX-DRAIN-PAYLOADREF gates (3/3), ENOBUFS gates (4/4), and unparseable-loud (6/6). Previously the process died after assertion 15/28. THE SIX unparseable-loud ASSERTIONS ALL PASS ON FIRST GENUINE EXECUTION — they were written this session in commit c6e548ca2 against a TRUNCATED COPY of the test file and had never run in the real suite, so a failure here was live-possible and would have meant the 0-byte-handling guard shipped wrong. It did not. Zero regressions across all 13. Commit 2e5b325d2 scope verified via --stat = exactly 2 files (drain-signals.test.js + orch-state.json), no peer sweep despite a dirty tree.",

  router_fix_is_derived_not_hand_patched_20260721T2022: "THE FIX IS ROOT-CAUSE, NOT THE ONE-LINE PATCH ROUTER AND PO BOTH SCOPED. Router asked for the copy list to be fixed and merely PREFERRED a derived list; developer built one. drain-signals.test.js:255-265 now defines deriveOrchApplyHelpers(), which reads scripts/orch-apply.sh's own source and regex-extracts every `${REPO_ROOT}/scripts/<name>.<sh|mjs|js>` invocation, and line 275 spreads it as `['scripts/orch-apply.sh', ...deriveOrchApplyHelpers()]`. Router cross-checked the derivation against ground truth: grepping orch-apply.sh for that idiom yields exactly orch-validate.mjs, orch-stamp-updated-at.mjs, orch-conservation-check.mjs — the 3 the harness now copies, including the one whose absence caused this bug. A hand-appended fourth entry would have re-armed the identical trap on the next dependency; this does not. Credited because the agent chose the wider fix on its own reasoning (AC4), not because it was told to.",

  router_residual_partial_drift_not_caught_20260721T2022: "KNOWN BOUND ON THE FIX — RECORDED SO A LATER SWEEP DOES NOT RE-DISCOVER IT AS A MISS, AND SO NOBODY READS THIS ROW AS HAVING CLOSED THE CLASS ENTIRELY. The derivation is REGEX-COUPLED TO ONE INVOCATION IDIOM. Its stale-regex guard (line 261-263) throws only when the match count is ZERO, so it catches TOTAL regex rot and NOT PARTIAL DRIFT: if orch-apply.sh later invokes a fourth helper via `$SCRIPT_DIR/`, a bare relative path, or a variable, the derivation silently returns 3 of 4 and the sandbox breaks exactly the way it did before this fix — same failure mode, one level rarer. Router verified the idiom is CURRENTLY exhaustive: every non-matching `scripts/` mention in orch-apply.sh is a comment line (3, 15, 17, 22, 34, 38, 62, 124, 146, 168), with no live invocation escaping the pattern, so the derivation is complete as of 2026-07-21T20:22Z. Not a defect in what shipped, and deliberately NOT expanded into scope now. A stronger form would assert the derived set against orch-apply.sh's actual runtime behaviour rather than its text. ROUTER DID NOT MINT."
})

| annotate("CLEAN-COWORK-DISPATCHER-TELEMETRY-DRAIN-DIR"; {
  router_step3_both_gates_met_dispatched_20260721T2022: "STEP (3) IS NOW FULLY UNBLOCKED — BOTH PRECONDITIONS SATISFIED AND VERIFIED SEPARATELY. Router's gate (a live cowork tick must exercise the new atomic writer) was met at 20:20Z: docs/signals/cowork-team-20260721T201005Z.json, 7625 bytes, valid JSON, zero new 0-byte files since fix commit 4d13b0e1e, zero orphaned .cowork-team-*.tmp.* temps. PO's ADDED gate (FIX-DRAIN-TEST-HARNESS-ORCH-HELPER-COPY-LIST green first, so the deletion is covered by a live assertion rather than by inspection) was met at 20:22Z and router verified it by RUNNING the suite rather than reading the agent's report — 28/28, execution confirmed past the old crash point. Re-checked at dispatch: exactly 2 zero-byte files remain (cowork-team-20260721T183028Z.json, cowork-team-20260721T192339Z.json), inbox at 58 *.json. Dispatched to developer 20:22Z under intent:developer:telemetry-drain-dir-step3-20260721T2022, scoped to step (3) ONLY, with a STOP condition: re-run the 0-byte find before deleting and abort if it returns anything other than those exact two paths, since a third file would mean the atomic-write fix is not holding and deletion must not proceed. Also instructed that clearing the >50 PERSIST GUARD is explicitly NOT in this row's scope — removing these two leaves 56, still above threshold, and the remainder is the separate 46-dead-tick-file backlog.",

  router_root_cause_still_open_after_step3_20260721T2022: "DO NOT LET STEP (3) CLOSING READ AS THE DEFECT BEING FIXED. When the two artifacts are deleted this row is complete as SCOPED, but the thing that produced them is untouched: something terminates cowork-team ticks mid-heredoc at a measured 2-of-4 rate on 2026-07-21, and commit 4d13b0e1e changed only what happens WHEN that occurs, not WHETHER it occurs. The fix also made the cause quieter — a permanent visible 0-byte file became a dot-temp that self-deletes after 60 minutes plus an ephemeral stderr WARN nothing durably captures. So after this row closes, the system will still lose telemetry ticks at the same rate, with LESS evidence than it had today. That work lives in FIX-COWORK-TICK-MIDWRITE-DEATH-DURABLE-FAILURE-COUNTER (backlog/P1/M, developer), whose ordering constraint — durable counter BEFORE investigation, and the counter must not itself write to docs/signals/*.json — exists precisely because the investigation is otherwise blind. Router flags that closing this row LOWERS the system's ability to diagnose the open one, which is an argument for pulling that backlog row forward, not a reason to hold this one open."
})
