(.task_board.review[] | select(.id=="FIX-NEWS-CB-FALSE-CLOSED")) |= (
  .status = "REVIEW"
  | .next_agent = "developer"
  | .updated_at = "2026-07-08T05:45:00Z"
  | .updated_by = "router (independent re-verification — reverted premature DONE_VERIFIED)"
  | .verification_gap_note = ("dev-team independently re-queried live get_system_status post-swap (2026-07-08T05:31Z, container uptime 2m27s at query time) and found Reuters RSS + Trading Economics STILL showing \"Suy giảm\" (degraded) with climbing consecutive-error counts (2 and 2) rather than \"disabled\" like newsapi shows — the exact CB-false-closed symptom this task targets is still reproducing, within 2 minutes of a fresh restart. " +
      "Root cause: apps/mcp-server/src/interface/mcp/routes/pushNewsHandler.ts:84 (handlePushNews, fires on every VPS POST /api/push-news event — far more frequent than the 15-min scheduled cycle) has its OWN independent reuters/tradingeconomics stub injection into pollNews() (`reuters: async () => [], tradingeconomics: async () => []`) that commit aa87cfe05 never touched — only intelligenceCycleJob.ts defaultPollNews (the scheduled-cron call site) was patched. This second call site reproduces the identical bug: pollNews.ts's health loop (STUB_CAPABLE_KEYS = new Set([\"newsapi\"]) only) treats the fulfilled-but-empty stub result as a real failure for reuters/tradingeconomics, overwriting the one-time recordDisabled() seed on every VPS push. " +
      "ops flipped this row's status to DONE_VERIFIED without completing the PO-mandated live get_system_status re-check (self-reported: no MCP gateway access in its sub-session) — reverting to REVIEW/developer rather than accepting an unverified sign-off. Ops's deploy work itself (rebuild+swap to image f47c89142f7d, /health 200 toolCount=183 unchanged, 11 peer containers untouched) is independently confirmed correct via docker inspect equivalents and does NOT need to be redone — only the pushNewsHandler.ts:84 stub needs the same fix pattern applied (omit reuters/tradingeconomics keys entirely, do not stub them), then a fresh rebuild+swap+live-verify.")
  | del(.verified_at) | del(.verified_by) | del(.verified_note)
)
