def annotate($id; $keys):
  (.task_board // {}) |= (
    to_entries
    | map(.value |= (
        if (. | type) == "array"
        then map(if (.id? // "") == $id then . + $keys else . end)
        else . end
      ))
    | from_entries
  );

annotate("CLEAN-COWORK-DISPATCHER-TELEMETRY-DRAIN-DIR"; {
  router_step3_verified_closed_20260721T2028: "STEP (3) DONE AND ROUTER VERIFIED IT AT SOURCE. Both artifacts are gone from disk; `find docs/signals -maxdepth 1 -name '*.json' -size 0` now returns ZERO, down from 2. Commit d2714a84b scope confirmed via --name-status = exactly ONE file (docs/data/orch/orch-state.json), explicit pathspec, no peer sweep despite a heavily dirty tree (49 dirty lines before and after, delta exactly the one committed file). Row sits in task_board.review, updated_by=developer/step3-20260721T2026. Inbox count reconciled: router predicted 58→56, observed 57, and the difference is NOT a miscount — a new cowork tick landed at 20:25:08Z during the run, so 58 − 2 deleted + 1 new = 57. Router checked rather than assuming the agent had miscounted.",

  router_writer_holding_two_consecutive_20260721T2028: "THE ATOMIC WRITER HAS NOW HELD ACROSS TWO CONSECUTIVE PRODUCTION TICKS, NOT ONE. First post-fix write cowork-team-20260721T201005Z.json (7625B, valid, type=cowork-fire); second cowork-team-20260721T202508Z.json (4452B, valid, type=dispatcher_telemetry). Zero 0-byte files and zero orphaned .cowork-team-*.tmp.* temps at 20:28Z. Two samples is evidence the writer works, and is NOT evidence the interruptions stopped — at the measured 50% pre-fix failure rate, two clean writes in a row is an unremarkable outcome either way. Do not read this as the mid-write deaths having gone away.",

  router_artifacts_were_never_git_tracked_20260721T2028: "PO'S STEP (3) WORDING RESTED ON A FALSE PREMISE, AND ROUTER REPEATED IT WITHOUT CHECKING. The scope said `git rm` the artifacts. `git rm` FAILED with exit 128 (pathspec did not match) because NEITHER FILE WAS EVER GIT-TRACKED — confirmed by `git log --all --diff-filter=A` returning empty for both paths on every branch, and they were not gitignored either. developer correctly fell back to plain `rm`, which is the right operation for an untracked path, and flagged the deviation rather than silently substituting the command. Harmless in outcome, but router had annotated this row earlier claiming their forensic content IS their existence and treating them as durable evidence. They were on disk only. A `git clean -fd` at any point in the last two hours would have destroyed the entire evidentiary basis of this row with no trace in history, and nothing was protecting them. LESSON: do not call a working-tree file durable evidence without checking `git ls-files`."
})

| annotate("FIX-COWORK-TICK-MIDWRITE-DEATH-DURABLE-FAILURE-COUNTER"; {
  router_death_window_narrowed_by_tracking_split_20260721T2028: "DIAGNOSTIC HANDED TO THIS ROW — THE never-tracked FINDING NARROWS WHERE THE TICK DIES, WHICH IS THIS ROW'S ACTUAL QUESTION. Router measured the tracking split in docs/signals/ at 20:28Z: of the 57 signal files on disk, `git ls-files` reports 57 TRACKED — i.e. every single healthy signal file has been committed by its writer. The only two files in the directory that were NEVER tracked were precisely the two zero-byte artifacts from interrupted ticks. That is not a coincidence and it is a free clue: a cowork tick's lifecycle reaches a git add/commit step for its telemetry signal, and on the failing runs it never got there. THE DEATH THEREFORE FALLS BETWEEN THE HEREDOC WRITE AND THE COMMIT STEP, not after the tick's work completed and not before it began emitting. That is a materially smaller search window than 'something kills the tick', and it was obtained for free from a failed `git rm` rather than from instrumentation. Router did NOT verify what sits between those two points in the cowork flow, so the next owner should read docs/agents/cowork-team/flow/telemetry.md around the Step 6.1 writer and establish what actually runs there before adding a counter. ROUTER TESTED THE ONE ALTERNATIVE THAT WOULD HAVE KILLED THIS INFERENCE AND EXCLUDED IT. If the healthy files had merely been swept into some later peer's bare commit, the tracking split would say nothing about the tick's own lifecycle. They were not: `git log --diff-filter=A` shows each healthy signal was ADDED BY ITS OWN TICK'S COMMIT — cowork-team-20260721T201005Z.json by 9e8c2b5fe 'chore(cowork-team): tick 20:00Z FIRE — 3 gatherer slots spawned', and cowork-team-20260721T202508Z.json by dc4ffd976 'chore(cowork): tick 20:15Z — tnb-audit spawned'. So a completing tick demonstrably commits its own telemetry signal, and the failing ticks did not reach that step. The inference holds. REMAINING WEAKNESS IS SAMPLE SIZE, NOT MECHANISM: n=2 failing observations, both on 2026-07-21. Treat the window as strongly indicated, not proven."
})
