def annotate($id; $keys):
  (.task_board // {}) |= (
    to_entries
    | map(.value |= (
        if (. | type) == "array"
        then map(if (.id? // "") == $id then . + $keys else . end)
        else . end
      ))
    | from_entries
  );

annotate("CLEAN-COWORK-DISPATCHER-TELEMETRY-DRAIN-DIR"; {
  router_step3_wild_evidence_met_20260721T2020: "STEP (3) WILD-EVIDENCE PRECONDITION IS NOW MET — but the row is still blocked, on PO's ADDED precondition, not router's. Router's original gate was: delete the two 0-byte artifacts only after a LIVE cowork tick exercises the new atomic writer. That has now happened and router verified it. Fix commit 4d13b0e1e landed 2026-07-21T20:02:11Z. The cowork 20:00Z tick fired at 20:10:20Z (commit 9e8c2b5fe, '3 gatherer slots spawned') and its telemetry write went through the NEW writer, producing docs/signals/cowork-team-20260721T201005Z.json — 7625 bytes, valid JSON, from=cowork-team type=cowork-fire. Cross-checks at 20:20Z: ZERO new 0-byte files created since the fix timestamp (`find -size 0 -newermt`), ZERO orphaned .cowork-team-*.tmp.* temps. So the writer works end-to-end in production, not merely in agent-father's scratch harness. PO then CONFIRMED the gate and added one condition router did not have: FIX-DRAIN-TEST-HARNESS-ORCH-HELPER-COPY-LIST must be green first, so the deletion is covered by a live assertion rather than by inspection. Router accepts that as strictly stronger and defers. DO NOT git rm the two artifacts until that harness row is green.",

  router_coldevict_sweep_recurrence_20260721T2020: "RECURRING DEFECT, SECOND CONFIRMED OCCURRENCE — THE COLD-EVICT AUTO-COMMIT SWEPT A LIVE PEER'S UNCOMMITTED BOARD WRITES. At 20:14:18Z the cold-eviction inside dev-team-tick-preflight.sh wrote docs/data/orch/orch-state.json and immediately committed it as e3e5c9f92 ('chore(tasks): cold-evict terminal sprints/done lanes → archive/2026-07.json'). PO was LIVE at that moment, mid-ruling. Router verified the commit diff contains PO's work, not the evictor's: 4 task rows (FIX-SLA-SBV-FX-BUSINESS-DAY-AWARE relocated; FIX-DRAIN-FILEPLANE-PEER-COLLISION-GUARD, FIX-COWORK-TICK-MIDWRITE-DEATH-DURABLE-FAILURE-COUNTER, FIX-DRAIN-TEST-HARNESS-ORCH-HELPER-COPY-LIST newly minted) plus 20 po_*/router_* annotation keys. After it, `git status --porcelain` on the file was EMPTY — PO had nothing left to commit and its own commit 208abc972 carries only its notebook. PO independently reported the same sweep and confirmed content intact in HEAD. LOSS IS ATTRIBUTION-ONLY, NOT DATA — but the failure mode is real: git archaeology for 'when was FIX-DRAIN-FILEPLANE-PEER-COLLISION-GUARD minted' lands on a cold-evict chore commit, and a peer that re-applies its transform after finding a clean tree would double-mint, which is precisely the duplicate-row class PO was dispatched to rule on. PO subsequently verified the race outcome at FIELD LEVEL against what it intended to write — all three transforms landed COMPLETELY (fold+retire, 5 annotations across 3 rows + 3 mints, journal entry), no partial application, and a BOARD-WIDE DUPLICATE-ID SCAN RETURNS none. The retired row sits in task_board.archive as CANCELLED with superseded_by intact and does NOT also appear in docs/data/orch/archive/2026-07.json, so cold-evict did not double-file it. So on THIS occurrence the harm was bounded to attribution. That is the outcome to prioritise against: the race is not currently corrupting data, but it is one unlucky interleaving away from doing so, and the double-mint path only stayed shut because PO detected the sweep itself and router warned it mid-run not to re-apply. Neither of those is a mechanism. Prior art exists at memory feedback_coldevict_bare_commit_sweeps_worker_staged_index.md, so this is occurrence 2+ and crosses the repo's recurring-defect escalation bar. Router mitigated live by messaging PO mid-run not to re-apply. FOR PO: this needs a row — the evictor should commit ONLY the paths it evicted, or take commit-mutex:main, or skip its auto-commit when the file is dirty from a peer. ROUTER DID NOT MINT."
})

| annotate("FIX-AUDITOR-SBVFX-SLA-POSTMARKET-TOLERANCE"; {
  router_accepts_po_correction_20260721T2020: "ROUTER'S OWN ANALYSIS ON THIS TOPIC WAS WRONG AND PO CORRECTED IT BY MEASUREMENT — the correction stands, router's earlier key does not. At 19:35Z router annotated the (now-superseded) duplicate row asserting the real defect was the intra-day arm only and the fix was '~3 lines mirroring the NEWS branch at 667-673, both helpers already exist'. PO imported freshnessSlaChecker under bun and RAN it rather than reading it, and found that mirroring the news branch WOULD NOT CLEAR THE FALSE POSITIVE. Router re-verified the root fact at source: freshnessSlaChecker.ts:562 hardcodes `const SBV_WINDOW_END_UTC_HOUR = 10; // 17:00 VN = 10:00 UTC`, while this row's own ground truth has SBV publishing ~03:05Z (10:05 VN). Age therefore clocks from the ~03:05Z publish while the threshold clocks from a 10:00Z window end, and OFF_HOURS_GRACE_MINUTES=30 (line 406) cannot absorb the ~6h55m gap. PO measured a CONSTANT 384-minute excess across two different days (Sat 10:00Z age=1854 thr=1470; Sun 06:00Z age=3054 thr=2670) — a constant offset is the signature of a MIS-SET CONSTANT, not a wrong branch. Router's proposed fix would have left that constant in place and shipped a row that did not fix the reported symptom.",

  router_shipped_arm_never_worked_20260721T2020: "THE SEVERE FINDING NEITHER ROUTER NOR PO HAD BEFORE THIS PASS: THE ALREADY-SHIPPED WEEKEND ARM HAS NEVER WORKED AT REAL CADENCE. Commit d71e3f2e2 closed FIX-SLA-EXEMPT-NEWS-SBVFX with a dedicated passing regression file, and router cited that passing file at 19:35Z as PROOF the capability existed and PO's premise was false. The capability exists; it does not FUNCTION. Per PO's measurement its S-1 fixture asserts '289 min NOT breached' against a 1470 threshold — but 289 was never derived from the source's real cadence, which is ~1854. So the fixture is satisfiable by a broken implementation, and the row closed green while the false positives it existed to stop kept firing. THIS IS THE 'TEST PINS THE DEFECT' CLASS, one level worse than clause (E)'s pinning test: not a test that must be updated by the fix, but a test whose fixture was never grounded in the source's real behaviour, so it certified a non-working arm. LESSON FOR THE ROW AND FOR ROUTER: a passing regression file is evidence a code path EXISTS, never evidence it WORKS. Router treated the former as the latter. This row now covers BOTH arms plus a mandatory S-1 re-base against real ~03:05Z cadence; do not close it by fixing the intra-day arm alone.",

  router_clause_e_scope_correction_20260721T2020: "CLAUSE (E) SCOPE CORRECTED — router overstated it. Router called 1920i-freshness-sla-extension.test.ts:273 'the row's most valuable clause', on the belief it pins the 30-minute default against any fix. PO checked and it asserts against the DEFAULT_SLA_CONFIG FIELD, not getSlaThreshold's OUTPUT. So it does NOT block a branch-level fix; it only bites if the chosen remedy changes the config field itself. It is real but CONDITIONAL ON THE PATH TAKEN, not unconditional. Recorded so nobody plans around a constraint that may not apply to their chosen approach."
})

| annotate("FIX-DRAIN-TEST-HARNESS-ORCH-HELPER-COPY-LIST"; {
  router_ac7_claim_retracted_20260721T2020: "ROUTER RETRACTS ITS OWN SEVERITY CLAIM ON THIS ROW — PO'S CORRECTION IS RIGHT AND RAISES SEVERITY RATHER THAN LOWERING IT. At 19:58Z router wrote that the AC7 golden-stdout regression guard 'has been unguarded since a5d079663'. FALSE, and router re-verified the line ordering at source: the AC7 assertions are at drain-signals.test.js:189-190, while makeOrchRefHarness() is DEFINED at 248 and first CALLED at 273. AC7 executes and passes before the crash ever happens. What is ACTUALLY dark is the 13 assertions AFTER line 273 — FIX-DRAIN-PAYLOADREF (3, ~305/310/321), ENOBUFS (4, ~374-382), and unparseable-loud (6, ~411-420). THE LAST GROUP IS WHY THIS IS P0 DESPITE A ONE-LINE DIFF: those six assertions were written THIS SESSION in commit c6e548ca2 to guard 0-byte / truncated-write handling, were verified only against a TRUNCATED COPY of the test file, and have never executed in the real suite. The coverage guarding the exact behaviour under active change in CLEAN-COWORK-DISPATCHER-TELEMETRY-DRAIN-DIR and FIX-COWORK-TICK-MIDWRITE-DEATH-DURABLE-FAILURE-COUNTER is the coverage that is not running. Router's original framing would have justified a lower priority on a false basis. Dispatched to developer 20:20Z with instructions to run the FULL suite (no truncated copy) and to REPORT rather than fix any of the 13 dark assertions that fail once genuinely executed — an assertion that has never run may have been wrong since it was written."
})
