def annotate($id; $keys):
  (.task_board // {}) |= (
    to_entries
    | map(.value |= (
        if (. | type) == "array"
        then map(if (.id? // "") == $id then . + $keys else . end)
        else . end
      ))
    | from_entries
  );

annotate("CLEAN-COWORK-DISPATCHER-TELEMETRY-DRAIN-DIR"; {
  router_rate_correction_20260721T1958: "ROUTER CORRECTS ITS OWN PRIOR CLAIM ON THIS ROW. At 19:46Z router annotated this row as an active producer at 'roughly 1 file/hour', inferred from two 0-byte files 53 minutes apart. That framing was WRONG in shape, and the correction makes the row worse, not better. Full enumeration of every cowork-team telemetry write on 2026-07-21: 15:24:00Z=2520B OK, 18:30:28Z=0B BROKEN, 19:23:39Z=0B BROKEN, 19:54:43Z=5898B OK. That is 2 of 4 = a 50% FAILURE RATE, intermittent, not a steady hourly drip. The 19:54:43Z healthy write landed DURING the developer's run on this row and is what refuted the hourly-producer model — a steady producer would have truncated it too. Router had inferred a rate from two adjacent samples without enumerating the population; the two samples happened to be consecutive failures. Prior key router_premise_escalation_20260721T1946 remains correct that this is an ACTIVE producer and not a cleanup row; only its rate model was wrong.",

  router_zone_reroute_20260721T1958: "STEP (1) RE-ROUTED — DEVELOPER WAS THE WRONG OWNER AND SAID SO RATHER THAN PROCEEDING. developer (dispatched 19:46Z) grepped for the writer at source instead of guessing from the filename and found it is docs/agents/cowork-team/flow/telemetry.md line 34, a `cat > docs/signals/cowork-team-${ISO}.json <<EOF` heredoc inside a bash fence in a FLOW DOC executed by the cowork-team LLM agent — not a script. Router re-verified that line at source. docs/agents/*/flow/ is agent-father's zone (.claude/skills/dispatch/SKILL.md line 48, 'All agent-file lifecycle'), so developer stopped at the boundary rather than drive-by editing, which is the correct behaviour and is credited here. Step (1) re-dispatched to agent-father at 19:57Z under intent:agent-father:telemetry-atomic-write-20260721T1957, with scope WIDENED to also cover the identical defect at telemetry.md line 104 (the -error.json writer, which fires exactly when a tick is already failing i.e. when interruption is most likely) plus a sweep for the same `cat > ... <<EOF` shape in other agent flow docs.",

  router_atomic_rename_alone_is_not_the_fix_20260721T1958: "DESIGN CONSTRAINT PASSED TO AGENT-FATHER, RECORDED HERE SO THE ACCEPTANCE GATE CAN CHECK IT. A bare temp+rename DOES NOT fix this defect. `cat > $TMP <<EOF` followed by `mv $TMP $FINAL` still yields a 0-byte file at the final path when the write is interrupted mid-heredoc — it merely renames the identical broken artifact. The fix MUST validate the temp file before renaming (non-zero size AND `jq empty` parseability) and leave NOTHING at the final path on failure. Whoever grades this row: do not accept a diff that renames without validating, and require a demonstration that a deliberately truncated temp file is REJECTED rather than promoted. A fix that cannot be shown rejecting a bad write has not been verified.",

  router_step2_shipped_20260721T1958: "STEP (2) IS DONE AND ROUTER VERIFIED IT AT SOURCE. commit c6e548ca2, scope confirmed via git show --name-status = exactly 2 files (scripts/agents-flow/drain-signals.js, scripts/agents-flow/drain-signals.test.js), no peer-index sweep. The JSON.parse catch now emits an immediate `[drain-signals] WARN unparseable JSON: <file> — <msg>` on STDERR, distinct from the benign `SKIP non-signal shape` path (well-formed JSON merely lacking from/type). Previously it only appended to a batched report array printed once at the end on stdout, indistinguishable in prominence from routine routed-to-po traffic. stderr was chosen deliberately so the warning cannot pollute the AC7 golden-stdout regression guard — router endorses that reasoning. Step (3) correctly NOT done and still blocked behind step (1)."
})

| annotate("SPIKE-SATURATED-COUNT-THRESHOLD-GATES-SWEEP"; {
  router_sibling_harness_break_20260721T1958: "ADJACENT FINDING — NOT A NEW SWEEP INSTANCE, BUT THE SAME FALSE-GREEN FAMILY, ROUTED HERE FOR PO TO PLACE. Surfaced by developer during CLEAN-COWORK-DISPATCHER-TELEMETRY-DRAIN-DIR and independently re-verified by router at source. scripts/agents-flow/drain-signals.test.js:256 builds its sandbox by copying a FIXED LIST of orch helpers: ['scripts/orch-apply.sh','scripts/orch-validate.mjs','scripts/orch-conservation-check.mjs']. Commit a5d079663 (FIX-ORCHSTATE-UPDATED-AT-WRITE-PATH, same day) ADDED scripts/orch-stamp-updated-at.mjs and MODIFIED scripts/orch-apply.sh to invoke it — without adding the new file to that copy list. So orch-apply.sh inside the sandbox now calls a file that is not there, and the makeOrchRefHarness scenario CRASHES THE WHOLE TEST PROCESS, taking every later scenario in the file with it. developer confirmed via git stash that this predates its own change, declined to fix it as out-of-scope, and worked around it by running a truncated copy through the 15 pre-existing scenarios that precede the break. Router endorses the scope call. WHY IT BELONGS NEAR THIS SWEEP: a fix in file A silently disabled a test suite in file B, and nobody noticed — which means that suite was not run after a5d079663 landed. The AC7 golden-stdout regression guard for the drain has therefore been unguarded since that commit. Distinct from instances 1-8 in mechanism (this is a broken fixture, not a gate reporting PASS on a degenerate input) but identical in consequence: an assertion nobody can see is failing. Fix is one array entry; the coverage question behind it is not. PO to rule whether this folds here or needs its own row — ROUTER DID NOT MINT."
})
