def annotate($id; $keys):
  (.task_board // {}) |= (
    to_entries
    | map(.value |= (
        if (. | type) == "array"
        then map(if (.id? // "") == $id then . + $keys else . end)
        else . end
      ))
    | from_entries
  );

annotate("CLEAN-COWORK-DISPATCHER-TELEMETRY-DRAIN-DIR"; {
  router_step1_verified_at_source_20260721T2005: "STEP (1) SHIPPED AND ROUTER VERIFIED IT AT SOURCE — NOT TAKEN ON THE AGENT'S WORD. commit 4d13b0e1e, git show --name-status = exactly ONE file (docs/agents/cowork-team/flow/telemetry.md), explicit pathspec, no peer-index sweep despite a dirty tree and a concurrent peer. Read back in the file: BOTH writers carry validate-before-rename — the Step 6.1 telemetry writer (FINAL/TMP at lines 42-43, guard at line 88) and the Error Guard writer (lines 128-129, guard at 135). Guard is `[[ -s \"$TMP\" ]] && jq empty \"$TMP\"`, so $FINAL is never touched unless the temp is BOTH non-empty AND parseable; on failure nothing is renamed. The validate-before-rename trap flagged at dispatch was closed, not papered over: agent-father demonstrated rejection against a 0-byte temp, a mid-JSON-truncated temp, and a valid control, confirming $FINAL appeared only in the control case. TMP naming is the detail worth crediting — `docs/signals/.cowork-team-${ISO}.json.tmp.$$` is dot-prefixed AND does not end in .json, so orphaned temps are invisible to every `docs/signals/*.json` glob the drain and the MANDATORY PERSIST GUARD count. A hard kill mid-heredoc can no longer ratchet the guard at all, which is the actual harm this row existed to stop. Stale-temp sweep at line 46 (-mmin +60 -delete) bounds hidden debris.",

  router_blast_radius_not_root_cause_20260721T2005: "READ THIS BEFORE CLOSING THE ROW — WHAT SHIPPED FIXES THE BLAST RADIUS, NOT THE CAUSE. The atomic+validate rewrite stops interrupted writes from CORRUPTING THE INBOX. It does not stop the interruptions. Whatever is terminating cowork-team ticks mid-heredoc — 2 of 4 writes on 2026-07-21, a 50% rate — is entirely untouched by commit 4d13b0e1e and will keep happening at the same rate. Worse for detectability: the fix makes that cause HARDER to observe. Before, a failed write left a permanent, visible 0-byte file in docs/signals/ that the drain tripped over every tick. Now it leaves a dot-prefixed temp that auto-deletes after 60 minutes and a WARN on stderr that nothing durably captures — the cowork agent sees it in its own Bash tool result and may or may not carry it into its notebook. So the system traded LOUD-PERMANENT-HARM for QUIET-TRANSIENT-LOSS. That is the correct trade for the guard ratchet and the wrong place to stop investigating. Concretely: a tick can now produce NO telemetry signal at all, and after 60 minutes there is no durable record that it ever tried. FOR PO: this needs a follow-up row for (a) a durable failure counter or signal so validation failures are countable rather than ephemeral, and (b) an actual investigation of why ~half of cowork ticks die mid-write. ROUTER DID NOT MINT.",

  router_step3_gate_20260721T2005: "STEP (3) IS NOW UNBLOCKED IN PRINCIPLE BUT NOT YET EARNED — DO NOT git rm THE TWO ARTIFACTS THIS TICK. The precondition router set was that step (1) must ship BEFORE deletion, and it has. The remaining precondition is EVIDENCE, not sequence: the fix has been demonstrated in a scratch harness, but has not yet been exercised by a real cowork tick. docs/signals/cowork-team-20260721T183028Z.json and docs/signals/cowork-team-20260721T192339Z.json are both still present and untouched (verified 20:05Z, count still exactly 2). Delete them only after at least one live cowork tick has run through the new writer and produced either a valid signal file or a clean validated rejection with no new 0-byte file in docs/signals/. Until then they remain the only durable evidence of the defect, and their forensic content IS their existence.",

  router_other_flow_docs_swept_20260721T2005: "SCOPE ITEM 3 ANSWERED — NO OTHER LIVE AGENT FLOW DOC HAS THIS SHAPE. agent-father grepped all docs/agents/*/flow/*.md for `cat > docs/signals/... <<EOF` plus other write shapes targeting docs/signals/; only telemetry.md lines 34 and 104 matched, both now fixed. Two files outside the agent-flow tree use the identical pattern — docs/handoffs/TASK_P2-D.md and docs/handoffs/TASK_P2-C.md — but they are CLOSED task handoff docs, not live flow files, and were correctly left untouched. docs/agents/cowork-team/flow/tick-snapshot.md already used temp+rename for a different target (docs/data/cycle-snapshot-*.json); it is inherently safer because jq itself fails loudly on bad content rather than a heredoc silently truncating, so it needed no change. Router accepts that reasoning and records it so a later sweep does not re-open it as a miss."
})
