/**
 * news-fetch Sandbox — result reporting
 *
 * Per-scenario console output, run summary, and the JSON trace + data.js
 * inline sidecar writer (file:// dashboard rendering — headless Chromium
 * blocks file://→file:// XHR as cross-origin; a <script src="data.js">
 * tag is not blocked). Split out of runner.ts (FACTORY-NEWS-split-sandbox).
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import type { ScenarioResult } from './execute.js';

export function printScenarioResult(result: ScenarioResult): void {
  const icon = result.status === 'PASS' ? 'PASS' : result.status === 'FAIL' ? 'FAIL' : 'ERROR';
  const label = result.primitive ?? result.module ?? 'unknown';
  const type = result.scenarioType ? ` [${result.scenarioType}]` : '';
  console.log(`  ${icon}  ${label}${type} — ${result.file.split('/').slice(-3).join('/')}`);
  if (result.diff) {
    console.log(`         ${result.diff}`);
  }
}

export interface RunCounts {
  passCount: number;
  failCount: number;
  errorCount: number;
}

export function printSummary(results: ScenarioResult[]): RunCounts {
  const counts: RunCounts = {
    passCount: results.filter((r) => r.status === 'PASS').length,
    failCount: results.filter((r) => r.status === 'FAIL').length,
    errorCount: results.filter((r) => r.status === 'ERROR').length,
  };
  console.log('');
  console.log(`[sandbox] Result: ${counts.passCount} PASS, ${counts.failCount} FAIL, ${counts.errorCount} ERROR`);
  return counts;
}

export function writeTraceOutput(
  outputFlag: string,
  tier: string,
  module_: string,
  results: ScenarioResult[],
  counts: RunCounts,
): void {
  const trace = {
    runAt: new Date().toISOString(),
    tier,
    module: module_,
    totals: { pass: counts.passCount, fail: counts.failCount, error: counts.errorCount },
    results: results.map((r) => ({
      file: r.file,
      status: r.status,
      primitive: r.primitive,
      module: r.module,
      scenarioType: r.scenarioType,
      diff: r.diff,
    })),
  };
  const outPath = resolve(outputFlag);
  const outDir = dirname(outPath);
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }
  writeFileSync(outPath, JSON.stringify(trace, null, 2), 'utf-8');
  console.log(`[sandbox] Trace written to: ${outPath}`);

  // Inline sidecar: replaces XHR for file:// compatibility (zero CORS). Mirrors the
  // kinh-dich fleet precedent (G9 PASS).
  const dataJsPath = resolve(outDir, 'data.js');
  const dataJsContent =
    '// Generated by sandbox runner — DO NOT EDIT BY HAND.\n' +
    '// Inline sidecar: replaces XHR for file:// compatibility (zero CORS).\n' +
    '// Regenerate: bun run src/sandbox/runner.ts --tier=all --module=news-fetch --scenario=all --output=dashboard/results.json\n' +
    'window.__NEWS_FETCH_DATA__ = ' +
    JSON.stringify(trace, null, 2) +
    ';\n';
  writeFileSync(dataJsPath, dataJsContent, 'utf-8');
  console.log(`[sandbox] Inline sidecar written to: ${dataJsPath}`);
}
