Bun.env["DB_PATH"] = ":memory:";

/**
 * Task 1255 — Alert Commander: alerts generated but never sent off-hours
 *
 * Bug: step E (send HIGH/CRITICAL alerts) was inside the `if (marketHours)`
 * block. Macro sigma alerts (USD/VND, gold, etc.) are generated by step A2.5
 * 24/7 but were never sent outside 02:00–08:59 UTC Mon–Fri.
 *
 * Fix: move step E outside the marketHours guard so off-hours alerts are sent.
 *
 * Acceptance criteria:
 *   AC-1: runIntelligenceCycle off-hours → readUnnotifiedAlertsFn is called
 *   AC-2: runIntelligenceCycle off-hours + unnotified HIGH alert → sendAlertsFn called
 *   AC-3: during market hours, step E still works (no regression)
 */

import { describe, it, expect, beforeAll, afterAll } from "bun:test";

const _origDbPath = Bun.env["DB_PATH"];
beforeAll(() => {
  process.env["TEST_LOG_SUPPRESS"] = "1";
});
afterAll(() => {
  delete process.env["TEST_LOG_SUPPRESS"];
  if (_origDbPath !== undefined) Bun.env["DB_PATH"] = _origDbPath;
});

import type { Alert } from "../domain/services/alertGenerator";

const mockHighAlert: Alert = {
  id: "test-alert-1255",
  actionCode: "VCB",
  severity: "high",
  signals: [{
    type: "price_drop",
    confidence: 0.85,
    message: "VCB dropped 5σ",
    severity: "high",
    actionCode: "VCB",
    detectedAt: new Date().toISOString(),
  }],
  message: "VCB: price_drop detected",
  isRead: false,
  createdAt: new Date().toISOString(),
};

function buildOffHoursDeps(overrides: Record<string, unknown> = {}) {
  return {
    pollNewsFn: async () => ({ fetched: 0, inserted: 0, duplicates: 0, alerts: 0, errors: 0 }),
    listSscDocsFn: async () => [],
    fetchPricesFn: async () => 0,
    runImpactChainFn: async () => 0,
    getWatchlistCodesFn: async () => [],
    syncSectorPeersFn: async () => ({ synced: 0, skipped: 0, apiCalls: 0 }),
    computeHexagramsFn: async () => 0,
    isMarketHoursFn: () => false, // OFF-HOURS
    ...overrides,
  };
}

describe("Task 1255 — alert sending off-hours", () => {
  it("AC-1: readUnnotifiedAlertsFn is called even off-hours", async () => {
    const { runIntelligenceCycle, resetCycleGuard } = await import("../scheduler/news-analysis/intelligenceCycleJob.js");
    resetCycleGuard();

    let readAlertsCalled = false;

    const result = await runIntelligenceCycle({
      ...buildOffHoursDeps(),
      readUnnotifiedAlertsFn: async (_windowMs) => {
        readAlertsCalled = true;
        return [];
      },
      markAlertNotifiedFn: async () => {},
      sendAlertsFn: async () => 0,
    });

    expect(result).not.toBeNull();
    expect(readAlertsCalled).toBe(true);
  });

  it("AC-2: off-hours + unnotified HIGH alert → sendAlertsFn called and alert marked notified", async () => {
    const { runIntelligenceCycle, resetCycleGuard } = await import("../scheduler/news-analysis/intelligenceCycleJob.js");
    resetCycleGuard();

    let sendAlertsCalled = false;
    let markNotifiedCalled = false;

    const result = await runIntelligenceCycle({
      ...buildOffHoursDeps(),
      readUnnotifiedAlertsFn: async () => [mockHighAlert],
      sendAlertsFn: async (alerts) => {
        sendAlertsCalled = true;
        return alerts.length; // return 1 = success
      },
      markAlertNotifiedFn: async () => {
        markNotifiedCalled = true;
      },
    });

    expect(result).not.toBeNull();
    expect(sendAlertsCalled).toBe(true);
    expect(markNotifiedCalled).toBe(true);
    expect(result!.telegramAlertsSent).toBe(1);
  });

  it("AC-3: during market hours, step E still works (no regression)", async () => {
    const { runIntelligenceCycle, resetCycleGuard } = await import("../scheduler/news-analysis/intelligenceCycleJob.js");
    resetCycleGuard();

    let sendAlertsCalled = false;

    await runIntelligenceCycle({
      pollNewsFn: async () => ({ fetched: 0, inserted: 0, duplicates: 0, alerts: 0, errors: 0 }),
      listSscDocsFn: async () => [],
      fetchPricesFn: async () => 0,
      runImpactChainFn: async () => 0,
      getWatchlistCodesFn: async () => [],
      syncSectorPeersFn: async () => ({ synced: 0, skipped: 0, apiCalls: 0 }),
      computeHexagramsFn: async () => 0,
      isMarketHoursFn: () => true, // MARKET HOURS
      readUnnotifiedAlertsFn: async () => [mockHighAlert],
      sendAlertsFn: async (alerts) => {
        sendAlertsCalled = true;
        return alerts.length;
      },
      markAlertNotifiedFn: async () => {},
    });

    expect(sendAlertsCalled).toBe(true);
  });
});
