// Generated by sandbox runner — DO NOT EDIT BY HAND.
// Inline sidecar: replaces XHR for file:// compatibility (zero CORS).
// Regenerate: bun run src/sandbox/runner.ts --tier=all --module=news-fetch --scenario=all --output=dashboard/results.json
window.__NEWS_FETCH_DATA__ = {
  "runAt": "2026-05-24T09:05:01.755Z",
  "tier": "all",
  "module": "news-fetch",
  "totals": {
    "pass": 13,
    "fail": 0,
    "error": 0
  },
  "results": [
    {
      "file": "/Users/admin/Documents/Hung/__works__/__PROJET/__labo/VN-Market-Intelligence-MCP/docs/scenarios/news-fetch/primitives/article-relevance-filter/edge.json",
      "status": "PASS",
      "primitive": "article-relevance-filter",
      "scenarioType": "edge"
    },
    {
      "file": "/Users/admin/Documents/Hung/__works__/__PROJET/__labo/VN-Market-Intelligence-MCP/docs/scenarios/news-fetch/primitives/article-relevance-filter/failure.json",
      "status": "PASS",
      "primitive": "article-relevance-filter",
      "scenarioType": "failure"
    },
    {
      "file": "/Users/admin/Documents/Hung/__works__/__PROJET/__labo/VN-Market-Intelligence-MCP/docs/scenarios/news-fetch/primitives/article-relevance-filter/golden.json",
      "status": "PASS",
      "primitive": "article-relevance-filter",
      "scenarioType": "golden"
    },
    {
      "file": "/Users/admin/Documents/Hung/__works__/__PROJET/__labo/VN-Market-Intelligence-MCP/docs/scenarios/news-fetch/primitives/source-dedup-key/edge.json",
      "status": "PASS",
      "primitive": "source-dedup-key",
      "scenarioType": "edge"
    },
    {
      "file": "/Users/admin/Documents/Hung/__works__/__PROJET/__labo/VN-Market-Intelligence-MCP/docs/scenarios/news-fetch/primitives/source-dedup-key/failure.json",
      "status": "PASS",
      "primitive": "source-dedup-key",
      "scenarioType": "failure"
    },
    {
      "file": "/Users/admin/Documents/Hung/__works__/__PROJET/__labo/VN-Market-Intelligence-MCP/docs/scenarios/news-fetch/primitives/source-dedup-key/golden.json",
      "status": "PASS",
      "primitive": "source-dedup-key",
      "scenarioType": "golden"
    },
    {
      "file": "/Users/admin/Documents/Hung/__works__/__PROJET/__labo/VN-Market-Intelligence-MCP/docs/scenarios/news-fetch/primitives/published-at-parser/edge.json",
      "status": "PASS",
      "primitive": "published-at-parser",
      "scenarioType": "edge"
    },
    {
      "file": "/Users/admin/Documents/Hung/__works__/__PROJET/__labo/VN-Market-Intelligence-MCP/docs/scenarios/news-fetch/primitives/published-at-parser/failure.json",
      "status": "PASS",
      "primitive": "published-at-parser",
      "scenarioType": "failure"
    },
    {
      "file": "/Users/admin/Documents/Hung/__works__/__PROJET/__labo/VN-Market-Intelligence-MCP/docs/scenarios/news-fetch/primitives/published-at-parser/golden.json",
      "status": "PASS",
      "primitive": "published-at-parser",
      "scenarioType": "golden"
    },
    {
      "file": "/Users/admin/Documents/Hung/__works__/__PROJET/__labo/VN-Market-Intelligence-MCP/docs/scenarios/news-fetch/primitives/headline-normalizer/edge.json",
      "status": "PASS",
      "primitive": "headline-normalizer",
      "scenarioType": "edge"
    },
    {
      "file": "/Users/admin/Documents/Hung/__works__/__PROJET/__labo/VN-Market-Intelligence-MCP/docs/scenarios/news-fetch/primitives/headline-normalizer/failure.json",
      "status": "PASS",
      "primitive": "headline-normalizer",
      "scenarioType": "failure"
    },
    {
      "file": "/Users/admin/Documents/Hung/__works__/__PROJET/__labo/VN-Market-Intelligence-MCP/docs/scenarios/news-fetch/primitives/headline-normalizer/golden.json",
      "status": "PASS",
      "primitive": "headline-normalizer",
      "scenarioType": "golden"
    },
    {
      "file": "/Users/admin/Documents/Hung/__works__/__PROJET/__labo/VN-Market-Intelligence-MCP/docs/scenarios/news-fetch/module/multi-source-ingest.json",
      "status": "PASS",
      "module": "news_ingest",
      "scenarioType": "multi-primitive"
    }
  ]
};
