// AUTO-GENERATED by sandbox/gen_traces_js.py — do not edit by hand.
// Regenerated on every sandbox/rerun.sh invocation.
// Loaded via <script src="traces.js"> so index.html works under file:// without fetch().
// SI-2 BOUNDARY: pdf-extractor zone only.
// Generated: 2026-05-24T16:55:37.793294+00:00

window.__TRACES_LOADED_AT = "2026-05-24T16:55:37.793294+00:00";
window.__TRACES = {
  "validate-financial-figures": {
    "primitive": "validate_financial_figures",
    "module": null,
    "inputs": {
      "total_assets": 10000.0,
      "total_equity": 4000.0,
      "total_liabilities": 6000.0,
      "operating_margin": 0.15,
      "net_revenue": 5000.0
    },
    "expected": 1.0,
    "actual": 1.0,
    "pass": true,
    "error": null
  },
  "decimal-normalizer": {
    "primitive": "decimal_normalizer",
    "module": null,
    "inputs": {
      "raw_string": "1234.5",
      "unit_hint": "billion_vnd"
    },
    "expected": 1234.5,
    "actual": 1234.5,
    "pass": true,
    "error": null
  },
  "confidence-scorer": {
    "primitive": "confidence_scorer",
    "module": null,
    "inputs": {
      "ocr_confidence": 0.85,
      "table_count": 2
    },
    "expected": {
      "pass": true,
      "quality_score": 0.85
    },
    "actual": {
      "pass": true,
      "quality_score": 0.85
    },
    "pass": true,
    "error": null
  },
  "low-confidence-gate": {
    "primitive": "low_confidence_gate",
    "module": null,
    "inputs": {
      "confidence": 0.85
    },
    "expected": "normal",
    "actual": "normal",
    "pass": true,
    "error": null
  },
  "ratio-computer": {
    "primitive": "ratio_computer",
    "module": null,
    "inputs": {
      "numerator": 300.0,
      "denominator": 1000.0,
      "ratio_type": "gross_margin"
    },
    "expected": 0.3,
    "actual": 0.3,
    "pass": true,
    "error": null
  },
  "field-extractor": {
    "primitive": "field_extractor",
    "module": null,
    "inputs": {
      "text": "Doanh thu thuần: 1,234.5\nLợi nhuận sau thuế: 456.0",
      "field_name": "net_revenue"
    },
    "expected": "1,234.5",
    "actual": "1,234.5",
    "pass": true,
    "error": null
  },
  "financial-reports": {
    "primitive": null,
    "module": "financial_reports",
    "inputs": {
      "raw_assets": "10000.0",
      "raw_equity": "4000.0",
      "raw_liabilities": "6000.0",
      "raw_margin": "0.15",
      "raw_revenue": "5000.0",
      "unit_hint": "billion_vnd",
      "ocr_confidence": 0.85,
      "table_count": 2,
      "ocr_text": "Doanh thu thuan: 5000.0"
    },
    "expected": {
      "confidence": 1.0,
      "ocr_quality_pass": true,
      "disposition": "normal"
    },
    "actual": {
      "normalized_assets": 10000.0,
      "normalized_equity": 4000.0,
      "normalized_liabilities": 6000.0,
      "normalized_margin": 0.15,
      "normalized_revenue": 5000.0,
      "confidence": 1.0,
      "ocr_quality_pass": true,
      "ocr_quality_score": 0.85,
      "disposition": "normal",
      "gross_margin": 2.9999999999999997e-05,
      "extracted_net_revenue": "5000.0"
    },
    "pass": true,
    "error": null
  },
  "pdf-extractor": {
    "primitive": null,
    "module": null,
    "service": "pdf_extractor",
    "inputs": {},
    "expected": null,
    "actual": null,
    "pass": null,
    "error": null,
    "_note": "Service-tier scenarios not yet authored (Phase 2+). pass=null renders as NOT-RUN (honest)."
  }
};
